### ISSUE TITLE
Please add bulletvpn.  Config files are attached

### ISSUE THREAD

**Issue by bijfy** [qdm12/gluetun#1000]
Please add bulletvpn.  Config files are attached 

_Originally posted by @bijfy in https://github.com/qdm12/gluetun/issues/983#issuecomment-1132584646_

**Comment by qdm12** [comment]
Closing due to duplicate. Don't worry I got it, it's just I'm short-staffed/short-timed 😄 
I'm also refactoring Gluetun's code quite a lot to make it a lot more easier to add providers, since there is a bunch to be added.
