### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by joelstitch** [qdm12/gluetun#1001]
### Host OS

Synology

### VPN service provider

Private Internet Access

### What are you using to run the container

Portainer

### What is the version of Gluetun

3.29.0

### What's the problem 🤔

I want to connect to PIA VPN with TCP port 443. That's the only way I can access a specific website. I am able to change the settings on the PIA app on my phone and desktop but not sure how to do it on docker_compose.yml

### Share your configuration

```version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6077:6077
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /volume1/docker/piavpn:/gluetun
      - /volume1/docker/piavpn/forwarded_port:/tmp/gluetun/forwarded_port
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      #- VPN_PROTO=tcp
      # OpenVPN:
      - OPENVPN_USER=USER
      - OPENVPN_PASSWORD=PASS
      #- VPN_ENDPOINT_PORT=443
      #- PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      #- SERVER_NAMES=siliconvalley407
      - SERVER_REGIONS=US East Streaming Optimized
      #- PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=America/Chicago
      
  cabernet:
    image: ghcr.io/cabernetwork/cabernet:latest
    container_name: cabernet
    network_mode: "service:gluetun"
    environment:
        - WEBUI_PORT=6077
        - PUID=1026
        - PGID=101
    volumes:
        - /volume1/docker/cabernet:/app
    depends_on:
        - gluetun
    restart: always
```

**Comment by qdm12** [comment]
Please create a discussion next time instead of an issue. Also please set a title to the issue otherwise it's hard for me to recall what it is.

As documented on the [PIA wiki page](https://github.com/qdm12/gluetun/wiki/Private-internet-access#optional-environment-variables), you can set `VPN_ENDPOINT_PORT=443`, together with `OPENVPN_PROTOCOL=tcp` ([wiki page](https://github.com/qdm12/gluetun/wiki/OpenVPN-options)). That may or may not work depending on which server is used and if they always listen on port 443 tcp.
