### ISSUE TITLE
Wiki issue: Expanded ProtonVPN info

### ISSUE THREAD

**Issue by mtalexan** [qdm12/gluetun#1020]
The following section should be added to the wiki for ProtonVPN

# Moderate NAT/NAT Type 2
Paid ProtonVPN subscribers can optionally use [Moderate NAT](https://protonvpn.com/support/moderate-nat/) on their connections.  To do so, the OpenVPN username assigned by ProtonVPN should have `+nr` appended to the end of it.

**Comment by qdm12** [comment]
Added at https://github.com/qdm12/gluetun/wiki/ProtonVPN#moderate-natnat-type-2

Thanks!
