### ISSUE TITLE
Wiki issue: provides a false sense of security about ISP/gov/other snooping

### ISSUE THREAD

**Issue by quivalen** [qdm12/gluetun#1025]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Explanations

### What's the issue?

> Gluetun works by using IP addresses directly to connect to VPN servers, instead of VPN server hostnames.

>This is like so to avoid leaking a DNS resolution out of the VPN at start (to resolve vpn.domain.com to an IP address). Otherwise your ISP/government/other could know which VPN server you are connecting to or at best see you use encrypted DNS queries.

This seems to point to the fact that by using IP addresses directly a 3rd party cannot understand which VPN server is being used. This is far from true, in fact

> The program comes with more than 10,000 IP addresses built in the program, split for each VPN provider supported.

The very same list can be used to track exactly which server is going to be used as a reverse IP. 

Previous statement should be reviseted to clearly show that this approach isn't a silver-bullet that makes you untrackable and at best, **reduces** the chances that ISP/government/other could know which VPN server you are connecting to

I don't want to be blunt here, you did an amazing job with gluetun, keep it up!

**Comment by qdm12** [comment]
Awesome thanks for the heads up. Indeed, and also I think it's not even relevant. At the end of the day we could just use DNS over TLS which is encrypted as a VPN, and that would work. The main point is to avoid other containers/proxied machines from leaking data (like torrenting and stuff) when gluetun boots up during the first ~5s I would say. I even paid attention to have the firewall setup under 20ms (it was 150ms a few releases ago)! 😉 

Anyway wiki updated 💯 !
