### ISSUE TITLE
Wiki issue: "🐛 Found a bug in the Wiki?!" links are broken due to template filename change

### ISSUE THREAD

**Issue by gene1wood** [qdm12/gluetun#1027]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki

### What's the issue?

In 56ea722f93fc78b4487d95219b5f6bc2a66fed07 the GitHub issue template was changed from `wiki issue.md` to `wiki issue.yml`.

All of the links in the wiki that say `🐛 Found a bug in the Wiki?!` link to the old filename which no longer exists

https://github.com/qdm12/gluetun/issues/new?assignees=&labels=%F0%9F%93%84+Wiki+issue&template=wiki+issue.md&title=Wiki+issue%3A+

As a result, whenever you click any of these links in the wiki, it takes you to a 500 error on GitHub.

These links need to be changed to this

https://github.com/qdm12/gluetun/issues/new?assignees=&labels=%F0%9F%93%84+Wiki+issue&template=wiki+issue.yml&title=Wiki+issue%3A+

**Comment by gene1wood** [comment]
The problem is present in these wiki pages
* `Home.md`
* `_Footer.md`
* `_Sidebar.md`

**Comment by qdm12** [comment]
Done! Awesome 👍 

I really need to have this Wiki as a separate repository to accept PRs, this is shame github doesn't support this with their wiki 😢
