### ISSUE TITLE
Feature request: Port forwarding for Windscribe

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#103]

**Comment by harrv** [comment]
@qdm12 It would be awesome if whatever you come up with worked with [Windscribe ephemeral port forwarding](https://windscribe.com/support/article/37/what-is-ephemeral-port-forwarding-and-how-to-use-it), even if that meant I had to manually request a port through their page every week and update an environment variable in docker-compose.yml. In the end, I'd like to use that forwarded port with a qbittorrent container that has `network_mode: "service:gluetun"`.

**Comment by qdm12** [comment]
@harrv actually it has been working with it all along 😄 Sorry I haven't answered earlier. Simply set `FIREWALL_VPN_INPUT_PORTS` to the port you got assigned from their web UI and it should work 😉 I've [updated the Wiki](https://github.com/qdm12/gluetun/wiki/Port-forwarding#windscribe) with that, although Windscribe could had been in the `Other VPN providers` section too.

Feel free to subscribe to the issue #426 so you could update the firewall input port more easily without having to restart the container(s). Cheers!
