### ISSUE TITLE
FastestVPN gluetun container unhealthy

### ISSUE THREAD

**Issue by rkbest13** [qdm12/gluetun#1038]
I have been trying to use fastestvpn with the docker as in the wiki setting, but any country or server i picks reurns unhelthy container. 
The logs show the connection started but 'Sent packets are not comperssed...'
UDP link local: (not bound)
UDP link remote: IP
Healthcheck: program has been unhealthy for xx m
[VPN]: Stopping.

This repeats and i can never get a connection established. I used the server listed on wiki and also from fastestVPN website with now luck. Tries, Romania, Switzerland, Sweden  with same results. Then tried with German servers that returned connection refused CODE 111. 

What is wrong . Could the container need more Env variables in this version that is limiting the operation.

**Comment by qdm12** [comment]
I need more information, please create a big issue using [this link](https://github.com/qdm12/gluetun/issues/new?assignees=&labels=%3Abug%3A+bug&template=bug.yml&title=Bug%3A+) and fill up the fields, especially the full logs.
