### ISSUE TITLE
Wiki issue: Public IP repsonse wrong

### ISSUE THREAD

**Issue by Fietspomp86** [qdm12/gluetun#1043]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/HTTP-control-server

### What's the issue?

According the WiKi, the HTTP control server will respond with "public_ip" at "/v1/publicip/ip".
However, I'm not sure when it has been changed, now it responds with just "ip".

Here's my "v1/publicip/ip"

`{"ip":"9.99.999.999","region":"North Holland","country":"Netherlands","city":"Amsterdam","loc":"52.3740,4.8897","org":"AS34971 Prometeus di Daniela Agro","postal":"1012","timezone":"Europe/Amsterdam"}`

**Comment by qdm12** [comment]
Indeed! Reverted it in de62dde283cf03d4e15897285a2cf9f618266390 to keep retro-compatibility, so it's now back to `public_ip`

**Comment by jnines** [comment]
With de62dde `/v1/publicip/ip` is giving me
`{"region":"Texas","country":"United States","city":"Dallas","loc":"32.7831,-96.8067","org":"AS174 Cogent Communications","postal":"75201","timezone":"America/Chicago"}`

Basically everything but the IP

**Comment by qdm12** [comment]
Re-fixed in 037f19e852b7e19d5185b930b1fe55b01707b72a
