### ISSUE TITLE
Configurable ports for containers with the same image

### ISSUE THREAD

**Issue by A54DH** [qdm12/gluetun#1061]
Hi, not sure if this is something that's already been implemented (I've searched the WIKI to no avail). I'm looking to have two containers routed through gluten but can't get it working.

Scenario example:

Say you've got two containers in docker, let's say they're radarr. Ones for 4K ones for 1080P. As both point to the same ports 7878, you can't access one of them because it can't bind to the port because it's in use. Is there a way around this? I've tried specifying the port myself for the container, but it then throws an error about a conflict with gluetun.

**Comment by leo15dev** [comment]
If you used Shadowsocks , try 

```
Container A 
   ports:
      -18388:8388/tcp # Shadowsocks
      -18388:8388/udp # Shadowsocks

Container B 
   ports:
      -28388:8388/tcp # Shadowsocks
      -28388:8388/udp # Shadowsocks
```

then you have two gluetun Container but  used same docker images.

**Comment by qdm12** [comment]
No, no workaround afaik.

Your program (such as radar) should have its port configurable internally, and, if not, create an issue there to have it configurable.

There might be some routing/ruling ninja possible to do this, but then security (leak) might be affected and it becomes a host routing nightmare I'd rather avoid to support for all users 😅

But if you ever find a solution, please share it and I can add it to the Wiki!
