### ISSUE TITLE
Wiki issue: wrong account name on ivpn page

### ISSUE THREAD

**Issue by swixfort** [qdm12/gluetun#1075]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/IVPN#vpn-port-forwarding

### What's the issue?

Under _VPN Port Forwarding_ the first point says "Log in your Mullvad account at https://ivpn.net/en/account", it should be _IVPN Account_ instead of _Mullvad account_

**Comment by qdm12** [comment]
Thanks, fixed! 👍
