### ISSUE TITLE
Feature request: P2P for ProtonVPN

### ISSUE THREAD

**Issue by danielriddell21** [qdm12/gluetun#1076]
### What's the feature 🧐

Allow Port Forwarding on ProtonVPN. 

I am hitting an issue with qBittorrent where passing it through gluetun will return me

`cannot process request for client 172.19.0.13:53049: Get "http://example.com": read tcp 10.45.0.8:46256->176.31.225.118:80: read: connection reset by peer`

I believe this is because no port is open protonvpn side. It seems protonvpn does offer fortwarding on there p2p servers so would be good to know if this is possible with gluetun.

### Extra information and references

This seems to be possible now via the cli
https://github.com/Rafficer/linux-cli-community/blob/master/USAGE.md#commands

**Comment by qdm12** [comment]
I think this error is completely unrelated to port forwarding, it's just the peer `176.31.225.118` closed the connection you initiated to them for whatever reason.

BUT could you link up some documentation on port forwarding for protonvpn? I can have a look and implement it some day.

**Comment by N47H4N** [comment]
would it help?

https://protonvpn.com/support/port-forwarding/

I'm also looking to use port forwarding for ProtonVPN

**Comment by qdm12** [comment]
@danielriddell21 please pull the latest image and try again? This changes https://github.com/qdm12/gluetun/issues/1103#issuecomment-2260712551 might solve your issue.

**Comment by qdm12** [comment]
Port forwarding (and also wireguard) is supported for Protonvpn, I'm closing this 😉  There is also auto-filtering of servers supporting p2p if port forwarding is requested on Gluetun's side.
