### ISSUE TITLE
Wiki issue: Different default options for healthcheck url

### ISSUE THREAD

**Issue by iluvatyr** [qdm12/gluetun#1085]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Health-options

### What's the issue?

I just wanted to let you know that within https://github.com/qdm12/gluetun/wiki/Health-options it shows github.com:443 as default and within https://github.com/qdm12/gluetun/wiki/Healthcheck#internal-healthcheck it shows cloudflare.com:443

**Comment by qdm12** [comment]
Done thanks for pointing it out!
