### ISSUE TITLE
Mullvad, wireguard on unraid

### ISSUE THREAD

**Issue by Brutus11111** [qdm12/gluetun#1096]
I'm new to docker. I'm trying to setup an Unraid server and use Gluetun. 

I have an account with Mullvad and wish to use their Wireguard system with Gluetun on the Unraid server. 

So in Unraid, I search for Gluetun, press install. It then asks me a whole bunch of things to fill out. 

I've set:
TIMEZONE: Europe/Amsterdam
VPN_TYPE: wireguard
WIREGUARD_PRIVATE_KEY: the line behind PrivateKey in the config file
WIREGUARD_ADDRES: 10.65.26.44/32
WIREGUARD_ENDPOINT_IP: 185.65.134.130
WIREGUARD_ENDPOINT_PORT: 3113
WIREGUARD_PUBLIC_KEY: from the config file

Now when I press Apply it should install, but instead it asks me for my OpenVPN username. I don't have one. When I fill out the Mullvad account name, it asks me for my OpenVPN password. I'm not trying to use OpenVPN. I'm trying to use Wireguard.

**Comment by qdm12** [comment]
This is an Unraid issue, please read https://github.com/qdm12/gluetun/discussions/550 since I can't really help. DiamondPrecisionComputing is probably the one who would know how to fix this. Thanks! Feel free to re-comment here in case you or DiamondPrecisionComputing need help.
