### ISSUE TITLE
Feature request: SERVER_CITIES for NordVPN

### ISSUE THREAD

**Issue by Andystew94** [qdm12/gluetun#1097]
### What's the feature 🧐

The addition of the "SERVER_CITIES" environment variable for NordVPN.

### Extra information and references

I am looking to force a connection to:

        "vpn": "openvpn",
        "country": "Australia",
        "city": "Brisbane",

However, the only variable which works is SERVER_REGIONS=Australia. This often leads to longer ping times and slower speeds as it may select a connection in Perth (for example).

**Comment by qdm12** [comment]
Nordvpn doesn't expose the city for each server on their API endpoint: https://nordvpn.com/api/server
Therefore I cannot have the city for each server (at least reliably) in Gluetun, so I will keep it as is.

On the other hand, you can filter using `SERVER_HOSTNAMES` to get the right server you want, if that's your thing 😉
