### ISSUE TITLE
Connection issue to VPN Unlimited Server

### ISSUE THREAD

**Issue by sinjinsmythe** [qdm12/gluetun#1099]
Hey Quentin

My connection has been rock solid for over a year to my VPN through Gluetun to VPN Unlimited, I pulled the latest gluetun image today and have now run into some issues connecting again.  I think the connection still thinks its connecting to "PIA" rather than VPN Unlimited and doesn't seem to recognise the Country name Romania as i think its looking at the PIA Country lis.  I matched it up as per the wiki, but i think the VPN Service Provider isn't being read in correctly.

This is my command to create the container.

`docker run -d --name gluetun --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER="vpn unlimited" -e SERVER_COUNTRIES=Romania -e SERVER_HOSTNAMES=ro.vpnunlimitedapp.com -e TZ=europe/london -e PUID=1024 -e PGID=101 -v "/volume1/configs/gluetun:/gluetun" -e OPENVPN_CLIENTCRT_SECRETFILE=/gluetun/client.crt -e OPENVPN_CLIENTKEY_SECRETFILE=/gluetun/client.key -e PORT_FORWARDING=on -e FIREWALL_VPN_INPUT_PORTS=51413 -e PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port -e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf  -e OPENVPN_USER=myemail@server.com -e OPENVPN_PASSWORD=ofkyoOMnj8sk qmcgaw/gluetun`

This is the error log when i launch the container :

```
========================================,
========================================,
=============== gluetun ================,
========================================,
=========== Made with ❤️ by ============,
======= https://github.com/qdm12 =======,
========================================,
========================================,
,
Running version latest built on 2022-08-01T21:13:33.396Z (commit a6f00f2),
,
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new,
🐛 Bug? https://github.com/qdm12/gluetun/issues/new,
✨ New feature? https://github.com/qdm12/gluetun/issues/new,
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new,
💻 Email? quentin.mcgaw@gmail.com,
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12,
2022-08-08T18:26:36Z WARN You are using the old environment variable PORT_FORWARDING, please consider changing it to PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING,
2022-08-08T18:26:36Z WARN You are using the old environment variable PORT_FORWARDING_STATUS_FILE, please consider changing it to PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE,
2022-08-08T18:26:36Z INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.5,
2022-08-08T18:26:36Z INFO [routing] local ethernet link found: eth0,
2022-08-08T18:26:36Z INFO [routing] local ipnet found: 172.17.0.0/16,
2022-08-08T18:26:36Z INFO [firewall] enabling...,
2022-08-08T18:26:37Z INFO [firewall] enabled successfully,
2022-08-08T18:26:37Z INFO [storage] merging by most recent 11232 hardcoded servers and 11232 servers read from /gluetun/servers.json,
2022-08-08T18:26:38Z ERROR VPN settings: provider settings: server selection: the country specified is not valid: one or more values is set but there is no possible value available,
2022-08-08T18:26:38Z INFO Shutdown successful
```

Grateful for any advice you could give

**Comment by qdm12** [comment]
Have you tried `rm "/volume1/configs/gluetun/servers.json"`? Maybe there is something wrong in there? 🤔 

I just ran `docker run -it --rm --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER="vpn unlimited" -e SERVER_COUNTRIES=Romania -e OPENVPN_USER=a -e OPENVPN_PASSWORD=a -e OPENVPN_CERT=YQo= -e OPENVPN_KEY=YQo= qmcgaw/gluetun` and it doesn't complain about the country.

**Comment by sinjinsmythe** [comment]
Hi Quentin

I deleted and recreated that server file.

When I ran my command to recreate the container

docker run -d --name gluetun --cap-add=NET_ADMIN -e
VPN_SERVICE_PROVIDER="vpn unlimited" -e SERVER_COUNTRIES=Romania -e
TZ=europe/london -e PUID=1024 -e PGID=101 -v
"/volume1/configs/gluetun:/gluetun" -e
OPENVPN_CLIENTCRT_SECRETFILE=/gluetun/client.crt -e
OPENVPN_CLIENTKEY_SECRETFILE=/gluetun/client.key -e
OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf  -e OPENVPN_USER=
***@***.*** -e OPENVPN_PASSWORD=mypaswordhere qmcgaw/gluetun

I got :


========================================,
========================================,
=============== gluetun ================,
========================================,
=========== Made with ❤️ by ============,
======= https://github.com/qdm12 =======,
========================================,
========================================,
,
Running version latest built on 2022-08-15T23:58:49.621Z (commit a182e35),
,
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new,
🐛 Bug? https://github.com/qdm12/gluetun/issues/new,
✨ New feature? https://github.com/qdm12/gluetun/issues/new,
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new,
💻 Email? ***@***.***,
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12,
2022-08-24T20:55:57Z INFO [routing] default route found: interface eth0,
gateway 172.17.0.1 and assigned IP 172.17.0.5,
2022-08-24T20:55:57Z INFO [routing] local ethernet link found: eth0,
2022-08-24T20:55:57Z INFO [routing] local ipnet found: 172.17.0.0/16,
2022-08-24T20:55:57Z INFO [firewall] enabling...,
2022-08-24T20:55:57Z INFO [firewall] enabled successfully,
2022-08-24T20:55:58Z INFO [storage] merging by most recent 11432 hardcoded
servers and 11432 servers read from /gluetun/servers.json,
2022-08-24T20:55:58Z ERROR VPN settings: provider settings: server
selection: the country specified is not valid: one or more values is set
but there is no possible value available,
2022-08-24T20:55:58Z INFO Shutdown successful

I can see the servers in the servers.json file so there are definitely
there.

      {
        "vpn": "openvpn",
        "country": "Romania",
        "hostname": "ro.vpnunlimitedapp.com",
        "udp": true,
        "ips": [
          "77.81.98.70",
          "93.115.92.207",
          "93.115.92.208",
          "185.144.83.11",
          "185.144.83.13"
        ]

**Comment by qdm12** [comment]
Ah it's because of `OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf`. For retro-compatibility reasons, Gluetun assumes you want to use the `custom` provider if you set the custom configuration path. Therefore for the `custom` provider, yeah, there is no country available. I'll change the code to override it with the value in `VPN_SERVICE_PROVIDER`, please leave this opened for now.

**Comment by qdm12** [comment]
Done in fba73a0a0f4fe4e68be984973dfecfbc348b3918

**Comment by sinjinsmythe** [comment]
Thank you so much!
I'll test this out later today 😊

**Comment by sinjinsmythe** [comment]
Quentin I can confirm this is working again now. Thank you so much for your
assistance 😁👍👍
