### ISSUE TITLE
Wiki issue: Health-options page says the default is github.com but it's actually cloudflare.com

### ISSUE THREAD

**Issue by gene1wood** [qdm12/gluetun#1100]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Health-options

### What's the issue?

This wiki page https://github.com/qdm12/gluetun/wiki/Health-options also still says the default is `github.com`. Would you update it to `cloudflare.com`? (Related to #1028)

**Comment by qdm12** [comment]
Indeed, re-fixed (maybe some bad git force push of some kind reverted it)
