### ISSUE TITLE
Wiki issue: Change examples using port 8888 to a different port to avoid collision with proxy

### ISSUE THREAD

**Issue by gene1wood** [qdm12/gluetun#1101]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding

### What's the issue?

On this wiki page https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding
it uses port `8888` as an example port that you would want to forward from your VPN provider.

This example would be confusing as port 8888 is used by the HTTP proxy. Would you change the example port to some other value?

**Comment by qdm12** [comment]
Done 👍 !
