### ISSUE TITLE
Wiki issue: Mistype in openvpn custom config help page. Volume path needs to swap '.' for '/'

### ISSUE THREAD

**Issue by littlejeem** [qdm12/gluetun#1121]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/OpenVPN-configuration-file

### What's the issue?

on the page there is a really helpful example command for running the docker using customer openvpn file, it reads:
```docker run -it --rm --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER=custom -e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf -v /yourpath/custom.conf:/gluetun.custom.conf:ro -e OPENVPN_USER="youruser" -e OPENVPN_PASSWORD="yourpassword" qmcgaw/gluetun```

when used this generates a glutun error that the config file doesn't exist, this is because the docker volume has a . not a / in the path name, it should read.

```docker run -it --rm --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER=custom -e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf -v /yourpath/custom.conf:/gluetun/custom.conf:ro -e OPENVPN_USER="youruser" -e OPENVPN_PASSWORD="yourpassword" qmcgaw/gluetun```

**Comment by qdm12** [comment]
Awesome, thanks for taking the time to report it.
Fixed!
