### ISSUE TITLE
VPN provider support: HIDEME

### ISSUE THREAD

**Issue by Viciooso** [qdm12/gluetun#1131]
One of the following is required:

- Publicly accessible URL to a zip file containing the Openvpn configuration files
- Publicly accessible URL to a structured (JSON etc.) list of servers **and attach** an example Openvpn configuration file for both TCP and UDP
- Publicly accessible URL to the list of servers **and attach** an example Openvpn configuration file for both TCP and UDP

If the list of servers requires to login **or** is hidden behind an interactive configurator,
you can only use a custom Openvpn configuration file.
[The Wiki](https://github.com/qdm12/gluetun/wiki/Openvpn-file) describes how to do so.

**Comment by qdm12** [comment]
I'm closing this due to missing information. Feel free to edit and comment here once you added the required information as requested above.
