### ISSUE TITLE
Bug: cannot update files: Get "https://www.internic.net/domain/named.root": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by the-lazy-fox** [qdm12/gluetun#1140]
### Is this urgent?

Yes

### Host OS

Debian 11

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-08-15T23:58:49.621Z (commit a182e35)

### What's the problem 🤔

For few hours, it has decided to not connect anymore... No configuration changes on my side.
Logs mention WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Share your logs

```plain text
https://cp.thelazyfox.xyz/?11147278739d84b0#3yvPeWEvLVwYNRgdf286dVpqc9GvAd1unZVZrHLuGgrB
```

**Comment by qdm12** [comment]
It looks like it's working for me. It might had been a bad vpn connection perhaps. Also this will be thrown out with #137 soon, so closing this 😉 Thanks for reporting still.

**Comment by rkabrick** [comment]
Having same issue. Same OS & Arch... Except using Mullvad wireguard

**Comment by tomnieuwland** [comment]
> Having same issue. Same OS & Arch... Except using Mullvad wireguard

Did you resolve this? I am also having problems.

**Comment by qdm12** [comment]
If you see this, it just means http doesn't work and times out, so just the vpn connection doesn't work; try another server
