### ISSUE TITLE
Bug: Unraid not retaining Manual entries through GUI 

### ISSUE THREAD

**Issue by bguskey** [qdm12/gluetun#1147]
### Host OS

Unraid

### VPN service provider

IPVanish

### What are you using to run the container

docker run

### What is the version of Gluetun

latest

### What's the problem 🤔

When trying to add a Port for an external docker, Gluetun will accept it but then will not build it out once I hit apply. I apologize as I am fairly new to Unraid so I hope my explanation makes sense. From what I understand and have been reading on, it appears I may be one of the very few that use the GUI instead of the Terminal to make any changes to the docker.

The below screenshots show me adding the new Container Port 5, rebuilding the docker, then when I open the docker up again to Edit showing the new Port I added is not there.

![image](https://user-images.githubusercontent.com/49000211/189666158-e274ef73-1e05-4a24-b127-9c83ea25c41b.png)
![image](https://user-images.githubusercontent.com/49000211/189666729-5cd4bc8e-c3a7-421f-9317-faca7bf7af4e.png)
![image](https://user-images.githubusercontent.com/49000211/189666906-8a367cbb-ddf4-4f75-bf32-6e3e5d77b684.png)

### Share your logs

```plain text
2022-09-12T09:26:00-04:00 INFO Settings summary:
├── VPN settings:
| ├── VPN provider settings:
| | ├── Name: ipvanish
| | └── Server selection settings:
| | ├── VPN type: openvpn
| | └── OpenVPN server selection settings:
| | └── Protocol: UDP
| └── OpenVPN settings:
| ├── OpenVPN version: 2.5

| ├── User: [set]
| ├── Password: [set]
| ├── Network interface: tun0
| ├── Run OpenVPN as: root
| └── Verbosity level: 1
├── DNS settings:
| ├── DNS server address to use: 192.168.1.1
| ├── Keep existing nameserver(s): yes
| └── DNS over TLS settings:
| ├── Enabled: yes
| ├── Update period: every 24h0m0s
| ├── Unbound settings:
| | ├── Authoritative servers:
| | | └── cloudflare
| | ├── Caching: yes
| | ├── IPv6: no
| | ├── Verbosity level: 1
| | ├── Verbosity details level: 0
| | ├── Validation log level: 0
| | ├── System user: root
| | └── Allowed networks:
| | ├── 0.0.0.0/0
| | └── ::/0
| └── DNS filtering settings:
| ├── Block malicious: yes
| ├── Block ads: yes
| ├── Block surveillance: yes
| └── Blocked IP networks:
| ├── 127.0.0.1/8
| ├── 10.0.0.0/8
| ├── 172.16.0.0/12
| ├── 192.168.0.0/12
| ├── 169.254.0.0/16
| ├── ::1/128
| ├── fc00::/7
| ├── fe80::/10
| ├── ::ffff:7f00:1/104
| ├── ::ffff:a00:0/104
| ├── ::ffff:a9fe:0/112
| ├── ::ffff:ac10:0/108
| └── ::ffff:c0a8:0/112
├── Firewall settings:
| ├── Enabled: yes
| ├── Debug mode: on
| ├── VPN input ports:
| | ├── 8787
| | ├── 8112
| | └── 8989
| └── Input ports:
| ├── 8787
| ├── 8112
| └── 8989
├── Log settings:
| └── Log level: INFO
├── Health settings:
| ├── Server listening address: 127.0.0.1:9999
| ├── Target address: cloudflare.com:443
| ├── Read header timeout: 100ms
| ├── Read timeout: 500ms
| └── VPN wait durations:
| ├── Initial duration: 6s
| └── Additional duration: 5s
├── Shadowsocks server settings:
| └── Enabled: no
├── HTTP proxy settings:
| └── Enabled: no
├── Control server settings:
| ├── Listening address: :8000
| └── Logging: yes
├── OS Alpine settings:
| ├── Process UID: 1000
| ├── Process GID: 1000
| └── Timezone: America/New_York
├── Public IP settings:
| ├── Fetching: every 12h0m0s
| └── IP file path: /tmp/gluetun/ip
```

**Comment by qdm12** [comment]
That looks like an issue with Unraid and/or the Gluetun Unraid template. I don't personally have Unraid installed and don't manage this template either, so I can't really help. Please see https://github.com/qdm12/gluetun/discussions/550 instead and create an issue on the corresponding repository (from DiamondPrecisionComputing) or ask on the Unraid forums linked in that Github discussion. Closing this for now since this is not a Gluetun bug directly. Good luck!
