### ISSUE TITLE
Getting incorrect username or password when downloading

### ISSUE THREAD

**Issue by fwarren** [qdm12/gluetun#1155]
`docker pull  qmcgaw/gluetun` fails with:  incorrect username or password when downloading  

if a `git clone https://github.com/qdm12/gluetun.git` is performed  the `docker build . -t qmcgaw/gluetun` produces the following output
```
Using default tag: latest
Error response from daemon: Head "https://registry-1.docker.io/v2/qmcgaw/gluetun/manifests/latest": unauthorized: incorrect username or password
```

**Comment by qdm12** [comment]
The docker pull command works for me. Maybe you reached the free number of Docker pulls from docker hub?

Your build command is incorrect it should be `docker build -t qmcgaw/gluetun .`. You can also directly build using `docker build -t qmcgaw/gluetun https://github.com/qdm12/gluetun.git`

**Comment by fwarren** [comment]
Yeah I am baffled. I logged in with another local user account that can use docker and had no problem with doing the pull. You can mark this closed. Thank you very much for your prompt response
