### ISSUE TITLE
Bug: Leaks when healthcheck fails and vpn connection is restarted

### ISSUE THREAD

**Issue by dfadev** [qdm12/gluetun#1175]
### Is this urgent?

No

### Host OS

openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-09-14T13:28:28.429Z (commit e5be20d)

### What's the problem 🤔

T-Mobile does DPI and will disable your connection if it detects "bad" packets.

Whenever gluetun's healthcheck fails and restarts the VPN, T-Mobile kills my cell connection leading me to believe there is some leaking going on.

I think it's because there's a default route that points to the container's network gateway that doesn't apply until the VPN is disconnected.

### Share your logs

```plain text
❯ docker exec -it gluetun /bin/sh
/ # ip r
0.0.0.0/1 via 10.6.112.1 dev tun0 
default via 10.0.0.1 dev eth0 
10.0.0.0/24 dev eth0 proto kernel scope link src 10.0.0.2 
10.6.112.0/24 dev tun0 proto kernel scope link src 10.6.112.207 
95.181.XXX.XX via 10.0.0.1 dev eth0 
128.0.0.0/1 via 10.6.112.1 dev tun0
```

**Comment by qdm12** [comment]
I don't think so, the firewall only allows a vpn connection to the vpn server ip:port and everything else is blocked, whatever the routes are.

For reference here's the vpn connection setup code for the firewall: https://github.com/qdm12/gluetun/blob/master/internal/firewall/vpn.go#L27-L56

You can also exec in the container and print the iptables rules if you want (or run FIREWALL_DEBUG=on).

Maybe I'm wrong though, let me know what you find on your end. If you want, I can build you a custom image making the restart take 1 minute for debugging purposes.

**Comment by dfadev** [comment]
Yeah I think you're right.  I was able to repro with the VPN up and that route deleted, so it must be something else going on.
