### ISSUE TITLE
Feature request: Allow multiple input ports for Mullvad

### ISSUE THREAD

**Issue by mikewilzn** [qdm12/gluetun#1184]
### What's the feature 🧐

Mullvad allows you to have multiple forwarded ports for a single Wireguard configuration, however it seems that the `FIREWALL_VPN_INPUT_PORTS` variable only accepts one value.

### Extra information and references

I tried various yaml formats such as
```yaml
FIREWALL_VPN_INPUT_PORTS: "12345;54321"
```
and
```yaml
FIREWALL_VPN_INPUT_PORTS:
               - 12345
               - 54321
```
but it did not want to accept it. Looking at `ports.go` it seems only one value is accepted anyway.

**Comment by olvier** [comment]
https://github.com/qdm12/gluetun/issues/196#issuecomment-660758293

**Comment by qdm12** [comment]
Thanks @olvier 

@mikewilzn as described in the wiki at https://github.com/qdm12/gluetun/wiki/Firewall-options it's a **comma** separated value (not semi-colon). Also the code reading the env variable is at https://github.com/qdm12/gluetun/blob/e583f9de47b2b1a2496fe3e47f1b231c77cc5916/internal/configuration/sources/env/firewall.go#L13 and the function is `envToCSV` so it's a comma separated value (csv).

**Comment by GlassedSilver** [comment]
> Should be cancelled, mullvad no longer supports port forwarding :(

Not supported, but still works. Also why burn this bridge, any VPN could at any moment support multi-port forwarding per connection. We don't need to argue about the likelihood, all that matters is that it's pointless to kill syntax support for something that can change any moment for the better.
