### ISSUE TITLE
/bin/sh: /entrypoint: not found

### ISSUE THREAD

**Issue by nfornarotto** [qdm12/gluetun#1202]
I recently updated gluetun and I am now showing an unhealthy container and outputting

/bin/sh: /entrypoint: not found

Any insight on how to fix this?

**Comment by qdm12** [comment]
I guess you are using Portainer? Just remove the container completely and re-setup it. That's a bug where the entrypoint doesn't get updated with a newer image (it changed from /gluetun to /gluetun-entrypoint I think)
