### ISSUE TITLE
Feature request (?): Torguard port fowarding (or update to docs)

### ISSUE THREAD

**Issue by perry-mitchell** [qdm12/gluetun#1212]
### What's the feature 🧐

It's not clear, through the wiki or other documentation, whether or not port forwarding is available for all VPN providers that support it, or just for PIA (as linked to from the readme). Could you kindly confirm whether or not it is supported at a general level? Should port forwarding work with Torguard?

**Comment by bnhf** [comment]
@perry-mitchell 

Port forwarding works for me (AirVPN), and should work for any provider that supports it. In addition to setting it up on your provider's website, you also need to open the port(s) in the gluetun firewall using the environment variable:

```
        ports:
            - xxxx:xxxx # Replace with the same port number open on your VPN provider and through the firewall
        environment:
            - FIREWALL_VPN_INPUT_PORTS=xxxx # Replace with the port number or comma separated list
```

These ports typically need to be configured on the setup page of your application as well.

**Comment by qdm12** [comment]
Thanks @bnhf it's also documented in https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding

As far as I know, only PIA requires some custom code to obtain the port forwarded, all the other providers can be configured through their web ui or similar, so gluetun just needs its firewall to allow traffic through it.

**Comment by perry-mitchell** [comment]
Thanks for the quick assistance! Much appreciated.. :)
