### ISSUE TITLE
Bug: Purevpn dedicated IP

### ISSUE THREAD

**Issue by Chris3481** [qdm12/gluetun#1215]
### VPN service provider

PureVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Hello !
I purchased a Purevpn dedicated address IP with port-forwarding feature. 
It looks like it's not possible to use this feature with this container.

I tryed with the  VPN_ENDPOINT_IP env variable but it didn't work.

Thanks for you're help !

### Share your logs

```plain text
vpn         | 2022-10-25T21:08:48+02:00 INFO [firewall] allowing VPN connection...
vpn         | 2022-10-25T21:08:48+02:00 INFO [openvpn] OpenVPN 2.5.6 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
vpn         | 2022-10-25T21:08:48+02:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
vpn         | 2022-10-25T21:08:48+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]172.94.15.209:53
vpn         | 2022-10-25T21:08:48+02:00 INFO [openvpn] UDP link local: (not bound)
vpn         | 2022-10-25T21:08:48+02:00 INFO [openvpn] UDP link remote: [AF_INET]172.94.15.209:53
vpn         | 2022-10-25T21:09:30+02:00 INFO [healthcheck] program has been unhealthy for 41s: restarting VPN
vpn         | 2022-10-25T21:09:30+02:00 INFO [vpn] stopping
```

### Share your configuration

```yml
environment:
      - VPN_SERVICE_PROVIDER=purevpn
      - OPENVPN_USER=xxxxx
      - OPENVPN_PASSWORD=xxxx
      - VPN_ENDPOINT_IP=172.94.xxx.xxx
```

**Comment by qdm12** [comment]
How does the openvpn config downloaded from Purevpn changes for a dedicated ip? Is it even possible with just openvpn? 🤔 

Sometime the endpoint server vpn ip address is not the same as the vpn public ip you get (aka dedicated ip), maybe that's the case here?

**Comment by Chris3481** [comment]
Thanks for your reply. I'm so sad, bu I've seen with the pureVpn customer support and they told me that it's not possible to use a dedicated IP using openVpn. 

Luckily  I got a refund (1 month trial). If you're trying to setup a seedbox on a raspberry pie, I do not recommend this provider.

Do you know a VPN provider who allows port forwarding that works with tour service ?

**Comment by bnhf** [comment]
@Chris3481 

Just a thought, but you could set up your own VPN server with a dedicated IP using a cloud provider like Vultr. Could be as cheap as $5/mo. Choose Debian or Ubuntu, and install OpenVPN server with the PiVPN script.

You could then connect to that server via Gluetun, using the Custom Provider option -- and a .ovpn file generated from your cloud-based server.

**Comment by Chris3481** [comment]
Thanks, looks like it's the best solution to have a dedicated vpn IP address for almost nothing :)

**Comment by qdm12** [comment]
Ok closing this then.

> Do you know a VPN provider who allows port forwarding that works with tour service ?

What port do you need forwarded for Tor? AFAIK most providers assign you a port but you can't really pick so that can be problematic.
