### ISSUE TITLE
Bug: Docker won't run if certain VPN passwords have exclamation marks

### ISSUE THREAD

**Issue by skudave** [qdm12/gluetun#1225]
### Is this urgent?

No

### Host OS

Slackware 15.0 (Unraid)

### CPU arch

x86_64

### VPN service provider

PrivateVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2022-10-31T11:25:29.199Z (commit 192a7a5)

### What's the problem 🤔

Certain passwords used for the VPN containing a "!" returns: "ERROR VPN settings: OpenVPN settings: password is empty"

pas!sword - error
password! - works ok

Edit: Now noticing other special characters throw a fit too like "&" but "*" and "@" work ok apparently.

### Share your logs

```plain text
2022-11-06T19:28:26Z INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.10
2022-11-06T19:28:26Z INFO [routing] local ethernet link found: eth0
2022-11-06T19:28:26Z INFO [routing] local ipnet found: 172.17.0.0/16
2022-11-06T19:28:26Z INFO [firewall] enabling...
2022-11-06T19:28:26Z INFO [firewall] enabled successfully
2022-11-06T19:28:26Z INFO [storage] merging by most recent 13220 hardcoded servers and 13220 servers read from /gluetun/servers.json
2022-11-06T19:28:26Z ERROR VPN settings: OpenVPN settings: password is empty
2022-11-06T19:28:26Z INFO Shutdown successful
```

### Share your configuration

```yml
docker run -it --rm \
	--cap-add=NET_ADMIN \
	--name gluetun \
	-e VPN_SERVICE_PROVIDER=privatevpn \
	-e OPENVPN_USER=username \
	-e OPENVPN_PASSWORD=pas!sword \
	-e SERVER_COUNTRIES=Netherlands \
	-v /mnt/user/appdata/gluetun:/gluetun \
	qmcgaw/gluetun
```

**Comment by qdm12** [comment]
That's just due to your shell not escaping special symbols. Use `-e OPENVPN_PASSWORD="pas!sword"` and it'll work. Or you can escape characters with `\`.

FYI Gluetun is full Go code without any shell scripting, so it handles anything you throw at it since there is no shell or interpreter involved.

**Comment by skudave** [comment]
Thanks! I did try the quotes before posting, that doesn't work for me. Escaping with the backslash does work however, and I should know that from regex.

**Comment by qdm12** [comment]
Uh interesting, maybe try `-e "OPENVPN_PASSWORD=pas!sword"`?

**Comment by skudave** [comment]
That doesn't work either, it's being stubborn. I just ended up changing my password and I do know backslash escapes work for me.

**Comment by lmatzer** [comment]
I would like to see this reopened. Escaping and quotes both don't work here. Can it really be the only solution not to allow special characters in passwords? What if we have no influence in the creation process of our credentials?
