### ISSUE TITLE
Wiki issue: port taken

### ISSUE THREAD

**Issue by rightsaidfred99** [qdm12/gluetun#1256]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Port-mapping

### What's the issue?

All that happens is this

Bind for 0.0.0.0:9000 failed: port is already allocated

**Comment by bnhf** [comment]
@rightsaidfred99 

Not much information to go on here -- but the obvious question:

Is port 9000 already in use on your system? Portainer for one uses 9000 as its default http port.

In the Wiki example that you reference port 9000 is being forwarded in gluetun on behalf of the second container in the stack called xyz. If xyz requires port 9000, but it's not available on your system, you'd map it to another port (say 9100) like so:
```
   ports:
      - 9100:9000/tcp
```

**Comment by qdm12** [comment]
Thanks @bnhf for the answer, which is correct. This is just an example on top of this :wink:
