### ISSUE TITLE
Wiki issue: Broken link on HTTP-control-server-options page

### ISSUE THREAD

**Issue by gene1wood** [qdm12/gluetun#1262]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/HTTP-control-server-options

### What's the issue?

The line

> This is to configure the [HTTP Control server](HTTP Control server).

is a broken link and probably meant to be

> This is to configure the [HTTP control server](HTTP control server).

**Comment by qdm12** [comment]
Thanks for reporting it, fixed!
