### ISSUE TITLE
VPN provider support: ivacy

### ISSUE THREAD

**Issue by Vultilion** [qdm12/gluetun#1281]
One of the following is required:

- Publicly accessible URL to a zip file containing the Openvpn configuration files
[Link rar](https://support.ivacy.com/vpnusecases/openvpn-files-windows-routers-ios-linux-and-mac/)
[Link zip](https://ivacy-blog-assets.s3.amazonaws.com/blog/wp-content/uploads/2022/03/OpenVPN-Configs.zip)
- Publicly accessible URL to a structured (JSON etc.) list of servers **and attach** an example Openvpn configuration file for both TCP and UDP
- Publicly accessible URL to the list of servers **and attach** an example Openvpn configuration file for both TCP and UDP

If the list of servers requires to login **or** is hidden behind an interactive configurator,
you can only use a custom Openvpn configuration file.
[The Wiki](https://github.com/qdm12/gluetun/wiki/Openvpn-file) describes how to do so.
[OpenVPN-Configs.zip](https://github.com/qdm12/gluetun/files/10198981/OpenVPN-Configs.zip)

**Comment by qdm12** [comment]
Awesome thanks for all the details provided :medal_military: I linked up your issue in the previous already existing ivacy issue, please subscribe (button on the right) to #794 to be notified when it's implemented. Also sorry I'm facing a rather mega huge backlog for Gluetun (and work, life etc.), so please be patient :pray:
