### ISSUE TITLE
Wiki issue: /etc/systemd/system/tun.service

### ISSUE THREAD

**Issue by schnillerman** [qdm12/gluetun#1296]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Synology-prerequisites

### What's the issue?

Fiddling with the tun.service file does not seem necessary (at least for me, DSM 7.1.x).

Under https://www.tecmint.com/load-and-unload-kernel-modules-in-linux/, it says:

_In Linux, all modules end with the .ko extension, and they are normally loaded automatically as the hardware is detected at system boot._

For my current setup ([qbittorrent-openvpn](https://hub.docker.com/r/guillaumedsde/qbittorrent-openvpn/#!)), merely installing tun with insmod suffices, it's automatically loaded and available even across restart cycles of both the container and the whole DSM.

**Comment by qdm12** [comment]
Fixed, thanks for the information 👍

**Comment by elcid2012** [comment]
I had to re-run the `sudo insmod /lib/modules/tun.ko` command after a recent DSM update (DSM 7.1.1-42962 Update 4)

**Comment by luispuerto** [comment]
At least in my case, this is not happening and I need to create the service.

**Comment by elcid2012** [comment]
Had to run it again for DSM 7.1.1-42962 Update 5.

**Comment by drewstopherlee** [comment]
Same here, also running DSM 7.1.1-42962 Update 5.

**Comment by Kamikaze01git** [comment]
DS920+ with 7.2-64551

Have to re-run the `sudo insmod /lib/modules/tun.ko` command after every scheduled restart :(

Will try the script.

**Comment by Delgrey** [comment]
Having all sorts of issues trying to get gluetun running on Container Manager under DSM 7.2.1. Is this module command still and issues in 2024? When I run the command in the docs, it already seems to be there. It gives the following output. Do the docs need to be updated? Or am I missing something?

`sudo insmod /lib/modules/tun.ko`

**Comment by Silversurfer79** [comment]
> Having all sorts of issues trying to get gluetun running on Container Manager under DSM 7.2.1. Is this module command still and issues in 2024? When I run the command in the docs, it already seems to be there. It gives the following output. Do the docs need to be updated? Or am I missing something?
> 
> `sudo insmod /lib/modules/tun.ko`

Having the same issue... 
![image](https://github.com/user-attachments/assets/4bff28ac-5613-4ed7-8a62-5ca2856dc8fb)

**Comment by nota3k** [comment]
Any fix for this? Seeing the same thing on DSM 7.2.2-72806.

**Comment by Kamikaze01git** [comment]
i am having no problems with following settings

i am (also) on newest 7.2.2-72806 with my DS920+
<img width="457" alt="image" src="https://github.com/user-attachments/assets/832ae767-312a-41a2-b6ef-b873e13902a1">

and a scheduled job at every start as root
<img width="495" alt="image" src="https://github.com/user-attachments/assets/e9ae4452-82c1-4c82-9cb1-5f089d88cb9b">

**Comment by Silversurfer79** [comment]
Did some testing,

I have added the bootup script and it is created on boot. 
The Gluetun container now runs and in turn Transmisson now connects again.

Epic, thanks @Kamikaze01git !

**Comment by juanbretti** [comment]
Still not working for me. Any new ideas? I have `DSM 7.2.2-72806 Update 2`.
Some days it works, most of the days it does not work.

OpenVPN using the included application, works.
I mean:
`Control Panel > Network > Network Interface > Create... Connect...`
