### ISSUE TITLE
Feature request: Add curl to the image

### ISSUE THREAD

**Issue by jaroslawjanas** [qdm12/gluetun#1305]
### What's the feature 🧐

Add `curl` to the image.

It's practical and a pain in the butt to install myself.

**Comment by frepke** [comment]
I don't know if it's coming in Gluetun, but installing curl by yourself isn't that hard.
Run `docker exec -ti gluetun apk add curl` in the terminal and done.

**Comment by jaroslawjanas** [comment]
> I don't know if it's coming in Gluetun, but installing curl by yourself isn't that hard. Run `docker exec -ti gluetun apk add curl` in the terminal and done.

Oh yeah, I know.
I actually edited the `Dockerfile` instead of doing that.
But it'd be nice just to have it available.
I think it's worth considering.

**Comment by qdm12** [comment]
You can also have a Dockerfile

```Dockerfile
FROM qmcgaw/gluetun
RUN apk add curl
```

And build it with `docker build -t qmcgaw/gluetun .`

I'm trying to reduce the size and attack surface as much as possible, so adding `curl` goes against this. You can however use `wget` which is built-in Alpine's busybox (although note it doesn't https validate really unless they fixed it already, so would have to `apk add wget` to have a TLS validating http client).

**Comment by jaroslawjanas** [comment]
Fair.
Also, `wget` is kinda useless for what I need.

**Comment by qdm12** [comment]
@jaroslawjanas What do you need?
