### ISSUE TITLE
Wiki issue: Surfshark Wireguard IP

### ISSUE THREAD

**Issue by hkoci** [qdm12/gluetun#1310]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Surfshark

### What's the issue?

When using the Wireguard interface on Surfshark, the provided Wireguard address is incorrect.

I downloaded the United Kingdom (London) profile from Surfshark below:

```
#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = REDACTED
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = REDACTED
AllowedIPs = 0.0.0.0/0
Endpoint = uk-lon.prod.surfshark.com:51820
```

The WIREGUARD_ADDRESSES variable should be `10.14.0.2/16` for Surfshark for Wireguard to work, it is currently set to `10.64.222.21/16` on the wiki.

After setting it to the same IP as the profile - can confirm this works on Docker running on Proxmox container.

**Comment by qdm12** [comment]
Thanks for reporting the issue! However, as far as I know, the interface address is user specific so this serves as an example. If it's not user specific please correct me by commenting on this issue though! Thanks

**Comment by frepke** [comment]
@qdm12 Maybe you can use `10.14.0.2/16` in the wiki as the "sample" address. For me this address is the same and a while ago there was an issue where user ? had the same address.
