### ISSUE TITLE
Bug: JSON password parser fails to account for quotes then fails "ERROR unexpected end of JSON input"

### ISSUE THREAD

**Issue by SillyKeith** [qdm12/gluetun#1320]
### Is this urgent?

No

### Host OS

Unraid

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-12-15T10:02:42.178Z (commit 490693b)

### What's the problem 🤔

The following error occurs and the container won't start if your VPN password contains quotes or double quotes ( '  " ) 
**ERROR unexpected end of JSON input:**

It would be great if the JSON parser were able to process these without quitting prematurely.

Repro:
1. Have your VPN password contain a quote or double quote.  Mine had both.   12345'345"2345
2. Setup GluetunVPN docker using the wiki for PIA
3. Start the container.
4. The container never starts and throws: **ERROR unexpected end of JSON input:**
5. Change your VPN password and remove any quotes/double quotes.
6. Modify the docker VPN password variable 
7. Container starts fine.

Workaround: Change your VPN password and omit any quotes AND double quotes.

### Share your logs

```plain text
I've wiped the container logs already after fixing this but it's very easy to repro.
```

**Comment by qdm12** [comment]
There is no Json parsing for configuration, this is an error coming most likely from an intermediary with Unraid. Please see #550. Otherwise you could also try escaping the double quoted with `\"`? Closing this here since it's not a direct gluetun issue
