### ISSUE TITLE
Wiki issue: Misleading Volume Name

### ISSUE THREAD

**Issue by LuposX** [qdm12/gluetun#1329]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Custom-provider

### What's the issue?

The `compose.yml` for WireGuard has listed as volume:
` - ./yourovpnconfig.conf:/gluetun/config.conf:ro`

Which doesn't make sense, since this should describe a wireguard setup which doesn't have a `yourovpnconfig.conf` file.

**Comment by qdm12** [comment]
Fixed! I separated Wireguard and OpenVPN in two subsections, it was indeed not clear at all.
