### ISSUE TITLE
Bug: Release tags not working for ghcr.io

### ISSUE THREAD

**Issue by aleksasiriski** [qdm12/gluetun#1342]
### Is this urgent?

No

### Host OS

RHEL

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

Podman

### What is the version of Gluetun

latest

### What's the problem 🤔

`qmcgaw/gluetun:v3` works
`ghcr.io/qdm12/gluetun:v3` doesn't

### Share your logs

```plain text
to pull ghcr.io/qdm12/gluetun:v3...
Error: initializing source docker://ghcr.io/qdm12/gluetun:v3: reading manifest v3 in ghcr.io/qdm12/gluetun: manifest unknown
```

### Share your configuration

```yml
podman pull ghcr.io/qdm12/gluetun:v3
```

**Comment by qdm12** [comment]
`ghcr.io/qdm12/gluetun:v3` and `ghcr.io/qdm12/gluetun:v3.33.0` are now available.

They were not present before because no release was made since the addition of the new image-pushing for ghcr.io (and don't really want to fiddle with the build to re-build everything 😉)
