### ISSUE TITLE
Bug: Can't connect to VPN every time I restart (Mullvad)

### ISSUE THREAD

**Issue by MrZomka** [qdm12/gluetun#1365]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-12-31T17:50:58.654Z (commit ea40b84)

### What's the problem 🤔

Whenever I need to restart my container, I can't connect to the VPN unless I generate a new private key.

### Share your logs

```plain text
https://pastes.dev/manVVhFX5M
```

**Comment by MrZomka** [comment]
Now my VPN connection drops even when the container is still up... great... 😓

**Comment by bnhf** [comment]
@MrZomka 

> Now my VPN connection drops even when the container is still up... great... 😓

Probably worth trying OpenVPN to see if you have the same issues with Mullvad.

**Comment by itsokk** [comment]
`|   └── Wireguard settings:
|       ├── Private key: +H...k8=
|       ├── Interface addresses:
|       |   └── **x.x.x.x**/32
|       └── Network interface: tun0`
I think you need to change that according to the mullvad config you've generated. I'm not sure but you can try

**Comment by itsokk** [comment]
Just tested, same issue. OpenVPN works perfectly

**Comment by qdm12** [comment]
> Now my VPN connection drops even when the container is still up... great...

If it drops as soon as it says `Wireguard is up`, then it's just your keys/server data is wrong. Wireguard is a silent protocol so it won't report an authentication failure, it will simply be up and no traffic will go through.

If this is the case, re-check your keys it's a problem on your side (it works for me Wireguard+Mullvad). If not, please re-comment here.
