### ISSUE TITLE
Bug: port 8000 is being used by Portainer 

### ISSUE THREAD

**Issue by TibiaBubble** [qdm12/gluetun#1370]
### Is this urgent?

None

### Host OS

Docker

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c).

### What's the problem 🤔

I am tyring to publish port 8000 to use with my new [homepage setup](https://gethomepage.dev/en/services/gluetun/) and get it to show [my public IP adress.](https://github.com/benphelps/homepage/pull/512)
The problem seams to be that port 8000 is used with portainer and I am wondering is it is possible to use a diffrent port?

 

[the link to the gluetun setup page with port 8000.](https://github.com/qdm12/gluetun/wiki/HTTP-control-server)

### Share your logs

```plain text
§
```

**Comment by TibiaBubble** [comment]
Nervermind I fixed the issue with a diffrent port :)

**Comment by TibiaBubble** [comment]
I thought it was handled but I can’t seam to get an IP adress when I enter the port 8000? I just get an empty output like {}.

**Comment by qdm12** [comment]
You can also specify another listening address for the http control server of gluetun (see the wiki on the http control server page).

> I just get an empty output like {}.

That might be a bug I need to fix (see #1243 maybe?)

Closing this but feel free to comment. Note I'm currently moving places so I might be quite offline for the next 10 days.
