### ISSUE TITLE
Feature request: WireGuard KeepAlive support

### ISSUE THREAD

**Issue by eanzie** [qdm12/gluetun#1416]
### What's the feature 🧐

Inside wgtypes.PeerConfig there is an option that is currently not set by gluetune to set KeepAlive for the WireGuard connection.  Please add an env configuration to allow setting this to a non-zero value that is passed into the PeerConfig at

```
	// PersistentKeepaliveInterval specifies the persistent keepalive interval
	// for this peer, if not nil.
	//
	// A non-nil value of 0 will clear the persistent keepalive interval.
	PersistentKeepaliveInterval *time.Duration
```

### Extra information and references

- https://github.com/qdm12/gluetun/blob/ea40b84ec06fcb30172db01421a1acb13899a4e4/internal/wireguard/config.go#L51
- https://github.com/WireGuard/wgctrl-go/blob/9c5414ab4bdeb6d059e474d1589e6c5d21ff3dc9/wgtypes/types.go#L266

**Comment by JayKotan** [comment]
Has there been an update on this? The file I get from my VPN (VPNUnlimited) provider has a persistentkeepalive field.

**Comment by LouisH98** [comment]
+1 - PureVPN has this field

**Comment by qdm12** [comment]
Done in c87c0e12fe50a63a1fe785953bce6f68a03aaf40

Sorry for the massive delay for this small-ish addition 😅
