### ISSUE TITLE
Feature request: Support for custom ipinfo.io tokens

### ISSUE THREAD

**Issue by Fukitsu** [qdm12/gluetun#1450]
### What's the feature 🧐

I often connect to a service and get an error when gluetun tries to get the public IP.
`WARN [ip getter] too many requests sent for this month from https://ipinfo.io/: 403 403 Forbidden`
So I'd like support for custom ipinfo.io tokens, something like an env variable
`IPINFO_TOKEN=token`

**Comment by qdm12** [comment]
@Fukitsu done in 6a6337b98f32afdcee59465a98834d9cf8fe0ae2 with `PUBLICIP_API_TOKEN`

@notDavid this cannot work since it only echoes back the IP and no other information. In Gluetun we want the country, city etc. to cross check.
