### ISSUE TITLE
VPNSecure.me not working due to openssl upgrade and no longer secured DES encryption for keys

### ISSUE THREAD

**Issue by calimansi** [qdm12/gluetun#1451]
Hi,

So, I am unable to get this working via VPNSecure.me.  I followed the wiki exactly.  The error I'm getting is:

```
2023-03-12T05:12:10Z INFO [openvpn] Cannot load private key file [[INLINE]]
2023-03-12T05:12:10Z INFO [openvpn] SIGUSR1[soft,private-key-password-failure] received, process restarting
```

I did pass in my VPNSecure.me passthrough through OPENVPN_KEY_PASSPHRASE.

I did upload client.crt and openvpn_encrypted_key files on my server.

It looks like the passphrase can't decrypt the encrypted key file.

I also should write that I'm running docker on a Synology box.  The tun module is loaded.

Any other pointers?  I will follow up.

**Comment by calimansi** [comment]
Here is a little more info:

```
2023-03-13T06:48:23-07:00 INFO [openvpn] OpenSSL: error:0308010C:digital envelope routines::unsupported
2023-03-13T06:48:23-07:00 INFO [openvpn] OpenSSL: error:0308010C:digital envelope routines::unsupported
2023-03-13T06:48:23-07:00 INFO [openvpn] Cannot load private key file [[INLINE]]
2023-03-13T06:48:23-07:00 INFO [openvpn] SIGUSR1[soft,private-key-password-failure] received, process restarting
2023-03-13T06:48:33-07:00 INFO [openvpn] neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Private Key Password:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
2023-03-13T06:48:33-07:00 INFO [openvpn] Exiting due to fatal error
2023-03-13T06:48:33-07:00 ERROR [vpn] exit status 1
```

Maybe a openssl version issue?

**Comment by calimansi** [comment]
So I can decrypt the key file manually by using the following command:

`openssl rsa -noout -modulus -in openvpn_encrypted_key | openssl sha256`

I then type in my password to vpnsecure and it works... am I doing something wrong?

**Comment by calimansi** [comment]
My compose:

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=vpnsecure
      - OPENVPN_KEY_PASSPHRASE=xxx
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
```

**Comment by calimansi** [comment]
Ok.  I think I got it.  Had to use the tag v3.32.0 instead of latest.

**Comment by MadBloris** [comment]
I'm also getting this issue with VPN secure, any chance you can run me through what you did to resolve it?

I've tried using the latest source and using the git master, and still no go.

**Comment by calimansi** [comment]
@MadBloris - The thing that solved this for me was using v3.32.0 as the tag.  Compose below.  I removed by passphrase as well as my region:

version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.32.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=vpnsecure
      - OPENVPN_KEY_PASSPHRASE=xxx
      - SERVER_REGIONS=xxx
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks

**Comment by MadBloris** [comment]
Ha! How simple. I didn't know I could do that with docker. I presumed it was from the source.

Cheers for the tip. I shall get testing.

**Comment by calimansi** [comment]
Noice!

**Comment by JohnTa15** [comment]
you are a lifesavior dude nice!

**Comment by aldur** [comment]
Here's what I think happened: OpenSSLv3 deprecates `des` encryption, used by VPNSecure to encrypt the client private key. To use `latest`, just re-encrypt it using `aes`, as follows (using macOS and homebrew):

```bash
/opt/homebrew/opt/openssl@1.1/bin/openssl pkcs8 -v2 aes256 -in /tmp/pk.pem -topk8 -out /tmp/pk.new.pem
```

Replace `pk.pem` with the old private key (e.g. `openvpn_encrypted_key`).
Move the result to `openvpn_encrypted_key`.

**Comment by qdm12** [comment]
@aldur awesome yes that's the problem. That recent upgrade to Alpine 3.17 (and thus bumped openvpn+openssl) broke a lot of things (and I'm also super busy with life), sorry about all this mess.

I just went down a rabbit hole to automate this re-encryption in Gluetun, but unfortunately I believe this stupid PKCS#8 encrypted key format does not precise the algorithm used for encrypting the key, so it's not possible to know what algorithm to use to decrypt. Please correct me if I'm wrong though. If I'm right, then yes we should run your openssl command for the time being, and I would add it to the wiki as a an extra step (again) for vpn secure.

**Comment by aldur** [comment]
First things first: thank you for your work! 

Let's sort this out: The PKCS #8 [RFC](https://datatracker.ietf.org/doc/html/rfc5208#section-5) states that the format does include the encryption algorithm:

>  Private-key information shall have ASN.1 type PrivateKeyInfo:

      PrivateKeyInfo ::= SEQUENCE {
        version                   Version,
        privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
        privateKey                PrivateKey,
        attributes           [0]  IMPLICIT Attributes OPTIONAL }

In `openssl`, you can get it as follows:

```bash
openssl asn1parse -inform pem -in pk.pem
```

Will output something like this before conversion

```   
...
50:d=4  hl=2 l=   5 prim: OBJECT            :des-cbc
...
```

And after:

```
...
   64:d=4  hl=2 l=   9 prim: OBJECT            :aes-256-cbc
...
```

That said: what version of OpenSSL were you trying to use? For the command to work, we need v1 -- which means we'd have to ship it in the container.

Also, assuming v1.1 available: the command to re-encrypt seems to be idem-potent. So assuming we can feed it the password, we could also consider just re-running it every time.

If you push the "rabbit hole" code somewhere, I can take a stab at it.

**Comment by qdm12** [comment]
@aldur I'm trying to do this in Go without relying on openssl. The PR is at #1471 however, I keep on getting a mismatch between the DES decrypted RSA key and the AES-re-encrypted decrypted key in this test https://github.com/qdm12/gluetun/blob/fdbea0de40817731cd29fc07f12d37bb5b9316b7/internal/openvpn/pkcs8/upgrade_test.go#L12 if you want to take a stab at why go for it 😉 I'll probably get back to it sometime this weekend or from Tuesday.

Also slightly related issue created for the unofficial pkcs8 library dealing with ciphers out there: https://github.com/youmark/pkcs8/issues/29

**Comment by qdm12** [comment]
Cracked it (openssl was decrypting to pkcs1 format so that was just a format mismatch).
Can any of you try image `qmcgaw/gluetun:pr-1471` see how it behaves (with your old ugly DES encrypted key)? Thanks!

**Comment by kevocl** [comment]
I tried `qmcgaw/gluetun:pr-1471` with my old encrypted key, but the logs show this error:

```
gluetun  | 2023-03-31T21:28:57+01:00 INFO [firewall] allowing VPN connection...
gluetun  | 2023-03-31T21:28:57+01:00 ERROR [openvpn] Unrecognized option or missing or extra parameter(s) in /etc/openvpn/target.ovpn:35: ---BEGIN (2.5.8)
gluetun  | 2023-03-31T21:28:57+01:00 INFO [openvpn] Use --help for more information.
gluetun  | 2023-03-31T21:28:57+01:00 ERROR [vpn] exit status 1
gluetun  | 2023-03-31T21:28:57+01:00 INFO [vpn] retrying in 15s
gluetun  | 2023-03-31T21:29:03+01:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
gluetun  | 2023-03-31T21:29:12+01:00 INFO [firewall] allowing VPN connection...
gluetun  | 2023-03-31T21:29:12+01:00 ERROR [openvpn] Unrecognized option or missing or extra parameter(s) in /etc/openvpn/target.ovpn:35: ---BEGIN (2.5.8)
gluetun  | 2023-03-31T21:29:12+01:00 INFO [openvpn] Use --help for more information.
gluetun  | 2023-03-31T21:29:12+01:00 ERROR [vpn] exit status 1
gluetun  | 2023-03-31T21:29:12+01:00 INFO [vpn] retrying in 30s
```

**Comment by qdm12** [comment]
Oops forgot to remove the PEM headers `---BEGIN...` can you try again, using `docker pull qmcgaw/gluetun:pr-1471`? Thanks!

**Comment by kevocl** [comment]
Just tried it and `qmcgaw/gluetun:pr-1471` now works with my 'old ugly DES encrypted key' 👍
