### ISSUE TITLE
Feature request: Create a new release?

### ISSUE THREAD

**Issue by bjw-s** [qdm12/gluetun#1456]
### What's the feature 🧐

There have been quite a number of commits since the latest release (and a number of months have passed).

With the increased concern over Docker Hub as an image registry for the OSS community it would also be nice to have a (new) official release that is published on GHCR with the new workflow.

I was wondering if/when you would be able to create a new Gluetun release?

Thank you for considering!

**Comment by qdm12** [comment]
100% but I did the sort of mistake to merge PRs bumping Alpine from 3.16 to 3.17... and that bumped openssl 1.x.x to 3.x.x which is used for openvpn... meaning now the latest image is broken for a bunch of vpn providers using now unsecured algorithms (sha1, des etc.). Trying to resolve these before bumping release.

**Comment by qdm12** [comment]
- [x] SlickVPN got fixed (well not really, we just allow their - excuse the term - shitty certificate, with ugly OpenVPN workarounds)
- [ ] VPN secure should be fixed, but waiting for someone to test
- [ ] VPN Unlimited will be fixed soon (same problem as SlickVPN), and waiting for someone to reply back

**Comment by qdm12** [comment]
Finally done 🎆 

https://github.com/qdm12/gluetun/releases/tag/v3.33.0
