### ISSUE TITLE
Restarting container loses access to VPN

### ISSUE THREAD

**Issue by paulmorabito** [qdm12/gluetun#1477]
Hi,

I’ve using the container to link multiple containers to the VPN connection (via Mullvad). The problem I am having is that when one of these connected containers restarts, it restarts gluetun and then the other connected containers lose internet access. I generally need to do a full docker compose up -d” to get all the containers working again via the connection. 

Is there something I’ve missed with configuration here or how can I manage containers updating themselves via watchtower etc? (I’ve got gluetun currently set as “restart: always” if that makes a difference).

Thanks in advance

**Comment by qdm12** [comment]
This is a known issue, there is already one (if not multiple) issues tracking this. For now the best solution is to only update it manually and reboot your docker-compose stack.
