### ISSUE TITLE
[custom provider] allow domain name for VPN_ENDPOINT_IP

### ISSUE THREAD

**Issue by vdrover** [qdm12/gluetun#1496]
### What's the feature 🧐

Custom VPN providers like PureVPN do not provide an IP address in their custom wireguard. Rather, a domain/subdomain is listed and gluetun does not accept this for the VPN_ENDPOINT_IP parameter.

I traced the domain to an IP address, and used that instead. However, if someone changes the DNS records for the domain, my connection will break.

Thus, allowing a domain that is then resolved to an IP dynamically would be useful for PureVPN and perhaps other custom VPN providers.

**Comment by qdm12** [comment]
Thank you for taking the time to create the issue. However please subscribe to #788 which your issue duplicates 😉

**Comment by vdrover** [comment]
TY.
