### ISSUE TITLE
Wiki issue: shadowsocks client download page 404s

### ISSUE THREAD

**Issue by bianchidotdev** [qdm12/gluetun#1516]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Connect-a-LAN-device-to-gluetun#shadowsocks-proxy

### What's the issue?

Under https://github.com/qdm12/gluetun/wiki/Connect-a-LAN-device-to-gluetun#shadowsocks-proxy, the [ShadowSocks clients for all platforms](https://shadowsocks.org/en/download/clients.html) now 404s. I can't find what would be the perfect equivalent for client downloads would be, but their [Getting Started](https://shadowsocks.org/guide/getting-started.html) page might be an appropriate replacement

**Comment by qdm12** [comment]
Thanks, fixed 👍
