### ISSUE TITLE
Bug: Mullvad have cut Australia Wireguard servers down to 3 in the last week with different IP's. Unable to connect.

### ISSUE THREAD

**Issue by Avsynthe** [qdm12/gluetun#1530]
### Is this urgent?

Yes

### Host OS

unRAID

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker run

### What is the version of Gluetun

3.33.0

### What's the problem 🤔

Hi there,

As per title, things have changed at Mullvad for Sydney/Australia Wireguard servers. There used to be about 13x 1gbps servers and 3x 10gbps. Only the 3x 10gbps servers remain albeit with different IP addresses than before. This has happened countrywide as per the following reddit post, not just in Sydney:

https://www.reddit.com/r/mullvadvpn/comments/11rnake/mullvad_just_lost_76_servers_including_all_of/

While I have adjusted my config, the container still attempts to connect to an old IP address listed in servers.json of a now nonexistent Wireguard server. I'm unable to get any manual json changes to stick after container start to circumvent the issue and thus can't connect. Not sure if that's an unRAID issue.

Any help would be greatly appreciated. Cheers

### Share your logs

```plain text
18/04/2023 21:00:48
2023-04-18T21:00:48+10:00 INFO [wireguard] Connecting to 89.44.10.82:51820
18/04/2023 21:00:48
2023-04-18T21:00:48+10:00 INFO [wireguard] Wireguard is up
18/04/2023 21:00:48
2023-04-18T21:00:48+10:00 INFO [firewall] setting allowed input port 54911 through interface wg0...
18/04/2023 21:00:48
2023-04-18T21:00:48+10:00 INFO [firewall] setting allowed input port 58972 through interface wg0...
18/04/2023 21:00:53
2023-04-18T21:00:53+10:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [healthcheck] program has been unhealthy for 16s: restarting VPN (see https://github.com/qdm12/gluetun/wiki/Healthcheck)
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [vpn] stopping
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [firewall] removing allowed port 54911...
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [firewall] removing allowed port 58972...
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [vpn] starting
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [firewall] allowing VPN connection...
18/04/2023 21:01:04
2023-04-18T21:01:04+10:00 INFO [wireguard] Connecting to 89.44.10.114:51820
```

**Comment by bnhf** [comment]
@Avsynthe 

Do you have /gluetun mapped to a directory on your host? If not, servers.json wouldn't be persistent. Also, have you tried updating servers.json using the method described in the Wiki?

I just used a special update stack I have setup for testing, and got the following as updates to the Australia - Sydney servers:

```json
   {
        "vpn": "openvpn",
        "country": "Australia",
        "city": "Sydney",
        "isp": "M247",
        "hostname": "au-syd-ovpn-001",
        "tcp": true,
        "udp": true,
        "ips": [
          "2001:ac8:84:3::1f",
          "146.70.200.130"
        ]
      },
      {
        "vpn": "openvpn",
        "country": "Australia",
        "city": "Sydney",
        "isp": "M247",
        "hostname": "au-syd-ovpn-002",
        "tcp": true,
        "udp": true,
        "ips": [
          "2001:ac8:84:2::2f",
          "146.70.200.66"
        ]
      },
      {
        "vpn": "wireguard",
        "country": "Australia",
        "city": "Sydney",
        "isp": "M247",
        "hostname": "au-syd-wg-001",
        "wgpubkey": "4JpfHBvthTFOhCK0f5HAbzLXAVcB97uAkuLx7E8kqW0=",
        "ips": [
          "2001:ac8:84:5::1f",
          "146.70.200.2"
        ]
      },
      {
        "vpn": "wireguard",
        "country": "Australia",
        "city": "Sydney",
        "isp": "M247",
        "hostname": "au-syd-wg-002",
        "wgpubkey": "lUeDAOy+iAhZDuz5+6zh0Co8wZcs3ahdu2jfqQoDW3E=",
        "ips": [
          "2001:ac8:84:6::2f",
          "146.70.141.194"
        ]
      },
      {
        "vpn": "wireguard",
        "country": "Australia",
        "city": "Sydney",
        "isp": "M247",
        "hostname": "au-syd-wg-003",
        "wgpubkey": "LXuRwa9JRTt2/UtldklKGlj/IVLORITqgET4II4DRkU=",
        "ips": [
          "2001:ac8:84:4::3f",
          "146.70.200.194"
        ]
      },
```

Here's the update stack I use, in case you're not familiar with the process:

```yml
version: '3'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-update
    cap_add:
      - NET_ADMIN
    volumes:
      - /data/gluetun:/gluetun
    command: update -enduser -providers mullvad
```

With a persistent servers.json, and an update to the list, hopefully you'll be on track.

**Comment by Avsynthe** [comment]
Excellent! Thanks so much for the compose stack.

I do have /gluetun mapped but I've come across many containers on unRAID that revert any changes to config files once the container is started.

For instance, I can't tell you how many different qBittorrent and SABnsbd containers I had to try before I could find two that allowed me to change the internal port to have them both run through Gluetun and not conflict. Whether I made the change within the app itself or in their respective config files, the changes would go right back to the defaults set by the maintainer on start or on save.

Everyone needs to stop creating containers that use port 8080! 🤣

Anyways, I'm running your stack before the container on every boot. Solved my problem instantly. Thanks again!

**Comment by Avsynthe** [comment]
Reopening. I've restarted the server and gluetun logs now reads the following and obviously isn't connecting. I have no idea what to do now, the only change I made was introduce this stack

`2023-04-19T20:19:42+10:00 ERROR [vpn] kernel does not support Wireguard
`

**Comment by Avsynthe** [comment]
So after using the update stack to modify the servers.json due to me not being able to do so, the logs now read: 

`2023-04-19T22:41:43+10:00 WARN [ip getter] too many requests sent for this month from https://ipinfo.io/: 429 429 Too Many Requests
`

Does this mean I won't able to use Mullvad again until the month is up?

**Comment by qdm12** [comment]
Thanks @bnhf right on point. Since this issue is diverging quite a bit (please use github discussions on this repo next time), I'm closing it.

Now adding my 2 cents to a few points:

> For instance, I can't tell you how many different qBittorrent and SABnzbd containers I had to try before I could find two that allowed me to change the internal port to have them both run through Gluetun and not conflict.

Totally, this is so annoying most images don't have this easily configurable with an env variable. But there is no workaround with gluetun as far as I know.

> It works when I set it to userspace but that's not ideal. No idea how it now thinks Kernel support does not exist

Honestly except if you run on a raspberry pi or other very low power device, userspace is quite fast, especially if you have multiple CPU cores.

> Does this mean I won't able to use Mullvad again until the month is up?

As @bnhf said, this is just for the `ip getter`... maybe not the best name, true that, but it's just a part of the program fetching your ip from https://ipinfo.io.
