### ISSUE TITLE
Wiki issue: Possible Solution for ERROR creating TUN device file node: file exists

### ISSUE THREAD

**Issue by aviolaris** [qdm12/gluetun#1537]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/TUN-device-errors#cannot-create-tun-device-file-node-file-exists

### What's the issue?

I recently encountered an error on a Raspberry Pi that stated:

> ERROR creating TUN device file node: file exists.

Upon further analysis, I found that the cause of this issue was a mismatch between the running kernel and the installed modules, including the TUN module, which probably occurred after an unattended kernel upgrade without rebooting.

Given that uptime is often crucial on Raspberry Pis, and one can avoid rebooting for an extended period, it may be useful to update the relevant wiki thread to include rebooting as a possible solution for the aforementioned error.

**Comment by qdm12** [comment]
Thanks, added! 👍
