### ISSUE TITLE
Feature request: Firewall configuration for ipv6

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#154]
1. What's the feature?

Firewall setup for ipv6 if `IPV6=on` (and add environment variable `IPV6`). Important for **Mullvad** is ipv6 is used.

2. Why do you need this feature?

For people using ipv6 on their network / Docker network

3. Extra information?

May refer to #153

**Comment by qdm12** [comment]
https://github.com/qdm12/gluetun/commit/7ba98af1cc4a969ff44ca4d9166b57654e534677 addressed part of the problem.

What is left to do is to:

1. allow the user to pick an IPv6 VPN server IP address
2. allow outbound IPv6 traffic through the tunnel

**Comment by EkilDeew** [comment]
Any updates on this ?
Its fairly easy to just comment the few lines in `internal/provider/utils/connection.go:55-58` to let Gluetun pick an IPv6 server ( which should be preferred over IPv4 ).
However it get stucks just after when `downloading DNS over TLS cryptographic files`. So for now Gluetun can't even connect to an IPv6 server.

ip6tables is still blocking some outgoing data i guess.
