### ISSUE TITLE
Wiki issue: Outdated Mullvad servers

### ISSUE THREAD

**Issue by mtorressahli** [qdm12/gluetun#1547]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Mullvad-servers

### What's the issue?

Mullvad servers seem quite outdated (if I'm not wrong last update was mid 2022). In particular, I use wireguard Sao Paulo servers, of which the two on record are now offline. Here's the data from [their website](https://mullvad.net/en/servers) on the currently existing Sao Paulo servers, although br1-wireguard has been offline for weeks:

| Server Name       | Country | City       | Provider   | Speed  | Type   | Domain Name                          | IPv4            | IPv6                              | Public Key                                                     | Socks5 Proxy Address                      | Multihop Port |
| ----------------- | ------- | ---------- | --------- | ------ | ------ | ------------------------------------ | -------------- | --------------------------------- | -------------------------------------------------------------- | ---------------------------------------- | -------------- |
| br1-wireguard     | Brazil  | Sao Paulo  | Qnax      | 1 Gbps | Rented | br1-wireguard.relays.mullvad.net     | 45.162.228.186 | 2804:5364:3100:9::a01f           | 2eYsuY/H7kpeam31OG+eQ7s43BeuyzoVgqwdeGXMd3A=     | br1-wg.socks5.relays.mullvad.net:1080     | 3055           |
| br-sao-001        | Brazil  | Sao Paulo  | Qnax      | 1 Gbps | Rented | br-sao-001.relays.mullvad.net        | 177.67.80.186  | 2804:5364:2100:6::1f             |                                                              |                                          |                |
| br-sao-wg-201     | Brazil  | Sao Paulo  | DataPacket | 10 Gbps| Rented | br-sao-wg-201.relays.mullvad.net     | 169.150.198.66 | 2a02:6ea0:d00e:1::a01f           | 8c9M6w1BQbgMVr/Zgrj4GwSdU6q3qfQfWs17kMLC9y4=     | br-sao-wg-socks5-201.relays.mullvad.net:1080 | 3539           |
| br-sao-wg-202     | Brazil  | Sao Paulo  | DataPacket | 10 Gbps| Rented | br-sao-wg-202.relays.mullvad.net     | 169.150.198.79 | 2a02:6ea0:d00e:2::a02f           | jWURoz8SLBUlRTQnAFTA/LDZUTpvlO0ghiVWH7MgaHQ=     | br-sao-wg-socks5-202.relays.mullvad.net:1080 | 3540           |

**Comment by Schaka** [comment]
I use Netherlands, Amsterdam and OpenVPN. I haven't been able to connect to the server that Gluetun tries to connect to. 
Server list was updated manually as per Wiki.

**Comment by Schaka** [comment]
I had previous tried updating my servers manually and it didn't seem to work at all. I'll give it another shot, as today all `nl-ams-ovpn` mullvad servers stopped working.
