### ISSUE TITLE
Feature request: Protonvpn filtering by features

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#1582]
### What's the feature 🧐

Each server JSON object from their API has a feature number corresponding to a feature detailed in https://github.com/ProtonVPN/protonvpn-nm-lib/blob/31d5f99fbc89274e4e977a11e7432c0eab5a3ef8/protonvpn_nm_lib/enums.py#L44-L49

Gluetun should allow to filter servers by feature

**Comment by ProfDoof** [comment]
What needs to be done to support this? I'd be willing to take a brief crack at it here in the next couple of weeks but don't know where you would want me to start.
