### ISSUE TITLE
No longer connecting to PIA, no config changes

### ISSUE THREAD

**Issue by bear359** [qdm12/gluetun#1618]
Hi there,

Since last gluetun update, now getting the following error whilst using PIA:

ERROR VPN settings: provider settings: server selection: for VPN service provider private internet access: the region specified is not valid: value is not one of the possible choices:

Docker compose:
`###############################################################################
# GLUETUN
###############################################################################
# https://github.com/qdm12/gluetun/wiki
###############################################################################
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 127.0.0.1:8112:8112     # Deluge Web UI (binding to locahost to keep it more secure)
      - 6882:6882               # Deluge Incoming Port
      - 58846:58846             # Deluge Daemon Port
      - 58946:58946             # Deluge TCP port for BitTorrent
      - 58946:58946/udp         # Deluge UDP port for BitTorrent
    volumes:
      - ./gluetun:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - TZ=${TZ}
    restart: unless-stopped`

Please advise and thanks in advance.

**Comment by frepke** [comment]
Pull the latest image, issue is solved yesterday
