### ISSUE TITLE
Cannot add address to wireguard interface

### ISSUE THREAD

**Issue by rightsaidfred99** [qdm12/gluetun#1619]
I was running glueton for about a year, via docker. It pretty much ran itself without being touched. 
All of a sudden out of nowhere it refuses to work since about 3 weeks now:

This is the only clue in the logs but I can't work out what "file exists"...even blowing away everything to recreate the stack results in the below logs and it is stuck on "unhealthy". 

Cannot add address to wireguard interface: file exists: when adding address x.x.x.x.x/32 to link tun0

**Comment by qdm12** [comment]
What version are you using?

I just pushed 9d1a0b60a29cc03e252d0e350c44ab21cf5399ba which now replaces an address (add if it doesn't exist, replace if it exists), that should resolve your issue I think. You can get it by pulling the latest image.

But before closing this, does this error happen on the first run or after an internal restart? Would you mind sharing more logs? Maybe there is a logic bug not tearing down the entire Wireguard link like it should 🤔

**Comment by rightsaidfred99** [comment]
This fixed the issue, whatever you did :)

Thank you.

This happens on both first run and or internal restart. Do you still want some logs?

**Comment by qdm12** [comment]
Yeah that would be nice, maybe even running with `LOG_LEVEL=debug` to see why the address is not removed or added twice.
