### ISSUE TITLE
Bug: `fork/exec /sbin/iptables: no such file or directory`

### ISSUE THREAD

**Issue by LeeroyDing** [qdm12/gluetun#1635]
Logs:

```
pia  | 2023-05-31T14:58:10+01:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4
pia  | 2023-05-31T14:58:10+01:00 INFO [routing] local ethernet link found: eth0
pia  | 2023-05-31T14:58:10+01:00 INFO [routing] local ipnet found: 172.18.0.0/16
pia  | 2023-05-31T14:58:10+01:00 ERROR no iptables supported found: errors encountered are: iptables-nft:  (fork/exec /sbin/iptables-nft: no such file or directory); iptables:  (fork/exec /sbin/iptables: no such file or directory)
pia  | 2023-05-31T14:58:10+01:00 INFO Shutdown successful
```

Started from v3.34.2, not a problem on v3.34.1. I suspect it's because of some changes in alpine 3.18.

**Comment by LeeroyDing** [comment]
I suspect that's caused by Alpine 3.18 pointing `iptables` to the `nft` variant [by default](https://git.alpinelinux.org/aports/commit/?id=f87a191922955bcf5c5f3fc66a425263a4588d48), thus breaking firewall on systems that don't have `nft` support (e.g. Synology DSM).

If that's the case, it can be fixed by updating the [firewall](https://github.com/qdm12/gluetun/blob/b87b2109b15bd5565cfe61e2ebadc9d993cd5adc/internal/firewall/firewall.go#L40) & [ipv6 firewall](https://github.com/qdm12/gluetun/blob/b87b2109b15bd5565cfe61e2ebadc9d993cd5adc/internal/firewall/ip6tables.go#L18) to include `iptables-legacy` and `ip6tables-legacy` respectively. I'm not confident in Go enough to contribute but happy to if requested.

**Comment by qdm12** [comment]
Whoops you made me realize v3.34.2 was wrongly pointed to the master branch instead of the v3.34 branch 😭 I re-created the release, and also created v3.34.3 (same commit as the 'new' v3.34.2) to avoid any possible confusion.

Anyway, now that that is done, from the looks of it Alpine 3.18 still uses the legacy iptables by default:

```sh
$ docker run -it --rm alpine:3.18 apk add iptables ip6tables && iptables --version && ip6tables --version
# ...
iptables v1.8.8 (legacy)
ip6tables v1.8.8 (legacy)
```

Running gluetun with

```sh
$ docker run -it --rm --entrypoint /bin/sh qmcgaw/gluetun -c "iptables --version"
iptables v1.8.9 (legacy)
```

Also works.

Now the error `fork/exec /sbin/iptables: no such file or directory` makes me suspect you are running the wrong CPU architecture perhaps? What's your machine (you can check with `uname -a`)??

**Comment by LeeroyDing** [comment]
Interesting! The `uname -a` output is this (masked out the machine name):

```
Linux ######## 4.4.180+ #42962 SMP Sat Apr 8 00:32:09 CST 2023 x86_64 GNU/Linux synology_r1000_923+
```

**Comment by LeeroyDing** [comment]
I get an error message trying to run `alpine:3.18`

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "apk": executable file not found in $PATH: unknown.
```

Same output with yours on 3.17.

**Comment by LeeroyDing** [comment]
Not only does it not have `apk`, but also missing `/bin/sh` and `/bin/ash`, which makes me wonder whether I got a bad image. Deleting it all and restarting :)
