### ISSUE TITLE
Wiki issue: Mullvad removing port forwarding

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [qdm12/gluetun#1639]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Mullvad#vpn-port-forwarding

### What's the issue?

https://mullvad.net/en/blog/2023/5/29/removing-the-support-for-forwarded-ports/

The section on port forwarding with Mullvad can be removed from the wiki, as users can no longer forward new ports and it will be removed entirely in July

**Comment by qdm12** [comment]
Done, thanks for the heads up!! 👍
