### ISSUE TITLE
Feature request: Filter NordVPN servers by group

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#1643]
### What's the feature 🧐

NordVPN servers have groups, it would be nice to be able to filter by group.

- [ ] Change `internal/providers/nordvpn/updater` code
- [ ] Update `internal/storage/servers.json`
- [ ] Update Github wiki NorVPN servers list

Blocked by #1380 

### Extra information and references

Requested in:

- https://github.com/qdm12/gluetun/issues/719#issuecomment-1258403893
- https://github.com/qdm12/gluetun/issues/1541

**Comment by vdrover** [comment]
following.
