### ISSUE TITLE
Wiki issue: PIA docs not updated with rename to VPN_PORT_FORWARDING

### ISSUE THREAD

**Issue by zsabra** [qdm12/gluetun#1656]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Private-internet-access

### What's the issue?

Just noticed this - the docs for PIA still show the old variable names. 

PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING
PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE

which have been renamed to 

VPN_PORT_FORWARDING
VPN_PORT_FORWARDING_STATUS_FILE

Would love to contribute to the wiki for changes like this rather than create an issue, if possible? :)

**Comment by qdm12** [comment]
Thanks! 👍 
Updated!

Unfortunately Github Wiki is kind of bad and, although it's a git repository, it's not available on Github or does not accept pull requests... 😢 I opened issue #579 to move to another system, feel free to subscribe to it or comment over there on a better system! 😉
