### ISSUE TITLE
Wiki issue: copy/paste error?

### ISSUE THREAD

**Issue by vdrover** [qdm12/gluetun#1673]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/NordVPN

### What's the issue?

This looks to be a copy/paste error:

```
# Wireguard
docker run -it --rm --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER=mullvad \
```

I think `mullvad` should be `nordvpn`.

**Comment by qdm12** [comment]
Indeed, fixed 👍
