### ISSUE TITLE
Wiki issue: 'ShadowSocks clients for all platforms' Hyperlink is 404

### ISSUE THREAD

**Issue by DieSchoeneWolke** [qdm12/gluetun#1683]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/Connect-a-LAN-device-to-gluetun#shadowsocks-proxy

### What's the issue?

New page is now: https://shadowsocks.org/doc/getting-started.html#gui-clients

**Comment by qdm12** [comment]
Done, thanks!!
Note the wiki now moved to github.com/qdm12/gluetun-wiki
