### ISSUE TITLE
Bug: Can't retrieve my private key from nordvpn

### ISSUE THREAD

**Issue by handsome1987** [qdm12/gluetun#1693]
### Is this urgent?

Yes

### Host OS

DSM Synology

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

0

### What's the problem 🤔

I cant get my private key.
I got the message a new version is available please update the application.
Whoops! Connection failed. Please try again. If the problem persists contact our customer support.
 
I use this command with my token from Nordvpn
docker run --rm --cap-add=NET_ADMIN \
  -e TOKEN='abcxyz' ghcr.io/bubuntux/nordvpn:get_private_key

### Share your logs

```plain text
none
```

**Comment by vnnegt** [comment]
I had the same issue.

I received `Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.` when attempting to run the container on WSL2 for Windows 10, but it worked fine in macOS.

**Comment by handsome1987** [comment]
> I had the same issue.
> 
> I received `Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.` when attempting to run the container on WSL2 for Windows 10, but it worked fine in macOS.

Thank you i installed ubuntu trough vmware and retrieved my private key trough there.
Its working now with wireguard.

**Comment by qdm12** [comment]
@bubuntux any idea why this error showed up?

**Comment by bubuntux** [comment]
The container needs wireguard installed in the host to work, it doesn't install it at the user level, so my guess is that WSL dosen't have wireguard installed

**Comment by qdm12** [comment]
Interesting, how do you launch nordvpn/nordlynx/wireguard? Is it the nordvpn pre-built app requiring wireguard in the kernel and there is no way around this? 🤔

**Comment by vnnegt** [comment]
I didn't need to install `wireguard` on macOS

i think something about `ghcr.io/bubuntux/nordvpn` doesn't play nice with WSL2

i tried to install it on WSL2 directly and receive this:


```
A new version of NordVPN is available! Please update the application.
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

A new version of NordVPN is available! Please update the application.
Technology is already set to 'NORDLYNX'.

A new version of NordVPN is available! Please update the application.
Subnet [192.168.200.0/24](http://192.168.200.0/24) is whitelisted successfully.
Connecting...

A new version of NordVPN is available! Please update the application.
Connecting to United States #9369 ([us9369.nordvpn.com](http://us9369.nordvpn.com/))
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.
Unable to connect retrying in 1 seconds.

A new version of NordVPN is available! Please update the application.
Connecting to United States #5058 ([us5058.nordvpn.com](http://us5058.nordvpn.com/))
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.
Unable to connect retrying in 2 seconds.
```

**Comment by qdm12** [comment]
> I didn't need to install `wireguard` on macOS

You do have wireguard in your kernel, you can check with `genl-ctrl-list` (on Linux, maybe a similar command on osx).

I would guess on WSL, if you run `genl-ctrl-list` you won't see `wireguard`. Somehow my WSL has wireguard, but I guess by default it doesn't come with it 🤔 

@bubuntux maybe worth adding to your repository a check to see if wireguard is supported in the kernel? 🤔
