### ISSUE TITLE
Bug: Cyberghost error importing certificate as env key

### ISSUE THREAD

**Issue by emanuellopes** [qdm12/gluetun#1703]
### Is this urgent?

None

### Host OS

TrueNas Scale

### CPU arch

x86_64

### VPN service provider

Cyberghost

### What are you using to run the container

Kubernetes

### What is the version of Gluetun

latest version

### What's the problem 🤔

I'm trying pass the OPENVPN_KEY as a base64 string but I receive always an error.

torrent_openvpn-gluetun-1  | 2023-06-24T17:55:54Z INFO [openvpn] OpenSSL: error:068000A8:asn1 encoding routines::wrong tag
torrent_openvpn-gluetun-1  | 2023-06-24T17:55:54Z INFO [openvpn] OpenSSL: error:0688010A:asn1 encoding routines::nested asn1 error
torrent_openvpn-gluetun-1  | 2023-06-24T17:55:54Z INFO [openvpn] OpenSSL: error:0488000D:PEM routines::ASN1 lib
torrent_openvpn-gluetun-1  | 2023-06-24T17:55:54Z INFO [openvpn] OpenSSL: error:0A080009:SSL routines::PEM lib
torrent_openvpn-gluetun-1  | 2023-06-24T17:55:54Z INFO [openvpn] Cannot load inline certificate file
torrent_openvpn-gluetun-1  | 2023-06-24T17:55:54Z INFO [openvpn] Exiting due to fatal error

I don't understand What is wrong with my cert and private key, I already enconded the key using base64 in cyberchef, but nothing worked

If I use the files directly will work fine, I tried in docker compose and I receive the same error.

Can you please give me an example how to convert my key to a single line?

### Share your logs

```plain text
.
```

### Share your configuration

```yml
.
```

**Comment by emanuellopes** [comment]
Fixed

**Comment by dragid10** [comment]
Sooo what was the fix here???

**Comment by emanuellopes** [comment]
The issue was related to \n. 
For some reason when I started encoding the cert, the encoder removed the breakline.

**Comment by dragid10** [comment]
Were you just using a command to encode the cert?
