### ISSUE TITLE
Bug: AUTH_FAILED out of the blue

### ISSUE THREAD

**Issue by casudo** [qdm12/gluetun#1708]
### Is this urgent?

None

### Host OS

Ubuntu 22.04

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

sha256:0293640326ff3b55c594a5373c705daf318c274d242bd632b3fd48e2de0caeb6

### What's the problem 🤔

Today out of the blue I received the "ERROR [openvpn] AUTH: Received control message: AUTH_FAILED Your credentials might be wrong 🤨" error in the logs. It worked flawlessly for weeks without changing anything. The login is also correct and hasn't changed. I've also tried an other account (which works on the desktop) but not on Gluetun.

### Share your logs

```plain text
2023-06-28T13:46:54+02:00 INFO [openvpn] SIGUSR1[soft,auth-failure] received, process restarting

2023-06-28T13:47:04+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]<IP>:1194

2023-06-28T13:47:04+02:00 INFO [openvpn] UDP link local: (not bound)

2023-06-28T13:47:04+02:00 INFO [openvpn] UDP link remote: [AF_INET]<IP>:1194

2023-06-28T13:47:05+02:00 INFO [openvpn] [kr34.nordvpn.com] Peer Connection Initiated with [AF_INET]<IP>:1194

2023-06-28T13:47:11+02:00 ERROR [openvpn] AUTH: Received control message: AUTH_FAILED

Your credentials might be wrong 🤨

2023-06-28T13:47:11+02:00 INFO [openvpn] SIGUSR1[soft,auth-failure] received, process restarting

2023-06-28T13:47:13+02:00 INFO [healthcheck] program has been unhealthy for 26s: restarting VPN (see https://github.com/qdm12/gluetun/wiki/Healthcheck)

2023-06-28T13:47:13+02:00 INFO [vpn] stopping

2023-06-28T13:47:13+02:00 INFO [vpn] starting

2023-06-28T13:47:13+02:00 INFO [firewall] allowing VPN connection...

2023-06-28T13:47:13+02:00 INFO [openvpn] OpenVPN 2.5.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  2 2022

2023-06-28T13:47:13+02:00 INFO [openvpn] library versions: OpenSSL 3.1.1 30 May 2023, LZO 2.10

2023-06-28T13:47:13+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]<IP>:1194

2023-06-28T13:47:13+02:00 INFO [openvpn] UDP link local: (not bound)

2023-06-28T13:47:13+02:00 INFO [openvpn] UDP link remote: [AF_INET]<IP>:1194

2023-06-28T13:47:14+02:00 INFO [openvpn] [ee51.nordvpn.com] Peer Connection Initiated with [AF_INET]<IP>:1194

2023-06-28T13:47:20+02:00 ERROR [openvpn] AUTH: Received control message: AUTH_FAILED

Your credentials might be wrong 🤨
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=<MYMAIL>
      - OPENVPN_PASSWORD=<MYPASS>
      - SERVER_REGIONS=Albania,Argentina,Australia,Belgium,Bosnia and Herzegovina,Brazil,Bulgaria,Canada,Chile,Costa Rica,Croatia,Cyprus,Czech Republic,Estonia,Finland,France,Georgia,Greece,Hungary,Iceland,India,Indonesia,Ireland,Israel,Italy,Japan,Latvia,Lithuania,Malaysia,Mexico,Moldova,Netherlands,New Zealand,North Macedonia,Norway,Poland,Portugal,Romania,Serbia,Singapore,Slovakia,Slovenia,South Africa,South Korea,Spain,Sweden,Switzerland,Taiwan,Thailand,United Kingdom,United States
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTP_CONTROL_SERVER_LOG=on
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true  
    restart: unless-stopped  
    ports:
      - 8001:8000/tcp 
      - 8124:8124 
      - 6881:6881 
      - 6881:6881/udp 
    networks:
      - <MYNETWORK>
```

**Comment by casudo** [comment]
EDIT: Starting logs
```
2023-06-28T13:53:23+02:00 INFO OpenVPN 2.5 version: 2.5.8

2023-06-28T13:53:23+02:00 INFO OpenVPN 2.6 version: 2.6.5

2023-06-28T13:53:23+02:00 INFO Unbound version: 1.17.1

2023-06-28T13:53:23+02:00 INFO IPtables version: v1.8.9

2023-06-28T13:53:23+02:00 INFO Settings summary:

├── VPN settings:

|   ├── VPN provider settings:

|   |   ├── Name: nordvpn

|   |   └── Server selection settings:

|   |       ├── VPN type: openvpn

|   |       ├── Countries: albania, argentina, australia, belgium, bosnia and herzegovina, brazil, bulgaria, canada, chile, costa rica, croatia, cyprus, czech republic, estonia, finland, france, georgia, greece, hungary, iceland, indonesia, ireland, israel, italy, japan, latvia, lithuania, malaysia, mexico, moldova, netherlands, new zealand, north macedonia, norway, poland, portugal, romania, serbia, singapore, slovakia, slovenia, south africa, south korea, spain, sweden, switzerland, taiwan, thailand, united kingdom, united states

|   |       └── OpenVPN server selection settings:

|   |           └── Protocol: UDP

|   └── OpenVPN settings:

|       ├── OpenVPN version: 2.5

|       ├── User: [set]

|       ├── Password: [set]

|       ├── Network interface: tun0

|       ├── Run OpenVPN as: root

|       └── Verbosity level: 1

├── DNS settings:

|   ├── DNS server address to use: 127.0.0.1

|   ├── Keep existing nameserver(s): no

|   └── DNS over TLS settings:

|       ├── Enabled: yes

|       ├── Update period: every 24h0m0s

|       ├── Unbound settings:

|       |   ├── Authoritative servers:

|       |   |   └── cloudflare

|       |   ├── Caching: yes

|       |   ├── IPv6: no

|       |   ├── Verbosity level: 1

|       |   ├── Verbosity details level: 0

|       |   ├── Validation log level: 0

|       |   ├── System user: root

|       |   └── Allowed networks:

|       |       ├── 0.0.0.0/0

|       |       └── ::/0

|       └── DNS filtering settings:

|           ├── Block malicious: yes

|           ├── Block ads: no

|           ├── Block surveillance: no

|           └── Blocked IP networks:

|               ├── 127.0.0.1/8

|               ├── 10.0.0.0/8

|               ├── 172.16.0.0/12

|               ├── 192.168.0.0/16

|               ├── 169.254.0.0/16

|               ├── ::1/128

|               ├── fc00::/7

|               ├── fe80::/10

|               ├── ::ffff:127.0.0.1/104

|               ├── ::ffff:10.0.0.0/104

|               ├── ::ffff:169.254.0.0/112

|               ├── ::ffff:172.16.0.0/108

|               └── ::ffff:192.168.0.0/112

├── Firewall settings:

|   └── Enabled: yes

├── Log settings:

|   └── Log level: INFO

├── Health settings:

|   ├── Server listening address: 127.0.0.1:9999

|   ├── Target address: cloudflare.com:443

|   ├── Duration to wait after success: 5s

|   ├── Read header timeout: 100ms

|   ├── Read timeout: 500ms

|   └── VPN wait durations:

|       ├── Initial duration: 6s

|       └── Additional duration: 5s

├── Shadowsocks server settings:

|   └── Enabled: no

├── HTTP proxy settings:

|   └── Enabled: no

├── Control server settings:

|   ├── Listening address: :8000

|   └── Logging: yes

├── OS Alpine settings:

|   ├── Process UID: 1000

|   ├── Process GID: 1000

|   └── Timezone: europe/berlin

├── Public IP settings:

|   ├── Fetching: every 12h0m0s

|   └── IP file path: /tmp/gluetun/ip

└── Version settings:

    └── Enabled: yes
```

**Comment by qdm12** [comment]
This might be just a misbehaving Nordvpn server, I've seen this multiple times with them. Try narrowing down the server filters to a single country/hostname to check if it works on another server?

**Comment by mbkoper** [comment]
I can also report I have the same issue. I changed my password, changed the country and also tried the old version (v3.34.2), but all gave the same result: "AUTH: Received control message: AUTH_FAILED".

**Comment by porter707** [comment]
I've also started getting the same, I was running v3.33.0 but just upgraded to v3.34.3 and theres no change

**Comment by francescodesu** [comment]
same for me since few hours ago. nordvpn with v3.34.3

**Comment by qdm12** [comment]
For more users having this problem please just 👍 the original issue.

1. Maybe this is a problem on nordvpn servers since all of you seem to have this problem since recently, without an image change? Did they announce any change on their end?
2. Try with `OPENVPN_VERSION=2.6` maybe?
3. Try with Openvpn outside Gluetun (a bit not so useful, I would guess it would fail too)

**Comment by flshaun** [comment]
Can confirm same issue - between 2 vpn's, proton and nord.

**Comment by mbkoper** [comment]
> 2. Try with `OPENVPN_VERSION=2.6` maybe?

Tried option 2: didn't help, still the same error

**Comment by porter707** [comment]
Just tried v3.35.0 with OPENVPN_VERSION 2.6 and still get the same auth error

**Comment by doorssbm** [comment]
> I started my morning with this issue. Just messing around with my NordVPN settings, I changed my login credentials in my Portainer Stack FROM my email and password, TO my Service Credentials and it worked right away. Find this in your NordVPN account under Manual Setup. Maybe Nord changed what they accept for a headless login from a Docker container over night? Either way, it's working for me now using these different login credentials.

This fixed it for me as well. Should I be concerned that I was able to remotely access the webui on things I put behind gluetun even when I was getting the Auth error? Does that mean the firewall isn't working correctly or am I misunderstanding this?

**Comment by qdm12** [comment]
Awesome thanks @joem569 💯 
I documented it in the wiki:

> 💁 Your credentials are NO LONGER your email+password, it is now your service credentials.

If they didn't announce anything, shame on nordvpn really 😠 

@flshaun open another issue for protonvpn if you still have a problem.

**Comment by JohnnyDeeee** [comment]
> If they didn't announce anything, shame on nordvpn really 😠

I got this in an email on 21-06-2023

> Dear customer,
> 
> We’d like to inform you that we are upgrading our infrastructure to meet the highest security standards. As a result, there will be some changes for users who connect to our servers through third party clients and manual setups. These changes will come into effect on **June 27, 2023**. The login method through NordVPN applications will not change.
> 
> If you were using your login credentials (emails/usernames and passwords) for manual setups, you will need to update your configurations. You’ll need to use **Service credentials** located in your user control panel, under **Services → NordVPN** section. Follow these steps to set it up:
> 
> - Log in to your Nord Account.
> - Click on the NordVPN tab on the left panel which is under the Services tab.
> - Scroll down and locate the Manual Setup tab, then click on Set up NordVPN manually.
> - Verify your email by entering the one-time code you will receive in your registered email inbox. If you are unable to find the email, check your spam/junk folder.
> - Copy your service credentials by using the buttons on the right.
> 
> Please note that Service credentials are only necessary for manual configurations, and you may still use your regular credentials for our applications.

**Comment by casudo** [comment]
> Awesome thanks @joem569 💯 I documented it in the wiki:
> 
> > 💁 Your credentials are NO LONGER your email+password, it is now your service credentials.
> 
> If they didn't announce anything, shame on nordvpn really 😠
> 
> @flshaun open another issue for protonvpn if you still have a problem.

Here's the article I got from the support:
https://support.nordvpn.com/Connectivity/Linux/1905092252/How-to-log-in-to-NordVPN-on-Linux-with-a-token.htm
