### ISSUE TITLE
Wiki issue: 

### ISSUE THREAD

**Issue by bigbadbabey** [qdm12/gluetun#1713]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/AirVPN

### What's the issue?

No option for port forwarding. Here is a write up if that helps: 

VPN Port forwarding

Log in your AirVPN account at https://airvpn.org/client/
Obtain a port from https://airvpn.org/ports/
Add the port to the environment variable FIREWALL_VPN_INPUT_PORTS

**Comment by qdm12** [comment]
Thanks, done in https://github.com/qdm12/gluetun-wiki/commit/f85b0d27bad7f74d6257d747dcda8335cf5ad633
