### ISSUE TITLE
Bug: NordVPN Missing Valid Servers

### ISSUE THREAD

**Issue by spencercharest** [qdm12/gluetun#1715]
### Is this urgent?

None

### Host OS

Ubuntu Jammy Jellyfish 

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2023-06-30T17:28:02.006Z (commit fae6544)

### What's the problem 🤔

I need to connect to a specific NordVPN server in order to use their dedicated ip feature. I'm seeing an error that this is not a valid hostname when it seems that it should be.

```sh
 ERROR VPN settings: provider settings: server selection: for VPN service provider nordvpn: the hostname specified is not valid: value is not one of the possible choices: value us10291.nordvpn.com, choices available are
```

<img width="1132" alt="Screenshot 2023-06-30 at 10 50 20 AM" src="https://github.com/qdm12/gluetun/assets/18563732/bf06a494-f1f8-47b2-92c3-c7f308929f88">

### Share your logs

```plain text
Running version latest built on 2023-06-30T17:28:02.006Z (commit fae6544)

📣 Wiki moved to https://github.com/qdm12/gluetun-wiki

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-06-30T12:54:46-05:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1, assigned IP 172.17.0.2 and family v4
2023-06-30T12:54:46-05:00 INFO [routing] local ethernet link found: eth0
2023-06-30T12:54:46-05:00 INFO [routing] local ipnet found: 172.17.0.0/16
2023-06-30T12:54:46-05:00 INFO [firewall] enabling...
2023-06-30T12:54:46-05:00 INFO [firewall] enabled successfully
2023-06-30T12:54:46-05:00 INFO [storage] merging by most recent 17657 hardcoded servers and 17657 servers read from /gluetun/servers.json
2023-06-30T12:54:46-05:00 ERROR VPN settings: provider settings: server selection: for VPN service provider nordvpn: the hostname specified is not valid: value is not one of the possible choices: value us10291.nordvpn.com, choices available are ...
2023-06-30T12:54:46-05:00 INFO Shutdown successful
```

### Share your configuration

```yml
docker create \
  --name=vpn \
  --restart=unless-stopped \
  --cap-add=NET_ADMIN \
  --cap-add=NET_RAW \
  -e VPN_SERVICE_PROVIDER=nordvpn \
  -e OPENVPN_USER=XXX \
  -e OPENVPN_PASSWORD=XXX \
  -e SERVER_HOSTNAMES=us10291.nordvpn.com \
  -e TECHNOLOGY=OpenVPN \
  -e TZ=America/Chicago \
  qmcgaw/gluetun:latest
```

**Comment by Inous2018** [comment]
I believe some servers get pruned on NordVPN's side. I used a specific server for a long time and then it got removed at some point. I had to look up the server numbers and change my server, you can find the server numbers online pretty easily. Check my config below for the options.

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=XXXXXXXXXXXXXXXXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXXX
      - SERVER_REGIONS=United States
      - SERVER_NUMBER=5070
```

**Comment by qdm12** [comment]
NordVPN has a TON of servers (about 3MB of JSON servers), which means I can't really update it regularly in the built-in servers data, since that would make this repository huge very fast (update it 10 times, and that makes around +20MB of deltas in the repository). Anyway, having said that, you can update servers data yourself, see https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list

If after updating the servers data you still can't use that hostname, feel free to create another issue.

EDIT: Also just saw @Inous2018 comment, maybe worth having a look!

**Comment by spencercharest** [comment]
Awesome, my apologies I missed that in the wiki. Thanks for the info @Inous2018 @qdm12!
