### ISSUE TITLE
Bug: servers.json file update

### ISSUE THREAD

**Issue by zLaTk3c** [qdm12/gluetun#1739]
### Is this urgent?

Yes

### CPU arch

None

### VPN service provider

Cyberghost

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Server list outdated
      {
        "vpn": "openvpn",
        "country": "Croatia",
        "hostname": "87-1-hr.cg-dialup.net",
        "udp": true,
        "ips": [
          "146.70.8.3",
          "146.70.8.5",
          "146.70.8.6",
          "146.70.8.7",
          "146.70.8.8",
          "146.70.8.9",
          "146.70.8.10",
          "146.70.8.13",
          "146.70.8.14",
          "146.70.8.16"
        ]
      },
      {
        "vpn": "openvpn",
        "country": "Croatia",
        "hostname": "97-1-hr.cg-dialup.net",
        "tcp": true,
        "ips": [
          "146.70.8.3",
          "146.70.8.5",
          "146.70.8.6",
          "146.70.8.7",
          "146.70.8.10",
          "146.70.8.11",
          "146.70.8.12",
          "146.70.8.13",
          "146.70.8.14",
          "146.70.8.16"
        ]
      },
This should be the right ones:
          154.47.29.240
          154.47.29.232
          154.47.29.219
          154.47.29.208
          154.47.29.246
          154.47.29.199
          154.47.29.239
          154.47.29.194
          154.47.29.216
          154.47.29.237

### Share your logs

```plain text
.
```

**Comment by qdm12** [comment]
You can update the servers list yourself, see https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list

It will eventually be updated in the baked-in list, probably before next release.
