### ISSUE TITLE
new Providers:  cryptostorm, ghostpath, vpngate

### ISSUE THREAD

**Issue by d3xt3r01** [qdm12/gluetun#1775]
### What's the feature 🧐

I saw the servers json and thought you might want to add a few server providers.

Cryptostorm `https://cryptostorm.is/configs/rsa/configs.zip`
Ghostpath `https://ghostpath.com/servers`
Vpngate `'https://www.vpngate.net/en/`

**Comment by qdm12** [comment]
It's not as simple as modifying the servers.json file, there is a lot more work involved. Please create one issue per new provider request.

As for:

- Ghostpath: existing issue is #1361
- VPNGate: existing issue is #706 

So just create another issue for cryptostorm, with the issue template for a new provider.
