### ISSUE TITLE
VPN provider support: IVACY

### ISSUE THREAD

**Issue by sbag91** [qdm12/gluetun#1781]
**list of servers** : https://support.ivacy.com/servers-list/
**openvpn files** : https://support.ivacy.com/vpnusecases/openvpn-files-windows-routers-ios-linux-and-mac/

Would love to request a config file for IVACY, I have lifetime subscription to them, have had since 2016 and been great, great support, and supports port forwarding now. 

Thank you for your time!

**Comment by qdm12** [comment]
Thanks! List of servers added to existing issue #794 please subscribe to that one instead 😉 
Closing this since it's a duplicate issue.
