### ISSUE TITLE
Bug: VPN fails if ipinfo.io is unavailable

### ISSUE THREAD

**Issue by Gurnox** [qdm12/gluetun#1783]
### Is this urgent?

No

### Host OS

Unraid 6.11.5

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

Other

### What is the version of Gluetun

Latest (Apologies, can't find logs in Container)

### What's the problem 🤔

I'm noticing an issue where the VPN connection fails if https://ipinfo.io is unavailable. The issue seems to be common across multiple endpoints/geographies using both Nord and PrivateVPN. Wireguard and OpenVPN.

Is it possible to set a failback such as ipconfig.io to obtain the endpoint IP address in these instances? 

Thanks in advance!

### Share your logs

```plain text
ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 127.0.0.11:53: server misbehaving
```

**Comment by qdm12** [comment]
The VPN doesn't fail, the ip getter fails because the VPN doesn't work. It's separate subroutines, and the ip getter does not influence the vpn subroutine at all.

Check the wiki url from the unhealthy message logged to resolve your issue 😉
