### ISSUE TITLE
Feature request: run a script on interface up/down

### ISSUE THREAD

**Issue by Diaoul** [qdm12/gluetun#1785]
### What's the feature 🧐

Run a shell script when interface is up (or down)

### Extra information and references

It can be useful to set a dynamic ip in a whitelist somewhere (like [here](https://www.myanonamouse.net/api/endpoint.php/3/json/dynamicSeedbox.php))

**Comment by joshhoughton** [comment]
Agreed, this would be extremely useful!

**Comment by pauldiloreto** [comment]
+1, would love to have this as an option.

Does anyone have a work around for this scenario?

**Comment by mtfurlan** [comment]
For wireguard, we just need to set [PostUp/PostDown](https://github.com/pirate/wireguard-docs?tab=readme-ov-file#preup) in the config.

Given that the both openvpn and wireguard have support for this, I think a reasonable interface would be something along the lines of
```
environment:
    POST_INTERFACE_UP_SCRIPT=/gluetun/tun_up.sh
volumes:
    - /path/to/tun_up.sh:/gluetun/tun_up.sh
```

**Comment by qdm12** [comment]
Prioritizing this since it's kind of long overdued. Also it will be as a command to be cross-OS instead of a script path (but you could do `/bin/sh -c "my shell commands"` if you want.

This is also kind of needed to make sense of newly opened PR #2392  (more details why https://github.com/qdm12/gluetun/discussions/2393#discussioncomment-10288125)

**Comment by qdm12** [comment]
Up command is finally available: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#custom-port-forwarding-up-command
Working on the down command right now

**Comment by qdm12** [comment]
- [↪️ Documentation for up & down commands](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#custom-port-forwarding-updown-command)
- Up command added in a035a151bd44ff85087b05f62fc72bcda63af60a
- Down command added in 0374c14e429df16734d2cfa0784027f43624c247

Enjoy! 🎉
