### ISSUE TITLE
Bug: ProtonVPN cannot enable port forwarding

### ISSUE THREAD

**Issue by runverzagt** [qdm12/gluetun#1802]
### Is this urgent?

No

### Host OS

Arch-linux

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-06-18T11:04:31.032Z (commit 515ae8e)

### What's the problem 🤔

I have used Gluetun for some time with NordVPN without issue. I am switching to ProtonVPN, and wish to enable Port Forwarding. 

According to [the wiki](https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md) , if I am using OpenVPN, all I need to do is set the environment variable `VPN_PORT_FORWARDING=on` and ensure I am using a host that supports P2P. In addition, on the [ProtonVPN guide](https://protonvpn.com/support/port-forwarding-manual-setup/)  I see that I need to append +pmp to my username, which I did.

After bringing up docker-compose, I get the error seen at the bottom of the log.
This seems to imply that protonvpn doesn't support port forwarding.
I should note that when I remove `VPN_PORT_FORWARDING=on`, I am able to connect to the VPN without problem. But it appears that no port is forwarded.

I would love to know if I have made any configuration mistakes, or if this is a real bug.

Thank you!

### Share your logs

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2023-06-18T11:04:31.032Z (commit 515ae8e)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-08-17T01:12:27Z INFO [routing] default route found: interface eth0, gateway 192.168.208.1, assigned IP 192.168.208.2 and family v4
2023-08-17T01:12:27Z INFO [routing] local ethernet link found: eth0
2023-08-17T01:12:27Z INFO [routing] local ipnet found: 192.168.208.0/20
2023-08-17T01:12:27Z INFO [firewall] enabling...
2023-08-17T01:12:27Z INFO [firewall] enabled successfully
2023-08-17T01:12:28Z INFO [storage] creating /gluetun/servers.json with 17678 hardcoded servers
2023-08-17T01:12:28Z ERROR VPN settings: provider settings: port forwarding: port forwarding cannot be enabled: value is not one of the possible choices: protonvpn must be one of private internet access
2023-08-17T01:12:28Z INFO Shutdown successful
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=[username]+pmp
      - OPENVPN_PASSWORD=[password]
      - SERVER_HOSTNAMES=node-nl-47.protonvpn.net
      - VPN_PORT_FORWARDING=on
      - UPDATER_PERIOD=24h
    ports:
      - 8080:8080
      - 59636:59636
      - 59636:59636/udp
```

**Comment by qdm12** [comment]
Try pulling the image again? It might be before the port forwarding got implemented for protonvpn

**Comment by runverzagt** [comment]
Oh wow, I feel dumb. Looks like that fixed it, thanks!
