### ISSUE TITLE
VPN provider support: AzireVPN

### ISSUE THREAD

**Issue by bytechomp** [qdm12/gluetun#1818]
Please add support for [AzireVPN](https://www.azirevpn.com). They offer both OpenVPN (config examples attached) and [Wireguard](https://www.azirevpn.com/support/guides/computer/linux/wireguard-cli). They also support port forwarding.

Publicly accessible URL to the list of servers **and attach** an example Openvpn configuration file for both TCP and UDP
https://www.azirevpn.com/docs/servers#servers
[AzireVPN-se-sto-tcp.ovpn.zip](https://github.com/qdm12/gluetun/files/12418286/AzireVPN-se-sto-tcp.ovpn.zip)
[AzireVPN-se-sto-udp.ovpn.zip](https://github.com/qdm12/gluetun/files/12418284/AzireVPN-se-sto-udp.ovpn.zip)

**Comment by qdm12** [comment]
Information migrated to existing issue #497 thanks! You might want to subscribe to #497 to be alerted when changes are done.
