### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by privacyguy123** [qdm12/gluetun#1837]
### What's the feature 🧐

Https proxy 

Forgive my ignorance but is there some reason Https wouldn't be supported for the proxy?

**Comment by gmillerd** [comment]
Gluetun feature set reads ...

> Built in Shadowsocks proxy (protocol based on SOCKS5 with an encryption layer, tunnels TCP+UDP)

It's shadow proxy https://github.com/guyingbo/shadowproxy

With that said, it does support http and http and anything shadowproxy supports (socks!) if you are confused on what is supported (eg, why cannot i use it to get to https sites)

**Comment by privacyguy123** [comment]
I'm confused as to why my apps refuse the HTTPS connection saying something like "can't connect via TCP" or refusing connection altogether. Something like Privoxy doesn't have this issue.

**Comment by qdm12** [comment]
Issue title missing
