### ISSUE TITLE
Bug: Can't specify url in custom openvpn config

### ISSUE THREAD

**Issue by AnderssonPeter** [qdm12/gluetun#1865]
### Is this urgent?

No

### Host OS

Debian Bookworm

### CPU arch

x64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

3.35.0

### What's the problem 🤔

My openvpn config contains the following:
`remote pool-1.prd.domain.com 443`

But gluetun seems to fail to parse domains as it prints
`2023-09-17T18:29:18+02:00 ERROR VPN settings: OpenVPN settings: custom configuration file: extracting information from custom configuration file: extracting connection from file: on line 13: extracting from remote line: host is not an IP address: pool-1.prd.domain.com`

**Comment by bnhf** [comment]
@AnderssonPeter 

This is the way Gluetun is designed to work. No DNS until the tunnel is established. You need to use an IP address in your OpenVPN config file, as described in this part of the Wiki: https://github.com/qdm12/gluetun-wiki/blob/main/setup/openvpn-configuration-file.md

**Comment by AnderssonPeter** [comment]
So if I just resolve then manually and specify the IPs instead it should just work?

**Comment by bnhf** [comment]
@AnderssonPeter 

> So if I just resolve then manually and specify the IPs instead it should just work?

Yes.

**Comment by rugarci** [comment]
How is this supposed to work with a dynamic IP OpenVPN server?
