### ISSUE TITLE
ERROR VPN settings: OpenVPN settings: client certificate: missing value

### ISSUE THREAD

**Issue by millionsofplayers** [qdm12/gluetun#1879]
### Is this urgent?

No

### Host OS

Debian (openmediavault)

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2023-09-23T13:31:26.334Z (commit aa6dc78)

### What's the problem 🤔

When i try to start up gluetun using Airvpn (and a client.key and client.cert in the gluetun directory), it displays the error in the title and shuts down immediately. I think it's worth noting that my openvpn config file has 2 certificates and both of them are in the cert file.

### Share your logs (at least 10 lines)

```plain text
========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================

Running version latest built on 2023-09-23T13:31:26.334Z (commit aa6dc78)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2023-09-23T17:10:32-04:00 INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.2 and family v4

2023-09-23T17:10:32-04:00 INFO [routing] local ethernet link found: eth0

2023-09-23T17:10:32-04:00 INFO [routing] local ipnet found: 172.22.0.0/16

2023-09-23T17:10:32-04:00 INFO [firewall] enabling...

2023-09-23T17:10:32-04:00 INFO [firewall] enabled successfully

2023-09-23T17:10:33-04:00 INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json

2023-09-23T17:10:34-04:00 ERROR VPN settings: OpenVPN settings: client certificate: missing value

2023-09-23T17:10:34-04:00 INFO Shutdown successful
```

### Share your configuration

```yml
Portainer stack used this time

version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp
    volumes:
      - /srv/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=openvpn
      # Timezone for accurate log times
      - TZ=America/New_York
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=48h
```

**Comment by bnhf** [comment]
@millionsofplayers 

> client.key and client.cert

The certificate needs to be named: ```client.crt```

**Comment by millionsofplayers** [comment]
That seems to have worked but now i'm getting a problem connecting qbittorrent to gluetun, i'm getting "failed to deploy a stack: Container qbittorrent Creating Error response from daemon: conflicting options: port publishing and the container type network mode". Here's the docker compose: `---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /home/millions/downloads:/downloads
      - /media:/media
      - /config/qbitr/config:/config
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    `

**Comment by bnhf** [comment]
@millionsofplayers 

> ports: - 6881:6881 - 6881:6881/udp

All ports need to be opened in the Gluetun container, and removed from dependent containers. Also, I'd recommend putting all your dependent containers in the same stack, and use ```network_mode: "service:gluetun"``` instead. This way you can start and stop everything together.

**Comment by millionsofplayers** [comment]
forgot about that. Fixed and now it works again! :)
