### ISSUE TITLE
Bug: failed: Name does not resolve.

### ISSUE THREAD

**Issue by lesc6** [qdm12/gluetun#1889]
### Is this urgent?

Yes

### Host OS

Ubuntu

### CPU arch

amd64

### VPN service provider

NordVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

3.35.0

### What's the problem 🤔

not all domains are resolving:

### Share your logs (at least 10 lines)

```plain text
/ # wget http://ip-api.com/json/
----  http://ip-api.com/json/
Resolving ip-api.com (ip-api.com)... failed: Name does not resolve.
wget: unable to resolve host address 'ip-api.com'
/ # wget http://google.com
----  http://google.com/
Resolving google.com (google.com)... 142.250.187.206, 2a00:1450:4009:823::200e
Connecting to google.com (google.com)|142.250.187.206|:80... connected.
```

**Comment by bnhf** [comment]
@lesc6 

Try adding ```UNBLOCK=ip-api.com``` as an environment variable for Gluetun -- and see if that takes care of it.

**Comment by lesc6** [comment]
work like a charm! thx

**Comment by qdm12** [comment]
Thanks for the hand @bnhf !! 👍

**Comment by TheoOliveira** [comment]
There is nothing in the docs takling about that, where can i find more about these extra options?
