### ISSUE TITLE
Bug: FastestVPN [New?] Servers Issues

### ISSUE THREAD

**Issue by ZippoD** [qdm12/gluetun#1913]
EDIT: I figured out how to do a custom connect (via file, replaced server host with IP address). So the only issue here is the outdated server address/IP? for the fastestvpn NL-1 server. What prompted this troubleshooting is that the latest version of the docker was creating a duplicate "service provider" variable and I *think* it was trying to connect twice (causing it to crash). Clean install of the container took care of this problem. Can be closed I guess.

### Is this urgent?
No

### Host OS

Unraid/Docker

### CPU arch

None

### VPN service provider

FastestVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

v3.35.0

### What's the problem 🤔

Perhaps fastest VPN has changed their servers, Netherlands and others. I am not able connect to Netherlands. So I download the .ovpn config file from the provider, and the servers for Netherlands are:
nl-01.jumptoserver.com
nl-02.jumptoserver.com

When I manually specify server hostname with those values, GlueTun boot loops with error at the end "not a hostname for this provider" and lists [hard baked?] different servers for NL. 

Then I tried custom and I am also getting "hostname specified is not valid: one or more value is set but there is no possible value available"

### Share your logs (at least 10 lines)

```plain text
Sorry, only have screenshots as I don't know how to retrieve previous logs (container reboots before I have a chance to copy the logs). Should be easy to replicate.
```

**Comment by qdm12** [comment]
Hey there! Sorry I'm so late to the party. Note you can update servers data yourself (see the wiki).
Anyway, with recent updates (did you know fastestvpn wireguard is now supported 🙄 ) all servers data built-in gluetun should be up to date!
