### ISSUE TITLE
Different Speed for different vps

### ISSUE THREAD

**Issue by harissoot** [qdm12/gluetun#1916]
I have 2 vps 
1-gcp 2 core 1gb ram(US)
2-other with 4cpu 4gb ram (EU)

both use same configuration using docker compose but have way different speed
1-can get 1gbps
2-only around 400mbps

any idea how to get better speed for my 2nd vps?

**Comment by qdm12** [comment]
It depends on many factors, please read https://github.com/qdm12/gluetun-wiki/blob/main/faq/bandwidth.md
