### ISSUE TITLE
WireGuard PresharedKey parsed from wrong section of config file

### ISSUE THREAD

**Issue by kjcolley7** [qdm12/gluetun#1997]
### Is this urgent?

No

### CPU arch

None

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-11-28T07:51:53.661Z (commit c326b61)

### What's the problem 🤔

According to https://manpages.debian.org/unstable/wireguard-tools/wg.8.en.html, the configuration file format used by WireGuard should only have a `PresharedKey` field in the `[Peer]` section. However, the code in gluetun only looks for this field in the `[Interface]` section:

https://github.com/qdm12/gluetun/blob/c326b616b418a4c4de380c97bc8f47e14fe5fa5c/internal/configuration/sources/files/wireguard.go#L56

This leads to the `PresharedKey` not being loaded from properly-formatted WireGuard config files.

### Share your logs (at least 10 lines)

```plain text
gluetun  | 2023-12-08T03:11:42-08:00 INFO [routing] default route found: interface eth0, gateway <ip>, assigned IP <ip> and family v4
gluetun  | 2023-12-08T03:11:42-08:00 INFO [routing] local ethernet link found: eth0
gluetun  | 2023-12-08T03:11:42-08:00 INFO [routing] local ipnet found: <ip>/16
gluetun  | 2023-12-08T03:11:42-08:00 INFO [firewall] enabling...
gluetun  | 2023-12-08T03:11:42-08:00 INFO [firewall] enabled successfully
gluetun  | 2023-12-08T03:11:42-08:00 INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json
gluetun  | 2023-12-08T03:11:42-08:00 ERROR VPN settings: Wireguard settings: pre-shared key is not set
gluetun  | 2023-12-08T03:11:42-08:00 INFO Shutdown successful
adding an extra
couple of lines
to ensure that
this issue does
not get closed
for a dumb reason
kthxbai :)
```

### Share your configuration

```yml
Suffice it to say that I'm using `qmcgaw/gluetun` with a custom WireGuard config file bind-mounted to `/gluetun/wireguard/wg0.conf`.
```

**Comment by qdm12** [comment]
Indeed! Thanks for the detailed issue 💯 
Fixed in b00237ae6eff74504bb139f6883948e731ae604f
