### ISSUE TITLE
Feature request: fastestvpn wireguard support

### ISSUE THREAD

**Issue by bijfy** [qdm12/gluetun#2009]
Fastestvpn wireguard support

Fastestvpn wireguard request

### Extra information and references

Hi, fastestvpn has wireguard now. Kindly add that in the gluetun. If need any further info plz let me know.

**Comment by Zerauskire** [comment]
@qdm12  Any chance you'd be able to add the FastestVPN wireguard support in your next update? 
Pretty much all the existing servers support Wireguard and they all use the same Public Key.
https://github.com/qdm12/gluetun-wiki/issues/76

**Comment by qdm12** [comment]
This is done, and part of release v3.39.0 😉
