### ISSUE TITLE
Feature request: Adding secrets _FILE backend to credentials => OpenVpn/WireGuard

### ISSUE THREAD

**Issue by nolimitech** [qdm12/gluetun#2024]
### What's the feature 🧐

Implements secrets files. 
Keep the environment variables but add new one with _FILE at the end.
Exemple:
- OPENVPN_USER_FILE=/run/secrets/nordvpn_user
- OPENVPN_PASSWORD_FILE=/run/secrets/nordvpn_password

Should be a MUST. Using .env file should not be the way.

Keep the good work. Great job.

**Comment by qdm12** [comment]
There is already such feature, see https://github.com/qdm12/gluetun-wiki/blob/eb05fb39aee4e299f077796fb8660dafa4aaa3cb/setup/advanced/docker-secrets.md?plain=1

**Comment by qdm12** [comment]
Just the suffix is `_SECRETFILE` not `_FILE`. This may change in the future, but not for now.
