### ISSUE TITLE
Feature request: Support portforwarded endpoint on the HTTP control server for Wireguard connections

### ISSUE THREAD

**Issue by FlorentLM** [qdm12/gluetun#2026]
### What's the feature 🧐

~~Title says almost all, according to [the wiki](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md) there is a `/v1/publicip/ip` and a `/v1/openvpn/portforwarded` endpoints on the control server which are usable when connected through OpenVPN, but the port one is not available when connected through Wireguard.~~

The `/v1/openvpn/portforwarded` endpoint actually works with Wireguard, I'm an idiot.

### Extra information and references

~~I currently use the `/tmp/gluetun/forwarded_port` file bind-mounted in my other containers, but it's not as clean as using a http GET request, imo.~~

**Comment by cohenchris** [comment]
I'm also looking for this. I can see that my port is forwarded correctly through wireguard, but when I query `/v1/openvpn/portforwarded`, it responds with `{"port":0} `

Am I missing something here?

**Comment by qdm12** [comment]
@FlorentLM 

> I'm an idiot.

You're 100% not, that route `/v1/openvpn/portforwarded` is quite misleading. Just keeping it for historical reasons, and not adding more routes for now (eyeing doing a v4 release to remove a bunch of retro-compatibility before adding more things to the server).

@cohenchris subscribe to #2391 this is likely a bug somewhere, I'll check it out soon.

Closing this 😉
