### ISSUE TITLE
Feature request: Remap PIA port forwarded to a fixed port

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#203]
Remap PIA port forwarded to a fixed port, for example port `10000`. This would allow the user to simply listen on port 10000 no matter what the actual port forwarded is.

The rule should be (maybe tun0 or eth0):

```
iptables -t nat -A PREROUTING -i tun0 -p tcp --dport <port-forwarded> -j REDIRECT --to-port <published-local-port>
```

Changes are already implemented locally but I need to be able to test port forwarding first.

Refers to #201 
Blocked by #177

**Comment by qdm12** [comment]
@iquam

Yes it's not in the Docker image yet.

Actually can you please try, assuming your container name is `gluetun` and your PIA forwarded port is `5899`:

```sh
docker exec gluetun iptables -t nat -A PREROUTING -i tun0 -p tcp --dport 5899 -j REDIRECT --to-port 9000
docker exec gluetun iptables -t nat -A PREROUTING -i tun0 -p udp --dport 5899 -j REDIRECT --to-port 9000
```

And try to change your qbittorrent to use port `9000`, does it work?

If not, can you also try:

```sh
# Delete the previous rules
docker exec gluetun iptables -t nat -D PREROUTING -i tun0 -p tcp --dport 5899 -j REDIRECT --to-port 9000
docker exec gluetun iptables -t nat -D PREROUTING -i tun0 -p udp --dport 5899 -j REDIRECT --to-port 9000
# Try these rules, on all interfaces and not just the vpn tun0 interface
docker exec gluetun iptables -t nat -A PREROUTING -p tcp --dport 5899 -j REDIRECT --to-port 9000
docker exec gluetun iptables -t nat -A PREROUTING -p udp --dport 5899 -j REDIRECT --to-port 9000
```

**Comment by qdm12** [comment]
@inquam Alternatively you can try running the image with tag `:static-port-forward`. It should redirect the port to `9000`. Please let me know if it works so I can merge it in the main Docker image. Thanks!

**Comment by inquam** [comment]
@qdm12: Been a busy few days so not much time in front of computer. I'll have a look asap and let you know.

**Comment by qdm12** [comment]
You can still try, although with #242 you should be able to re-use the same port forward across reboots if you use the newer (v4) PIA servers (using `-e VPNSP=pia` which is the default). So I might just close the PR for the sake of keeping things simple. Although for the interest of truth, I would still be curious if this remapping works out.

**Comment by qdm12** [comment]
> nc -zvw10 returns...

```
nc: connect to 172.98.71.x port 9000 (tcp) failed: Connection refused
nc: connect to 172.98.71.x port 49254 (tcp)
```

@coreshift just to be sure, that nc command works without the port redirection right? I'll dig into it, either an iptables rule is missing or the port you specify in for example torrent clients is to be used by other peers and so there is nothing we can do to remap it as it's on the VPN server side of things.

**Comment by coreshift** [comment]
Yeah, the nc command returns success using the latest image. The forwarded port is being used for a Deluge if that matters. And I did switch the port Deluge listens on to 9000 in my testing. Should I be exposing port 9000 in my docker-compose (I tried it exposed and not and it didn't work either way)?

```
nc -zvw10 172.98.71.x 49254
Connection to 172.98.71.x 49254 port [tcp/*] succeeded!
```

**Comment by qdm12** [comment]
> Hold on. In what scenario would the static port ever work?

Indeed the scope is ridiculous! You would manually change the port number on the client side, but your service on your server side could still listen on the same port `9000`. Let's close the PR and issue, as it adds some firewall gymnastic complexity for not much.
