### ISSUE TITLE
Bug: Privado not listing Sweden in country list (Stockholm)

### ISSUE THREAD

**Issue by phase3** [qdm12/gluetun#2032]
### Is this urgent?

No

### Host OS

Docker 

### CPU arch

None

### VPN service provider

Privado

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2024-01-01T18:24:19.221Z (commit c826707)

### What's the problem 🤔

The servers file does not provide the Privado Sweden hosts (Stockholm 1-4)
They are:
      {
        "vpn": "openvpn",
        "country": "Sweden",
        "region": "Stockholm",
        "city": "Stockholm",
        "hostname": "arn-001.vpn.privado.io",
        "udp": true,
        "ips": [
          "86.106.103.67"
        ]
      },
      {
        "vpn": "openvpn",
        "country": "Sweden",
        "region": "Stockholm",
        "city": "Stockholm",
        "hostname": "arn-002.vpn.privado.io",
        "udp": true,
        "ips": [
          "86.106.103.74"
        ]
      },
      {
        "vpn": "openvpn",
        "country": "Sweden",
        "region": "Stockholm",
        "city": "Stockholm",
        "hostname": "arn-003.vpn.privado.io",
        "udp": true,
        "ips": [
          "86.106.103.81"
        ]
      },
      {
        "vpn": "openvpn",
        "country": "Sweden",
        "region": "Stockholm",
        "city": "Stockholm",
        "hostname": "arn-004.vpn.privado.io",
        "udp": true,
        "ips": [
          "86.106.103.88"
        ]
      },

### Share your logs (at least 10 lines)

```plain text
2024/01/03 18:46:39	stdout	2024-01-04T02:46:39Z INFO Shutdown successful
2024/01/03 18:46:39	stdout	2024-01-04T02:46:39Z ERROR VPN settings: provider settings: server selection: for VPN service provider privado: the country specified is not valid: value is not one of the possible choices: value sweden, choices available are Albania, Argentina, Australia, Austria, Brazil, Bulgaria, Canada, Czech Republic, Denmark, Finland, France, Germany, Greece, Hong Kong, Hungary, Iceland, India, Indonesia, Ireland, Israel, Italy, Japan, Korea, Latvia, Malaysia, Netherlands, New Zealand, Norway, Philippines, Poland, Portugal, Romania, Serbia, Singapore, Slovakia, Slovenia, South Africa, Spain, Switzerland, Taiwan, Turkey, United Kingdom, United States
2024/01/03 18:46:38	stdout	2024-01-04T02:46:38Z INFO [storage] merging by most recent 17743 hardcoded servers and 17747 servers read from /gluetun/servers.json
2024/01/03 18:46:38	stdout	2024-01-04T02:46:38Z INFO [firewall] enabled successfully
2024/01/03 18:46:38	stdout	2024-01-04T02:46:38Z INFO [firewall] enabling...
2024/01/03 18:46:38	stdout	2024-01-04T02:46:38Z INFO [routing] local ipnet found: 172.19.0.0/16
2024/01/03 18:46:38	stdout	2024-01-04T02:46:38Z INFO [routing] local ethernet link found: eth0
2024/01/03 18:46:38	stdout	2024-01-04T02:46:38Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1, assigned IP 172.19.0.2 and family v4
2024/01/03 18:46:38	stdout	💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024/01/03 18:46:38	stdout	💻 Email? quentin.mcgaw@gmail.com
2024/01/03 18:46:38	stdout	☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
2024/01/03 18:46:38	stdout	✨ New feature? https://github.com/qdm12/gluetun/issues/new
2024/01/03 18:46:38	stdout	🐛 Bug? https://github.com/qdm12/gluetun/issues/new
2024/01/03 18:46:38	stdout	🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
2024/01/03 18:46:38	stdout	
2024/01/03 18:46:38	stdout	Running version latest built on 2024-01-01T18:24:19.221Z (commit c826707)
```

**Comment by phase3** [comment]
It does find the servers once the update process completes, but it is not in the default.

**Comment by qdm12** [comment]
Please reply to https://github.com/qdm12/gluetun/issues/2118#issuecomment-2262936929 on where you found these server hostnames? Closing this as duplicate #2118 thanks!
