### ISSUE TITLE
allow to change MTU for all VPNs

### ISSUE THREAD

**Issue by ak370** [qdm12/gluetun#2044]
### What's the feature 🧐

In certain circumstances MTU needs to be smaller as some networks have issues. Wireguard side seems to have now(link below) MTU parameter but not OpenVPN. Can there be a feature that allows setting lower MTU irrespective of if it is Wireguard or OpenVPN.
I resolve OpenVPN MTU limit problem simply executing below after starting the container, however this should be configurable parameter.
docker exec f86573009ed6 /sbin/ip link set dev tun0 up mtu 1300

https://github.com/qdm12/gluetun/issues/1650

**Comment by qdm12** [comment]
Does using `OPENVPN_MSSFIX=1300` fixes it?

**Comment by qdm12** [comment]
See the `mssfix` documentation at https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/

Basically the mtu is unchanged, but internal TCP connections will have packets at most as MTU-MSSFIX. I guess your issues are related to TCP (tunneled over UDP), if you have issues with UDP tunneled over UDP, then using the `--fragment` option might be of interest but that's rather rare so far and I would prefer to no add this option.

**Comment by qdm12** [comment]
Is this resolved now? Can this be closed? Thanks!
