### ISSUE TITLE
Alternative to using IPInfo

### ISSUE THREAD

**Issue by ip2location** [qdm12/gluetun#2047]
### What's the feature 🧐

It would be good to have an alternative geolocation provider [IP2Location.io](https://www.ip2location.io/) instead of just relying on IPInfo. Perhaps you can consider the use of the IP2Location.io API. It allows 500 free geolocation queries per day without an API key. If you sign up for a free API plan and use its API key, you can get 30,000 geolocation queries per month.

**Comment by bertho-zero** [comment]
There is also https://seeip.org which is completely free and without any real limits:

IPv4:
```sh
curl https://ipv4.seeip.org
```

IPv6:
```sh
curl https://ipv6.seeip.org
```

**Comment by qdm12** [comment]
@ip2location Thanks for pointing your service out, this is awesome. Implemented in commit 423a5c37e0888e4c130e81b1d9ce26010e45dbf1 you now have a variable `PUBLICIP_API` which can be `ipinfo` or `ip2location` (together with `PUBLICIP_API_TOKEN` if you want to set it)

@bertho-zero seeip does not return information about the ip address, unlike ipinfo.io so we don't really want to use it for Gluetun. However, I added it in another project 😉 https://github.com/qdm12/ddns-updater/commit/346f4aa7f72768bd9de64e9056988590d9f03db8

**Comment by frepke** [comment]
Nice,
Can you also add https://ipdata.co/
