### ISSUE TITLE
VPN provider support: AirVPN dynamic server list

### ISSUE THREAD

**Issue by sevier** [qdm12/gluetun#2082]
Gluetun server.json is hardcoded and requires manual intervention every time AirVPN adds or removes servers.

They discuss this and some of the possible solutions here: https://airvpn.org/forums/topic/57227-server-name-cities-list-fails-check/
status.json contains a full list: https://airvpn.org/api/status/

If building this dynamic connection isn't feasible now, it would be helpful to do a one-time refresh due to their recent replacement of a handful of servers:

https://airvpn.org/forums/topic/57167-usa-servers-withdrawal-and-replacement-announcement/

Thanks.

**Comment by JordanDiefenbach** [comment]
Would like an update on this. I have a server I cannot connect to because it is not in the list.

**Comment by qdm12** [comment]
Read https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
