### ISSUE TITLE
Cyberghost not stable

### ISSUE THREAD

**Issue by klavertje44** [qdm12/gluetun#210]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [ ] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [x] Cyberghost

3. What's the version of the program?

    Running version latest built on 2020-07-20T02:32:36Z (commit a5c3545)

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Unfortunately the vpn connection is not stable. If in another container (transmission) running via gluetun network the connection drops.
I can't find anything about it in the log.
Network in transmission container is 'none'. --network=container:gluetun and the port forwarding for transmission is configured in the gluetun container.
The cyberghost account i give you is still active.

**Comment by qdm12** [comment]
When that happens with Transmission disconnecting, can you please try

```sh
docker run exec gluetun wget -qO- https://ipinfo.io
```

In order to see if the vpn is still connected?

If it works:

1. Please share your docker-compose.yml for transmission and gluetun
2. I think I deleted your credentials, would you mind resending them to [quentin.mcgaw@gmail.com](mailto:quentin.mcgaw@gmail.com)?

Thanks!

**Comment by klavertje44** [comment]
With Transmission disconnected the output is:

 "ip": "84.17.47.68",
  "hostname": "unn-84-17-47-68.cdn77.com",
  "city": "Langeheit",
  "region": "North Holland",
  "country": "NL",
  "loc": "52.4920,4.7585",
  "org": "AS60068 Datacamp Limited",
  "postal": "1566",
  "timezone": "Europe/Amsterdam",
  "readme": "https://ipinfo.io/missingauth"
The IP is not my home IP. It's from cyberghost.

After connecting Transmission after a few minutes the output is:
wget: can't connect to remote host (216.239.36.21): Operation timed out

`version: "3.3"
services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # Tinyproxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8001:8000/tcp # Built-in HTTP control server
      - 9092:9091/tcp     # Transmission
      - 51413:51413/tcp   # Transmission
      - 51413:51413/udp   # Transmission
    # command:
    # volumes: 
    # - /srv/dev-disk-by-label-PI4DATA/PI4DATA/appdata/vpn/client.key:/files/client.key:ro
    devices:
      - /dev/net/tun
    environment:
      # More variables are available, see the readme table
      - VPNSP=cyberghost
      - PROTOCOL=udp
      - OPENVPN_VERBOSITY=5
      - OPENVPN_ROOT=no
      - OPENVPN_TARGET_IP=
      # - OPENVPN_CIPHER=aes-256-cbc
      # - OPENVPN_AUTH=sha256
      - TZ=Europe/Amsterdam
      - UID=1001
      - GID=100

      # PIA, Windscribe, Surfshark and Cyberghost only
      - REGION=Netherlands
      - USER=1234567890 myuser
      - PASSWORD=1234567890 mypassword
      # PIA only
      # - PIA_ENCRYPTION=strong
      # - PORT_FORWARDING=off

      # Mullvad only
      # - COUNTRY=Sweden
      # - CITY=
      # - ISP=

      # Mullvad and Windscribe only
      # - PORT=

      # Cyberghost only
      - CYBERGHOST_GROUP=Premium UDP Europe
      - CLIENT_KEY=MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQChunY2UZQcw0F7TxgQ6dUbdAmMXdlpdtGET8gj2ua2AlM1m0OiEYKG8WU1GwTErNWsrEcJ64mRV9/DNDp9iTj8zVF1gslSHRRXDd7hZ0CnDwTtMlnENibhIdA1dS+3VG3lOOyVxfEikNmCsxJz+QdE5gQv212B3M9kStQl6FfIk+ETMivOYAmHnTXHtbAo/P1y1JWUi3Jq+oRYUXa/JRrpf0NiYP2ZBPPlz5Vc07kOReY8UEhoRUOe8W1yMYnnrIS8WdZW6Qv45Rft7OjCsg4U5yn252OCl6Ier5e+xDoRHQMm3bkyIQh3c2OTG1nwGK0N+1Nws3+S3zWFYpPtp0xVzeSkhnzRzGvBEK20x3uwcDMoj27ukzG/XR5Q6wgRjzt7AF7eXoq8SeMD724iOKbqAst5sMhoQfnQR70/M0nx+pDa7ngBvhu3TT8fWxScnpKz/5axAM4rUGw9Eopycdme06UeuzZO7n63Eo1TZw5qkjxKNVQtQ0qtFcBJul9actR+uL8c7vjZslv9OOQ4lw7G1reFM8UCFpFYG6xWUHjVdUd64fkMCG6Bhd5I0rr/pSXxi8pQ0f/tBvG4YgZd+2HX1eXhAsjW6bISNmilKW3e06I7ZXWyhU1JAIJ/FdWgJMwRIwuOGSNZ2YEOF3LYZNbtLhigl+pUqJLXytiQ3sjhkwIDAQABAoICAGq8ukoNOzhkcXIleFepS/mrcqXORrABODQfx5JKZZvYGvy1NUTgU4omBUqwQ0xeWUN2DAhzCD8BhO+7J6M0joTiKRHqOF5WTNdLkz6mO5hGJFU7ttz1dGF/RIATkGNpeIIhOJt8oTHT8Yn+D36062RAfqDrIWKUzdd+P1epaU46swBNS3YQEhoL2rOsqM/UcJ15yiLYibIrFm+HjFyI66MRV/K02opEJ4gToZs7LNZLsbE6tx8CH6fl5PrJ0R8y0APTMs/3TOx+nnVrtw7QHtUS37JRcm59DwU7lGXV8hDbWforuY9pF8JmSGCNW6VHU+d3aNFn1hmj8RnQPptJn+mwV7LnaYKGRa14DrXFcG9yrP13jogLn4J/CHkWj25imPx39bM6VPkWy1GFz1YVv8M+CC5u+CEvDtrrY8ZdcfFsILB4NqJDJpxmJcqqY/X1nsEP9KWSi9EJuAIZKU8cf44BZanxPY3Lcan17kc8DflkiI3VmMnHRj1p2XIafAACcLRIiNpb9FRqLBt2psVANOqHWQkbPE6bv5sy+1Io5dTxm8Ii/kghlPxn45IATQNHQL6J1wii7KTzsywwkUn0jhA8jD/inXLCSTOFHIY/CueI0EAK34jZJSTK2DV4hXyoVVW8dsipQiTV5WAfnqZj0jJyiNXwXUIjWkkBnMnsZkNxAoIBAQDW04Bq7pHgIoO/0nUWAnNQkSb20UdCZ5XMshGRiKKrm7FuELZjW2xGrvcs4eMb+z9U2WFY7vITXMvIQQaTYzRfbfM7Xjo2UbT7ncD7P3/WpvIQUd1W4E5Gp7WOnXmsWFKOLEDrsleYL+v6kf8gRagLtdV1HBOB3W7HX040bnnNvC8CVjeINYTIHUdG9pk9TFI5cpzYwsDo5MSBmKhHj7tVtzhlNOBudBWM9MogGv5ctZSlc3flh1OSm9i4fpKVgJGPZuJ6GzMLGeF5FyRT7UUN983009GAdZ+A/WPy7Qzi3+yFNGSZMHF6SzHalP06xpn83SQh0LMRObf/sl2iWSt5AoIBAQDAubQB6d75/5nclU2T2vluX0W/EEDMJ7G+VYfpiAV+za4pmOJWCP4chV1P7YU5V2ulnBURuksFpmkeqF61vUf75N42auFLr5EvXban9B/IwFECHBRgmDeGg954qnxcwKqFPeWTkwFZ/g3vgKn1g4hTAm0daSb7wUvS6RCSBTMErVtY41wc+5ejmkTJmlv5AZXnvw3p6x6VX7AAhqAYVatGo+rHt8CRtAZ2SAjN/KcBBjBvb5EZ2Qt4NJyHQjAcY0d6qo2WvTK0yowrUQWQBzYcAiwsk3yHHkKjQb/ubAofhGyHjz5hbvHRX8/KdEpusvTZsxZ2u3TUpS7Ny8uX3eZrAoIBAQCS4Y9XDYEN12tvVy0Y/FntxyD19scbHwnsKAAdGmfmn5Aj6idaLaMNfQmhVVzbv+BgWjTWAqHfHT5z0An38gdYDCwW9mkkxJ7Svty4rITytbih8ec9RCYg5wAa347WiJkBfj5xKMH9Wx6kdvgSD65DO3MUHDs2OrlIdeBZtwNu6HDXzy0u4zDDRkl6upaxs6Iwhy24gwg09F1rIn5EV4DFrX1QrWOaAaLOenxMkUhDCR/2M8nRVMKOZiI6msgMkhh0DOtig4BV4b8o9Oqwu3TQhRL7h2whwcpp/lY9PVjnMiVcOiNiHh4oeItAoUe2zR1yJ51RxYj5iRZGLKUaoI85AoIBAQCLgGAp2m2KLFfk8TWcRq6yE8haips8q6bfDO46PjksFhlxBrcea5f0cRygFF+QqBTFZXtiv6Q6TMBebqVPi9klHf8zCJ5XuJew33atj+nJ2FtK2aRuXwAiICXS1iT6xoMnuywIbCpYR6syp8Fec30kCOeOmGSdasdFvWo/KABL7GfoqXotiHe09p/ABjl4vosRmpuprIUQvpiZaNlNhAVcNp5lPj7nuJXM3EtzPuRru10n7Gvtd8vzkLGUvnYwtjQxOG8Qo5amgs5/NECAhpfGIlRzV7aV33OA1MDnBdE2Cxa78RXIVRQ4589yzkZqZqMRSa6C9yGUIpUEZfXS0c5NAoIBACfZs6+NZJPEWvAEAzW2yJ22PSlvcCgLhw8iTMYkda/klUl+yWeiLg8ClvBDWcKqluOVRaZSFRqG2fBLtF8MyIPXkNDVq2J1cvW3cSs0jvZEmsjeE59hq7IM1F/F0olLKtsjaa3zLrfjAfI+dT795tUaynvvFiGiVsNyBKTvTL56gpiCFCnCJxF9rls9wlNGcqfRVhppn6ftvrTYC2+ilzcejb8q4WxXp2JqCHKO2NLJZNYtDCidX8dpJ+rgxbdfKu7LbVPU7IQNs2ZIt2MkLi9C0WYC3n5JTg0jWWiLYQ4taf8L0aMUuleM8j7IwvBFqEoE/ouCssEQ/GIqnRXw8nw=
      # DNS over TLS
      - DOT=on
      - DOT_PROVIDERS=cloudflare
      - DOT_IPV6=off
      - DOT_VERBOSITY=1
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - UNBLOCK=
      - DNS_UPDATE_PERIOD=24h
      # Firewall
      - FIREWALL=off
      - EXTRA_SUBNETS=
      # Shadowsocks
      - SHADOWSOCKS=off
      - SHADOWSOCKS_PASSWORD=
      # Tinyproxy
      - TINYPROXY=on
      - TINYPROXY_USER=
      - TINYPROXY_PASSWORD=
    restart: unless-stopped  `


`version: "2.2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=
      - PASS=
      # - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
    volumes:
      - /srv/dev-disk-by-label-PI4DATA/PI4DATA/appdata/Transmission:/config
      - /srv/dev-disk-by-label-PI4DATA/PI4DATA/appdata/downloads:/downloads
      - /srv/dev-disk-by-label-PI4DATA/PI4DATA/appdata/Transmission/watch:/watch

    # ports:
    # - 9092:9091
    # - 51413:51413
    # - 51413:51413/udp
    network_mode: container:gluetun
    restart: unless-stopped`

I will send you account information to private mail

**Comment by qdm12** [comment]
Thanks for all the information, I'll work on it this evening/tomorrow
morning. Sorry again for the inconvenience, I know it's frustrating when
stuff doesn't work.

**Comment by qdm12** [comment]
As silly as it might seem, try maybe setting Transmission docker-compose's version to 3.3 instead of 2.2? I had the case where docker-compose of different versions would conflict each other's network.

**Comment by klavertje44** [comment]
It is stable now. No errors ans vpn connection on both containers. I have to find out how to access the transmission container (port 9092). That didn't work.

**Comment by qdm12** [comment]
Sorry I haven't had the time to try on my side lately, git swamped with new job & personal work.

The obvious thing that could conflict is the docker-compose version in my opinion. If that doesn't work, you could also try putting both transmission and gluetun in the same compose file, using the `"service:gluetun"` instead of `container:gluetun` for the network.

**Comment by qdm12** [comment]
I updated the Cyberghost servers information, maybe try pulling it if you encounter any issue. It should have the most up to date IP addresses. Also see #217 to track when you would be able to update the servers information yourself at some point. For now you can use it with the container as a CLI i.e. `docker run -it --rm -v /yourpath:/gluetun qmcgaw/private-internet-access update -help` which will write to `/yourpath/servers.json` the server information. I'll put more information in the readme/wiki when the issue #217 is closed.

**Comment by qdm12** [comment]
Hello there, please note that the Cyberghost setup got fixed and was changed slightly from `:latest` and `:v3.8.0`, see the [newer readme](https://github.com/qdm12/gluetun/blob/1cc0f5fee9b9947bd71a6329dff5ea760e9aa862/README.md#vpn). Essentially you need to move both your client.key and client.crt in the /gluetun directory.
