### ISSUE TITLE
Feature request: Auto adding of new servers to servers.json - Unable to use some servers due to not being in the list

### ISSUE THREAD

**Issue by JordanDiefenbach** [qdm12/gluetun#2106]
### What's the feature 🧐

auto-update/dynamically add/remove servers to server.json list

### Extra information and references

I am unable to use some of AirVPN's servers because they are not listed in the servers.json list. An update to the list would be appreciated, but I wish we could see that this list would auto-update/dynamically add/remove servers. Or even have a workaround so that the server you are attempting to connect to doesn't give an error that it isn't in the list. This may help: https://airvpn.org/forums/topic/57227-server-name-cities-list-fails-check/

**Comment by qdm12** [comment]
You can update it manually or periodically already, read https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md
