### ISSUE TITLE
Shadowsocks crashing and exiting on startup

### ISSUE THREAD

**Issue by lavaguy1** [qdm12/gluetun#211]
This is a new problem for me - since yesterday 24.7.20, I'm getting this in my PIA container log:

```
2020-07-24T11:03:31.113+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __gettimeofday_time64: symbol not found
2020-07-24T11:03:31.114+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __stat_time64: symbol not found
2020-07-24T11:03:31.114+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __localtime64_r: symbol not found
2020-07-24T11:03:31.115+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __gmtime64_r: symbol not found
2020-07-24T11:03:31.116+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/bin/ss-server: __time64: symbol not found
2020-07-24T11:03:31.117+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/bin/ss-server: __localtime64: symbol not found
2020-07-24T11:03:31.117+0200	ERROR	shadowsocks: exit status 127
2020-07-24T11:03:31.118+0200	INFO	shadowsocks: retrying in 1 minute
```

running on Raspbian, on Raspberry PI 4 (Linux pi4 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l GNU/Linux)

Anyone have any tips?

Thanks in advance,

Steve

**Comment by qdm12** [comment]
Related to the [latest commit](https://github.com/qdm12/private-internet-access-docker/commit/43b997580df4eb58c05d500b4b073be71774563b). Using the standard alpine package repository failed to install shadowsocks (bad signature). I changed it to the Netherlands mirror to fix it. Well it seems that fixed the installation but it installs a non working version... I'll try another repository. Thanks for reporting!

**Comment by Frepke** [comment]
Hmmm, no Shadowsocks problems for me.

**Comment by qdm12** [comment]
Yes it should fail only on arm32v6/v7 and 386 I think. Arm64 and amd64 were working fine. What cpu arch are you running on again Frepke? Maybe it's a 32 bit/64 bit related issue. I'll look into compiling shadowsocks from source otherwise.

**Comment by Frepke** [comment]
Running in an AMD64

**Comment by lavaguy1** [comment]
Hi, mine is running on Arm7 ... everything worked fine until picking up the latest container image... now no connection, dns tls doesn't seem to work and neither does ShadowSocks

**Comment by lavaguy1** [comment]
Super, thanks for the tip! I'll keep watching for the update.

**Comment by qdm12** [comment]
It should work now, it seems Alpine fixed their signature error for Shadowsocks. (wait for [build to finish](https://github.com/qdm12/private-internet-access-docker/runs/909946999?check_suite_focus=true)). Let me know and feel free to close the issue.

**Comment by lavaguy1** [comment]
Thanks, still need to try the latest version...

**Comment by lavaguy1** [comment]
Sorry to bother about this again, but I am getting the same behavior again - shadowsocks fails with the exact same errors as reported above, when using v3.1.0 or latest... I am using 32bit Arm Raspbian on a Pi 4 b. The only build that works is 3.0.1, and it seems to have issues with DOT...

**Comment by qdm12** [comment]
Ok I'll dig into it this weekend. For instance, on v3.0.1 what's the shadowsocks version logged at the top?

I might just try coding shadowsocks directly in the Go entrypoint program to remove that flaky dependency from Alpine.

**Comment by lavaguy1** [comment]
I'll check and let you know tomorrow... it's 3:30 on a work night here...

**Comment by lavaguy1** [comment]
the ShadowSocks version reported at start is 3.3.4
![image](https://user-images.githubusercontent.com/21985291/89748876-bf3bc800-dac5-11ea-8d6d-74fb2c6bb0a6.png)

**Comment by qdm12** [comment]
Sorry I didn't get the time to implement shadowsocks from scratch over the weekend, will try the coming evenings.

On the other hand, I see [Alpine Shadowsocks builds](https://pkgs.alpinelinux.org/packages?name=shadowsocks-libev&branch=edge) are from January so it shouldn't be a recent update that broke it 🤔

But from the logs, it's some C weird dependency problem. Maybe try with the Dockerfile:

```Dockerfile
FROM qmcgaw/private-internet-access
RUN apk add build-base
```

and build it with

```sh
docker build -t gluetun-test .
```

And replace `qmcgaw/private-internet-access` by `gluetun-test` in your run command. That might work although it makes the docker image like 300MB bigger. Maybe ARM requires some C libs for whatever Alpine related reason.

**Comment by lavaguy1** [comment]
I'll try that... I'm pretty new with docker, though - I haven't actually ever built a container with build before... ;)

Thanks for the quick reply!

**Comment by qdm12** [comment]
Let me know if you need help. Here are more detailed commands to run on your raspberry pi. Run these in a terminal:

```sh
mkdir -p ~/Desktop/gluetun
cd ~/Desktop/gluetun
echo "FROM qmcgaw/private-interner-access" > Dockerfile
echo "RUN apk add build-base" >> Dockerfile
docker build -t gluetun-test .
docker run -it --rm -e SHADOWSOCKS=on -e USER=blabla -e PASSWORD=blabla gluetun-test
```

And see if shadowsocks can start properly. Press CTRL+C to quit and remove the container.

**Comment by lavaguy1** [comment]
Awesome! thanks so much. I think I found my problem with this bit... Does it have to be in a project folder called "gluetun" (i used "~/docker" where my composefiles are)

my first attempt looked like this (i made a text file called dockerfile with the 'FROM' and 'RUN' lines in it):

user@machine:~/docker $ docker build -t gluetun-test .
Sending build context to Docker daemon  16.14GB
Step 1/2 : FROM gmcgaw/private-internet-access
pull access denied for gmcgaw/private-internet-access, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by lavaguy1** [comment]
ok. tried this:

user@machine:~/docker/gluetun/docker login -p blabla -u username
WARNING! Your password will be stored unencrypted in /home/user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
user@machine:~/docker/gluetun $ docker build -t gluetun-test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM gmcgaw/private-internet-access
pull access denied for gmcgaw/private-internet-access, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

no joy.

**Comment by qdm12** [comment]
Typo alert 🚒

It's `qmcgaw` not `gmcgaw`, then it should be able to pull even without having to login Docker. Docker thought it was a private image because of the typo.

**Comment by lavaguy1** [comment]
duh! thanks... I'm getting too old. it's always either my bad eyesight or
sleep-deprivation...

**Comment by lavaguy1** [comment]
hmmm... that builds now, but it looks like ShadowSocks is dropping an error...

![image](https://user-images.githubusercontent.com/21985291/89815044-695a3500-db44-11ea-827a-e47a87820bcd.png)

**Comment by qdm12** [comment]
Bummer 😕

In a directory, try with the Dockerfile

```Dockerfile
FROM alpine:3.12
RUN echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add -q --progress --no-cache --update shadowsocks-libev
```

With a terminal in that directory, build the image (should take a second)

```sh
docker build -t test .
```

Run it interactively

```sh
docker run -it --rm test
```

And try:

```sh
ss-server
echo $?
exit
```

Does ss-server work? What's the output exit code from `$?`?

You can remove the (10MB) built image with `docker image rm test` 😉

I have a raspberry pi 3b (somewhere hiding), I'll dig it out and try on my end.

**Comment by lavaguy1** [comment]
Thanks for the detailed help, and yes I have learned a bit!

But, I did that, and got this result:

![image](https://user-images.githubusercontent.com/21985291/89842344-a1c63700-db75-11ea-887f-e59e282ef2ff.png)

**Comment by qdm12** [comment]
retry these steps but install as well

```sh
apk add --update libcork-dev
```

before calling `ss-server` and let's see if any error shows.

I'm in the process of setting up my Raspberry Pi with Docker etc. but my god it's painfully slow, especially when coming from a 6 cores ryzen cpu 😄 I'll check about the raspberry pi 4, it might be decently faster.

**Comment by lavaguy1** [comment]
thanks i'll try. an overclocked pi4 is actually pretty snappy.

**Comment by lavaguy1** [comment]
sorry, that did the same error list with symbol not found:

Error relocating /usr/lib/libcork.so.15: __gettimeofday_time64: symbol not found
Error relocating /usr/lib/libcork.so.15: __stat_time64: symbol not found
Error relocating /usr/lib/libcork.so.15: __localtime64_r: symbol not found
Error relocating /usr/lib/libcork.so.15: __gmtime64_r: symbol not found
Error relocating /usr/bin/ss-server: __time64: symbol not found
Error relocating /usr/bin/ss-server: __localtime64: symbol not found

**Comment by qdm12** [comment]
I tried putting it every way on my raspberry pi, it won't work either 😢 They wrong-compiled their ss-server binary for ARM it seems and Alpine doesn't keep older versions of shadowsocks in their edge/testing category.

I wanted to compile it myself but [the instructions](https://github.com/shadowsocks/shadowsocks-libev#linux) seems overkill and I don't want to bloat the Dockerfile even more.

Anyway it has been long I wanted to do it with a Go program, let me try to do a quick fix with [go-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2) tomorrow.

For instance what you could do - a bit stretched but it should work - is to run a connected Shadowsocks container to gluetun, for example have:

Gluetun with Shadowsocks off but the port published

```sh
docker run ... -p 8388:8388/udp -p 8388:8388/tcp -e SHADOWSOCKS=off gluetun
```

And the connected Shadowsocks container

```sh
docker run ... -e PASSWORD=<password> --network_mode="container:gluetun" shadowsocks/shadowsocks-libev
```

And then you can access Shadowsocks as before (untested & commands are not exact). Let me know I can write you a docker-compose.yml file to run these two containers if you need.

A bit convoluted, but it should work 😄

**Comment by lavaguy1** [comment]
Thanks a lot for your generous offer! Please take your time.

I'll give the secondary container approach a try (I'm actually doing that
on an older machine that I'm replacing with this new one, but using the
container "serjs/go-socks5-proxy" which pretty much works. Not sure if it's
optimized, and it certainly isn't as feature-rich as ShadowSocks seems to
be.

**Comment by lavaguy1** [comment]
Also, is there any chance you could open a ticket on Alpine that doesn't
sound like a monkey trying to describe the low gravity Space Station
toilet? I'm not sure if I can...

**Comment by qdm12** [comment]
Done, I flagged the `shadowsocks-libev` package. I'm working on integrating Shadowsocks directly in the Go code but it might take more than one day. I'll ping back here once it's done.

**Comment by lavaguy1** [comment]
thanks again! no pressure, whenever you've got time.

**Comment by qdm12** [comment]
Quick update, I'm like 80% done, I made another whole Docker image to run a Shadowsocks server (going a bit off the goal here but why not)... It's working well, I'm just polishing off the code to have as a nice Go API so that I can easily plug it in gluetun. Should be done this weekend 👍

**Comment by qdm12** [comment]
Alright my [Go Shadowsocks server is ready](https://github.com/qdm12/ss-server), I just need to plug it in Gluetun now. Will do it tomorrow 😉

**Comment by lavaguy1** [comment]
Thanks so much Quentin! looking forward to taking it for a spin when it's
done!

**Comment by qdm12** [comment]
Can you please try (no hurry) with the image `qmcgaw/private-internet-access:shadowsocks`? It seems to work for TCP for me, but haven't tested UDP so far. You might also want to set `-e SHADOWSOCKS_LOG=on` to get some information.

**Comment by lavaguy1** [comment]
that was fast! I'll try it tomorrow night, my time (CET).

Sorry if it's getting old, but thanks for working on this!

**Comment by lavaguy1** [comment]
hmmm... that seems to have gone badly...

I added the new image name to my docker-compose.yml and did the whole:

pi@pi4:~/docker $ docker-compose stop && docker-compose rm -f
...
pi@pi4:~/docker $ docker-compose up --force-recreate --always-recreate-deps
--remove-orphans -d
Creating pia       ... done
Creating portainer ... done
Creating airsonic  ... done
Creating heimdall  ... error

and then it dumped a lot of errors about pia container not being started
yet (i have all my server processes routing over the pia container with
network directives in my compose.yml)

in the pia container itself i see:

2020-08-17T21:54:31.463209691Z [FATAL tini (6)] exec /entrypoint
failed: Exec format error


2020-08-17T21:54:37.332465839Z [FATAL tini (6)] exec /entrypoint
failed: Exec format error


2020-08-17T21:54:42.643346627Z [FATAL tini (6)] exec /entrypoint
failed: Exec format error


2020-08-17T21:54:47.635999278Z [FATAL tini (6)] exec /entrypoint
failed: Exec format error


2020-08-17T21:54:52.630045564Z [FATAL tini (7)] exec /entrypoint
failed: Exec format error


2020-08-17T21:54:57.450812121Z [FATAL tini (6)] exec /entrypoint
failed: Exec format error


2020-08-17T21:55:03.489404244Z [FATAL tini (7)] exec /entrypoint
failed: Exec format error


2020-08-17T21:55:13.429993775Z [FATAL tini (7)] exec /entrypoint
failed: Exec format error


2020-08-17T21:55:29.106910084Z [FATAL tini (7)] exec /entrypoint
failed: Exec format error


2020-08-17T21:55:57.699688877Z [FATAL tini (6)] exec /entrypoint
failed: Exec format error

**Comment by qdm12** [comment]
Hm strange, are you sure you are using the `:shadowsocks` tag?

Try with

```sh
docker run -it --rm --cap-add=NET_ADMIN -e REGION="Switzerland" -e USER=js89ds7 -e PASSWORD=8fd9s239G -e SHADOWSOCKS=on -e SHADOWSOCKS_LOG=on qmcgaw/private-internet-access:shadowsocks
```

?

**Comment by qdm12** [comment]
As mentioned in my edit, sorry that image was not built for arm and other architectures.

I made a release `v3.2.0-rc1` on Github, that *should* had triggered a cross-architecture build with the Docker tag `:v3.2.0-rc1`.

Please try with the tag `:v3.2.0-rc1` instead.

**Comment by Frepke** [comment]
With the tag `:v3.2.0-rc1` sometimes the cpu load is exceptional high. In HTOP I read CPU-loads of 380% (/entrypoint).

**Comment by lavaguy1** [comment]
will do! thanks, sorry for forgetting to mention that I'm on arm 32bit.

**Comment by lavaguy1** [comment]
Ok, that one worked fine - pulled and started ok, works fine with
ShadowSocks for windows (v. 4.1.10.0) as a local proxy.

**Comment by lavaguy1** [comment]
whoops. Yeah, i can verify... htop showing extremely high CPU utilization
up to 230% for me.

**Comment by qdm12** [comment]
Oops, it seems like I rushed Shadowsocks a bit too much. Give me a few more days 😄

**Comment by lavaguy1** [comment]
no problem - cpu load seems to drop down a lot after running for a while...
I've been running since my last post. When ShadowSocks isn't actually
processing web requests, it seems  to be well behaved. It does spike cpu
when it is processing, though, the individual "/entrypoint" processes all
go up to about 15-25% cpu (according to HTOP) and it takes a little while
to settle down (ads, maybe?). I'll keep it running until it gets in the way
of something and see how it goes...

**Comment by qdm12** [comment]
I'll profile resources for the standalone shadowsocks program I wrote to see where the crazy cpu spikes come from.

Also note that now shadowsocks is part of /entrypoint (well I should change the name to gluetun haha). The Go version might also be a tiny bit more cpu taxing than the C version although it shouldn't be such a big change I think. Maybe try with another encryption method (`SHADOWSOCKS_METHOD=aes_128_gcm`).

**Comment by Frepke** [comment]
> I'll profile resources for the standalone shadowsocks program I wrote to see where the crazy cpu spikes come from.
> 
> Also note that now shadowsocks is part of /entrypoint (well I should change the name to gluetun haha). The Go version might also be a tiny bit more cpu taxing than the C version although it shouldn't be such a big change I think. Maybe try with another encryption method (`SHADOWSOCKS_METHOD=aes_128_gcm`).

Those aren't only spike, some periods are more than 15 minutes long.

**Comment by qdm12** [comment]
Alright so it seems cpu usage steadily increases, I'm probably forgetting to close connections/threads somewhere. It also reaches 100% on my 8 cores after a few web page loads 😄 So yes definitely a problem! I'm still investigating. Sorry if that messed up your device/services when trying it.

**Comment by lavaguy1** [comment]
no problem here... easy to switch back.

**Comment by qdm12** [comment]
Should be fixed 👍  It was [essentially changing a `continue` to a `return n, nil`](https://github.com/qdm12/ss-server/commit/bc71f94681de2600b04c64f60b8114e6428a0edb) 😄 But that was challenging to find haha

Try with Docker image tag `:3.2.0-rc2`

**Comment by Frepke** [comment]
> 
> 
> Should be fixed 👍 It was [essentially changing a `continue` to a `return n, nil`](https://github.com/qdm12/ss-server/commit/bc71f94681de2600b04c64f60b8114e6428a0edb) 😄 But that was challenging to find haha
> 
> Try with Docker image tag `:3.2.0-rc2`

Running for 2 hours now without problems or high cpu-usage.
I noticed a little modification in the Shadowsocks INFO, /TCP in the info is missing 😄

**Comment by qdm12** [comment]
You mean the new one has `TCP` in the logs right?

I wanted to know when UDP is used. It turns out very little clients support UDP tunneling to shadowsocks 😕

**Comment by Frepke** [comment]
> 
> 
> You mean the new one has `TCP` in the logs right?
> 
> I wanted to know when UDP is used. It turns out very little clients support UDP tunneling to shadowsocks 😕

rc1 had it in the log, in rc2 it's gone.

**Comment by qdm12** [comment]
Ah oops probably made the wrong release then (chose the master branch instead of shadowsocks branch). Thanks for the good 👀!!

Wait for [the build](https://github.com/qdm12/gluetun/actions/runs/215259761) and pull that rc2 tag again.

**Comment by lavaguy1** [comment]
hmm... (using 3.2.0-rc2) started ok, but then the following happened. I
restarted the container a couple of times, but this was always the result:

Firewall settings:
>
>
>  |--Allowed subnets: <ip network>/24
>
>
>  |--VPN input ports:
>
>
> TinyProxy settings:
>
>
> Port: 8888
>
>
>  |--Authentication: enabled
>
>
>  |--Log level: info
>
>
> ShadowSocks settings:
>
>
>  |--Password: [redacted]
>
>
>  |--Log: disabled
>
>
>  |--Port: 8388
>
>
>  |--Method: chacha20-ietf-poly1305
>
>
> Public IP check period: 12h0m0s
>
>
> 2020-08-19T22:06:43.411+0200	INFO	routing: default route found: interface eth0, gateway xxx.xxx.0.1
>
>
> 2020-08-19T22:06:43.411+0200	INFO	routing: local subnet found: xxx.xxx.0.0/16
>
>
> 2020-08-19T22:06:43.411+0200	INFO	openvpn configurator: checking for device /dev/net/tun
>
>
> 2020-08-19T22:06:43.411+0200	WARN	TUN device is not available: open /dev/net/tun: no such file or directory
>
>
> 2020-08-19T22:06:43.411+0200	INFO	openvpn configurator: creating /dev/net/tun
>
>
> 2020-08-19T22:06:43.411+0200	INFO	firewall: enabling...
>
>
> 2020-08-19T22:06:43.411+0200	INFO	Launching standard output merger
>
>
> 2020-08-19T22:06:43.443+0200	INFO	firewall: enabled successfully
>
>
> 2020-08-19T22:06:43.444+0200	INFO	firewall: setting allowed subnets through firewall...
>
>
> 2020-08-19T22:06:43.452+0200	INFO	routing: adding <ip network> as route via xxx.xxx.0.1 eth0
>
>
> 2020-08-19T22:06:43.456+0200	INFO	tinyproxy configurator: generating tinyproxy configuration file
>
>
> 2020-08-19T22:06:43.456+0200	INFO	dns over tls: falling back on plaintext DNS at address 1.1.1.1
>
>
> 2020-08-19T22:06:43.456+0200	INFO	dns configurator: using DNS address 1.1.1.1 internally
>
>
> 2020-08-19T22:06:43.457+0200	INFO	dns configurator: using DNS address 1.1.1.1 system wide
>
>
> 2020-08-19T22:06:43.457+0200	INFO	http server: listening on 0.0.0.0:8000
>
>
> 2020-08-19T22:06:43.457+0200	INFO	shadowsocks configurator: generating configuration file
>
>
> 2020-08-19T22:06:43.457+0200	INFO	firewall: setting allowed input port 8888 through interface eth0...
>
>
> 2020-08-19T22:06:43.467+0200	INFO	tinyproxy configurator: starting tinyproxy server
>
>
> 2020-08-19T22:06:43.467+0200	INFO	firewall: setting allowed input port 8388 through interface eth0...
>
>
> 2020-08-19T22:06:43.476+0200	INFO	shadowsocks configurator: starting shadowsocks server
>
>
> 2020-08-19T22:06:43.476+0200	INFO	firewall: setting VPN connections through firewall...
>
>
> 2020-08-19T22:06:43.483+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __gettimeofday_time64: symbol not found
>
>
> 2020-08-19T22:06:43.486+0200	ERROR	shadowsocks: exit status 127
>
>
> 2020-08-19T22:06:43.487+0200	INFO	shadowsocks: retrying in 1 minute
>
>
> 2020-08-19T22:06:43.486+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __stat_time64: symbol not found
>
>
> 2020-08-19T22:06:43.487+0200	WARN	shadowsocks: stream error: read |0: file already closed
>
>
> 2020-08-19T22:06:43.488+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __localtime64_r: symbol not found
>
>
> 2020-08-19T22:06:43.488+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/lib/libcork.so.15: __gmtime64_r: symbol not found
>
>
> 2020-08-19T22:06:43.488+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/bin/ss-server: __time64: symbol not found
>
>
> 2020-08-19T22:06:43.488+0200	ERROR	shadowsocks: shadowsocks error: Error relocating /usr/bin/ss-server: __localtime64: symbol not found
>
>
> 2020-08-19T22:06:43.489+0200	WARN	close |0: file already closed
>
>
> 2020-08-19T22:06:43.489+0200	WARN	close |0: file already closed
>
>
> 2020-08-19T22:06:43.489+0200	WARN	shadowsocks error: stream error: read |0: file already closed
>
>
> 2020-08-19T22:06:43.527+0200	INFO	tinyproxy: Initializing tinyproxy ...
>
>

**Comment by qdm12** [comment]
@lavaguy1 That's the other rc2 that I wrongly based on the master branch (alpine's shadowsocks), I think you need to re-pull the image since I re-created the rc2 release this morning. I can make another release otherwise to clear things up.

**Comment by Frepke** [comment]
Rc2 running for a few hours now without problems.

**Comment by lavaguy1** [comment]
I'll try again , but I did a fresh pull about 40 minutes ago...

**Comment by lavaguy1** [comment]
nope. just deleted everything on my end and started a new pull/start...
exact same error... Could it be that the symbols it's looking for are for
64bit? I'm running Raspberry Pi OS, it's 32-bit armhf

**Comment by qdm12** [comment]
Oh silly me, it's `:v3.2.0-rc2` not `:3.2.0-rc2` sorry for the confusion. I also deleted the wrong tag on Docker Hub just to avoid any confusion. And no the Go version, although compiled, doesn't give a **** about what architecture it's running on so you won't have any symbols issue (C dynamic libraries related issues), which is one of the main reason I went this route for Shadowsocks 😉

**Comment by lavaguy1** [comment]
Great to hear! Thanks for the quick reply! I’ll give it a try tomorrow!
