### ISSUE TITLE
Bug: PIA Removed US Texas, now must use US Dallas

### ISSUE THREAD

**Issue by halkon** [qdm12/gluetun#212]
PIA removed the `US Texas` profile and renamed it to `US Dallas`, for now `US Houston` works:

https://www.privateinternetaccess.com/helpdesk/news/posts/july-20-2020-important-updated-july-20-server-changes-and-related-issues

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

    `commit f95f6201b1b38d10e0234ff40260c9b8d7c8c98e`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log

```

Configuration file:

```yml

```

Host OS: Linux

**Comment by qdm12** [comment]
Done, thanks for letting me know 👍 !

**Comment by halkon** [comment]
Any chance we can add `US Dallas`  back in the list? 

Thanks for the quick update btw

**Comment by qdm12** [comment]
Done again, sorry I thought it was already in there (got mixed up with another vpn provider). Enjoy 😉

**Comment by halkon** [comment]
You're amazing, thank you!
