### ISSUE TITLE
Bug: OpenVPN version defaults to 2.5 instead of the latest one

### ISSUE THREAD

**Issue by thelittleblackbird** [qdm12/gluetun#2124]
### Is this urgent?

No

### Host OS

debian bookworm

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

OpenVPN 2.6.8 after forced with the "OPENVPN_VERSION=2.6" option

### What's the problem 🤔

I thiknk it would be wise to default to the latest available OPENVPN version instead of defaulting to a version of almost 4 years ago.

you can force the version of openVPN with the environment variable OPENVPN_VERSION forced to 2.6

### Share your logs (at least 10 lines)

```plain text
gluetun  | 2024-02-22T10:29:34Z INFO [http server] http server listening on [::]:8000
gluetun  | 2024-02-22T10:29:34Z INFO [healthcheck] listening on 127.0.0.1:9999
gluetun  | 2024-02-22T10:29:34Z INFO [firewall] allowing VPN connection...
gluetun  | 2024-02-22T10:29:35Z INFO [openvpn] OpenVPN 2.6.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] 
[LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]

The rest is simply not relevant
```

**Comment by the-hotmann** [comment]
Would like to see this aswell. Always good to use the latest and best version - if stable.

**Comment by qdm12** [comment]
I believe there were a few providers not supporting OpenVPN 2.6 well (same was the case for 2.5 when moving away from 2.4). So it's there for you to use, but not a default for now. I'm quite out of time currently, but let's keep this issue opened and I'll change the default on the latest image to see how people react to it, when I have a bit more time.

**Comment by bluskye** [comment]
Didnt even know this was happening, thanks for the tip to force the version

**Comment by qdm12** [comment]
Changed in e0a977cf83097d7499a4be8f7633cadb5c060b64
Hopefully it won't break many setups, I believe it has not many (if none at all) breaking changes compared to 2.5. The change from 2.4 to 2.5 is a complete different story though 🥲

**Comment by thelittleblackbird** [comment]
thanks for the update, personally i feel better with a recent and stable version of the tunnel
