### ISSUE TITLE
VyprVPN: almost every server IP changed, needs to be updated

### ISSUE THREAD

**Issue by Dominik-1980** [qdm12/gluetun#2129]
VyprVPN was working on their servers and almost every server IP changed.
The Europe ones and many others.
I still can connect to some asian servers.

If I can help with informations to update the servers IPs let me know.

**Comment by DennieDev** [comment]
If you run into this like me and need a temporary solution:

You can set VPN_ENDPOINT_IP to the new IP's (Find these using dig or something similar)

And it will bypass the servers.json file.

**Comment by qdm12** [comment]
You can update the servers list yourself: https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list

I also updated the data in the latest image, that might help.
