### ISSUE TITLE
Bug: PIA some EU Regions not working

### ISSUE THREAD

**Issue by philjones88** [qdm12/gluetun#215]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

    `Running version latest built on 2020-07-28T02:41:07Z (commit cd60fe4)`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Switzerland = works
DE Frankfurt = works
Sweden = broken
Netherlands = broken

I'll keep testing more. Perhaps the IP addresses are out of date?

Using the example docker-compose and been running fine with Switzerland but was trying to find another faster PIA server

Logs:

```log

```

Configuration file:

```yml

```

Host OS:

**Comment by qdm12** [comment]
Indeed it's most likely IP addresses out of date (ughhh)

I re-resolved all the subdomains so it might just work now. Let me know if any region doesn't for you.

Thanks for letting me know!
