### ISSUE TITLE
Bug:  client certificate: missing value

### ISSUE THREAD

**Issue by Dicara1** [qdm12/gluetun#2184]
### Is this urgent?

No

### Host OS

Debian Bookworm

### CPU arch

x86_64

### VPN service provider

Cyberghost

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2024-03-25T19:19:45.506Z (commit ecc80a5)

### What's the problem 🤔

When running the latest version it errors with "VPN settings: OpenVPN settings: client certificate: missing value"
Even though the Files are there, But if i roll back and use the previous version "qmcgaw/gluetun:v3.37" it connects without any issues and works just fine.

### Share your logs (at least 10 lines)

```plain text
Running version latest built on 2024-03-25T19:19:45.506Z (commit ecc80a5)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-03-25T21:40:02Z WARN You are using the old environment variable HTTPPROXY_LOG, please consider changing it to 
2024-03-25T21:40:02Z INFO [routing] default route found: interface eth0, gateway 172.29.0.1, assigned IP 172.29.0.2 and family v4
2024-03-25T21:40:02Z INFO [routing] local ethernet link found: eth0
2024-03-25T21:40:02Z INFO [routing] local ipnet found: 172.29.0.0/16
2024-03-25T21:40:02Z INFO [routing] local ipnet found: fe80::/64
2024-03-25T21:40:02Z INFO [firewall] enabling...
2024-03-25T21:40:02Z INFO [firewall] enabled successfully
2024-03-25T21:40:03Z INFO [storage] merging by most recent 19476 hardcoded servers and 19476 servers read from /gluetun/servers.json
2024-03-25T21:40:03Z ERROR VPN settings: OpenVPN settings: client certificate: missing value
2024-03-25T21:40:03Z INFO Shutdown successful
```

### Share your configuration

```yml
version: "3"
services:
    gluetun:
        stdin_open: true
        tty: true
        restart: always
        cap_add:
            - NET_ADMIN
        container_name: gluetun-latest
        ports:
            - 5800:5800
            - 5900:5900
            - 6080:6080
            - 3000:3000
            - 3001:3001
        environment:
            - VPN_SERVICE_PROVIDER=cyberghost
            - OPENVPN_USER=***************
            - OPENVPN_PASSWORD=**************
            - SERVER_COUNTRIES=Netherlands
        volumes:
            - /DockerConfigs/GlueTUN:/gluetun
        image: qmcgaw/gluetun:latest
```

**Comment by qdm12** [comment]
Thanks for reporting this, working on it! It's due to a rather large config rework in ecc80a5a9e3f5ba8c3096eb47c9ed8544a7e8867

You can revert to v3.38.0 for the time being, which is just before this commit.

**Comment by pokemaster974** [comment]
> Thanks for reporting this, working on it! It's due to a rather large config rework in [ecc80a5](https://github.com/qdm12/gluetun/commit/ecc80a5a9e3f5ba8c3096eb47c9ed8544a7e8867)
> 
> You can revert to v3.38.0 for the time being, which is just before this commit.

Hi, I think you mislabel to revert to 3.37 instead of 3.38 ? I revert back to 3.37 and confirm it "fixes" the issue.
Regards.

**Comment by qdm12** [comment]
No, release https://github.com/qdm12/gluetun/releases/tag/v3.38.0 dates from yesterday before I went ahead to do these "big messy config changes", so you could revert to it and keep recent updates. You can use the Docker image tag is `:v3.38` for example. Or v3.37 but that one is 4 months old.

Anyway, the latest image (tag `:latest` pointing to the last commit of the master branch) should be fixed in with 6b2f350ec960a8e07fd1a78fd180260645f1b25e

Let me know and I'll close the issue, thanks!

**Comment by pokemaster974** [comment]
> No, release https://github.com/qdm12/gluetun/releases/tag/v3.38.0 dates from yesterday before I went ahead to do these "big messy config changes", so you could revert to it and keep recent updates. You can use the Docker image tag is `:v3.38` for example. Or v3.37 but that one is 4 months old.
> 
> Anyway, the latest image (tag `:latest` pointing to the last commit of the master branch) should be fixed in with [6b2f350](https://github.com/qdm12/gluetun/commit/6b2f350ec960a8e07fd1a78fd180260645f1b25e)
> 
> Let me know and I'll close the issue, thanks!

I confirm using latest is working right now. Sorry for misunderstood your first reply.

**Comment by Dicara1** [comment]
Hi,
Yep, v3.38.0 works for me aswell. Thanks

**Comment by qdm12** [comment]
@Dicara1 v3.38.0 will work fine since nothing changed really
It's latest that was broken, and should be fixed now. I'll close the issue assuming it's fixed; if it's not please create another issue (even without information, just refer to this issue).
