### ISSUE TITLE
Feature request: support for shadowsocks 

### ISSUE THREAD

**Issue by JulyMin** [qdm12/gluetun#2191]
### What's the feature 🧐

Just wanted to drop a quick note about the mention of "Built-in Shadowsocks Proxy" in the README. It seems like it might cause some confusion because it sounds like we've got a Shadowsocks client, as gluetun is a vpn client.

Maybe we could edit README to make it clearer? Or, here's a better idea: could we add support for Shadowsocks client functionality? That might be super useful!

**Comment by cantidonandaba** [comment]
> Just wanted to drop a quick note about the mention of "Built-in Shadowsocks Proxy" in the README. It seems like it might cause some confusion because it sounds like we've got a Shadowsocks client, as gluetun is a vpn client.

Yes, it is a VPN client, but that doesn't stop it from being a Shadowsocks proxy server as well. If you connect to the running container via Shadowsocks, all of that client's traffic can get routed to the gluetun-container then through the connected VPN and then finally to its target. To me that was pretty clear in the README, since that was a proposed way to test the connectivity of the container.

**Comment by JulyMin** [comment]
> > Just wanted to drop a quick note about the mention of "Built-in Shadowsocks Proxy" in the README. It seems like it might cause some confusion because it sounds like we've got a Shadowsocks client, as gluetun is a vpn client.
> 
> Yes, it is a VPN client, but that doesn't stop it from being a Shadowsocks proxy server as well. If you connect to the running container via Shadowsocks, all of that client's traffic can get routed to the gluetun-container then through the connected VPN and then finally to its target. To me that was pretty clear in the README, since that was a proposed way to test the connectivity of the container.

Thanks for explaining. You are right that the Shadowsocks server functionality is useful. However, I just hope the author could clarify in the README that it supports a Shadowsocks 'server' instead. Here's the scenario: When looking for a VPN client that supports a Shadowsocks 'client' on some Docker repository platform, gluetun might appear as the first search result. Meanwhile, users looking for a built-in Shadowsocks server are another major group, but gluetun as a search result could be overwhelmed by other Shadowsocks client results (since there are more client than server projects).

**Comment by qdm12** [comment]
@JulyMin indeed, readme updated in ee8802ee86a01829dbf070d8c38bb127f678356b 😉 Thanks for the suggestion.

> could we add support for Shadowsocks client functionality? That might be super useful!

I thought there was an existing issue for this, but I cannot find it, so until then let's keep this issue opened. I renamed the title a bit.

**Comment by qdm12** [comment]
Actually, barely any vpn providers support shadowsocks so let's just close this for now. All support openvpn, some support Wireguard, but shadowsocks support is rare.
