### ISSUE TITLE
Feature request: support alpha-numeric Wireguard endpoints

### ISSUE THREAD

**Issue by chinarut** [qdm12/gluetun#2232]
### What's the feature 🧐

I got this config from my VPN provider (sanitized):
```
[Interface]
PrivateKey = ***
Address = *.*.*.*
DNS = 8.8.8.8

[Peer]
PublicKey = ***
AllowedIps = 0.0.0.0/0
Endpoint = uk.wg.vpnprovider.com:993
PersistentKeepalive = 21
```

Gluetun doesn't accept non-numeric IPs  so I had to ping the address and update it to:
```
Endpoint = 123.0.0.123:993
```

and all is good in the Gluetun hood - thank you for all your hard work! 🏹

**Comment by qdm12** [comment]
Thanks for taking the time to create the issue.
Please subscribe to issue #788 which would resolve this (it's a few weeks away still unfortunately due to how gluetun is designed). Closing this as a duplicate (-ish) issue 😉
