### ISSUE TITLE
Bug: Error while connecting

### ISSUE THREAD

**Issue by needsupport** [qdm12/gluetun#2244]
### Is this urgent?

None

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker run

### What is the version of Gluetun

latest

### What's the problem 🤔

I can not connect. wire guard config is fine. I tested it 

### Share your logs (at least 10 lines)

```plain text
|   └── Wireguard settings:
|       ├── Private key: 
|       ├── Interface addresses:
|       |   └── 172.17.80.199/32
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun1
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── VPN input ports:
|       └── XX
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   ├── IP file path: /tmp/gluetun/ip
|   └── Public IP data API: ipinfo
└── Version settings:
    └── Enabled: yes
2024-04-29T19:51:34Z WARN DNS address is set to XX so the DNS over TLS (DoT) server will not be used. The default value changed to 127.0.0.1 so it uses the internal DoT serves. If the DoT server fails to start, the IPv4 address of the first plaintext DNS server corresponding to the first DoT provider chosen is used.
2024-04-29T19:51:34Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4
2024-04-29T19:51:34Z INFO [routing] adding route for 0.0.0.0/0
2024-04-29T19:51:34Z INFO [firewall] setting allowed subnets...
2024-04-29T19:51:34Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4
2024-04-29T19:51:34Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2024-04-29T19:51:34Z INFO [dns] using plaintext DNS at address XX
2024-04-29T19:51:34Z INFO [http server] http server listening on [::]:8000
2024-04-29T19:51:34Z INFO [healthcheck] listening on 127.0.0.1:9999
panic: runtime error: index out of range [0] with length 0
goroutine 31 [running]:
github.com/qdm12/gluetun/internal/provider/custom.getWireguardConnection(...)
	github.com/qdm12/gluetun/internal/provider/custom/connection.go:60
github.com/qdm12/gluetun/internal/provider/custom.(*Provider).GetConnection(_, {{0xc000028021, 0x9}, {{0x0, 0xffff9859a204}, 0xc000010018}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
	github.com/qdm12/gluetun/internal/provider/custom/connection.go:24 +0x35a
github.com/qdm12/gluetun/internal/vpn.setupWireguard({_, _}, {_, _}, {_, _}, {_, _}, {{0xc000028021, 0x9}, ...}, ...)
	github.com/qdm12/gluetun/internal/vpn/wireguard.go:20 +0xbe
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc0002f2840, {0x1226060, 0xc0001d8b40}, 0xc00053cd20?)
	github.com/qdm12/gluetun/internal/vpn/run.go:40 +0x4df
created by main._main in goroutine 50
	./main.go:443 +0x33d7
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=X
      - VPN_ENDPOINT_PORT=X
      - WIREGUARD_PUBLIC_KEY=X
      - WIREGUARD_PRIVATE_KEY=X
      - WIREGUARD_ADDRESSES=X
      - DNS_ADDRESS=X
      - FIREWALL_VPN_INPUT_PORTS=6X
```

**Comment by westhecool** [comment]
> ### Is this urgent?
> None
> 
> ### Host OS
> Ubuntu
> 
> ### CPU arch
> x86_64
> 
> ### VPN service provider
> Custom
> 
> ### What are you using to run the container
> docker run
> 
> ### What is the version of Gluetun
> latest
> 
> ### What's the problem 🤔
> I can not connect. wire guard config is fine. I tested it
> 
> ### Share your logs (at least 10 lines)
> ```
> |   └── Wireguard settings:
> |       ├── Private key: 
> |       ├── Interface addresses:
> |       |   └── 172.17.80.199/32
> |       ├── Allowed IPs:
> |       |   ├── 0.0.0.0/0
> |       |   └── ::/0
> |       └── Network interface: tun1
> |           └── MTU: 1400
> ├── DNS settings:
> |   ├── Keep existing nameserver(s): no
> |   ├── DNS server address to use: 
> |   └── DNS over TLS settings:
> |       ├── Enabled: yes
> |       ├── Update period: every 24h0m0s
> |       ├── Unbound settings:
> |       |   ├── Authoritative servers:
> |       |   |   └── cloudflare
> |       |   ├── Caching: yes
> |       |   ├── IPv6: no
> |       |   ├── Verbosity level: 1
> |       |   ├── Verbosity details level: 0
> |       |   ├── Validation log level: 0
> |       |   ├── System user: root
> |       |   └── Allowed networks:
> |       |       ├── 0.0.0.0/0
> |       |       └── ::/0
> |       └── DNS filtering settings:
> |           ├── Block malicious: yes
> |           ├── Block ads: no
> |           ├── Block surveillance: no
> |           └── Blocked IP networks:
> |               ├── 127.0.0.1/8
> |               ├── 10.0.0.0/8
> |               ├── 172.16.0.0/12
> |               ├── 192.168.0.0/16
> |               ├── 169.254.0.0/16
> |               ├── ::1/128
> |               ├── fc00::/7
> |               ├── fe80::/10
> |               ├── ::ffff:127.0.0.1/104
> |               ├── ::ffff:10.0.0.0/104
> |               ├── ::ffff:169.254.0.0/112
> |               ├── ::ffff:172.16.0.0/108
> |               └── ::ffff:192.168.0.0/112
> ├── Firewall settings:
> |   ├── Enabled: yes
> |   └── VPN input ports:
> |       └── XX
> ├── Log settings:
> |   └── Log level: info
> ├── Health settings:
> |   ├── Server listening address: 127.0.0.1:9999
> |   ├── Target address: cloudflare.com:443
> |   ├── Duration to wait after success: 5s
> |   ├── Read header timeout: 100ms
> |   ├── Read timeout: 500ms
> |   └── VPN wait durations:
> |       ├── Initial duration: 6s
> |       └── Additional duration: 5s
> ├── Shadowsocks server settings:
> |   └── Enabled: no
> ├── HTTP proxy settings:
> |   └── Enabled: no
> ├── Control server settings:
> |   ├── Listening address: :8000
> |   └── Logging: yes
> ├── OS Alpine settings:
> |   ├── Process UID: 1000
> |   └── Process GID: 1000
> ├── Public IP settings:
> |   ├── Fetching: every 12h0m0s
> |   ├── IP file path: /tmp/gluetun/ip
> |   └── Public IP data API: ipinfo
> └── Version settings:
>     └── Enabled: yes
> 2024-04-29T19:51:34Z WARN DNS address is set to XX so the DNS over TLS (DoT) server will not be used. The default value changed to 127.0.0.1 so it uses the internal DoT serves. If the DoT server fails to start, the IPv4 address of the first plaintext DNS server corresponding to the first DoT provider chosen is used.
> 2024-04-29T19:51:34Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4
> 2024-04-29T19:51:34Z INFO [routing] adding route for 0.0.0.0/0
> 2024-04-29T19:51:34Z INFO [firewall] setting allowed subnets...
> 2024-04-29T19:51:34Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4
> 2024-04-29T19:51:34Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
> 2024-04-29T19:51:34Z INFO [dns] using plaintext DNS at address XX
> 2024-04-29T19:51:34Z INFO [http server] http server listening on [::]:8000
> 2024-04-29T19:51:34Z INFO [healthcheck] listening on 127.0.0.1:9999
> panic: runtime error: index out of range [0] with length 0
> goroutine 31 [running]:
> github.com/qdm12/gluetun/internal/provider/custom.getWireguardConnection(...)
> 	github.com/qdm12/gluetun/internal/provider/custom/connection.go:60
> github.com/qdm12/gluetun/internal/provider/custom.(*Provider).GetConnection(_, {{0xc000028021, 0x9}, {{0x0, 0xffff9859a204}, 0xc000010018}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
> 	github.com/qdm12/gluetun/internal/provider/custom/connection.go:24 +0x35a
> github.com/qdm12/gluetun/internal/vpn.setupWireguard({_, _}, {_, _}, {_, _}, {_, _}, {{0xc000028021, 0x9}, ...}, ...)
> 	github.com/qdm12/gluetun/internal/vpn/wireguard.go:20 +0xbe
> github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc0002f2840, {0x1226060, 0xc0001d8b40}, 0xc00053cd20?)
> 	github.com/qdm12/gluetun/internal/vpn/run.go:40 +0x4df
> created by main._main in goroutine 50
> 	./main.go:443 +0x33d7
> ```
> 
> ### Share your configuration
> ```yaml
> version: "3"
> services:
>   gluetun:
>     image: qmcgaw/gluetun
>     cap_add:
>       - NET_ADMIN
>     environment:
>       - VPN_SERVICE_PROVIDER=custom
>       - VPN_TYPE=wireguard
>       - VPN_ENDPOINT_IP=X
>       - VPN_ENDPOINT_PORT=X
>       - WIREGUARD_PUBLIC_KEY=X
>       - WIREGUARD_PRIVATE_KEY=X
>       - WIREGUARD_ADDRESSES=X
>       - DNS_ADDRESS=X
>       - FIREWALL_VPN_INPUT_PORTS=6X
> ```

I can also confirm that I'm getting this error. I suggest you just change the Docker image to `qmcgaw/gluetun:v3.37.0` (The previous latest stable version)

**Comment by khaosx** [comment]
Also getting this error with the same error messages the previous posters provided.. Can confirm, changing image to v3 restores service.

**Comment by CplPwnies** [comment]
I am also getting this error. Rolled back to container tag `v3.38` for the time being

**Comment by mblanco4x4** [comment]
Same here `index out of range [0] with length 0`

Thx

**Comment by fastily** [comment]
Also seeing this error on `latest` (72e2e4b).  I'm using a protonvpn with port forwarding, which of course requires a custom provider.  My `docker` command with volume bind mount paths edited for privacy:

```bash
docker run -it --rm --pull=always --cap-add=NET_ADMIN -e BLOCK_MALICIOUS=off -e VPN_TYPE=wireguard -e VPN_SERVICE_PROVIDER=custom -v /PATH/TO/CONF/conf.conf:/gluetun/wireguard/wg0.conf -e VPN_PORT_FORWARDING_PROVIDER=protonvpn -e VPN_PORT_FORWARDING=on -v gluetun:/gluetun -p 127.0.0.1:8888:8000 -p 8080:8080 -p 6881:6881 -p 6881:6881/udp --name my_qbt_gluetun qmcgaw/gluetun
```

**Comment by ShrirajHegde** [comment]
Having the same issue.

It's better gluetun has separate `stable` and `latest` tags

**Comment by jamespoore** [comment]
+1

Rolled back to v3.38.0 and back working.

**Comment by othyn** [comment]
+1 getting this issue too, exact same logs

**Comment by lemisieur** [comment]
Same here, rolling back to the latest known-working version fixed the issue

**Comment by kainzilla** [comment]
> Also seeing this error on `latest` ([72e2e4b](https://github.com/qdm12/gluetun/commit/72e2e4b82c481090d8287f7c8e4dc50d3de6a540)).

I think for line 67 on that commit `return connection` might be meant to be `return connection, nil` but I'm not in a position to test with my current setup

**Comment by machie27** [comment]
same indeed

**Comment by jimbobjonesbob** [comment]
hadn't seen this thread, but rolled back earlier due to it being borked

**Comment by qdm12** [comment]
Fixed in b25ee21e3e05f12c3b43930dacfc0e286c24da54 sorry about that (bad commit pushed yesterday)

**Comment by qdm12** [comment]
Also since you guys seem like living on the "latest" and rather quick at reporting issues, feel free to shoot me an email at quentin.mcgaw@gmail.com in case there is a `panic` bug in Gluetun. These are usually easily fixed and critical, so I'm happy to jump straight into it. I disabled notifications for Github issues/discussions given the large amount of them and for stress reasons, but I'm always happy to fix a panic! 😄

**Comment by westhecool** [comment]
> Also since you guys seem like living on the "latest" and rather quick at reporting issues, feel free to shoot me an email at [quentin.mcgaw@gmail.com](mailto:quentin.mcgaw@gmail.com) in case there is a `panic` bug in Gluetun. These are usually easily fixed and critical, so I'm happy to jump straight into it. I disabled notifications for Github issues/discussions given the large amount of them and for stress reasons, but I'm always happy to fix a panic! 😄

Thanks, I'll do that if I ever find another critical error. I do agree with @ShrirajHegde though, that there should be separate tags for the latest stable version and the latest unstable version. I know it would be easier for me if I was able to automatically upgrade to the latest stable version without manually setting the tag.

**Comment by qdm12** [comment]
@westhecool @ShrirajHegde use the `:v3` tag 😉 See https://github.com/qdm12/gluetun-wiki/blob/main/setup/docker-image-tags.md
I could also add a `:dev` tag and have `:latest` mirror `:v3`, but I (shameful admission) like the quick feedback on the development I'm doing 😄 And also it feels like all the issues would come up when doing a "stable" (actually unstable) release (i.e. v3.39.0), so it's just pushing the problems to the release, and I'm doing my best to keep tagged v3.x.x images stable and non-buggy.
