### ISSUE TITLE
Feature request: Selecting a VPN provider region from a list (randomly, at least for PIA)

### ISSUE THREAD

**Issue by lavaguy1** [qdm12/gluetun#231]
1. What's the feature? Instead of just having one region in the provider setup, user specifies a list, and gluetun picks one at random before connecting, at start or when reconnecting or when triggered by the user over the control server. 

2. Why do you need this feature? VPNs are inherently sneaky... this makes them sneakier.

3. Extra information? I think the parameter could look like this in compose:

...
  environment:
      - REGION=Switzerland,Austria,DE Frankfurt,Netherlands
...

And each connect attempt would pick REGIONS[rnd(n)] before connecting.
Unfortunately I have no clue how that would be done in GO, or any language newer than FORTRAN...

Thanks!

**Comment by qdm12** [comment]
> or any language newer than FORTRAN...

😄

Yes I'll work on it, might not be so trivial either so don't risk yourself 😉 
Although I have some stuff I'm working on already, so it might take a bit of time until I get to this issue. Thanks for the suggestion though 👍

**Comment by lavaguy1** [comment]
Thank you, Quentin!

**Comment by qdm12** [comment]
It's now a work in progress in #262 

Not so easy, but should be done soon 😉

**Comment by qdm12** [comment]
Hey @lavaguy1! I just wanted to drop you a thank you for your sponsorship 🎉 🥇 !

**Comment by lavaguy1** [comment]
No problem, glad to do it for
 such a great tool! Thank you for putting in the effort!
