### ISSUE TITLE
Feature request: retry logic for fetching the public ip information

### ISSUE THREAD

**Issue by ezekieldas** [qdm12/gluetun#2325]
### Is this urgent?

No

### Host OS

Ubuntu 22.04.4 LTS

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-06-17T22:37:52.988Z (commit 93ed87d)

### What's the problem 🤔

The publicip endpoint is no longer functional:

```
# curl localhost:8000/v1/publicip/ip
{"public_ip":""}
```
I discovered this just recently. I have a control wrapper/application which does a regular automated request against that endpoint and stores the results. 

I'm near certain, this is due to this commit: https://github.com/qdm12/gluetun/commit/4218dba177674f4a9e8ac98f98fc5ee0da4f4ccc

Again, I wish my Go skills and knowledge were better so that I might be able to offer an option. 

With my configuration I'm running DNS (blocky) with gluetun (`network_mode: "service:gluetun"`) so I don't expect the initial dns request to succeed. However, it would be nice if there were a latter request which would make the public address available. 

I did a quick test against `gluetun:v3` and found this was not the case with this release. I also applied the optional `PUBLICIP_API=ip2location` with both `gluetun:v3` and `gluetun:latest` and found the issue consistent only with the more recent release. 

### Share your logs (at least 10 lines)

```plain text
...
2024-06-19T07:25:33-07:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2024-06-19T07:25:33-07:00 ERROR [vpn] getting public IP address information: fetching information: Get "https://api.ip2location.io/": dial tcp: lookup api.ip2location.io on 127.0.0.1:53: read udp 127.0.0.1:36706->127.0.0.1:53: read: connection refused
2024-06-19T07:25:33-07:00 ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": dial tcp: lookup api.github.com on 127.0.0.1:53: read udp 127.0.0.1:52976->127.0.0.1:53: read: connection refused
2024-06-19T07:25:35-07:00 INFO [healthcheck] healthy!
...
```
```


### Share your configuration

_No response_

**Comment by qdm12** [comment]
Hi there! Thanks for the detailed issue.
`read udp 127.0.0.1:36706->127.0.0.1:53: read: connection refused` - does that mean the DNS request is sent to blocky but is refused somehow?? Usually this happens because it's blocked by the firewall 🤔

> so I don't expect the initial dns request to succeed

Why? 🤔 

I'm trying to understand if this is solvable in some cleaner way, than wrapping the public ip information fetch in some retry logic.

The commit you mention is indeed likely the source of your problem, especially since it 'fixes'

> - Prevents requesting the public IP address N times after N VPN failures

**Comment by qdm12** [comment]
> Would it be possible to retry this somehow that doesn't assume the vpn is failed (as in the commit mentioned above)?

a54be9a9f6807596f0fd402245ea0038a6fc9a50 adds a retry mechanism **only** when `connection refused` is contained as a suffix in the error message, which should do the trick. Not super fan of adding niche code, but I couldn't figure out a more generic approach, or it would block the rest of the 'on tunnel up' setup, in case it's just the public ip echo service which is not working.

**Comment by qdm12** [comment]
Just writing this last comment made me realize there is a better solution, done in 5a09cb7787d396ce612bb948c40bd989d36eef83:

1. Peddled back the changes mentioned above
2. Added a 'wait for dns' check IF the built-in Dns over tls server is not enabled, and before the public ip fetching. This one takes ~5 seconds maximum which should work in your case, and usually should work within 1 second.

**Comment by qdm12** [comment]
Commit overridden by commit 5fd0af9395b0c34d0922f128894d05d5cb49698e since it contained a linting error
