### ISSUE TITLE
Feature request: Possibility to have currently not available values in the SERVER_* environment variables

### ISSUE THREAD

**Issue by ioqy** [qdm12/gluetun#2337]
### What's the feature 🧐

Allow invalid values in the following environment variables so that it's possible to have a list of preferred values and if a value is not found in the servers.json it is just ignored and another value is used.

* SERVER_COUNTRIES
* SERVER_REGIONS
* SERVER_CITIES
* SERVER_NAMES
* SERVER_HOSTNAMES
* ISP

### Extra information and references

Background to my problem:

On multiple occasions I had the problem with AirVPN that servers where missing from the servers.json file and the gluetun would hang in a restart loop and could not establish a connection even though the server where listed on their websites. In the past the reason for this was that the country only had one server and it was temporarily offline. Today it was a region with multiple servers that was just missing from the servers.json even though it was listed on the website.

**Comment by qdm12** [comment]
Please see https://github.com/qdm12/gluetun/pull/2419 and try image `qmcgaw/gluetun:pr-2419` to check it fits your needs?

**Comment by ioqy** [comment]
Yes, works great.

Thanks for the quick implementation.
