### ISSUE TITLE
Feature request: Scraping Port Forward number from logs

### ISSUE THREAD

**Issue by minicoz** [qdm12/gluetun#2343]
### What's the feature 🧐

Im using Proton VPN. Whenever I connect, I seem to be assigned a random PortForward number that then I have to set on my torrent/soulseek provider manually. If I restart gluetun after a week, a  new random number is assigned. 

I want to see if there is a way to scrape the logs to get the number, then set that as an env variable so that whatever app can just ask what the portforward number is as a docker-compose stack. 

Does this make any sense?

**Comment by xtinct101** [comment]
cant you just use the
`- VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/port.txt`

**Comment by jagaimoworks** [comment]
According to Gluetun's wiki Gluetun will write the obtained forwarded port into  `/tmp/gluetun/forwarded_port` within the container, which is the default value of the `VPN_PORT_FORWARDING_STATUS_FILE` option that @xtinct101 mentioned.

There is also the arguably better suited approach by using the built-in [control server](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md) which is a simple http-server that can also tell you your forwarded port.

**Comment by qdm12** [comment]
Thanks @xtinct101 and @jagaimoworks exactly on point. Closing this since it's pretty already done.
Although I'm working (locally for now) on integrations with qbitorrent/transmission/deluge to update the clients on a port forward port obtention/change 😉 Stay tuned (subscribe to #1751)
