### ISSUE TITLE
Feature request: Webhook call when forwarded port change

### ISSUE THREAD

**Issue by antanilol** [qdm12/gluetun#2351]
### What's the feature 🧐

I use gluetun with PIA and forwarding. I have seen many ways to read the forwarded port from gluetun (most of them using the fwd_port file, wich I read is being deprecated) but I think the best way would be gluetun that makes a web request by itself calling a user-configured webhook when the port is being changed and maybe at the start of gluetun too.
Making the web request entirely configurable with a template inside the docker compose file (or a separate config file) would be ideal. 
I understand it can take some time to implement such a thing, so a simple GET or POST request with the forwarded port to a user-configurable endpoint it'd be nice too.

I found [a program (written in Go)](https://github.com/afiestas/gluetun-sync) that implement this, if you want to take a look 

Thank you for your work!

**Comment by qdm12** [comment]
You can now use `VPN_PORT_FORWARDING_UP_COMMAND`, see https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#custom-port-forwarding-up-command
For example with `wget` which is built-in:

```
VPN_PORT_FORWARDING_UP_COMMAND=wget -O- --post-data='{"some data to post..."}' 'https://example.com:9000'
```
