### ISSUE TITLE
Feature request: Private Internet Access Dedicated IP Server Selection

### ISSUE THREAD

**Issue by phoenix1of1** [qdm12/gluetun#2402]
### What's the feature 🧐

PIA supports the use of dedicated IPs which are restricted to one server location. For example, once I have purchased the necessary subscription addon, I am assigned a token which I can then redeem to gain a dedicated IP address on a single server location.

Is there any way in which Gluetun can support the use of the dedicated IP service so all traffic through a Docker Stack can be routed through that dedicated IP as opposed to being routed through one of their group shared IPs?

Thanks in advance!

**Comment by qdm12** [comment]
Duplicate of #1003 please subscribe to that one instead 😉
