### ISSUE TITLE
Feature request: wireguard custom tunnel with fqdn as endpoint instad of IP

### ISSUE THREAD

**Issue by christianmerges** [qdm12/gluetun#2422]
### What's the feature 🧐

At the moment a wireguard endpoint can only be an IP address. But this don't works with hosts, who have dynamic ips. Please allow me to use a fqdn instad of ip, so the container can just reconnect after wan ip change by looking up the new ip via dns.

### Extra information and references

My only solution is to lookup up the IP manually and recreate the container and restart all containers using the gluetun network.

**Comment by qdm12** [comment]
Please subscribe to #788 since this duplicates it.

PS: I'm slowly working on it, it might be done in 1-3 months
