### ISSUE TITLE
Bug: Shadowsocks is not SOCKS5

### ISSUE THREAD

**Issue by WoLpH** [qdm12/gluetun#245]
**TLDR**: *The documentation says that shadowsocks takes care of SOCKS5 support. It does not*

As explained by the Shadowsocks site, the protocol is loosely based on SOCKS5 but it certainly is no SOCKS5: https://shadowsocks.org/en/spec/Protocol.html

To test:
```
 curl --proxy socks5h://localhost:8388 -vvv google.com
```

**Comment by WoLpH** [comment]
To add SOCKS5 support I would suggest Privoxy :)

**Comment by WoLpH** [comment]
Actually... even when using proxychains it's not working with a roughly stock configuration. I think the shadowsocks server might simply be broken.

```
# docker run --name surfshark --rm --cap-add=NET_ADMIN -e VPNSP=surfshark -p 8888:8888/tcp -p 8388:8388/tcp -p 8388:8388/udp -p 8001:8000/tcp -e EXTRA_SUBNETS='192.168.0.0/24,127.0.0.0/8' -e TINYPROXY=on -e SHADOWSOCKS=on -e SHADOWSOCKS_LOG=on -e REGION='Netherlands Amsterdam' qmcgaw/private-internet-access:latest
```

```
# proxychains curl -vvv ifconfig.me                    
ProxyChains-3.1 (http://proxychains.sf.net)
*   Trying 216.239.38.21:80...
* TCP_NODELAY set
|D-chain|-<>-127.0.0.1:8388-<><>-216.239.38.21:80-<--timeout
* Immediate connect fail for 216.239.38.21: Connection refused
*   Trying 216.239.36.21:80...
* TCP_NODELAY set
|D-chain|-<>-127.0.0.1:8388-<><>-216.239.36.21:80-<--timeout
* Immediate connect fail for 216.239.36.21: Connection refused
*   Trying 216.239.34.21:80...
* TCP_NODELAY set
|D-chain|-<>-127.0.0.1:8388-<><>-216.239.34.21:80-<--timeout
* Immediate connect fail for 216.239.34.21: Connection refused
*   Trying 216.239.32.21:80...
* TCP_NODELAY set
|D-chain|-<>-127.0.0.1:8388-<><>-216.239.32.21:80-<--timeout
* Immediate connect fail for 216.239.32.21: Connection refused
* Closing connection 0
curl: (7) Couldn't connect to server
```

proxychains config:
```
[ProxyList]
socks5 127.0.0.1 8388
```

When using this config it does work:
```
[ProxyList]
http 127.0.0.1 8888
```

**Comment by qdm12** [comment]
Indeed thanks! Also see #234 to support that feature.

**Comment by WoLpH** [comment]
Excellent! That would make it a lot more versatile.

**Comment by WoLpH** [comment]
@qdm12 regarding the test with proxychains though... am I doing something wrong or is the current shadowsocks implementation broken?

**Comment by qdm12** [comment]
It's simply because shadowsocks is not a socks5 proxy (my bad). I even coded it from scratch for gluetun, I should had updated the documentation 😄 Anyway, it uses the socks5 protocol but adds an extra stream encryption layer on top. So with a socks5 client it will just reject you because you don't have the encryption nor the password to connect. Let me know, maybe I'm missing something out.

**Comment by WoLpH** [comment]
The thing is... the example from the Shadowsocks wiki shows exactly this example: https://github.com/shadowsocks/shadowsocks/wiki/Using-Shadowsocks-with-Command-Line-Tools

So I would expect it to work.

**Comment by qdm12** [comment]
Interesting. Although that wiki page has nothing about encryption nor password, which confuses me now 😕

**Comment by WoLpH** [comment]
Perhaps the wiki is just wrong. Can't say I've ever used shadowsocks beyond a random test so I'm not sure what to expect

**Comment by qdm12** [comment]
It seems to work with different Shadowsocks client, so my guess is it's fine. (although initially it was eating all your CPU but that's another silly story of mine haha!). I'd however be curious to run the same command in a socks5 proxy without encryption.

**Comment by WoLpH** [comment]
It must be due to proxychains not using encrypted connections in that case
