### ISSUE TITLE
Regarding the Gluetun port issue on my own VPS

### ISSUE THREAD

**Issue by CevreMuhendisi** [qdm12/gluetun#2461]
### Is this urgent?

None

### Host OS

debian 10

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Hello, I'm using Gluetun and qBittorrent via Docker Compose. I've set up OpenVPN on my VPS, which doesn't have its own firewall, and I'm connecting through OpenVPN. Despite not having a firewall, the port appears to be closed. I would appreciate your help.

### Share your logs (at least 10 lines)

```plain text
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8099:8080
      - 55555:55555
      - 55555:55555/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /root/qbit.ovpn:/gluetun/custom.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - FIREWALL_VPN_INPUT_PORTS=55555

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=55555

    volumes:
      - /root/qbit/config:/config
      - /root/qbit:/downloads
    restart: always
    network_mode: service:gluetun
```

**Comment by qdm12** [comment]
You need to make sure the VPN server does forward the port `55555` to your VPN client (Gluetun), and this is not something to configure on Gluetun. If this is configured correctly, setting `FIREWALL_VPN_INPUT_PORTS` does the trick to allow it in the Gluetun firewall, and `TORRENTING_PORT=55555` should do it for qbittorrent. 

Note your VPN server forwarded port is in the published port section `55555:55555`, it should not and port mapping on the container has nothing to do with the vpn server forwarded port really.

You can test your forwarded port following https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#test-it

If it still doesn't work, this is an error on the VPN server configuration side which is quite out of scope, especially for the custom provider, in this project, so I'm closing this issue.
