### ISSUE TITLE
Feature request: Disable logging of HTTP control server

### ISSUE THREAD

**Issue by ZerNico** [qdm12/gluetun#249]
1. What's the feature?

Disable logging of HTTP control server

2. Why do you need this feature?

When using the control server to retrieve the forwarded port repeatedly it spams the log with those requests. It would be useful to be able to disable that logging if you don't need it.

3. Extra information?

The setting should be changeable with an env var like `CONTROL_LOG` if possible.

**Comment by qdm12** [comment]
Self note: run healthcheck on another localhost http server and do not log except on failure.

**Comment by qdm12** [comment]
You can now set `HTTP_CONTROL_SERVER_LOG=off` to disable the logging.
