### ISSUE TITLE
Bug: chown /etc/openvpn/target.ovpn: operation not permitted

### ISSUE THREAD

**Issue by duhruh** [qdm12/gluetun#2495]
### Is this urgent?

None

### Host OS

Linux

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

Kubernetes

### What is the version of Gluetun

Running version latest built on 2024-09-18T11:32:40.539Z (commit a2e76e1)

### What's the problem 🤔

Fails to start

### Share your logs (at least 10 lines)

```plain text
2024-09-28T03:30:48Z ERROR [vpn] writing configuration to file: chown /etc/openvpn/target.ovpn: operation not permitted
2024-09-28T03:30:48Z INFO [vpn] retrying in 15s
2024-09-28T03:30:54Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
2024-09-28T03:30:54Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
```
```


### Share your configuration

_No response_

**Comment by qdm12** [comment]
> chown /etc/openvpn/target.ovpn: operation not permitted

That's a first 🤯 !

Are you bind mounting anything funny for example `/etc/openvpn`??

**Comment by duhruh** [comment]
Sorry for the noise turns out my kubernetes security policy was too restrictive, causing the container to not be able to do anything other than manage /dev/tun for those curious here was my fix

```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - NET_ADMIN   
```

The part to note is that i removed the `drop: ALL` i had there.
