### ISSUE TITLE
Feature request: Use your own DoT/DoH Provider

### ISSUE THREAD

**Issue by iluvatyr** [qdm12/gluetun#2592]
### What's the feature 🧐

I was reading the Docs about possible : [DNS-Settings](https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/dns.md)

I just wanted to ask if it would be possible to implement something to point to your own DoT (NextDNS Adguardhome, ControlD), or is there a reason why it is not supported right now?

**Comment by qdm12** [comment]
This is work in progress (#137), and duplicate of #2149 closing this, please subscribe to that other issue!
