### ISSUE TITLE
Help: ... Problem with port 8000 / HTTP control server 

### ISSUE THREAD

**Issue by blckwhtx** [qdm12/gluetun#261]
Is there a possibility to switch off the built-in HTTP control server or change the port, because I have a docker image that already runs over 8000 ports

I want to access Pyload via Gluetun and the Pyload port is 8000

**Comment by hugalafutro** [comment]
Hi, I have done this to work around this:
stop gluetun container
run pyload container
inside pyload config/general/webinterface change the port it listens on from 8000 to i.e. 8001
stop pyload container
change pyload docker-compose.yml ports to i.e. - 8001:8001
restart gluetun container
rebuild pyload container

Hope that helps.

**Comment by qdm12** [comment]
You can now set `HTTP_CONTROL_SERVER_PORT=8001` 😉 Thanks for reporting the issue.

**Comment by satosti** [comment]
This info should be added to the [Port mapping wiki article](https://github.com/qdm12/gluetun-wiki/blob/main/setup/port-mapping.md). The current article leads users straight into this issue.
