### ISSUE TITLE
Help: Port forwarding with PIA - cannot obtain token

### ISSUE THREAD

**Issue by pryd4** [qdm12/gluetun#263]
Hi,

Trying to set up port forwarding with PIA but I'm receiving a "cannot obtain token" error.

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

Running version latest built on 2020-10-20T02:46:12Z (commit 9c73faa)

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

It looks to be attempting to obtain a token for the wrong server. I've tried deleting all previous OpenVPN configuration files and certificates on the system and reinstalling the container but that hasn't fixed the issue.

I've managed to connect to multiple PIA and NordVPN servers and successfully route qBittorrent and Transmission through the container. Had a look through the recent threads and work done on port forwarding with PIA but couldn't see this issue anywhere.

Not at all experienced with this so apologies if I'm missing something obvious.

Logs:

OpenVPN settings:,
|--User: [redacted],
|--Password: [redacted],
|--Verbosity level: 1,
|--Run as root: no,
|--Private Internet Access settings:,
 |--Network protocol: udp,
 |--Regions: uk london,
 |--Encryption preset: strong,
 |--Port forwarding: on, saved in /tmp/gluetun/forwarded_port,

2020-10-20T17:46:40.514+0100	ERROR	port forwarding: cannot obtain token: Get "https://[piausername]:***@185.xxx.xxx.xxx/authv3/generateToken": x509: certificate is valid for frankfurt439, not london412,
2020-10-20T17:46:40.514+0100	INFO	port forwarding: Trying again in 10s

Host OS:

OMV on Raspberry Pi OS (Raspberry Pi 4)

**Comment by qdm12** [comment]
Thanks for reporting this issue.

I helped two days ago a PIA engineer to test out their new TLS certificate on a test Frankfurt server with a frankfurt name for their TLS certificate.

Now, can you please try in this order, if any step fails:

1. pulling the image and try again
1. trying another region than London
1. Let me know, I'll ask the PIA engineer and test it out myself tonight.

**Comment by pryd4** [comment]
Thanks for the very quick response.

1. Tried, no change
2. Tried with France and Austria, neither successful. Example log line:

2020-10-20T18:49:59.113+0100	INFO	port forwarding: Trying again in 10s,
2020-10-20T18:49:59.112+0100	ERROR	port forwarding: cannot obtain token: Get "https://[]:***@185.xxx.xxx.xxx/authv3/generateToken": x509: certificate is valid for frankfurt439, not vienna403

Really appreciate you looking into this!

**Comment by qdm12** [comment]
I messaged him, in my opinion it might be on their end where they upgraded the certificate without adapting the certificate server name for each server. I'll add an env variable tonight to disable TLS verification for PIA v4 in order to fix it for the coming few hours/days if it's unsolved by the time I get to it.

**Comment by qdm12** [comment]
Never mind, it's bad code from when I was testing it out that I committed to master, let me fix that now.

**Comment by qdm12** [comment]
Yes that `185.216.33.146` address was the meta ip for a Frankfurt server 😄 . Anyway it's now back to its `10.0.0.1` and should work, just wait for the build to finish (see Github actions) and re-pull the Docker image.

**Comment by pryd4** [comment]
Awesome, thank you for the quick fix. I thought the IP my be for that server but redacted it just in case...

Appreciate the work you're doing with this image.
