### ISSUE TITLE
Feature request: Alternative to SAN for PIA v4 port forwarding TLS verification

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#266]
See #264 

To have a complete and fully secured TLS certificate verification, there is a code workaround to not rely on SAN but achieve the same security.

The Docker image to test it out is

```sh
docker pull qmcgaw/private-internet-access:pia-san-alternative
```

**Comment by coreshift** [comment]
Using :pia-san-alternative...

```
pia    | 2020-10-22T00:32:56.155Z       INFO    dns over tls: DNS over TLS is ready
pia    | 2020-10-22T00:32:56.197Z       ERROR   port forwarding: cannot bind port: Get "https://montreal403:19999/bindPort?payload=<redacted>&signature=<redacted>: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
pia    | 2020-10-22T00:32:56.197Z       INFO    port forwarding: Trying again in 10s
```

Out of curiosity, do I actually need to redact that stuff?

**Comment by qdm12** [comment]
> Out of curiosity, do I actually need to redact that stuff?

Yes very good point! Sorry I forgot to think about it; as in it's not a big deal either, these are just temporary tokens/signatures which get revoked when you get new ones, but still.

Thanks for the test! And this is with the re-pulled `:pia-san-alternative` image right? I'll ask the person who proposed that solution that it doesn't really work then... 😕

**Comment by coreshift** [comment]
```services:
  pia:
    image: qmcgaw/private-internet-access:pia-san-alternative
```
Yup. I even retried docker-compose pull just to make sure. Same error. Could the server matter? I'm using  CA Montreal.

**Comment by qdm12** [comment]
Nah I don't think this alternative method works. Thanks for confirming it doesn't work haha. I'll ask around to see what's up.

**Comment by L11R** [comment]
@qdm12 interesting.

I send you an invitation to my small cli-tool. It's currently private but it does work (generates wg-profiles for the servers with the lowest latency). Please check it.

**Comment by qdm12** [comment]
This was solved on PIA's end and TLS is since commit https://github.com/qdm12/gluetun/commit/6208081788660c21a8322f3e844180b0940b5506 and release `v3.16.0` fully secured
