### ISSUE TITLE
Bug: Containers behind gluetun not being able to access local LAN

### ISSUE THREAD

**Issue by lokipo** [qdm12/gluetun#273]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent?

    - [x] Yes
    - [ ] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

    latest

 

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log

```

Configuration file:

```yml

```

Host OS:
Debian

Hi,

since the removal of the "extra subnets" environment variable, containers behind gluetun are not able to reach the local network any longer. Is this intentional? Any way around this, as it unfortunately completely breaks my setup.

Best regards!

**Comment by qdm12** [comment]
Hello there! Thanks for reporting the issue.

> containers behind gluetun are not able to reach the local network any longer

Do you mean that before gluetun (or containers behind it) was able to reach devices on your custom subnet, or local docker network? What's the use case if I may ask? I'll probably add back the extra subnets code but there could be a simpler solution.

**Comment by lokipo** [comment]
Hi,

thanks for your reply.
Before the patch I was able to add an extra subnet (ie 192.168.2.0/24, my physical LAN) and a container behind gluetun was able to access hosts on this subnet (in my case transmission could alert sickchill of a downloaded file), this is no longer possible.

**Comment by qdm12** [comment]
Interesting, gimme 24 hours 😅 I'll add the pieces necessary back. I might need some testing from you as well and will comment back here. Thanks for clarifying!

**Comment by lokipo** [comment]
Brilliant, would make my life a lot easier :-)

**Comment by Tdarnell** [comment]
Commenting to subscribe for an update when this is added back :) I'm experiencing the same cross container communication problem

**Comment by qdm12** [comment]
>  I'm experiencing the same cross container communication problem

Interesting, are you having trouble for containers to reach Gluetun or for Gluetun to reach containers in its Docker network? Or in another Docker network? Or both/something else? Thanks!

**Comment by Tdarnell** [comment]
My containers reach Gluetun (and PIA network) perfectly fine, but can no longer communicate across container using LAN addresses after the latest update. I am on a v4 PIA network opvn file.

I have them configured as follows:

**PIA Gluetun container is set up as**
image: qmcgaw/private-internet-access
container_name: pia
cap_add:
      - NET_ADMIN
    network_mode: bridge
# Firewall
      - EXTRA_SUBNETS=192.168.0.0/24
ports:
     - xxxx:xxxx

**other_containers**
network_mode: service:pia # run on the vpn network

My other containers used to communicate using their LAN ip and port with no problems (192.168.0.48:xxxx), but cannot see each other anymore.

**Comment by qdm12** [comment]
Can you guys try the image `qmcgaw/private-internet-access:subnets` using the environment variable `FIREWALL_OUTBOUND_SUBNETS=192.168.2.0/24` and see if it works?

You can also check out #277 for the ongoing pull request. We're close to solving this 😉

**Comment by npawelek** [comment]
I just realized the recent `EXTRA_SUBNETS` change broke my setup as well. I've tested the subnets tag with `FIREWALL_OUTBOUND_SUBNETS` defined and that seems to apply the setting properly:

```
/ # env | grep OUTBOUND
FIREWALL_OUTBOUND_SUBNETS=10.96.0.0/12,192.168.0.10/32
/ # iptables -vnL OUTPUT
Chain OUTPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      lo      0.0.0.0/0            0.0.0.0/0
  164 46435 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    8   336 ACCEPT     all  --  *      tun0    0.0.0.0/0            0.0.0.0/0
    6   342 ACCEPT     all  --  *      eth0    10.32.0.0/12         10.96.0.0/12
    0     0 ACCEPT     all  --  *      eth0    10.32.0.0/12         192.168.0.10
    3   180 ACCEPT     tcp  --  *      eth0    0.0.0.0/0            205.251.154.208      tcp dpt:501
```

**Comment by lokipo** [comment]
Hi,

adding FIREWALL_OUTBOUND_SUBNETS and pulling the "subnets"-image fixed my issue.
Thanks a lot!

**Comment by wickedlemon** [comment]
I was suffering from the same issue of docker containers not being able to talk to each other anymore.

I've tried the new image but just get:

Recreating pia ... done
Attaching to pia
pia            | standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by lokipo** [comment]
Did you sent FIREWALL_OUTBOUND_SUBNETS in your environment?

**Comment by wickedlemon** [comment]
> Did you sent FIREWALL_OUTBOUND_SUBNETS in your environment?

Yes

Replaced EXTRA_SUBNETS=192.168.1.0/24 with FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24

**Comment by qdm12** [comment]
Hello all, thanks for testing.

@npawelek what was your issue? Was this also gluetun trying to reach containers on other networks?

@wickedlemon I guess you're running on ARM, the image from branches is only built for amd64 and one of arm architectures if I recall correctly.

Under the hood, this adds an ip route to the routing table and allows in the firewall OUTPUT traffic from the local docker network to your specified subnet. This is still more restrictive than how it was before, that's why I'm asking so many questions to ensure the problem is solved 😅 

I'll try one last thing to make things more tight/secured: allow OUTPUT traffic from only the gluetun container IP address (not its local network) to the specified subnet. If that works as well, I'll merge it to :latest. I'll do that in the coming minutes 😉

Thanks!

**Comment by qdm12** [comment]
@wickedlemon indeed, images built from Git branches are only built for amd64 (for speedier development as ARM takes quite longer to build).

Can you non-ARM guys please re-pull

```sh
docker pull qmcgaw/private-internet-access:subnets
```

to see if it still works with the modifications?

Also, are you guys happy with `FIREWALL_OUTBOUND_SUBNETS`? Or would you have a better name?

Thanks

**Comment by npawelek** [comment]
@qdm12 My use-case is probably similar to the others here, and to an extent, it's due to Kubernetes and my local configuration. I don't use `DOT` as I have an internal service that handles this in my cluster. Additionally, there is a native dependence on having access to internal cluster DNS in Kubernetes. While it's not strictly required, that's the way it works out-of-the-box. With the lack of `EXTRA_SUBNETS`, the killswitch would prevent any access to that service.

I'm okay with the current name of the variable. It doesn't particularly bother me, as long as there's a mechanism to manipulate the firewall built-in.

**Comment by lokipo** [comment]
> @wickedlemon indeed, images built from Git branches are only built for amd64 (for speedier development as ARM takes quite longer to build).
> 
> Can you non-ARM guys please re-pull
> 
> ```shell
> docker pull qmcgaw/private-internet-access:subnets
> ```
> 
> to see if it still works with the modifications?
> 
> Also, are you guys happy with `FIREWALL_OUTBOUND_SUBNETS`? Or would you have a better name?
> 
> Thanks

Hi,

just repulled, still works fine!

**Comment by Tdarnell** [comment]
> Hello all, thanks for testing.
> 
> @npawelek what was your issue? Was this also gluetun trying to reach containers on other networks?
> 
> @wickedlemon I guess you're running on ARM, the image from branches is only built for amd64 and one of arm architectures if I recall correctly.
> 
> Under the hood, this adds an ip route to the routing table and allows in the firewall OUTPUT traffic from the local docker network to your specified subnet. This is still more restrictive than how it was before, that's why I'm asking so many questions to ensure the problem is solved 😅
> 
> I'll try one last thing to make things more tight/secured: allow OUTPUT traffic from only the gluetun container IP address (not its local network) to the specified subnet. If that works as well, I'll merge it to :latest. I'll do that in the coming minutes 😉
> 
> Thanks!

I will be unable to test as I am also on ARM (raspberry pi)

**Comment by qdm12** [comment]
I just pushed changes to build for `amd64` and `arm64` (i.e. raspberry pi 3), let me know if you need another architecture.

@wickedlemon  and @Tdarnell can you try pulling it again and test it out, just to make sure the problem solved in all your situations before merging it.

Thanks!

**Comment by Tdarnell** [comment]
`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

Raspberry Pi 4 here, sorry to be a pain!

**Comment by TravisAbram** [comment]
@qdm12 Confirming that the `subnets` branch repaired the loss of local lan connectivity by specifying the FIREWALL_OUTBOUND_SUBNETS environmental. When set to the local subnet, I can now reach other local machines and containers. Let me know if you need any specific testing.

**Comment by Tdarnell** [comment]
All fixed in the latest build, thanks @qdm12

**Comment by AdomasGrigolis** [comment]
Lifesaver man.
