### ISSUE TITLE
Configuration for Privado VPN

### ISSUE THREAD

**Issue by shuntera** [qdm12/gluetun#285]
1. What's the feature? Configuration details for the Privado VPN

2. Why do you need this feature? I have the Privado VPN

3. Extra information? https://privado.io/

**Comment by qdm12** [comment]
Thanks for creating the issue! I'm on it 👍 

For my future self:

- [documentation](https://support.privado.io/kb/article/359-linux-openvpn-setup/)
- [servers zip file](https://privado.io/apps/ovpn_configs.zip)

**Comment by qdm12** [comment]
Hey @shuntera I went extra quick on that one.

Can you please try it using the Docker image `qmcgaw/private-internet-access:privado`, documentation for it is [here](https://github.com/qdm12/gluetun/tree/privado).

Let me know, if everything works out of the box, I'll merge it with the main code base. Thanks!

**Comment by qdm12** [comment]
Hey @shuntera did you have time trying it? Otherwise I'll merge it by the end of the day. Thanks

**Comment by shuntera** [comment]
Testing it now.

**Comment by shuntera** [comment]
The VPNSP environment variable shown on the page at  https://github.com/qdm12/gluetun/tree/privado does not list privado as an option, I'm goingto just assume it is 'privado' and add that.

**Comment by shuntera** [comment]
Received this error when performing docker-compose up -d, have obscured my actual password with _mypassword_ but it is 11 characters and contains upper and lower case letters, numbers and other characters like &*%$@

**ERROR: Invalid interpolation format for "environment" option in service "gluetun": "PASSWORD=mypassword"**

**Comment by shuntera** [comment]
Found the problem: [https://stackoverflow.com/questions/49897503/docker-compose-invalid-interpolation-format-for-environment-option-in-service](url)

I have a $ sign in my password, I escaped it by adding another $ after it - solved!

**Comment by shuntera** [comment]
Checking docker-compose logs I can see the line 

**ip getter: Public IP address is** 

And the displayed IP address is what I expected to see.

So it is working just fine, thanks!!!

**Comment by shuntera** [comment]
Not sure if this should be a new issue, but seeing as you added a 'servers zip file' for yourself as a ToDo!

Given there are a bunch of servers you can connect to with Privado, it would be useful if you could select a number of servers from the list and have a way to either randomly choose one from the selected servers or perform a quick ping test on those selected and choose the one with the one with the best response time. Otherwise users will select one the first time and never ever look to other servers which might give them better performance.

It could even be a separate tool, one that goes through that server list, pings thm and then suggests to the user which one is currently giving the fastest respsonse times.

I also notice that on the Privado site each server is listed with its capacity.  If that capacity is exceeded how would the user know with gluetun - would something be written to the log (which they might never look at). Perhaps if gluetun could sense that it could try with another server in the list, either the full list or a subset that the user has nominated to choose from.

**Comment by qdm12** [comment]
Nice thanks for letting me know! 👍 

Yes the `$` causes issues because of how the shell works 😕

> as you added a 'servers zip file' for yourself as a ToDo

That's done!

> it would be useful if you could select a number of servers from the list

You can specify multiple cities with i.e. `City1,City2` and a random one will be picked from the filtered servers. Also subscribe to #290 for a better rotation system.

> perform a quick ping test on those selected and choose the one with the one with the best response time

Could you please create an issue with that? That's a good idea, although I'll not be able to do it soon I think (running out of time haha)

> each server is listed with its capacity

Where do you see this? Unfortunately, the server information is obtained from their ZIP file and hardcoded in the code and I don't think they have an API to get this live information. Plus I want to keep the 'not leak anything' until the VPN is up, so fetching the capacity at runtime is going against that. It could however get it once the tunnel is up with one of the servers and change server then. That looks rather complicated to implement, but if it's publicly accessible somewhere, I can create an issue about it.

I'll merge Privado in `:latest` tonight,

**Comment by shuntera** [comment]
This shows the server list with 'capacity' However I think this actually shows how many people are connected to it rather than what the max number of users is.

https://partners.privado.io/server-list

**Comment by qdm12** [comment]
Any chance to have access to that without logging in? 🤔

**Comment by shuntera** [comment]
>>You can specify multiple cities with i.e. City1,City2 and a random one
will be picked from the filtered servers


Currently there are variables for City and Server, and I am using:

CITY=jfk
SERVER_NUMBER=3

If I change that to CITY=jfk,mia,lax then what needs to happen with
SERVER_NUMBER as there seems to be 12 servers in Los Angeles, but only 3
for Miami or are you saying that CITY would change to
CITY=jfk1,jfk2,jfk3,lax1,lax2,lax3,lax4,lax5,lax7,mia1,mia2,mia3 or
something likethat with SERVER_NUMBER being ignored/redundant?

**Comment by shuntera** [comment]
Sure -- attached

**Comment by qdm12** [comment]
If you specify `CITY=jfk,mia,lax` and `SERVER_NUMBER=3` this acts as an AND filter, so only jfk-3, mia-3 and lax-3 will be used. Maybe I should change that to filter on the server hostname only (jfk-3,mia-3) instead? Breaking compatibility while it's not too late 😅

**Comment by qdm12** [comment]
FYI if you re-pull the latest image, you can now use `HOSTNAME` (only) to filter servers with i.e. `-e HOSTNAME=ams-001.vpn.privado.io,ams-003.vpn.privado.io`.
