### ISSUE TITLE
Help: 

### ISSUE THREAD

**Issue by zgababa** [qdm12/gluetun#286]
Hi, 

Thanks for this amazing work !  I'm currently using your project with my app running on docker-compose. To be fully integrated with this app. I have some questions :

   - How to know when the IP is ready, and what is it ? (Main usage, is to have a wait-for-it, start my app only when the vpn is setted)

   - How to renew the IP ? (without restart all the container if it's possible) And gets its new ip ? 

Thanks for your reply ! 
 
1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?
    - [x] NordVPN

3. What's the version of the program?

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

Host OS:
MacOS

**Comment by qdm12** [comment]
There is a firewall in place which blocks outbound traffic except to the VPN servers as soon as the container starts, so you shouldn't have to worry about starting another app using it. If the VPN is not up yet or doesn't work, no Internet will go through.

But let me know if there is a need for knowing when the VPN is up, I can add an endpoint to the HTTP control server to obtain the status, that would a be a nice little addition.

To renew the IP, you can simply restart openvpn using the HTTP control server, see [this Wiki page](https://github.com/qdm12/gluetun/wiki/Control-Openvpn#restart). You can automate that with for example `wget -qO- http://gluetun:8000/openvpn/actions/restart`.

However, with Nordvpn I believe it's only 1 IP address per server, so make sure you don't narrow the server selection (i.e. with `SERVER_NUMBER`) to a single server. You can use for example `SERVER_NUMBER=123,456` to specify two servers though. There are multiple servers per region, so specifying a single region should work too.

**Comment by qdm12** [comment]
Also you can get the IP address from the `/gluetun/ip` file that you can mount in a Docker volume or bind mount with your host.

I'll close this issue for now, let's continue the discussion on #287 for the future-to-be status endpoint which will return the IP address, and when things are 'up' over HTTP, that should be easier.
