### ISSUE TITLE
Feature request: Status endpoint

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#287]
1. What's the feature?

    Add a status endpoint to the HTTP control server giving

    - if the VPN is up
    - if DNS over TLS is up
    - what's your IP
    - if port forwarding is up

2. Why do you need this feature?

    To automate things

3. Extra information?

Refers to #286

**Comment by zgababa** [comment]
Thanks to have consideration for it.

In the file /gluetun/ip you save the ip. But I'm wondering, do you use this file like a "black list" ? 

If an IP is in the file, you don't take it, and ask to the vpn client to get a new one ? 

Thanks,

**Comment by qdm12** [comment]
@zgababa Good point, a better rotation would be nice. See #290 for that IP Rotation, I'll try to finish these two issues weekend.

**Comment by zgababa** [comment]
Thanks !

**Comment by qdm12** [comment]
Hey @zgababa sorry for the delay. The status endpoint is now done on the `:latest` Docker image and will be available on release v3.9.0 soon once I make a release. You can access it at the URIs `/v1/openvpn/status`, `/v1/dns/status` and `/v1/updater/status` depending on which status you want.

However the openvpn status will be running for a 2-3 seconds before it actually finishes initialization. No data will leak as the firewall would be up already, but you may want to use the status of the dns which is 'running' only when openvpn connects.

Thanks for your patience!
