### ISSUE TITLE
Bug: Gluetun cannot reach other containers in its local network

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#289]
**TLDR**: *Gluetun cannot reach other containers in its local Docker network*

It might be routing problem, see what changed in #268 

Also email *Matthias* about it once solved.

**Comment by networkprogrammer** [comment]
I mentioned this here. https://github.com/qdm12/gluetun/issues/281#issuecomment-722709887

**Comment by networkprogrammer** [comment]
I added the `FIREWALL_OUTBOUND_SUBNETS` env variable with the local docker network and that also resolved the issue.

**Comment by qdm12** [comment]
Thanks a ton @networkprogrammer !

I was being tired/idiot, it was just that iptables rule you mentioned missing. It now works.

I think it's fine to let gluetun reach other containers on its local private network as that will likely not leak Internet traffic.
But let me know if you think that's a risk, then I can add an environment variable to activate/deactivate that feature (probably left on by default for usability though).
