### ISSUE TITLE
Possibility to connect to LAN-devices through shadowsocks when outside my LAN

### ISSUE THREAD

**Issue by frepke** [qdm12/gluetun#291]
1. What's the feature?
Reach LAN-devices when connected to the Shadowsocks server from outside LAN-network

2. Why do you need this feature?
No need for another VPN-server

3. Extra information?

**Comment by VMax2** [comment]
If you open your ShadowSocks port on your router and redirect it to your Docker Host IP and in your container ENV section you set your "FIREWALL_OUTBOUND_SUBNETS" then you will be able to reack your LAN and devices under it giving to the shadowsocks client the router's public IP or a dinamic dns one if you don't have a public address

**Comment by qdm12** [comment]
Oh if that solves it then a big thanks @VMax2 ... easier than I thought 😄 

I'll test it in the coming days, but @frepke feel free to try too 🥼

**Comment by VMax2** [comment]
Yes it work for me ;-)

**Comment by frepke** [comment]
I can confirm it's working (although I don't need it anymore 🙃)

**Comment by qdm12** [comment]
Added documentation for it: https://github.com/qdm12/gluetun/wiki/Connect-to-gluetun#access-your-lan-through-gluetun

Thanks guys!
