### ISSUE TITLE
Block-outside-dns

### ISSUE THREAD

**Issue by Frepke** [qdm12/gluetun#316]
**Host OS** (approximate answer is fine too): Debian Buster

**Is this urgent?**: No

**What VPN provider are you using**: Surfshark

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-12-22T01:22:09Z (commit 22965cc)
```

**What's the problem** 🤔

`
ERROR	openvpn: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:7: block-outside-dns (2.4.9)
`

**Comment by Frepke** [comment]
Thanks,

And as quick as always 👍

**Comment by qdm12** [comment]
Alright, I'll see what I can do this evening. But essentially that's an option for Windows only which fails openvpn not accepting unknown config options. I thought adding a pull filter https://github.com/qdm12/gluetun/commit/bb76477467cc6f8053d5f55bdade12fcfcca6ed1 would had fixed it 🤔

**Comment by qdm12** [comment]
Can you please try again? Should be fixed. Thanks!

**Comment by Frepke** [comment]
Hi Quentin,
Tried the latest version and the error is gone 👍 

Thanks
