### ISSUE TITLE
Feature request: Please suppport VPN Unlimited

### ISSUE THREAD

**Issue by marcuslannister** [qdm12/gluetun#318]
**What's the feature?** 🧐
Suppport VPN Unlimited, the website is www.vpnunlimitedapp.com

- Support this new feature because that and that
Because I have VPN Unlimited account.

**Comment by qdm12** [comment]
Hello there, I sent an email to their support to obtain their servers information as well as some details on their openvpn configuration files as they don't seem to be exposed to the public sadly. I'll get back to you when they reply. Thanks!

**Comment by qdm12** [comment]
Alternatively subscribe to #223 which should allow you to plug in your ovpn file. Although there is still quite a bit of work to be done, so please don't expect it to be ready so soon. Thanks!

**Comment by qdm12** [comment]
I still haven't heard back from their support and I can't access their openvpn configuration files. I'll close it for now. It should be doable to use once #223 gets resolved.

**Comment by qdm12** [comment]
See https://github.com/qdm12/gluetun/issues/223#issuecomment-791994363
