### ISSUE TITLE
Help: How to get the public IP via HTTP?

### ISSUE THREAD

**Issue by averri** [qdm12/gluetun#319]
It's possible to get the forwarded port via HTTP using this URL:
```
http://<your-docker-host-ip>:8000/openvpn/portforwarded
```

How to get the assigned public IP via HTTP?

**Comment by qdm12** [comment]
Hey there!

Note that after v3.8.1, you should access the port forwarded with `/v1/openvpn/portforwarded` 😉 

I added an endpoint at `/v1/publicip/ip` which should return for example `{"public_ip": "2.4.1.5"}`, it will be available on the `:latest` image once the build completes. Note that I haven't tested it so feel free to let me know if it works or doesn't 😅

**Comment by Frepke** [comment]
For me it's working 😊

**Comment by qdm12** [comment]
Thanks @Frepke let's close it then 👍

**Comment by averri** [comment]
Hi @qdm12, that's very useful, thank you so much. :1st_place_medal:
