### ISSUE TITLE
Feature request: Ability to pass user provided OpenVPN opts

### ISSUE THREAD

**Issue by SudoNova** [qdm12/gluetun#334]
**What's the feature?** 🧐

  - Add ability to pass custom OpenVPN opts, to for e.g.change `redirect-gateway` or add `route`s.

**Optional extra information** 🚀

Hello. Personally I use the docker container with `--net=host` (`network_mode: host` in `docker-compose`), because I can't use port forwarding feature of PIA when the port is bound to docker bridge interface (I know there is a workaround [here](https://github.com/qdm12/gluetun/issues/53), your support is great).
Now forget about my situation, one might want to use this container as a proxy for other containers or operating systems, but want to bypass VPN if connection destination is a repository inside their private zone. 
I think it's a good idea, to let people pass openvpn opts directly (e.g. via an environment variable like `OPENVPN_OPTS="--route blahblah"`, or by passing parameters to entrypoint), or let them provide an openvpn compatible file that can be validated by openvpn binary, to be appended to the final `.ovpn` file you generate (there can be a bind mount for user's externally provided configuration inside the container).

**Comment by qdm12** [comment]
Good idea, also feel free to subscribe to #223 which is related.

**Comment by qdm12** [comment]
Done in 394abbbe352d369fb07eac9ba97d6a6f40efc9ed with `OPENVPN_FLAGS` (a month ago, sorry I forgot to mention!)
