### ISSUE TITLE
Feature request: support ExpressVPN

### ISSUE THREAD

**Issue by Leiasticot** [qdm12/gluetun#341]
**What's the feature?** 🧐

Can you add support of ExpressVPN : https://www.expressvpn.com/
Thanks you :)

**Comment by qdm12** [comment]
Hey, thanks for the suggestion.

Would you know if they offer some openvpn files for all their servers? In order not to break functionality, the minimum I need is:

- hostname and port for each server, which has to be obtained from a public webpage/zip file/etc.
- an example ovpn config file for tcp
- an example ovpn config file for udp

Ideally

- IP address per server instead of hostname
- An API HTTP endpoint from which you can get their server information
- Region/City names for each server

Maybe you can ask their support for it? That would help me greatly to implement it. Thanks!

**Comment by qdm12** [comment]
Alternatively subscribe to #223 which should allow you to plug in your ovpn file. Although there is still quite a bit of work to be done, so please don't expect it to be ready so soon. Thanks!

**Comment by qdm12** [comment]
Closing as it can't be added on its own, you will have to use a configuration file with #223 once it's resolved.

**Comment by qdm12** [comment]
See https://github.com/qdm12/gluetun/issues/223#issuecomment-791994363

**Comment by qdm12** [comment]
@Leiasticot could you upload all the openvpn files in a zip file here? I'll add support for expressvpn, although it won't automatically detect new servers added by expressvpn since their openvpn files are locked behind a login page (and it's too time consuming to implement the login etc.)

**Comment by 13steinj** [comment]
@qdm12 I can upload these files next evening as soon as I check that there isn't any user-specific / tokens directly in the files, if you just need anyone's config.

**Comment by qdm12** [comment]
Hey @13steinj thanks for the help!

If there is user specific private keys in the files I can still add support for expressvpn.

However, if there is user AND server specific keys, I won't add it, it's much simpler if you just add the openvpn config directly and follow the steps in the wiki.

**Comment by yolanv** [comment]
> Hey @13steinj thanks for the help!
> 
> If there is user specific private keys in the files I can still add support for expressvpn.
> 
> However, if there is user AND server specific keys, I won't add it, it's much simpler if you just add the openvpn config directly and follow the steps in the wiki.

ExpressVPN .ovpn files are not filled with private keys or anything of the likes. You have to provide username / password authentication upon each connect attempt.

**Comment by qdm12** [comment]
@yolanv can you share some of the configs then? If you have a zip file with all of them that would be ideal.

Even better if you find a publicly available url to download the zip file / config files from, so gluetun can auto-update server information.

**Comment by gerardlouw** [comment]
As far as I could tell, the .ovpn files for all of their locations are identical besides the endpoint. Here I've found an (unofficial) list of endpoints in the repo of a Kodi addon which seems up-to-date: https://github.com/Zomboided/service.vpn.manager.providers/blob/master/ExpressVPN/LOCATIONS.txt

As for the .ovpn files... I've only been able to find ones for the UDP endpoints. Someone uploaded a bunch of them to this repo: https://github.com/Xenov-X/docker-qbittorent-vpn/blob/b9b54d95156247c52da08bd4093f21bb2d6ec653/openvpn/expressvpn/my_expressvpn_macau_udp.ovpn I just confirmed that at least this particular file is identical to what can currently be downloaded from their website.

**Comment by qdm12** [comment]
@gerardlouw thanks! That definitely helps. I will however only add support for UDP since I don't want to try-and-fail every possible options to have a reliable tcp connection with their server, unless you can get me at least one single tcp config file?

I pinned the issue and will get to it soon, but I'm a bit swamped recently so it might take a few days/weeks.

**Comment by gaizaharduz** [comment]
@qdm12 I've searched their website everywhere, and was unable to find TCP .ovpn files. They only seem to provide UDP ones. Given this fact, restricting to UDP seems fine. They seem to recommend that anyway on https://www.expressvpn.com/what-is-vpn/protocols/openvpn.

**Comment by gerardlouw** [comment]
@qdm12 I've searched their website everywhere, and was unable to find TCP .ovpn files. They only seem to provide UDP ones. Given this fact, restricting to UDP seems fine. They seem to recommend that anyway on https://www.expressvpn.com/what-is-vpn/protocols/openvpn.

**Comment by qdm12** [comment]
Yes restricting to UDP works for me! I should have an image to try in the coming 1-2 days.

**Comment by qdm12** [comment]
I'm working on it now. Whilst I'm at it, does expressvpn support Wireguard? If yes can you get Wireguard configuration files?

**Comment by gerardlouw** [comment]
They specifically don't support Wireguard. For some reason they decided to develop their own open source "next gen" protocol instead: https://github.com/expressvpn/lightway-core. I'm not aware of any other providers who have implemented it, so for now it probably wouldn't make sense for you to support it.

**Comment by qdm12** [comment]
Thanks for the reply. Also in their OpenVPN config, are you sure it's always `verify-x509-name Server name-prefix`? That looks like a nice security hole, but I guess up to them 😄

**Comment by qdm12** [comment]
It's up! Can you try with:

```sh
docker run -it --rm --name gluetun --cap-add=NET_ADMIN -e VPNSP=expressvpn -e OPENVPN_USER=abc -e OPENVPN_PASSWORD=abc -e COUNTRY=Netherlands qmcgaw/gluetun:expressvpn
```

I removed the following servers since they don't resolve:

- `usa-los-angeles-4-ca-version-2.expressnetw.com`
- `azerbaijan-ca-version-2.expressnetw.com`
- `usa-washingtondc-2-ca-version-2.expressnetw.com`

**Comment by gerardlouw** [comment]
Thanks for doing this @qdm12! I've confirmed that it's working. :)

**Comment by qdm12** [comment]
It's now merged in the latest image, feel free to switch to it to get more recent updates (and also check it's still working 😄)
