### ISSUE TITLE
Setting MTU on poor connection

### ISSUE THREAD

**Issue by hassanalizadeh** [qdm12/gluetun#345]
Hi, Could you please tell me how can I set MTU size on low speed networks? I'm using PIA and there is an option use small packets, so when I'm using your container experiencing very slow connection.
I found I can do that by setting "mssfix" option to for example 1200 in openvpn config file, but I cant find any environment variable or any guide in your repository how to set it.
Please help me how can I do that
Thanks

**Comment by qdm12** [comment]
I've added it in https://github.com/qdm12/gluetun/commit/e7372f22cb2fae7a3322523a423d8d566250a704 with the environment variable `OPENVPN_MSSFIX` that you can set to for example `1300`. Don't forget to re-pull the `:latest` image 😉  Let me know if it doesn't work and I'll re-open the issue.

**Comment by hassanalizadeh** [comment]
It's working fine now. In my case 1200 is working fine. I appreciate your job. Thanks
