### ISSUE TITLE
Bug: Openvpn cipher option and data-ciphers

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#350]
```
DEPRECATED OPTION: --cipher set to 'aes-256-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-256-cbc' to --data-ciphers or change --cipher 'aes-256-cbc' to --data-ciphers-fallback 'aes-256-cbc' to silence this warning
```

To investigate and fix for all providers depending on the cipher set.

**Comment by dsm1212** [comment]
Seems like something maybe converts the cipher to lower case no matter what I set in the environment.

**Comment by qdm12** [comment]
oh yes it does convert it for consistency (and unit testing), but that doesn't matter to openvpn.

What you see is a change introduced a few days ago with openvpn 2.5.0 which now suggests to add the `data-ciphers` option on top of the `cipher` option. I'll address that in the coming weeks, as it's still working unless we update to the next openvpn release (which doesn't exist). But your `cipher` option, wether you set it manually or not, is well set don't worry.

**Comment by qdm12** [comment]
This is now solved (has been for a few days, sorry I forgot) on `:latest`; now when you set `OPENVPN_CIPHER` it does set it for all the cipher fields Openvpn 2.5.x requires. Let me know if you are still having troubles with it. Thanks!
