### ISSUE TITLE
Trackers are showing IP is from USA/New York. When I look up the IP is shows Switzerland like it should?

### ISSUE THREAD

**Issue by aprillia99** [qdm12/gluetun#353]
Is this a prob? Testing the connection through qBittorrent client and the testing trackers are showing USA/New York when I manually search the IP is shown in Switzerland like the settings say it should.

**Comment by qdm12** [comment]
Not sure what you mean.

1. Is your non vpn location new york?
2. What does https://ipinfo.io/xx.xx.xx.xx where xxs is your VPN ip address show?
3. Maybe that's the tracker location? Or qbittorrent's ip database is outdated?

**Comment by aprillia99** [comment]
Here are some photos- When using Check my IP for torrents it pulls that IP Address, it shows it in the US. When I use the link you posted it shows the same IP in switzerland. Does this make sense?

My non vpn location is the US, however not New York

![image](https://user-images.githubusercontent.com/20538128/105782043-b343a580-5f41-11eb-8fcd-63f3ae00acb4.png)

![image](https://user-images.githubusercontent.com/20538128/105782080-c8203900-5f41-11eb-9601-be1fb64deb02.png)

**Comment by qdm12** [comment]
Yes that's likely one of them - probably qbittorrrent's ip database - that is outdated. Public IP addresses do change places over time. Usually it's within the same country, from a region to another. But it can move country as well, see [this](https://en.wikipedia.org/wiki/IPv4_address_exhaustion#Markets_in_IP_addresses) 😉

Usually https://www.maxmind.com/en/home has the most updated data, you can have a go. I'll close the issue for now as I can't do anything really 😄
