### ISSUE TITLE
Help: PIA "region" values

### ISSUE THREAD

**Issue by dsm1212** [qdm12/gluetun#362]
The documentation links "regions" to the PIA site page. But it's not clear what the region values are supposed to be. The sample one "CA Montreal" is not even listed on the PIA page linked. It's I think what Canada resolves to. How do I determine the correct region names?

**Comment by qdm12** [comment]
Thanks for creating the issue.

I added the list [in the wiki here](https://github.com/qdm12/gluetun/wiki/Private-Internet-Access-Servers). Let me know if you find an inconsistency or a server no longer valid, although these should be fetched directly from PIA's API servers so they *should* be up to date. Thanks!
