### ISSUE TITLE
Bug: cannot update Surfshark servers

### ISSUE THREAD

**Issue by Frepke** [qdm12/gluetun#377]
**Host OS** (approximate answer is fine too): Debian Buster

**Is this urgent?**: No

**What VPN provider are you using**: Surfshark

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-02-09T03:06:18Z (commit f852b77)
```

**What's the problem** 🤔

`ERROR	updater: cannot update Surfshark servers: lookup pt-lou.prod.surfshark.com on 127.0.0.1:53: no such host`

**Share your logs...**

...*careful to remove i.e. token information with PIA port forwarding*

```
ERROR	updater: cannot update Surfshark servers: lookup pt-lou.prod.surfshark.com on 127.0.0.1:53: no such host
```

**Comment by qdm12** [comment]
Try with `:latest`? I think #364 somehow solved it, at least on my machine. I think `pt-lou.prod.surfshark.com` no longer exists 🧐

**Comment by Frepke** [comment]
Have to wait for the new build 😃

**Comment by qdm12** [comment]
You are fast 😄 Should be built now!

**Comment by Frepke** [comment]
Latest is running now

**Comment by Frepke** [comment]
Hmmmm, today it's `ERROR	updater: cannot update Surfshark servers: lookup vn-hcm.prod.surfshark.com on 127.0.0.1:53: no such host`

**Comment by qdm12** [comment]
Ahhh I think I know why.... these are due to some malicious IP addresses blocked by DNS over TLS 😄 Hard to say which ones though. Try when disabling BLOCK_MALICIOUS? I'll think about something to go around the restriction. The easy way is to use plain DNS without DNS over TLS but that's not great privacy wise (leaking DNS queries to the VPN provider).

**Comment by Frepke** [comment]
That's what I thought in the first place, but in the composefile I've `- BLOCK_MALICIOUS=off`

**Comment by qdm12** [comment]
Are you using the updater with the period or in CLI mode?

If you are using the one with the `UPDATER_PERIOD`, can you try the image with tag `:fix-updater-dns` (once it's built)? It's now using 1.1.1.1 in plaintext in order not be blocked eventually: https://github.com/qdm12/gluetun/commit/b5914aeff29ff2bd6b098790b35a7d0bb5c74fa0

**Comment by Frepke** [comment]
`:fix-updater-dns` is running right now with `UPDATER_PERIOD=1h`

**Comment by Frepke** [comment]
👍 `INFO	updater: updating Surfshark servers...`
Using 1.1.1.1 is a working solution

**Comment by qdm12** [comment]
Done in fe5ec205fc20d8f78f6f76fcc2a2bb62c031edc4

Until I do some re-implementation in Go of DNS over something-something let's keep it to use Cloudflare's DNS `1.1.1.1` over plaintext.
