### ISSUE TITLE
Add Deluge plugin to wiki

### ISSUE THREAD

**Issue by codetheweb** [qdm12/gluetun#382]
I had a lot of trouble getting port forwarding to work with my setup until I stumbled across this [plugin for Deluge](https://github.com/jawilson/deluge-piaportplugin), made specifically for gluetun. Would it be possible to add a note about it to the [port forwarding page of the wiki](https://github.com/qdm12/gluetun/wiki/Port-forwarding)? Or maybe make a new page for application-specific tips.

CC @jawilson

**Comment by qdm12** [comment]
Done [here](https://github.com/qdm12/gluetun/wiki/Port-forwarding#deluge) thanks for letting me know! 👍 🥇

**Comment by codetheweb** [comment]
Thank you!
