### ISSUE TITLE
VPN provider support: VPNUnlimited

### ISSUE THREAD

**Issue by dlshumway** [qdm12/gluetun#385]
1. Name of the provider: Keepsolid VPNUnlimited at https://www.vpnunlimitedapp.com/
2. URL to Openvpn configuration files (zip, JSON, etc.): Generated on site at https://my.keepsolid.com/
3. VPN server side port forwarding documentation, if available: Generated file attached - removed certificates
[vpnunl_calsample.ovpn.zip](https://github.com/qdm12/gluetun/files/5984104/vpnunl_calsample.ovpn.zip)

If 2. is not available, it's not possible to support the provider yet.
Please instead subscribe to #223

**Comment by qdm12** [comment]
Please subscribe to the issue #318 which this issue duplicates.

Unfortunately with the current implementation, 2. has to be accessible publicly (i'll precise that in the Github template, my bad) so this will have to wait for #223 unless VPNUnlimited expose their openvpn configuration files publicly.
