### ISSUE TITLE
Feature request: Restarting both openvpn and dns if it stays unhealthy for N seconds

### ISSUE THREAD

**Issue by ansred** [qdm12/gluetun#386]
**What's the feature?** 🧐
Restarting both openvpn and dns if it stays unhealthy for N seconds?

- Support this new feature because that and that
It will help many users with different VPN providers, especially in this thread, where it seems many people they have to restart manually as autoheal container is not doing what is supposed to do.

**Optional extra information** 🚀
Example:
[https://github.com/MarkusMcNugen/docker-qBittorrentvpn/issues/60](url)

Where in that thread, talking about qbittorrentVPN + AutoHeal container

so it would be nicer if gluetun, if would have a  built-in auto-heal feature within the container to restart itself after # of seconds, and we can configure that with env maybe or if it detects any errors per the logs (so we don't have to worry about configuring any env)

Slack chat thread:
[https://qdm12.slack.com/archives/CQQ5BQU8N/p1613421956000600](url)

Thanks

**Comment by qdm12** [comment]
There is a test image `qmcgaw/gluetun:restart-unhealthy` where openvpn gets restarted when the container is unhealthy, feel free to test it out 😉

**Comment by ansred** [comment]
Awesome! Deploying it now on a secondary stack and testing with netdata container.

**Comment by ansred** [comment]
I got some random restarts which is good, but not sure why.


Here is the latest logs


```
2021/04/10 16:45:52 INFO storage: merging by most recent 7350 hardcoded servers and 7350 servers read from /gluetun/servers.json


2021/04/10 16:45:52 INFO routing: default route found: interface eth0, gateway 192.168.0.1


2021/04/10 16:45:52 INFO routing: local ethernet link found: eth0


2021/04/10 16:45:52 INFO routing: local subnet found: 192.168.0.0/20


2021/04/10 16:45:52 INFO routing: default route found: interface eth0, gateway 192.168.0.1


2021/04/10 16:45:52 INFO routing: adding route for 0.0.0.0/0


2021/04/10 16:45:52 INFO firewall: firewall disabled, only updating allowed subnets internal list


2021/04/10 16:45:52 INFO routing: default route found: interface eth0, gateway 192.168.0.1


2021/04/10 16:45:52 INFO openvpn configurator: checking for device /dev/net/tun


2021/04/10 16:45:52 WARN TUN device is not available: open /dev/net/tun: no such file or directory


2021/04/10 16:45:52 INFO openvpn configurator: creating /dev/net/tun


2021/04/10 16:45:52 INFO firewall: enabling...


2021/04/10 16:45:52 INFO firewall: enabled successfully


2021/04/10 16:45:52 INFO healthcheck: listening on 127.0.0.1:9999


2021/04/10 16:45:52 INFO dns over tls: using plaintext DNS at address 1.1.1.1


2021/04/10 16:45:52 INFO http server: listening on 0.0.0.0:8000


2021/04/10 16:45:52 INFO firewall: setting VPN connection through firewall...


2021/04/10 16:45:52 INFO openvpn configurator: starting openvpn


2021/04/10 16:45:52 INFO openvpn: OpenVPN 2.4.10 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  4 2021


2021/04/10 16:45:52 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10


2021/04/10 16:45:52 INFO openvpn: CRL: loaded 1 CRLs from file [[INLINE]]


2021/04/10 16:45:52 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]154.13.1.50:1197


2021/04/10 16:45:52 INFO openvpn: UDP link local: (not bound)


2021/04/10 16:45:52 INFO openvpn: UDP link remote: [AF_INET]154.13.1.50:1197


2021/04/10 16:45:53 INFO openvpn: [berlin419] Peer Connection Initiated with [AF_INET]154.13.1.50:1197


2021/04/10 16:45:54 INFO openvpn: OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options


2021/04/10 16:45:54 INFO openvpn: OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3


2021/04/10 16:45:54 INFO openvpn: TUN/TAP device tun0 opened


2021/04/10 16:45:54 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500


2021/04/10 16:45:54 INFO openvpn: /sbin/ip addr add dev tun0 10.2.110.7/24 broadcast 10.2.110.255


2021/04/10 16:45:54 WARN openvpn: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.


2021/04/10 16:45:54 INFO openvpn: Initialization Sequence Completed


2021/04/10 16:45:54 INFO VPN routing IP address: 154.13.1.50


2021/04/10 16:45:54 INFO dns over tls: downloading DNS over TLS cryptographic files


2021/04/10 16:45:55 INFO healthcheck: healthy!


2021/04/10 16:46:07 INFO dns over tls: downloading hostnames and IP block lists


2021/04/10 16:46:09 INFO dns over tls: init module 0: validator


2021/04/10 16:46:09 INFO dns over tls: init module 1: iterator


2021/04/10 16:46:09 INFO dns over tls: start of service (unbound 1.10.1).


2021/04/10 16:46:09 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN


2021/04/10 16:46:12 INFO dns over tls: ready


2021/04/10 16:46:13 INFO There is a new release v3.15.0 (v3.15.0) created 43 days ago


2021/04/10 16:46:13 INFO VPN gateway IP address: 10.2.110.1


2021/04/10 16:46:13 INFO port forwarding: Found persistent forwarded port data for port 35256


2021/04/10 16:46:13 INFO port forwarding: Forwarded port data expires in 61 days


2021/04/10 16:46:13 INFO port forwarding: Port forwarded is 35256 expiring in 61 days


2021/04/10 16:46:13 INFO port forwarding: Writing port to / /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf


2021/04/10 16:46:13 ERROR port forwarding: open / /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf: no such file or directory


2021/04/10 16:46:13 INFO firewall: setting allowed input port 35256 through interface tun0...


2021/04/10 16:46:18 INFO ip getter: Public IP address is 154.13.1.50 (Germany, Berlin, Berlin)


2021/04/10 18:45:56 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN


2021/04/10 20:35:41 WARN Caught OS signal terminated, shutting down


2021/04/10 20:35:41 WARN ip getter: context canceled: exiting loop


2021/04/10 20:35:41 INFO ip getter: Removing ip file /tmp/gluetun/ip


2021/04/10 20:35:41 WARN dns over tls: context canceled: exiting loop


2021/04/10 20:35:41 WARN openvpn: context canceled: exiting loop


2021/04/10 20:35:41 INFO Clearing forwarded port status file / /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf


2021/04/10 20:35:41 WARN healthcheck: context canceled: shutting down server


2021/04/10 20:35:41 WARN http server: context canceled: shutting down


2021/04/10 20:35:41 WARN http server: shut down


2021/04/10 20:35:41 WARN healthcheck: server shut down


2021/04/10 20:35:41 WARN dns over tls: loop exited


2021/04/10 20:35:41 WARN openvpn: loop exited


2021/04/10 20:35:41 INFO firewall: removing allowed port 35256 through firewall...


2021/04/10 20:35:42 ERROR remove / /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf: no such file or directory


2021/04/10 20:35:42 WARN ip getter: loop exited


2021/04/10 20:35:43 ERROR port forwarding: cannot remove allowed port 35256 through interface tun0: failed executing "iptables --delete INPUT -i tun0 -p tcp --dport 35256 -j ACCEPT": : context deadline exceeded


2021/04/10 20:35:43 WARN port forwarding: loop exited


2021/04/10 20:35:43 INFO Shutdown successful


```

**Comment by qdm12** [comment]
This is due to

```
ERROR port forwarding: open / /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf: no such file or directory
```

What do you have set for `PORT_FORWARDING_STATUS_FILE`? You can try leaving it blank for now, I'll check on my end why it might not assemble the path correctly as `/ /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf`

**Comment by ansred** [comment]
Here is the stack I use for both the test image and the official one


```
---
version: '2.4'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Toronto
      - VPNSP=private internet access
      - REGION=CA Ontario
      - PORT_FORWARDING=on #Complete https://github.com/qdm12/gluetun/wiki/Environment-variables
      - PORT_FORWARDING_STATUS_FILE= /volume1/docker/gluetun/config/port-forwarding/port.conf
      - OPENVPN_USER=p###### #Change to YOUR Username
      - OPENVPN_PASSWORD=######## #Change to YOUR Password
    volumes:
      - /volume1/docker/gluetun/config:/gluetun
    ports:
      - 8000:8000 #HTTP Server https://github.com/qdm12/gluetun/wiki/HTTP-Control-server#OpenVPN
      #- 19999:19999 #Netdata
      - 666:80 #heimdal-VPN
      - 4466:443 #heimdal-VPN
      - 9080:9080 #QBitTorrent Web-UI
      - 6881:6881 #QBitTorrent
      - 6881:6881/udp #QBitTorrent
      #- 9117:9117 #Jackett
      #- 7878:7878 #Radarr
      #- 8989:8989 #Sonarr
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

when I use your HTTP method, it's working fine and it's able to locate the forwarded port with no issues

```
{
    "port": 52025
}
```


But in the logs, as you can see the path looks odd and it's not able to create the file and add write to it.

I even created the full path as you can see in the logs and it's not able to see it.

**Comment by qdm12** [comment]
You need to remove the space right after `PORT_FORWARDING_STATUS_FILE=` 😉 I might add some code to remove white spaces though.

Also please persist logs to see why the container restarts as it shouldn't by itself. Thanks!!

**Comment by ansred** [comment]
I tried that, but still not working, at least the extra / is gone

```
Today at 7:56 PM  2021/04/11 19:56:20 INFO port forwarding: Forwarded port data expires in 60 days
today at 7:56 PM  2021/04/11 19:56:20 INFO port forwarding: Port forwarded is 35256 expiring in 60 days
today at 7:56 PM  2021/04/11 19:56:21 INFO port forwarding: Writing port to /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf
today at 7:56 PM  2021/04/11 19:56:21 ERROR port forwarding: open /volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf: no such file or directory
today at 7:56 PM  2021/04/11 19:56:21 INFO firewall: setting allowed input port 35256 through interface tun0...
today at 7:56 PM  2021/04/11 19:56:25 INFO ip getter: Public IP address is 154.13.1.77 (Germany, Berlin, Berlin)
```

Is it a permission issue or it's literally can't see the path of the file? maybe I need to mount that file path?

Even though I have mounted the entire config directory 
`/volume1/docker/gluetun/gluetun-restart/config`

**Comment by qdm12** [comment]
Oh yes silly me, `/volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf` is the path on your host. Since your are bind mounting it as `/volume1/docker/gluetun/config:/gluetun`, you should set `PORT_FORWARDING_STATUS_FILE=/gluetun/port-forwarding/port.conf`. From the program perspective it's not aware of your host file system, only to the bind mount 😉

**Comment by ansred** [comment]
I tried for every scenario can be in the file path

```
today at 9:05 PM  2021/04/11 21:05:29 INFO port forwarding: Writing port to /config/port-forwarding/port.conf
today at 9:05 PM  2021/04/11 21:05:29 ERROR port forwarding: open /config/port-forwarding/port.conf: no such file or directory

```

and


`today at 9:11 PM  2021/04/11 21:11:00 ERROR port forwarding: open /config/port-forwarding/port.conf: no such file or directory
`

and

`today at 9:12 PM  2021/04/11 21:12:14 ERROR port forwarding: open /gluetun-restart/config/port-forwarding/port.conf: no such file or directory
`

and

`today at 9:13 PM  2021/04/11 21:13:08 ERROR port forwarding: open /gluetun/gluetun-restart/config/port-forwarding/port.conf: no such file or directory`



Here is the stack

```
---
version: '2.4'
services:
  gluetun:
    image: qmcgaw/gluetun:restart-unhealthy
    container_name: gluetun-restart
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Toronto
      - VPNSP=private internet access
      - REGION=DE Berlin #Config files from PIA from here https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files-2
      - PORT_FORWARDING=on #Complete https://github.com/qdm12/gluetun/wiki/Environment-variables
      - PORT_FORWARDING_STATUS_FILE=/gluetun/gluetun-restart/config/port-forwarding/port.conf 
      - OPENVPN_USER=p&&&&&&&&&& #Change to YOUR Username
      - OPENVPN_PASSWORD=&&&&&&&&&&&&&& #Change to YOUR Password
    volumes:
      - /volume1/docker/gluetun/gluetun-restart/config:/gluetun
    ports:
      - 8001:8000 #HTTP Server https://github.com/qdm12/gluetun/wiki/HTTP-Control-server#OpenVPN
      - 19999:19999 #Netdata
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

I used PUID and PGID as root for Synology 0 and 0

```
      - PUID=0
      - PGID=0
```

Still the same

`today at 9:16 PM  2021/04/11 21:16:24 ERROR port forwarding: open /config/port-forwarding/port.conf: no such file or directory
`


Here is the file I created manually in Synology DSM

![image](https://user-images.githubusercontent.com/5244872/114328750-7e3ffb80-9b0b-11eb-8af9-288cc7d2241d.png)

**Comment by qdm12** [comment]
Your file is at `/volume1/docker/gluetun/gluetun-restart/config/port-forwarding/port.conf` on your host.

You bind mount `/volume1/docker/gluetun/gluetun-restart/config` to `/gluetun` in the container.

Therefore, for the container, the file is at `/gluetun/port-forwarding/port.conf`, so try setting `PORT_FORWARDING_STATUS_FILE=/gluetun/port-forwarding/port.conf`. It's also not a matter of permission as the entrypoint program runs with root (to fiddle with firewall & routes).

Anyway, I'll delete those few back and forth we had about that other env variable issue on this issue to keep it tidy once you reply. Make sure you collect logs to see why the container would restart (maybe it crashes 🤔), feel free to ask me if you need help setting log collection in your docker-compose.yml to persist logs across restarts.

**Comment by ansred** [comment]
Man, you got it right. I am not sure why I got confused that much!

It's working now the mapping for that file, sorry, and thanks at the same time :)

```
2021/04/12 18:31:34 INFO port forwarding: Found persistent forwarded port data for port 35256
2021/04/12 18:31:34 INFO port forwarding: Forwarded port data expires in 59 days
2021/04/12 18:31:34 INFO port forwarding: Port forwarded is 35256 expiring in 59 days
2021/04/12 18:31:34 INFO port forwarding: Writing port to /gluetun/port-forwarding/port.conf
2021/04/12 18:31:34 INFO firewall: setting allowed input port 35256 through interface tun0...
```
![image](https://user-images.githubusercontent.com/5244872/114470888-a38d4200-9bbd-11eb-886c-32b203fbe0fc.png)



Regarding the persistent log collection. Do you have a wiki or steps on how to get debug logs to find out the causes of the restarts?

**Comment by qdm12** [comment]
Cool! For the logs you can actually simply find the container ID (using the Synology docker UI or `docker ps`) and the log file of the container and its previous instances will all be together in `/var/lib/docker/containers/<container-id>/<container-id>-json.log`

**Comment by ansred** [comment]
Nice. What do you recommend to change/add in the docker compose in gluetun restart in order to map the logs in a folder outside the container.

```
---
version: '2.4'
services:
  gluetun:
    image: qmcgaw/gluetun:restart-unhealthy
    container_name: gluetun-restart
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Toronto
      - VPNSP=private internet access
      - REGION=DE Berlin #Config files from PIA from here https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files-2
      - PORT_FORWARDING=on #Complete https://github.com/qdm12/gluetun/wiki/Environment-variables
      - PORT_FORWARDING_STATUS_FILE=/gluetun/port-forwarding/port.conf
      - OPENVPN_USER=p####### #Change to YOUR Username
      - OPENVPN_PASSWORD=############ #Change to YOUR Password
    volumes:
      - /volume1/docker/gluetun/gluetun-restart/config:/gluetun
    ports:
      - 8001:8000 #HTTP Server https://github.com/qdm12/gluetun/wiki/HTTP-Control-server#OpenVPN
      - 19999:19999 #Netdata
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

**Comment by qdm12** [comment]
I don't think you actually can after having a look at their docs, sorry for misleading that. So you cam either:

- Just check the file in the /var/lib/docker directory for that container id
- Setup Loki and Promtail. That's a fancy addition to have your logs collected and stored, accessible through a nice UI. That's on my TODO list so I can't help that much yet 😄

**Comment by ansred** [comment]
For gluetun restart container

I see the following

```
root@Synology:~# docker exec -it 89ab026e8ef6 /bin/sh
/ # cd /var/lib
/var/lib # ls -1
apk
arpd
ip6tables
iptables
misc
udhcpd
```

For netdata connected to the VPN container

I see

```
root@Synology:~# docker exec -it c4d16fa99986 /bin/sh
/ #
/ #
/ # cd /var/lib
/var/lib # ls -1
apk
arpd
ip6tables
iptables
libvirt
misc
netdata
nut
udhcpd
```


I don't see "docker" in "lib" as you mentioned. Not sure if I am missing something

**Comment by qdm12** [comment]
Oh you need to find it on your host 😉 I think you can use the Synology terminal App in their UI as I recall; otherwise you would have to SSH in there.

**Comment by ansred** [comment]
I think I found the logs location, it's a bit differnet from other docker hosts platforms

```
root@Synology:/volume1/@docker/containers#
root@Synology:/volume1/@docker/containers/89ab026e8ef6aa1964bc402724d5e5ef46a48cec6efa53d1465944f1f963342d# ls -1
checkpoints
config.v2.json
hostconfig.json
hostname
hosts
log.db
mounts
resolv.conf
resolv.conf.hash
```

And I noticed it's the same logs from the GUUI of the DSM Synology

![image](https://user-images.githubusercontent.com/5244872/114805267-ac724500-9d70-11eb-9d0e-81f3ab979baa.png)


Next Steps:
I will keep monitoring and share with you the logs on the next crash

**Comment by qdm12** [comment]
Any restart so far 🧐?

**Comment by qdm12** [comment]
Please re-pull that image `:restart-unhealthy` as the newer one contains a bunch of bug fixes and improvements. It should now detect when it's unhealthy within 1 to 5 seconds and should restart openvpn. If it's still unhealthy on the second try, it doubles the wait time from 6 to 12s and so on. I think that version should be good to go but I'll let you run it for a few days 😉

**Comment by ansred** [comment]
Believe or not, since I deployed the testing container, both were working fine. :s

Pulling both of them now and updating the containers with the new updated images.

Thank you for the headsup!

**Comment by ansred** [comment]
It's been up since I deployed the original and the test image.
I think your trick helped a lot here and we should maybe close?

**Comment by qdm12** [comment]
Glad to hear! Yeah let's close it. Although note that this only restarts openvpn, not the DNS server... although the DNS server is unlikely to fail I guess.
