### ISSUE TITLE
VPN provider support: PRIVATEVPN

### ISSUE THREAD

**Issue by khglhy1** [qdm12/gluetun#390]
1. Name of the provider: PrivateVPN
2. URL to Openvpn configuration files (zip, JSON, etc.): https://privatevpn.com/
3. VPN server side port forwarding documentation, if available: 

If 2. is not available, it's not possible to support the provider yet.
Please instead subscribe to #223

**Comment by qdm12** [comment]
Can you please comment with the link to the openvpn files? This is just a link to the vpn provider. Thank you!

**Comment by Frepke** [comment]
[think this will do](https://privatevpn.com/client/PrivateVPN-TUN.zip)

**Comment by qdm12** [comment]
Thanks @Frepke!! Does it support UDP or only TCP by the way?

**Comment by Frepke** [comment]
TCP and UDP is in the zip file.

**Comment by qdm12** [comment]
Can you try with the image `qmcgaw/gluetun:privatevpn` using the documentation found in the Wiki please? Ideally please try both TCP and UDP.

A few (~10) servers got omitted from the supported list as their hostname would not resolve to anything, but if they ever go back up, the automatic updater should pick them up (with `UPDATER_PERIOD`).

**Comment by khglhy1** [comment]
Thanks very much! qdm12 and Frepke...

**Comment by qdm12** [comment]
Does it work for you?
