### ISSUE TITLE
VPN provider support: hma aka hidemyass

### ISSUE THREAD

**Issue by smtm50** [qdm12/gluetun#391]
1. Name of the provider: hidemyass https://www.hidemyass.com/
2. URL to Openvpn configuration files (zip, JSON, etc.): https://vpn.hidemyass.com/vpn-config/
3. VPN server side port forwarding documentation, if available:

If 2. is not available, it's not possible to support the provider yet.
Please instead subscribe to #223

**Comment by qdm12** [comment]
Hey it should be ready. Can you please try with the image `qmcgaw/gluetun:hma`? The Github wiki is updated with information on how to set it up for HideMyAss (you can start [here](https://github.com/qdm12/gluetun/wiki/Environment-variables)).

Let me know if it works and I'll merge it in the main codebase. Thanks!

**Comment by smtm50** [comment]
Hey thanks for setting this up. I just switched to Privado as it comes with Usenet. I won’t able to test it. Sorry dude :-(

**Comment by qdm12** [comment]
Alright, I'll just assume it works then 😅 Hopefully someone will create an issue if it doesn't!
