### ISSUE TITLE
VPN provider support: ProtonVPN

### ISSUE THREAD

**Issue by mash-mi** [qdm12/gluetun#408]
Hello, I'm really happy if you support ProtonVPN.

- Publicly accessible URL to a structured (JSON etc.) list of servers **and attach** an example Openvpn configuration file for both TCP and UDP
  - JSON server list: https://api.protonmail.ch/vpn/logicals
  - Example .ovpn: 
    - tcp: https://account.protonvpn.com/api/vpn/config?Country=US&Platform=Linux&Protocol=tcp
    - udp: https://account.protonvpn.com/api/vpn/config?Country=US&Platform=Linux&Protocol=udp

I confirmed all of these URLs are publicly available, even via Tor. :)

**Comment by alant54** [comment]
+1 this provider can be very cool to have

**Comment by qdm12** [comment]
Sorry guys, it seems that issue fell off my brain. I'll get to it tomorrow!

**Comment by alant54** [comment]
nice ! good to know it

**Comment by qdm12** [comment]
Can you guys try with the image tag `:protonvpn`? Documentation is available in the Wiki (starting [here](https://github.com/qdm12/gluetun/wiki/Environment-variables)).

Let me know and I'll merge it in the base image once it's proven to be working!

**Comment by Guilvareux** [comment]
I've given it a test and I'm receiving this error. My configuration is VPNSP=protonvpn with username and passwd only.

<img width="980" alt="Screenshot 2021-04-20 at 15 39 27" src="https://user-images.githubusercontent.com/25768075/115415322-5543f880-a1e6-11eb-851b-617348f4757b.png">

**Comment by Guilvareux** [comment]
Hey! I've tried running it but i'm getting this error
<img width="982" alt="Screenshot 2021-04-20 at 16 07 11" src="https://user-images.githubusercontent.com/25768075/115419833-2a5ba380-a1ea-11eb-95f7-140e9b262970.png">

**Comment by qdm12** [comment]
Try pulling the image again and try again please, I just fixed it.

**Comment by alant54** [comment]
I had the same issue yesterday but i have test the new image and now it's working for me.

**Comment by qdm12** [comment]
Cool I'll merge it tonight in the base image.

**Comment by qdm12** [comment]
Added in `qmcgaw/gluetun:latest` with 62982fa05312596ad7810d62db382f5151151a46

**Comment by DarkVader-cell** [comment]
Sorry for bringing it up again, I know this is based on the API provided on the website but is there any way you could add the free servers on ProtonVPN? The current API only pulls the paid ones and the only other option is using a custom config.

**Comment by qdm12** [comment]
Sure @DarkVader-cell would you mind sending me where you find hostnames/IP addresses for those free tier servers? Ideally in a structured way (JSON etc.), thanks!

**Comment by DarkVader-cell** [comment]
@qdm12 Oh, these servers are now available in the above used API, it's a total of 17 servers and their IP remains static. I'll attach the .ovpn files as a zip (UDP). [
[ProtonVPN_server_configs.zip](https://github.com/qdm12/gluetun/files/6518351/ProtonVPN_server_configs.zip)
](url)

**Comment by DarkVader-cell** [comment]
@qdm12 Also, initiating a manual update gives me this error
 ` ERROR Get "https://api.protonmail.ch/vpn/logicals": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`
Tried the same for Mullvad and it seemed to update fine.

**Comment by qdm12** [comment]
I tried and the update works for me. The timeout you're seeing happens after 15s, maybe that was their API being down 🤔 

Anyway, there are already some VPN servers from the free tier such as name `NL-FREE#1` or hostname `lxc-nl-03.protonvpn.com`. The full table of servers is available [here](https://github.com/qdm12/gluetun/wiki/Protonvpn-Servers) you can CTRL+F for `free` to find free servers there 😉 Note that this table is up to date now but won't get updated if the server information changes in the code.

**Comment by DarkVader-cell** [comment]
@qdm12 gotcha, thank you!
