### ISSUE TITLE
Support for IPvanish VPN

### ISSUE THREAD

**Issue by neiliid** [qdm12/gluetun#410]
Hi,

Thanks for a great build. It would be great if you could include IPVanish vpn at some point the future, or an option to externalise the openvpn configuration files for the container thereby enabling access to any openvpn servers.

Thanks

**Comment by qdm12** [comment]
Thanks for taking the time to create an issue. Can you please create another issue using this [issue template](https://github.com/qdm12/gluetun/issues/new?assignees=&labels=%3Abulb%3A+New+provider&template=provider.md&title=VPN+provider+support%3A+NAME+OF+THE+PROVIDER) and answering the questions? Thanks!
