### ISSUE TITLE
Feature request: Support multiple networks within the gluetun container

### ISSUE THREAD

**Issue by michael-robbins** [qdm12/gluetun#411]
**What's the feature?** 🧐

Currently the gluetun firewall only supports the default gateway/subnet when it's enabled: https://github.com/qdm12/gluetun/blob/master/cmd/gluetun/main.go#L204

My setup currently involves:
* gluetun container
* deluge container joined to it (sharing network stack)
* gluetun container joined to docker network allowing Radarr/Sonarr/etc to communicate with Deluge
* gluetun container joined to docker network allowing Traefik proxy to access Deluge's UI to enable administration/etc

Currently gluetun supports reading the default gateway/subnet and setting the `iptables` correctly to allow traffic from one of the networks (the first one, aka the default one from the containers point of view).

I'd like it if gluetun took the approach where it looked for the other network interfaces (eth1, eth2, etc) which in this case, are other docker networks attached to the gluetun container, and performed the same 'Allow each subnet through the INPUT chain'.

Looking at https://github.com/qdm12/gluetun/wiki/Environment-variables#firewall-and-routing the only other way I can see here is adding some sort of 'FIREWALL_INBOUND_SUBNETS' instead, but I'd have to hardcode the docker network CIDRs which I'd prefer not to have to do.

Does this sound sane/feasible? Or am I missing something maybe?

**Optional extra information** 🚀
N/A

**Comment by qdm12** [comment]
I guess that's feasible although I can't give you an exact time of when I'll get to it/do it. I never thought of attaching to multiple networks, interesting problem. Also thanks for the detailed issue and even the digging in the code.

I'm currently in a deep dive in [DNS (over tls & https)](https://github.com/qdm12/dns/pull/58) (to be added to gluetun soon), as  well as Wireguard, and that's likely going to block me at least 2 weeks 😅

**Comment by michael-robbins** [comment]
Haha yeah np, just encountered this problem and sussed out why it's happening :)

My Go's a bit rusty (ba dum tish) but guessing I'd have to uplift https://github.com/qdm12/gluetun/tree/master/internal/routing to support iterating through all local interfaces vs just getting the default one.

Then exposing that into https://github.com/qdm12/gluetun/blob/master/cmd/gluetun/main.go#L204 and setting an iterable of (interface, address, gateway, subnet) that are all added to the firewall, and have the firewall able to take a bunch of them!

If I get some time I'll have a crack at it :)
