### ISSUE TITLE
PIA port forwarding - Bad Gateway

### ISSUE THREAD

**Issue by axxis1999** [qdm12/gluetun#423]
For a few days now I am no longer able to get port forwarding working. I have not changed anything, but am seeing this now in the logs:
`2021/04/16 00:09:14 ERROR port forwarding: cannot obtain token: 502 Bad Gateway: response received: "<html>\r<head><title>502 Bad Gateway</title></head>\r<body>\r<center><h1>502 Bad Gateway</h1></center>\r<hr><center>nginx/1.19.1</center>\r</body>\r</html>\r"`

**Comment by qdm12** [comment]
Did you try with another region? It looks like their token gateway is just down 🤔

**Comment by axxis1999** [comment]
Yes, I tried several regions and its happening everywhere. I am using docker-compose (well, portainer stack, if that makes a difference) on a Synology DSM.

My config looks like this:
`version: '2.2'
services:
  vpn:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 7999:8000/tcp # Built-in HTTP control server
      - 9091:9091 # Transmission
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment: 
      - VPNSP=private internet access
      - TZ=Europe/Berlin
      - REGION=UK London
      - OPENVPN_USER=xxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxx
      - PORT_FORWARDING=on
      - HTTPPROXY=on
      - SHADOWSOCKS=on
    restart: unless-stopped
  torrent:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - TZ=Europe/Berlin
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin #optional
      - PASS=admin #optional
      - PUID=1026
      - PGID=100
    volumes:
      - /volume1/docker/transmission/config:/config
      - /volume1/docker/transmission/downloads:/downloads
      - /volume1/docker/transmission/watch:/watch
    restart: unless-stopped`

**Comment by Raph521** [comment]
I just found mention of this on the PIA subreddit: https://www.reddit.com/r/PrivateInternetAccess/comments/msadq2/unable_to_generate_tokens_from_pia_api/

A comment suggests using a domain to access the token gateway instead (I haven't tried this myself yet)

**Comment by axxis1999** [comment]
That sounds like the right direction, thanks! I wish I could fix that myself, but I think I need to wait for @qdm12 to take a look.

**Comment by qdm12** [comment]
Can you guys try the image with tag `:fix-pia-token`?

If it works, please hold I might have 1 or 2 more tests for you to fix parallel issues related to PIA port forwarding, if you don't mind 🧐

**Comment by Raph521** [comment]
Hmm, looks like there might be an issue:

```
=========================================,
================ Gluetun ================,
=========================================,
==== A mix of OpenVPN, DNS over TLS, ====,
======= Shadowsocks and HTTP proxy ======,
========= all glued up with Go ==========,
=========================================,
=========== For tunneling to ============,
======== your favorite VPN server =======,
=========================================,
=== Made with ❤️  by github.com/qdm12 ====,
=========================================,
,
Running version fix-pia-token built on 2021-04-17T13:48:42Z (commit 12dca86),
,
,
🔧  Need help? https://github.com/qdm12/gluetun/issues/new,
💻  Email? quentin.mcgaw@gmail.com,
☕  Slack? Join from the Slack button on Github,
💸  Help me? https://github.com/sponsors/qdm12,
2021/04/17 10:24:31 INFO Unbound version: 1.10.1,
2021/04/17 10:24:31 INFO IPtables version: v1.8.4,
2021/04/17 10:24:31 INFO OpenVPN version: 2.4.10,
2021/04/17 10:24:31 INFO Settings summary below:,
|--OpenVPN:,
   |--Verbosity level: 1,
   |--Run as root: enabled,
   |--Provider:,
      |--Private Internet Access settings:,
         |--Network protocol: udp,
         |--Regions: ca toronto,
         |--Encryption preset: normal,
         |--Custom port: 0,
         |--Port forwarding:,
            |--File path: /tmp/gluetun/forwarded_port,
|--DNS:,
   |--Plaintext address: 1.1.1.1,
   |--DNS over TLS:,
      |--Unbound:,
          |--DNS over TLS providers:,
              |--cloudflare,
          |--Listening port: 53,
          |--Access control:,
              |--Allowed:,
                  |--0.0.0.0/0,
                  |--::/0,
          |--Caching: enabled,
          |--IPv4 resolution: enabled,
          |--IPv6 resolution: disabled,
          |--Verbosity level: 1/5,
          |--Verbosity details level: 0/4,
          |--Validation log level: 0/2,
          |--Blocked hostnames:,
          |--Blocked IP addresses:,
              |--127.0.0.1/8,
              |--10.0.0.0/8,
              |--172.16.0.0/12,
              |--192.168.0.0/16,
              |--169.254.0.0/16,
              |--::1/128,
              |--fc00::/7,
              |--fe80::/10,
              |--::ffff:0:0/96,
          |--Allowed hostnames:,
      |--Block malicious: enabled,
      |--Update: every 24h0m0s,
|--Firewall:,
|--System:,
   |--Process user ID: 1000,
   |--Process group ID: 1000,
   |--Timezone: america/new_york,
|--HTTP control server:,
   |--Listening port: 8000,
   |--Logging: enabled,
|--Public IP getter:,
   |--Fetch period: 12h0m0s,
   |--IP file: /tmp/gluetun/ip,
|--Github version information: enabled,
2021/04/17 10:24:31 INFO storage: merging by most recent 7378 hardcoded servers and 7378 servers read from /gluetun/servers.json,
2021/04/17 10:24:31 INFO routing: default route found: interface eth0, gateway 172.20.0.1,
2021/04/17 10:24:31 INFO routing: local ethernet link found: eth0,
2021/04/17 10:24:31 INFO routing: local ipnet found: 172.20.0.0/16,
2021/04/17 10:24:31 INFO routing: default route found: interface eth0, gateway 172.20.0.1,
2021/04/17 10:24:31 INFO routing: adding route for 0.0.0.0/0,
2021/04/17 10:24:31 INFO firewall: firewall disabled, only updating allowed subnets internal list,
2021/04/17 10:24:31 INFO routing: default route found: interface eth0, gateway 172.20.0.1,
2021/04/17 10:24:31 INFO openvpn configurator: checking for device /dev/net/tun,
2021/04/17 10:24:31 WARN TUN device is not available: open /dev/net/tun: no such file or directory,
2021/04/17 10:24:31 INFO openvpn configurator: creating /dev/net/tun,
2021/04/17 10:24:31 INFO firewall: enabling...,
2021/04/17 10:24:31 INFO firewall: enabled successfully,
2021/04/17 10:24:31 INFO healthcheck: listening on 127.0.0.1:9999,
2021/04/17 10:24:31 INFO dns over tls: using plaintext DNS at address 1.1.1.1,
2021/04/17 10:24:31 INFO http server: listening on 0.0.0.0:8000,
2021/04/17 10:24:31 INFO firewall: setting VPN connection through firewall...,
2021/04/17 10:24:31 INFO openvpn configurator: starting openvpn,
2021/04/17 10:24:31 INFO openvpn: OpenVPN 2.4.10 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  4 2021,
2021/04/17 10:24:31 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10,
2021/04/17 10:24:31 INFO openvpn: CRL: loaded 1 CRLs from file [[INLINE]],
2021/04/17 10:24:31 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]154.3.40.40:1198,
2021/04/17 10:24:31 INFO openvpn: UDP link local: (not bound),
2021/04/17 10:24:31 INFO openvpn: UDP link remote: [AF_INET]154.3.40.40:1198,
2021/04/17 10:24:31 INFO openvpn: [toronto415] Peer Connection Initiated with [AF_INET]154.3.40.40:1198,
2021/04/17 10:24:33 INFO openvpn: OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options,
2021/04/17 10:24:33 INFO openvpn: OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3,
2021/04/17 10:24:33 INFO openvpn: TUN/TAP device tun0 opened,
2021/04/17 10:24:33 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500,
2021/04/17 10:24:33 INFO openvpn: /sbin/ip addr add dev tun0 10.7.112.6/24 broadcast 10.7.112.255,
2021/04/17 10:24:33 WARN openvpn: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.,
2021/04/17 10:24:33 INFO openvpn: Initialization Sequence Completed,
2021/04/17 10:24:33 INFO VPN routing IP address: 154.3.40.40,
2021/04/17 10:24:33 INFO dns over tls: downloading DNS over TLS cryptographic files,
2021/04/17 10:24:33 INFO dns over tls: downloading hostnames and IP block lists,
2021/04/17 10:24:33 INFO healthcheck: healthy!,
2021/04/17 10:24:34 INFO dns over tls: init module 0: validator,
2021/04/17 10:24:34 INFO dns over tls: init module 1: iterator,
2021/04/17 10:24:34 INFO dns over tls: start of service (unbound 1.10.1).,
2021/04/17 10:24:34 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN,
2021/04/17 10:24:34 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN,
2021/04/17 10:24:35 INFO dns over tls: ready,
2021/04/17 10:24:35 INFO There is a new release v3.15.0 (v3.15.0) created 50 days ago,
2021/04/17 10:24:35 INFO VPN gateway IP address: 10.7.112.1,
panic: interface conversion: http.RoundTripper is nil, not *http.Transport,
,
goroutine 80 [running]:,
github.com/qdm12/gluetun/internal/provider.newPIAHTTPClient(0xc000106030, 0xa0fce8, 0xa, 0xc000095740, 0x0, 0x99a200),
	github.com/qdm12/gluetun/internal/provider/piav4.go:361 +0x3a6,
github.com/qdm12/gluetun/internal/provider.(*pia).PortForward(0xc0001620e0, 0xbce378, 0xc000326200, 0xc000106030, 0xc0000b4168, 0xbceff8, 0xc000100410, 0xc0000e3464, 0x4, 0x388, ...),
	github.com/qdm12/gluetun/internal/provider/piav4.go:224 +0x78,
github.com/qdm12/gluetun/internal/openvpn.(*looper).portForward(0xc0000d6a00, 0xbce378, 0xc000326200, 0xc0000a8540, 0xbcd170, 0xc0001620e0, 0xc000106030, 0xc0000e3464, 0x4, 0x388),
	github.com/qdm12/gluetun/internal/openvpn/loop.go:262 +0x1e7,
created by github.com/qdm12/gluetun/internal/openvpn.(*looper).Run.func1,
	github.com/qdm12/gluetun/internal/openvpn/loop.go:180 +0x105,
```

Notably, v3.15.0 works fine for me right now (brand new container that doesn't have an existing token).  

I hadn't restarted my containers in the last few weeks, so never encountered the same issues as @axxis1999.

**Comment by axxis1999** [comment]
Same issue as @Raph521 

> goroutine 144 [running]:
> 
> github.com/qdm12/gluetun/internal/provider.newPIAHTTPClient(0xc0001ba030, 0xa0e640, 0x9, 0x90, 0xc0001bd560, 0x0)
> 
> 	github.com/qdm12/gluetun/internal/provider/piav4.go:361 +0x3a6
> 
> github.com/qdm12/gluetun/internal/provider.(*pia).PortForward(0xc000168070, 0xbce378, 0xc0001b6100, 0xc0001ba030, 0xc0001c03c0, 0xbceff8, 0xc0001c43c0, 0xc00034c864, 0x4, 0x388, ...)
> 
> 	github.com/qdm12/gluetun/internal/provider/piav4.go:224 +0x78
> 
> github.com/qdm12/gluetun/internal/openvpn.(*looper).portForward(0xc000098a00, 0xbce378, 0xc0001b6100, 0xc00046be40, 0xbcd170, 0xc000168070, 0xc0001ba030, 0xc00034c864, 0x4, 0x388)
> 
> 	github.com/qdm12/gluetun/internal/openvpn/loop.go:262 +0x1e7
> 
> created by github.com/qdm12/gluetun/internal/openvpn.(*looper).Run.func1
> 
> 	github.com/qdm12/gluetun/internal/openvpn/loop.go:180 +0x105

**Comment by qdm12** [comment]
Try `docker pull qmcgaw/gluetun:fix-pia-token` again, my bad!

**Comment by axxis1999** [comment]
The problem before is gone, but I am getting this now (xxxxxxx is where my username appears):

`2021/04/17 17:07:51 ERROR port forwarding: cannot obtain token: Get "https://xxxxxxx:***@privateinternetaccess.com/gtoken/generateToken": x509: certificate is valid for *.privateinternetaccess.com, privateinternetaccess.com, not london404`

**Comment by qdm12** [comment]
Can you try pulling and try again please? Sorry for the back and forth, no PIA account here 😄

**Comment by axxis1999** [comment]
No worries, I really appreciate all the help -- one step further but not there yet :)

`2021/04/17 17:24:19 ERROR port forwarding: cannot obtain token: Get "https://p0179654:***@privateinternetaccess.com/gtoken/generateToken": x509: certificate signed by unknown authority`

**Comment by qdm12** [comment]
Try again 😉 I also added code changes to hide away the credentials/token/signature/etc. from error logs.

**Comment by axxis1999** [comment]
Still no luck --

```
2021/04/17 17:46:35 ERROR port forwarding: cannot obtain token: Get "https://<username>:***@privateinternetaccess.com/gtoken/generateToken": x509: certificate is valid for *.privateinternetaccess.com, privateinternetaccess.com, not london405,
2021/04/17 17:46:35 INFO port forwarding: Trying again in 10s
```

**Comment by qdm12** [comment]
Try again please 😆 I think (secretly hope) we're almost there.

**Comment by axxis1999** [comment]
Just tried again:

```
2021/04/17 17:52:10 ERROR port forwarding: cannot obtain token: Get "https://<username>:***@privateinternetaccess.com/gtoken/generateToken": x509: certificate is valid for *.privateinternetaccess.com, privateinternetaccess.com, not london402,
2021/04/17 17:52:10 INFO port forwarding: Trying again in 10s
```
and no, the password the 3 stars are cut and paste from the logs.

**Comment by qdm12** [comment]
Can you try again?

> and no, the password the 3 stars are cut and paste from the logs.

Oh yes the standard library makes the effort to hide the password from URLs, cool 👍 I'll leave it as is to hide the username then.

**Comment by axxis1999** [comment]
I think there might be still something wrong, although we seem to be close -

```
2021/04/17 18:52:43 INFO port forwarding: Trying again in 10s,
2021/04/17 18:53:04 INFO firewall: setting allowed input port 43537 through interface tun0...,
2021/04/17 18:52:43 ERROR port forwarding: cannot obtain port forwarding data: cannot decode payload: illegal base64 data at input byte 259,
2021/04/17 18:52:54 INFO port forwarding: Trying again in 10s,
2021/04/17 18:52:44 INFO ip getter: Public IP address is 212.102.52.129 (United Kingdom, England, London),
2021/04/17 18:52:54 ERROR port forwarding: cannot obtain port forwarding data: cannot decode payload: illegal base64 data at input byte 259,
2021/04/17 18:53:04 INFO port forwarding: Port forwarded is 43537 expiring in 62 days,
2021/04/17 18:53:04 INFO port forwarding: Writing port to /tmp/gluetun/forwarded_port
```

**Comment by qdm12** [comment]
Can you try again? There should be more logs showing how the data is formatted.
If you get sensitive encoded information, you can [email me](mailto:quentin.mcgaw@gmail.com) so sensitive information is not left here. If you just get an error message (which I'd expect at this point), just comment it here.

**Comment by axxis1999** [comment]
No more errors! ---

```
2021/04/17 19:09:26 INFO port forwarding: Port forwarded is 42909 expiring in 62 days,
2021/04/17 19:09:26 INFO ip getter: Public IP address is 212.102.53.68 (United Kingdom, England, London),
2021/04/17 19:09:26 INFO firewall: setting allowed input port 42909 through interface tun0...,
2021/04/17 19:09:26 INFO port forwarding: Writing port to /tmp/gluetun/forwarded_port
```

**Comment by qdm12** [comment]
Oh what how? 😄  Well great news then I guess... Can you delete that token/signature file (bind mounted with `/gluetun`) and restart the container, just to make sure it works for good?

**Comment by qdm12** [comment]
Also if it works, can you try re-pulling that image and try again? It might not work, but I want to check if PIA updated their TLS certificates 😉

**Comment by Raph521** [comment]
Sorry, I missed all the intermediate builds, but that latest one does work now!

```
Running version fix-pia-token built on 2021-04-17T18:13:58Z (commit a31e512)
```

**Comment by axxis1999** [comment]
@qdm12 - yes, I did that, thus the two different ports. Just did it again and it looks still fine! Thank again for all the work!

I don't know what happened to "cannot decode payload", but I'd file it under temporary glitch in the matrix.

```
2021/04/17 20:30:02 INFO port forwarding: Port forwarded is 53xxx expiring in 62 days,
2021/04/17 20:30:02 INFO ip getter: Public IP address is xxx.xxx.xxx.xxx (United Kingdom, England, London),
2021/04/17 20:30:02 INFO port forwarding: Writing port to /tmp/gluetun/forwarded_port,
2021/04/17 20:30:02 INFO firewall: setting allowed input port 53xxx through interface tun0...
```

**Comment by axxis1999** [comment]
I downloaded the image again and removed the token / signature file. Now I am seeing those issues again. I sent you an email with the details.

**Comment by qdm12** [comment]
Can you try again 😄 I fixed it, it was a too strict base64 decoding I was using that was at fault. The payload you sent me by email now decodes successfully.

Now this version is running without the environment variable `GODEBUG=x509ignoreCN=0` which had to be set for PIA port forwarding, so I'm curious to see if it works out!

**Comment by axxis1999** [comment]
ok, I tried a few more times with the latest image and I don't see an error anymore! 👍

**Comment by qdm12** [comment]
Awesome, even no TLS issue so that closes a bunch of related issues and pull requests, nice! I'll merge it now 👍
