### ISSUE TITLE
Multihop Surfshark  Issue

### ISSUE THREAD

**Issue by AxePlex** [qdm12/gluetun#424]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Ubuntu 20 Groovy

**CPU arch** or **device name**: amr64

**What VPN provider are you using**: Surfshark

**What are you using to run your container?**: Docker command

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-04-11T12:54:23Z (commit 69f9461)
```

**What's the problem** 🤔

That feature Multihop doesn't work

**Share your logs... (careful to remove in example tokens)**

```log

2021/04/16 14:06:33 INFO OpenVPN version: 2.4.10,
2021/04/16 14:06:33 INFO Unbound version: 1.10.1,
2021/04/16 14:06:33 INFO IPtables version: v1.8.4,
2021/04/16 14:06:33 ERROR environment variable "REGION": invalid values found: value "netherlands us" at position 1: possible values are: Albania, Argentina Buenos Aires, Australia Melbourne, Australia Perth, Australia Sydney, Austria, Belgium, Brazil, Bulgaria, Canada Montreal, Canada Toronto, Canada Toronto mp001, Chile, Colombia, Costa Rica, Croatia, Cyprus, Czech Republic, Estonia, Finland, France Bordeaux, France Marseilles, France Paris, Germany Berlin, Germany Frankfurt am Main, Germany Frankfurt am Main st001, Germany Frankfurt am Main st002, Germany Frankfurt am Main st003, Germany Frankfurt am Main st004, Germany Frankfurt am Main st005, Germany Frankfurt mp001, Germany Munich, Germany Nuremberg, Germany Singapour, Greece, Hong Kong, Iceland, India Chennai, India Indore, Indonesia, Ireland, Israel, Italy Milan, Italy Rome, Japan Tokyo, Japan Tokyo st001, Japan Tokyo st002, Japan Tokyo st003, Japan Tokyo st004, Japan Tokyo st005, Japan Tokyo st006, Japan Tokyo st007, Japan Tokyo st008, Japan Tokyo st009, Japan Tokyo st010, Japan Tokyo st011, Japan Tokyo st012, Japan Tokyo st013, Kazakhstan, Korea, Latvia, Luxembourg, Malaysia, Mexico City Mexico, Moldova, Netherlands Amsterdam, Netherlands Amsterdam mp001, Nigeria, North Macedonia, Norway, Paraguay, Philippines, Poland Gdansk, Poland Warsaw, Portugal Loule, Portugal Porto, Romania, Russia St. Petersburg, Serbia, Singapore, Singapore in, Singapore mp001, Singapore st001, Singapore st002, Singapore st003, Singapore st004, Slovekia, Slovenia, South Africa, Spain Barcelona, Spain Madrid, Spain Valencia, Sweden, Switzerland, Taiwan, Turkey Istanbul, UK Glasgow, UK London, UK London mp001, UK London st001, UK London st002, UK London st003, UK London st004, UK London st005, UK Manchester, US Bend, US Boston, US Charlotte, US Chicago, US Dallas, US Denver, US Gahanna, US Houston, US Kansas City, US Las Vegas, US Latham, US Los Angeles, US Miami, US New York City, US New York City mp001, US New York City st001, US New York City st002, US New York City st003, US New York City st004, US New York City st005, US Orlando, US Phoenix, US Saint Louis, US Salt Lake City, US San Francisco, US San Francisco mp001, US Tampa, Ukraine, United Arab Emirates, Vietnam,
2021/04/16 14:06:33 INFO Shutdown successful,
```

**Comment by Frepke** [comment]
I can confirm this

**Comment by qdm12** [comment]
It seems like Surfshark removed them from their [Zip file](https://my.surfshark.com/vpn/api/v1/server/configurations). I also cannot find them on [their API](https://my.surfshark.com/vpn/api/v4/server/clusters).

FYI We are searching for the server with hostname `nl-us.prod.surfshark.com` for example here.

Please let me know if you do contact them with what answer they have so I can update the Wiki with it. Thanks!

**Comment by AxePlex** [comment]
what can I ask them exactly to them so I can give you some direction? sorry I'm a beginner for all that...

**Comment by qdm12** [comment]
You can ask them if they still support multihop connections.

If they do, why are they no multihop connections in their Openvpn configuration zip file (https://my.surfshark.com/vpn/api/v1/server/configurations) nor in their API (https://my.surfshark.com/vpn/api/v4/server/clusters).

**Comment by Frepke** [comment]
I'm in contact with Surfshark right now

**Comment by Frepke** [comment]
There isn't an api or direct link at the moment for the multihop servers, but only a zipfile :(
[e4b85823e3319ec0a44be4670f2826dbadc0f8ee.zip](https://github.com/qdm12/gluetun/files/6327957/e4b85823e3319ec0a44be4670f2826dbadc0f8ee.zip)

**Comment by qdm12** [comment]
Is there a public URL to fetch that multi hop zip file? Thanks Frepke!

**Comment by Frepke** [comment]
> Is there a public URL to fetch that multi hop zip file? Thanks Frepke!

Unfortunately not at the moment

**Comment by qdm12** [comment]
So there was a bug in my logic trying to hack around Surfshark hiding some of their server (like multi hop). It should now contain these and a few additional others too.

@AxePlex Just `docker pull qmcgaw/gluetun` and restart the container to get the latest server information 😉

**Comment by Frepke** [comment]
I did a quick test and it's working again for me, hope for @AxePlex also 😄

**Comment by AxePlex** [comment]
it's good for me, it's working again.
