### ISSUE TITLE
Bug: Docker: modprobe: can't change directory to '/lib/modules': No such file or directory`

### ISSUE THREAD

**Issue by rotem925** [qdm12/gluetun#430]
**Is this urgent?**: Yes

**Host OS** (approximate answer is fine too): Docker

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: PIA

**What are you using to run your container?**: Docker Compose

**What is the version of the program** latest

```
Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)
```

**What's the problem** 🤔

On the latest version the container does not start correctly.
Fails at iptable phase with error:
`modprobe: can't change directory to '/lib/modules': No such file or directory`

Rolled back to 3.16.0 and it works
**Share your logs... (careful to remove in example tokens)**

```log

2021/04/19 19:53:24 INFO openvpn configurator: checking for device /dev/net/tun
2021/04/19 19:53:24 INFO firewall: enabling...
2021/04/19 19:53:24 ERROR failed enabling firewall: cannot enable firewall: failed ip6tables command "ip6tables --policy INPUT DROP": modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.6 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.: exit status 3
2021/04/19 19:53:24 INFO Shutdown successful

```

**Comment by Frepke** [comment]
+1

**Comment by qdm12** [comment]
Can any of you run

```sh
docker run -it --rm --cap-add=NET_ADMIN alpine:3.13
apk add ip6tables
ip6tables --version
```

If that fails, what's the error message? I'll use that message to make the program not use ip6tables on systems not supporting ipv6. In case that works, can you try

```sh
ip6tables -L
```

Thanks!

**Comment by oester** [comment]
oester@ubuntu:~$ docker run -it --rm --cap-add=NET_ADMIN alpine:3.13
Unable to find image 'alpine:3.13' locally
3.13: Pulling from library/alpine
540db60ca938: Already exists
Digest: sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Status: Downloaded newer image for alpine:3.13
apk add ip6tables
ip6tables --version/ # apk add ip6tables
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libmnl (1.0.4-r1)
(2/4) Installing libnftnl-libs (1.1.8-r0)
(3/4) Installing iptables (1.8.6-r0)
(4/4) Installing ip6tables (1.8.6-r0)
Executing busybox-1.32.1-r6.trigger
OK: 8 MiB in 18 packages

**Comment by qdm12** [comment]
@oester Thanks! What does `ip6tables --version` give you though, I don't see the output.

**Comment by oester** [comment]
ip6tables v1.8.4 (legacy)

**Comment by qdm12** [comment]
Can you try the image `qmcgaw/gluetun:ip6tables-support` see if it works?

**Comment by oester** [comment]
Yep, appears to connect:

021/04/19 18:21:04 INFO VPN routing IP address: 172.98.71.247
2021/04/19 18:21:04 INFO dns over tls: downloading DNS over TLS cryptographic files
2021/04/19 18:21:05 INFO healthcheck: healthy!
2021/04/19 18:21:05 INFO dns over tls: downloading hostnames and IP block lists
2021/04/19 18:21:05 INFO dns over tls: init module 0: validator
2021/04/19 18:21:05 INFO dns over tls: init module 1: iterator
2021/04/19 18:21:05 INFO dns over tls: start of service (unbound 1.13.0).
2021/04/19 18:21:06 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021/04/19 18:21:06 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021/04/19 18:21:06 INFO dns over tls: ready
2021/04/19 18:21:06 INFO There is a new release v3.16.0 (v3.16.0) created 42 hours ago

**Comment by oester** [comment]
What version will this be fixed in?

**Comment by qdm12** [comment]
In the latest image and v3.17.0 (not released yet). Although technically v3.16.0 is not affected either so I guess all versions are 'fixed'.

Make sure to re-pull `docker pull qmcgaw/gluetun`
