### ISSUE TITLE
Bug: Recent update broke tunneling capability

### ISSUE THREAD

**Issue by donaldrich80** [qdm12/gluetun#432]
**Is this urgent?**: Probably 

**Host OS** (approximate answer is fine too): Ubuntu 20.04

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: NordVPM

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
It was yesterday's push I believe. Sorry, on my phone and already fixed the issue.
```

**What's the problem** 🤔

Functionality broke, received errors about /dev/net/tun and IPv6.  I fixed this by adding the following to my docker compose setup:

```
devices:
  - /dev/net/tun
volumes:
  - "/lib/modules:/lib/modules:ro"
```

Not sure if these are best practice, but I've seen them on pretty popular containers (volume mod from linuxserver/wireguard)

Hope this helps.

**Share your logs... (careful to remove in example tokens)**

```log

As mentioned, fixed on mobile, couldn't save logs 

```

**Comment by qdm12** [comment]
Can you try pulling it and try again? I think it also got fixed yesterday. And you should avoid bind mounting /lib/modules, although I didn't think it would solve it 😄

**Comment by donaldrich80** [comment]
Indeed, the recent update fixed the issue.  Thanks for the prompt response and the awesome container!
