### ISSUE TITLE
Help: Connecting to selenium browser while using gluetun

### ISSUE THREAD

**Issue by Webscrapinger** [qdm12/gluetun#438]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Ubuntu 20.04

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: Nordvpn

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-04-24T13:57:53Z (commit b02a80a)
```

**What's the problem** 🤔

Hey,

I have a VPS and want to scrape websites. My plan was to run a gluetun vpn container, connect selenium chrome browsers to it and access them in R. I can't seem to get it working :/

Here is what I used:
```sh
docker run -d --name gluetun --cap-add=NET_ADMIN \
-e VPNSP="nordvpn" -e REGION="Germany" \
-e OPENVPN_USER=random@mail.com -e OPENVPN_PASSWORD=random_password \
-v /home/rstudio/gluetun \
-p 8888:8888/tcp \
qmcgaw/gluetun
```

The gluetun container seems to run fine:

```log
2021/04/27 16:19:14 INFO healthcheck: healthy!
2021/04/27 16:19:16 INFO dns over tls: downloading hostnames and IP block lists
2021/04/27 16:19:17 INFO dns over tls: init module 0: validator
2021/04/27 16:19:17 INFO dns over tls: init module 1: iterator
2021/04/27 16:19:17 INFO dns over tls: start of service (unbound 1.13.0).
2021/04/27 16:19:17 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021/04/27 16:19:17 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021/04/27 16:19:18 INFO dns over tls: ready
2021/04/27 16:19:18 INFO You are running 1 commit behind the most recent latest
2021/04/27 16:19:18 INFO ip getter: Public IP address is 217.138.216.36 (Germany, Hesse, Frankfurt am Main)
```

Then creating the chrome container:
```sh
docker run -d --shm-size 2g --network=container:gluetun --name test_tainer selenium/standalone-chrome
```

Also fine?!:

```log
2021-04-27 16:21:58,653 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2021-04-27 16:21:58,662 INFO supervisord started with pid 8
2021-04-27 16:21:59,665 INFO spawned: 'xvfb' with pid 10
2021-04-27 16:21:59,669 INFO spawned: 'selenium-standalone' with pid 11
16:22:00.513 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
2021-04-27 16:22:00,516 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-04-27 16:22:00,516 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
16:22:00.739 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2021-04-27 16:22:00.861:INFO::main: Logging initialized @1151ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:22:01.302 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
16:22:01.456 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
```

This is the R code, should be similar to other examples in Python etc.

```
library(RSelenium)

remDr <- remoteDriver(browserName= "chrome", port=8888, remoteServerAddr = "localhost") 
remDr$open(silent = TRUE) 

```
It won't connect:
```log
Error in checkError(res) : 
  Undefined error in httr call. httr output: Recv failure: Connection reset by peer
```

Is this even possibly the way I tried it? I am also open to other solutions for the problem.
Have been in despair over this, would really appreciate some help :(

**Comment by qdm12** [comment]
Where is your R code running?

**Comment by Webscrapinger** [comment]
I connect to RStudio Server on port <vps-ip>:8787
```
tcp        0      0 0.0.0.0:8787            0.0.0.0:*               LISTEN      705/rserver
tcp6       0      0 :::5973                 :::*                    LISTEN      157597/rsession
```

**Comment by qdm12** [comment]
The selenium server seems to run on `4444` should you change your `8888` to `4444` perhaps?

**Comment by Webscrapinger** [comment]
That actually worked, thank you so much :))

Any idea how I would add more containers now though?
Since they all seem to start on 4444.

**Comment by qdm12** [comment]
You need to configure the other containers to use something else than `4444` which might not be possible. But you probably can fiddle with tabs instead within the same instance, running multiple instances would likely result in a waste of resources.

If you are scrapping html code only, I made https://github.com/qdm12/htmlspitter a few years ago which worked well (based on chrome and pupetter). If this fits your needs, let me know and I'll upgrade it / rework it next weekend.
