### ISSUE TITLE
Help: Routing traffic from other containers to gluetun on DSM synology NAS

### ISSUE THREAD

**Issue by zyzzma** [qdm12/gluetun#439]
**Is this urgent?**: Yes

Hi everyone, this container is working great and I'm very happy with it. Already did curl ifconfig.io and I can see traffic is going through my NordVPN server. The problem comes when routing other containers through it.

This is on DSM latest version. I have minimal CLI knowledge but enough for basic commands. I need to route a certain container (transmission by linuxserver) through gluetun and I can't get it to work. I initially thought it was as easy as going on transmission's "links" and link it to gluetun but upon checking IP it's still showing host IP and not NordVPN's. Any help is greatly appreciated!

**Comment by qdm12** [comment]
What do you use to configure your Docker containers? the Synology UI/portainer/docker run/docker compose/other?

You need to specify the `network_mode` as `container:gluetun` for transmission. Note that you will have to publish port on gluetun to access the web ui of transmission as the transmission container will be on the gluetun 'network host' (it uses its whole network stackl

**Comment by zyzzma** [comment]
Wow that was quick, thanks for getting back to me so quickly! Lover your container by the way, best I've used when it comes to VPN. I just set up portainer 15 minutes ago as a colleague recommended it, they said it's much more powerful than synology UI. 

When I go under the transmission container I don't see a field "network_mode". I simply see "connected networks" > Join a Network. Sorry for my lack of knowledge, I'm very eager to learn!

**Comment by zyzzma** [comment]
SOLVED. Thanks for this awesome image!

**Comment by qdm12** [comment]
Great! Thanks for the compliments 😃 

And yes Synology UI doesn't allow to fiddle too much sadly. Portainer is better. If you want to fiddle a tiny bit more, use docker-compose.yml files with the terminal. I wouldn't recommend more complicated than that (👀 Kubernetes...) 😉

Don't forget to check back for updates to the image (you can subscribe to Github releases only), I'm about to take a few weeks off to work on it full time (add wireguard, dns over https and some metrics here and there), it's gonna be fun 🥳
