### ISSUE TITLE
Help: ERROR routing: cannot teardown routing: cannot delete route for 0.0.0.0/0: operation not permitted ERROR cannot setup routing:

### ISSUE THREAD

**Issue by zyzzma** [qdm12/gluetun#447]
Hi,

Running on synology using portainer
I love this container and it was working lovely until today. Error is in the title but also here:

```
2021/05/10 11:58:12 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/05/10 11:58:12 INFO routing: deleting route for 0.0.0.0/0
2021/05/10 11:58:12 ERROR routing: cannot teardown routing: cannot delete route for 0.0.0.0/0: operation not permitted
2021/05/10 11:58:12 ERROR cannot setup routing: operation not permitted
2021/05/10 11:58:12 INFO Shutdown successful
```

Unsure what happened all of a sudden? Thanks for any help!

**Comment by qdm12** [comment]
Actually the teardown error is a consequence of `cannot setup routing: operation not permitted` as the program tries to remove its changes if it fails the setup. And yes the order of logs is confusing 😄

Are you running with NET_ADMIN cap? Try using the Docker cli out of Portainer see if it works?

**Comment by qdm12** [comment]
Was due to `NET_ADMIN` capability missing, there is now a tip in the logs if you get a permission error when setting up routing.
