### ISSUE TITLE
Help: TLS Handshake Failed

### ISSUE THREAD

**Issue by DarkVader-cell** [qdm12/gluetun#457]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): DietPi (Based on Raspbian) 

**CPU arch** or **device name**: arm64

**What VPN provider are you using**: Proton VPN

**What is the version of the program** 

```
Running version latest built on 2020-05-19(commit a9589d8 
(Just pulled the latest from Docker Hub)
```

**What's the problem** 🤔
I'm getting a TLS handshake error when trying to connect using ProtonVPN, I have verified my credentials and tried multiple free servers but all show the same error, I have also tried syncing the time and setting the right time zone (different run but same error). Almost all the free servers seem to give me this error, my internet is working too.

**Share your logs... (careful to remove in example tokens)**

```log

2021/05/23 20:54:16 INFO firewall: setting VPN connection through firewall...,
2021/05/23 20:54:16 INFO openvpn configurator: starting openvpn,
2021/05/23 20:54:16 INFO openvpn: unhealthy program: waiting 24s for it to change to healthy,
2021/05/23 20:54:16 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021,
2021/05/23 20:54:16 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10,
2021/05/23 20:54:16 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]109.201.133.20:1194,
2021/05/23 20:54:16 INFO openvpn: UDP link local: (not bound),
2021/05/23 20:54:16 INFO openvpn: UDP link remote: [AF_INET]109.201.133.20:1194,
2021/05/23 20:54:22 DEBUG openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity),
🚒🚒🚒🚒🚒🚨🚨🚨🚨🚨🚨🚒🚒🚒🚒🚒,
That error usually happens because either:,
1. The VPN server IP address you are trying to connect to is no longer valid 🔌,
   Update your server information using https://github.com/qdm12/gluetun/wiki/Updating-Servers,
2. The VPN server crashed 💥, try changing your VPN servers filtering options such as REGION,
3. Your Internet connection is not working 🤯, ensure it works,
4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose,
2021/05/23 20:54:22 INFO openvpn: TLS Error: TLS handshake failed,
2021/05/23 20:54:22 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting,
2021/05/23 20:54:40 WARN openvpn: unhealthy program: restarting openvpn,
2021/05/23 20:54:40 INFO firewall: setting VPN connection through firewall...,
2021/05/23 20:54:40 INFO openvpn configurator: starting openvpn,
2021/05/23 20:54:40 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021,
2021/05/23 20:54:40 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10,
2021/05/23 20:54:40 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]109.201.133.20:1194,
2021/05/23 20:54:40 INFO openvpn: UDP link local: (not bound),
2021/05/23 20:54:40 INFO openvpn: UDP link remote: [AF_INET]109.201.133.20:1194,
2021/05/23 20:54:40 INFO openvpn: unhealthy program: waiting 48s for it to change to healthy,
2021/05/23 20:54:40 INFO openvpn: TLS Error: reading acknowledgement record from packet,
2021/05/23 20:54:40 DEBUG openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity),

```

**What are you using to run your container?**: Docker Run

Please also share your configuration file:

```sh
docker run -d --name gluetun --cap-add=NET_ADMIN \
-e VPNSP="protonvpn"  \
-e OPENVPN_USER=USERNAME -e OPENVPN_PASSWORD=PASSWORD \
-v /etc/vpn:/gluetun \
-p 9117:9117 \
-e SERVER_HOSTNAME=lxc-nl-09.protonvpn.com \
qmcgaw/gluetun
 
```

**Comment by qdm12** [comment]
Try with `qmcgaw/gluetun:alpine-3.12` see if it works (image is only built form armv7)? Maybe that's related to #442

**Comment by qdm12** [comment]
Little FYI, I re-pushed it just now with a fix (cipher compatibility error between OpenVPN 2.4.x and 2.5.x)

**Comment by DarkVader-cell** [comment]
Yep, just saw it ,Thank you.

Was just tested the build you suggested and got this `
2021/05/23 22:44:14 ERROR openvpn: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/target.ovpn:23: data-ciphers-fallback (2.4.11)`  .

**Comment by DarkVader-cell** [comment]
Ok, just tried the latest release and I'm still facing the same error.

**Comment by DarkVader-cell** [comment]
`2021/05/23 23:13:05 INFO openvpn: VERIFY ERROR: depth=2, error=format error in certificate's notBefore field: C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA, serial=1`
`2021/05/23 23:13:05 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed,
`2021/05/23 23:13:05 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error,
`2021/05/23 23:13:05 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error`
`2021/05/23 23:13:05 INFO openvpn: TLS Error: TLS handshake failed`

**Comment by qdm12** [comment]
I'll test it myself on free Protonvpn servers, I'm out right now so give me a few hours. Maybe it's just their CA cert that changed (we use that one: https://github.com/qdm12/gluetun/blob/master/internal/constants/protonvpn.go#L11)

**Comment by qdm12** [comment]
I just tried with `lxc-jp-13.protonvpn.com` and it worked for me.

I also pushed in the main image (`:latest`) an env variable ` -e FREE_ONLY=yes` you can use to filter out non-free tier servers, that made my life easier to test free servers, hopefully it helps you too 😉

I also checked and their constant values (CA cert and static key) did not change, so that's not it.

Try following the step 2 of the [setup](https://github.com/qdm12/gluetun#setup)? That time related TLS validation might be related to that (#360) 🤔

**Comment by DarkVader-cell** [comment]
Oh damn, that seems to have fixed it. Also the free tier env variable is godsent. I must have updated libseccomp2 last time when installing dependencies for other programs, so misunderstood it was gonna work out of the box.

Thank you for your time!
