### ISSUE TITLE
Feature request: Allow PIA with None encryption type

### ISSUE THREAD

**Issue by ridgewell** [qdm12/gluetun#474]
**What's the feature?** 🧐

- Support "None" encryption type in addition to the existing PIA "normal" and "strong" encryption presets
- Other VPN providers can be manually toggled to disable encryption by setting the environmental variable OPENVPN_CIPHER to none, but the PIA encryption preset overrides this environmental variable

**Next Steps**

I can probably take a stab at this since this seems like a trivial fix that just requires some experimenting with PIA, but I'd need to learn Go syntax. I just wanted to confirm that I'd primarily just need to modify [openvpnconf.go ](https://github.com/qdm12/gluetun/blob/9fc64f4d3cd3cf5da13feb82b31638c6de3aaf16/internal/provider/privateinternetaccess/openvpnconf.go) and [port.go](https://github.com/qdm12/gluetun/blob/e8c8742baefa6d063b6434d7c1560eb5e0108a01/internal/provider/privateinternetaccess/port.go).

**Optional extra information** 

- Use case: Many low-powered or repurposed machines do not provide an AES Instruction Set. For example, on the Intel C2955U, an AES-128 and AES-256 cipher can easily consume 60% of CPU time, while a Gluetun instance that uses the None encryption type can use half of that (25-30% CPU). If your use case doesn't require additional security (e.g. simply accessing geo-restricted content already secured by HTTPS), reducing overhead on a device like the Raspberry Pi can be conserve invaluable CPU resources.
- PIA outlines this preset as ["All Speed No Safety"](https://www.privateinternetaccess.com/pages/vpn-encryption)

**Comment by qdm12** [comment]
Done in 3c3cd431cd19a0aa0e79448c8968b17ca56d45f7

This does not set the `cipher` and `auth` instruction in the openvpn configuration file generated.

It's still however using the CA and X509 cert of the normal PIA encryption preset, as well as port 501 for tcp and 1194 for udp that corresponds to the normal PIA encryption preset. Let me know if it does work for you, thanks!

**Comment by ridgewell** [comment]
Works flawlessly as far as I can tell! Thanks Quentin!

**Comment by ridgewell** [comment]
By the way, I'm not entirely sure if I checked correctly. I was just able to initialize openvpn_cipher with none, without PIA interrupting that. Is there a need to include ncp-disable somehow to avoid OpenVPN upgrading the cipher to AES256 by default? I know this is a deprecated function and will be removed in OpenVPN 2.6, so I might be off base on this one.

**Comment by qdm12** [comment]
Actually I'm planning on bundling both openvpn 2.4 and 2.5 in the image as there are some issues on some specific devices/providers with 2.5.

Now I believe `ncp-disable` doesn't do anything on 2.5 right? Maybe there is a way to disable the negotiation with something else? I'll add it when running 2.4 though with the none encryption preset.

**Comment by qdm12** [comment]
With https://github.com/qdm12/gluetun/commit/01f9e71912ef5ad7a41e3ec7d648371879d0d918

Now the none encryption preset sets the cipher and auth to `cipher none` and `auth none`. `ncp-disable` is added in all cases since we already specify our own decent ciphers and not old broken ciphers that will be removed in 2.6 anyway.
