### ISSUE TITLE
Help: Installing on Raspberry Pi 4 B with OMV

### ISSUE THREAD

**Issue by mattdd50** [qdm12/gluetun#498]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Raspberry Pi OS Lite

**CPU arch** or **device name**: Raspberry Pi 4 B

**What VPN provider are you using**: CyberGhost

**What is the version of the program**: 2021-06-17T16:44:55Z

**What's the problem**

I'm trying to install on a Raspberry Pi 4 B with OMV 5 installed. I keep getting the same error message. I have updated to libseccomp2_2.5.1-1_armhf.deb and I have also run rpi-update but neither of these have made any difference.

This is the log of the error message shown in Portainer:

```
2021/06/18 11:25:23 INFO Alpine version: 3.13.5
2021/06/18 11:25:23 INFO OpenVPN 2.4 version: 2.4.11
2021/06/18 11:25:23 INFO OpenVPN 2.5 version: 2.5.2
2021/06/18 11:25:23 INFO Unbound version: 1.13.0
2021/06/18 11:25:23 INFO IPtables version: v1.8.6
2021/06/18 11:25:23 ERROR files do not exist: /run/secrets/openvpn_clientkey and /gluetun/client.key
2021/06/18 11:25:23 INFO Shutdown successful
```

And this is what I'm using to install (with correct USER and PW):

```sh
docker run -d --name gluetun --cap-add=NET_ADMIN \
-e VPNSP="cyberghost" -e REGION="87-1-gb.cg-dialup.net" \
-e OPENVPN_USER=USER -e OPENVPN_PASSWORD=PW \
-v /srv/dev/Config:/gluetun \
qmcgaw/gluetun
```

**What are you using to run your container?**: Portainer

**Comment by qdm12** [comment]
Do you have client.key in /srv/dev/Config? I'll recheck the logic on my side.

**Comment by mattdd50** [comment]
Nope I didn't have those files there. Apologies but the tutorial I read didn't mention that part. I have it working now thanks although I was unable to use UK servers with CyberGhost as it wouldn't connect. Working fine with a different country though.

**Comment by qdm12** [comment]
> Apologies but the tutorial I read didn't mention that part

What tutorial?

> I was unable to use UK servers with CyberGhost as it wouldn't connect.

If you need this, try following the Update servers Wiki page. It's most likely their IP addresses that changed with Their UK servers.

**Comment by mattdd50** [comment]
I tried doing the server update but I'm getting:

ERROR not enough hosts found: found 13 hosts but expected at least 103

The number of hosts found changes - have seen as high as 44 and as low as 3. It seems to give up fairly fast after only about 5 seconds. I don't know if there is a way to force it to run for longer?

**Comment by qdm12** [comment]
Sorry for the delay. What command are you using to update the servers?

I have updated the server information for Cyberghost, so you should be able to pull it to make it work. (wait for [this](https://github.com/qdm12/gluetun/actions/runs/958407069) to complete in the next 5 minutes though)

**Comment by mattdd50** [comment]
I was just using the command from the wiki to update so I used (with my path):

docker run -it --rm -v /yourpath:/gluetun qmcgaw/gluetun update -file -cyberghost

Just ran that again and I'm still getting the same error.

I tried to connect again to UK servers and it still didn't work. I'm just getting:

2021/06/21 21:55:12 ERROR openvpn: no server found: for protocol udp; group premium udp europe; region united kingdom

The correct hostname should be 87-1-gb.cg-dialup.net if that helps?

**Comment by qdm12** [comment]
🤔 Strange... I just tried:

```sh
docker pull qmcgaw/gluetun
docker run -it --rm -v "$(pwd)/gluetun":/gluetun qmcgaw/gluetun update -file -cyberghost
2021/06/21 21:22:13 INFO creating /gluetun/servers.json with 11118 hardcoded servers
2021/06/21 21:22:13 INFO updating Cyberghost servers...
```

And it worked successfully.

The hostname `87-1-gb.cg-dialup.net` is present for group `Premium UDP Europe` and region `United Kingdom`. 
Maybe check if you can find it in servers.json:

```sh
cat servers.json | grep 87-1-gb.cg-dialup.net
```

It's also present in the code [here](https://github.com/qdm12/gluetun/blob/master/internal/constants/cyberghost.go#L218) so even if you don't update the server information you should have it.

1. Did you pull the latest image?
2. If it doesn't work try by just setting `-e SERVER_HOSTNAME=87-1-gb.cg-dialup.net` as filter to see if it works?

**Comment by mattdd50** [comment]
I noticed that when you ran the update command you are getting 11118 hardcoded servers and I'm only getting 9142. So I'm guessing that's part of the problem? Any idea why that might be?

Apologies but I'm very out of my depth with all of this stuff! So I'm not sure how I would go about doing this:

> It's also present in the code [here](https://github.com/qdm12/gluetun/blob/master/internal/constants/cyberghost.go#L218) so even if you don't update the server information you should have it.
> 
> 1. Did you pull the latest image?
> 2. If it doesn't work try by just setting `-e SERVER_HOSTNAME=87-1-gb.cg-dialup.net` as filter to see if it works?

**Comment by qdm12** [comment]
Aha sorry, I need to add more documentation in the wiki to explain how things work as well!

So gluetun comes with server information inside the program. These are the `hardcoded` ones. It merges them with the ones you have in servers.json so you can manually update those without updating the program.

Try `docker pull qmcgaw/gluetun` and restart the container, that will upgrade the gluetun program and you have the new hardcoded servers (11k instead of 9k as you noticed).

**Comment by mattdd50** [comment]
Thanks for the explanation. I have now managed to connect to the UK servers after running:

> docker pull qmcgaw/gluetun

As you said. Thank you!

I do seem to be getting quite a lot of warnings in the log but everything seems to working very well and the speeds are great.

**Comment by qdm12** [comment]
Documentation added to the wiki in https://github.com/qdm12/gluetun/wiki/Explanations
