### ISSUE TITLE
Help: IPVanish unable to connect

### ISSUE THREAD

**Issue by DKennedya** [qdm12/gluetun#512]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Ubuntu 18.02

**CPU arch** or **device name**: amd

**What VPN provider are you using**: IPVanish

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)
```

**What's the problem**

I've been trying to connect to IPVanish, but it's unable to connect, and I'm not exactly sure why. I've looked through some of the past issues and didn't find the answer. 

**Share your logs... (careful to remove in example tokens)**

```log
2021/07/01 17:00:48 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/01 17:00:48 INFO openvpn: 2021-07-01 17:00:48 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2021/07/01 17:00:48 WARN openvpn: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
2021/07/01 17:00:48 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/01 17:00:48 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/01 17:00:48 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]5.183.92.66:443
2021/07/01 17:00:48 INFO openvpn: UDP link local: (not bound)
2021/07/01 17:00:48 INFO openvpn: UDP link remote: [AF_INET]5.183.92.66:443
2021/07/01 17:00:48 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2021/07/01 17:00:48 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error
2021/07/01 17:00:48 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error
2021/07/01 17:00:48 INFO openvpn: TLS Error: TLS handshake failed
2021/07/01 17:00:48 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting
2021/07/01 17:00:48 INFO openvpn: retrying in 15s
```

**Comment by qdm12** [comment]
Hmm not certain. I think I merged the IPVanish support without having a reply from the person who requested it.

Can you try with the image `qmcgaw/gluetun:test`? I updated the servers information and changed the openvpn configuration a bit, maybe it works now 🤔

**Comment by DKennedya** [comment]
Whatever was done fixed it! Thanks! The VPN is properly connecting now according to the docker logs. 

I've got another question, whenever I connect a vpn to another docker container,  it becomes I cannot access the webpage any longer even after port forwarding through glueten. I'm not sure if I'm missing something or doing something incorrectly.

**Comment by qdm12** [comment]
Ah alright cool! Feel free to change it to `qmcgaw/gluetun` (and repull with `docker pull qmcgaw/gluetun`), I added the changes in 92212fdd11be3904c63b07fb29354b62d0908fd0

> I've got another question, whenever I connect a vpn to another docker container, it becomes I cannot access the webpage any longer even after port forwarding through glueten. I'm not sure if I'm missing something or doing something incorrectly.

I'm not sure what you are trying to do, but I'll assume you connect a container to gluetun (with `network_mode` for example) and that you want to access the port of that container, say `9876`. See https://github.com/qdm12/gluetun/wiki/Connect-to-gluetun#access-ports-of-containers-connected-to-gluetun. If this isn't what you are looking for, please [open a discussion](https://github.com/qdm12/gluetun/discussions)

**Comment by excall06** [comment]
help
hello. i can't connect gluetun docker container to ipvanish 



   |--Timezone: america/caracas
|--Health:
   |--Server address: 127.0.0.1:9999
   |--OpenVPN:
      |--Initial duration: 6s
      |--Addition duration: 5s
|--HTTP control server:
   |--Listening port: 8000
   |--Logging: enabled
|--Public IP getter:
   |--Fetch period: 12h0m0s
   |--IP file: /tmp/gluetun/ip
|--Github version information: enabled
2021/08/12 02:34:09 INFO storage: merging by most recent 11007 hardcoded servers and 11007 servers read from /gluetun/servers.json
2021/08/12 02:34:09 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/08/12 02:34:09 INFO routing: local ethernet link found: eth0
2021/08/12 02:34:09 INFO routing: local ipnet found: 172.17.0.0/16
2021/08/12 02:34:09 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/08/12 02:34:09 INFO routing: adding route for 0.0.0.0/0
2021/08/12 02:34:09 INFO firewall: firewall disabled, only updating allowed subnets internal list
2021/08/12 02:34:09 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/08/12 02:34:09 INFO openvpn configurator: checking for device /dev/net/tun
2021/08/12 02:34:09 WARN TUN device is not available: open /dev/net/tun: no such file or directory
2021/08/12 02:34:09 INFO openvpn configurator: creating /dev/net/tun
2021/08/12 02:34:09 INFO firewall: enabling...
2021/08/12 02:34:09 INFO firewall: enabled successfully
2021/08/12 02:34:09 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2021/08/12 02:34:09 INFO http server: listening on :8000
2021/08/12 02:34:09 INFO healthcheck: listening on 127.0.0.1:9999
2021/08/12 02:34:09 INFO firewall: setting VPN connection through firewall...
2021/08/12 02:34:09 INFO openvpn configurator: starting OpenVPN 2.5
2021/08/12 02:34:09 INFO openvpn: 2021-08-12 02:34:09 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2021/08/12 02:34:09 WARN openvpn: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
2021/08/12 02:34:09 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/08/12 02:34:09 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/08/12 02:34:09 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]216.131.107.57:443
2021/08/12 02:34:09 INFO openvpn: UDP link local: (not bound)
2021/08/12 02:34:09 INFO openvpn: UDP link remote: [AF_INET]216.131.107.57:443
2021/08/12 02:34:10 INFO openvpn: [msy-c10.ipvanish.com] Peer Connection Initiated with [AF_INET]216.131.107.57:443
2021/08/12 02:34:12 ERROR openvpn: AUTH: Received control message: AUTH_FAILED
Your credentials might be wrong 🤨
2021/08/12 02:34:12 INFO openvpn: SIGUSR1[soft,auth-failure] received, process restarting
2021/08/12 02:34:15 INFO healthcheck: program has been unhealthy for 6s: restarting OpenVPN
2021/08/12 02:34:15 INFO openvpn: stopping
2021/08/12 02:34:15 INFO openvpn: starting
2021/08/12 02:34:15 INFO firewall: setting VPN connection through firewall...
2021/08/12 02:34:15 INFO openvpn configurator: starting OpenVPN 2.5

**Comment by qdm12** [comment]
@excall06 please create another issue with your configuration and these logs. It looks like an authentication problem, maybe try using double quotes around your Openvpn username and password.
