### ISSUE TITLE
Feature request: Wireguard support for PIA

### ISSUE THREAD

**Issue by sboger** [qdm12/gluetun#519]
Wireguard support for PIA

- Noticed these well-designed [linux] scripts in a gist that supports wireguard on Private Internet Access VPN. Thought it might be useful in integrating that feature into gluetun.

**Optional extra information** 🚀

- reference: https://gist.github.com/triffid/da48f3c99f1ff334571ae49be80d591b

**Comment by qdm12** [comment]
Thanks I'll use them in #134

closing this as duplicate, feel free to subscribe to #134

**Comment by qdm12** [comment]
Feel free to subscribe to https://github.com/qdm12/gluetun/issues/612 which is exclusively about PIA and Wireguard. Thanks
