### ISSUE TITLE
Help: High CPU Utilization on Raspberry Pi 4

### ISSUE THREAD

**Issue by BrodyStone21** [qdm12/gluetun#523]
Hello, I noticed my Raspberry Pi was running a little hot so I went ahead and ran `top` to see what was using the most processing power and it appears that "openvpn" is using, on average, 80-90% of my CPU. Now I do NOT have openvpn installed, I ONLY have it running through Docker. Does anyone have any ideas to limit the CPU utilization without limiting performance? It is worth mentioning that I am actively downloading some torrents so that could be the culprit. What do you guys think?

Edit: The high bandwith from torrenting is most definitely the issue here, closing.

**Comment by qdm12** [comment]
Hi there, maybe subscribe to #134 which may (or not) bring performance improvements. Most likely it's because the raspberry pi cpu doesn't have hardware acceleration for some encryptions. You may want to try other ciphers with OPENVPN_CIPHER (if the server accepts them) to reduce the load.

**Comment by BrodyStone21** [comment]
I appreciate the advice!

I ended up over clocking to 2GHz and rebooting my Pi and my temps are staying below 65⁰ C so I think I'll just leave it as is for now and toy around with more in depth settings if I end up switching to an Ubuntu based server. Probably won't though, gotta keep them energy costs low!
