### ISSUE TITLE
Help: A local IP address stop OpenVPN

### ISSUE THREAD

**Issue by April-ha** [qdm12/gluetun#541]
```
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2021-07-25T00:53:20Z (commit 8105437)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2021/07/25 17:28:58 INFO Alpine version: 3.14.0
2021/07/25 17:28:58 INFO OpenVPN 2.4 version: 2.4.11
2021/07/25 17:28:58 INFO OpenVPN 2.5 version: 2.5.2
2021/07/25 17:28:59 INFO Unbound version: 1.13.1
2021/07/25 17:28:59 INFO IPtables version: v1.8.7
2021/07/25 17:28:59 INFO Settings summary below:
|--OpenVPN:
   |--Version: 2.5
   |--Verbosity level: 1
   |--Run as root: enabled
   |--Custom cipher: aes-256-cbc
   |--Custom auth algorithm: sha512
   |--Provider:
      |--Vpn Unlimited settings:
         |--Network protocol: udp
         |--Countries: romania
         |--Hostnames: ro.vpnunlimitedapp.com
         |--Client key is set
|--DNS:
   |--Plaintext address: 1.1.1.1
   |--DNS over TLS:
      |--Unbound:
          |--DNS over TLS providers:
              |--Cloudflare
          |--Listening port: 53
          |--Access control:
              |--Allowed:
                  |--0.0.0.0/0
                  |--::/0
          |--Caching: enabled
          |--IPv4 resolution: enabled
          |--IPv6 resolution: disabled
          |--Verbosity level: 1/5
          |--Verbosity details level: 0/4
          |--Validation log level: 0/2
          |--Username: 
      |--Blacklist:
         |--Blocked categories: malicious
         |--Additional IP networks blocked: 13
      |--Update: every 24h0m0s
|--Firewall:
|--System:
   |--Process user ID: 1000
   |--Process group ID: 1000
   |--Timezone: europe/paris
```

this morning >

```
2021/07/26 09:17:45 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2021/07/26 10:41:49 INFO healthcheck: unhealthy: lookup github.com on 192.168.1.1:53: server misbehaving
2021/07/26 10:41:55 INFO healthcheck: program has been unhealthy for 6s: restarting OpenVPN
2021/07/26 10:41:55 INFO openvpn: stopping (last line)
```

I would like to thank you already for your excellent program.

Gluetun has been running for 2 days and this morning OpenVPN stopped
The local address 192.168.1.53 seems to stop OpenVPN.
I don't understand why OpenVPN doesn't restart.
Do you think the local address to block OpenVPN?
I have to tell the firewall to ignore the local addresses?

**Comment by qdm12** [comment]
> The local address 192.168.1.53 seems to stop OpenVPN.

You mean `192.168.1.1:53` right? Are you specifying the DNS for that container? It should be 127.0.0.1:53 (for dns over tls).

This is caused because the firewall blocks outgoing connections outside the VPN and containers in the same network. So 192.168.1.1 is outside so it's blocked, hence the DNS Resolution fails so gluetun thinks it doesn't work, so it tries to restart Openvpn (although it's probably working).

Now why it is stuck at that line, that might be a bug I introduced recently, I'm not sure. But anyway, it shouldn't use that lan address as it's dns.

**Comment by April-ha** [comment]
Thank you for your quick response
it is the IP 192.168.1.53 
I did not change the DNS.
here are all the logs before the problem, it can help

2021/07/25 17:28:59 INFO storage: merging by most recent 11022 hardcoded servers and 11022 servers read from /gluetun/servers.json
2021/07/25 17:28:59 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/07/25 17:28:59 INFO routing: local ethernet link found: eth0
2021/07/25 17:28:59 INFO routing: local ipnet found: 172.17.0.0/16
2021/07/25 17:28:59 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/07/25 17:28:59 INFO routing: adding route for 0.0.0.0/0
2021/07/25 17:28:59 INFO firewall: firewall disabled, only updating allowed subnets internal list
2021/07/25 17:28:59 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/07/25 17:28:59 INFO openvpn configurator: checking for device /dev/net/tun
2021/07/25 17:28:59 WARN TUN device is not available: open /dev/net/tun: no such file or directory
2021/07/25 17:28:59 INFO openvpn configurator: creating /dev/net/tun
2021/07/25 17:28:59 INFO firewall: enabling...
2021/07/25 17:28:59 INFO firewall: enabled successfully
2021/07/25 17:28:59 INFO healthcheck: listening on 127.0.0.1:9999
2021/07/25 17:28:59 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2021/07/25 17:28:59 INFO http server: listening on :8000
2021/07/25 17:28:59 INFO firewall: setting VPN connection through firewall...
2021/07/25 17:28:59 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/25 17:28:59 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/25 17:28:59 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/25 17:28:59 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]77.81.98.70:1194
2021/07/25 17:28:59 INFO openvpn: UDP link local: (not bound)
2021/07/25 17:28:59 INFO openvpn: UDP link remote: [AF_INET]77.81.98.70:1194
2021/07/25 17:28:59 INFO openvpn: [openvpn2.vpnunlimitedapp.com] Peer Connection Initiated with [AF_INET]77.81.98.70:1194
2021/07/25 17:29:05 INFO openvpn: TUN/TAP device tun0 opened
2021/07/25 17:29:05 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
2021/07/25 17:29:05 INFO openvpn: /sbin/ip link set dev tun0 up
2021/07/25 17:29:05 INFO openvpn: /sbin/ip addr add dev tun0 local 10.200.0.250 peer 10.200.0.249
2021/07/25 17:29:05 INFO openvpn: Initialization Sequence Completed
2021/07/25 17:29:05 INFO VPN routing IP address: 77.81.98.70
2021/07/25 17:29:05 INFO dns over tls: downloading DNS over TLS cryptographic files
2021/07/25 17:29:05 INFO healthcheck: program has been unhealthy for 6s: restarting OpenVPN
2021/07/25 17:29:05 INFO openvpn: stopping
2021/07/25 17:29:05 INFO openvpn: starting
2021/07/25 17:29:05 INFO firewall: setting VPN connection through firewall...
2021/07/25 17:29:05 INFO openvpn configurator: starting OpenVPN 2.5
2021/07/25 17:29:05 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/07/25 17:29:05 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/07/25 17:29:05 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]77.81.98.70:1194
2021/07/25 17:29:05 INFO openvpn: UDP link local: (not bound)
2021/07/25 17:29:05 INFO openvpn: UDP link remote: [AF_INET]77.81.98.70:1194
2021/07/25 17:29:05 INFO openvpn: [openvpn2.vpnunlimitedapp.com] Peer Connection Initiated with [AF_INET]77.81.98.70:1194
2021/07/25 17:29:10 WARN dns over tls: cannot update files
2021/07/25 17:29:10 INFO dns over tls: attempting restart in 10s
2021/07/25 17:29:12 INFO openvpn: TUN/TAP device tun0 opened
2021/07/25 17:29:12 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500

**Comment by qdm12** [comment]
> it is the IP 192.168.1.53

No it's trying to resolve using the IP `192.168.1.1` on port `53`.

This is strange. It managed to connect at `17:29` and later the DNS got changed to `192.168.1.1` in the Go runtime, not in the container OS level, which is even stranger. So obviously resolving with `192.168.1.1` failed since it's blocked.

Can you reproduce the issue or is this a one time issue you had?

**Comment by April-ha** [comment]
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8112:8112/tcp
      - 6888:6881
      - 6888:6881/udp
      - 8120:8000/tcp # Built-in HTTP control server
    volumes:
      - "/volume1/docker/Qbittorrent/gluetun:/gluetun"
    environment:
      - VPNSP=vpn unlimited
      - OPENVPN_CIPHER=AES-256-CBC
      - OPENVPN_AUTH=sha512
      - OPENVPN_USER=xxxxxxxxxxxxxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxxxxxx
      - COUNTRY=Romania
      - SERVER_HOSTNAME=ro.vpnunlimitedapp.com
      - TZ=Europe/Paris
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: Qbittorrent
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Europe/Paris
      - WEBUI_PORT=8112
    volumes:
      - "/volume1/docker/Qbittorrent/config:/config"
      - "/volume1/docker/Qbittorrent/downloads:/downloads"
    network_mode: "service:gluetun"
    restart: unless-stopped

**Comment by April-ha** [comment]
I restarted the container.
I'll wait to see if the problem happens again.

**Comment by April-ha** [comment]
there has been no new problem in 24 hours since the container was restarted.
Thanks for the help, I think the topic can be closed.
