### ISSUE TITLE
Bug: Wiki is incorrect about variables for HTTP proxy username

### ISSUE THREAD

**Issue by nearcatch** [qdm12/gluetun#544]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Unraid 6.9.2

```
cat /etc/os-release

NAME=Slackware
VERSION="14.2"
ID=slackware
VERSION_ID=14.2
PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=current
```

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: pia

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-07-27T19:49:22Z (commit 7d4f5c8)
```

**What's the problem** 🤔

Using `HTTPPROXY_USERNAME_SECRETFILE` to change the path of the secretfile doesn't work, even though [the current wiki](https://github.com/qdm12/gluetun/wiki/Docker-secrets) says it should. It appears `HTTPPROXY_USER_SECRETFILE` is the variable that actually works.

I also tested using the default secretfile of `httpproxy_username`. This also doesn't work; the correct secretfile is `httpproxy_user`.

Simple wiki update should take care of things.

**Share your logs... (careful to remove in example tokens)**

```log
logs not really necessary for this
```

**Comment by qdm12** [comment]
Hey there!

Thank you for taking the time to create the issue, I fixed it ✨ 

I also think you are the first Unraid user since my application was added recently by a certain Ethan to the Unraid store, so welcome aboard. If you find any issue with running it together with Unraid feel free to let me know and I can look into it. Cheers!

**Comment by nearcatch** [comment]
> Hey there!
> 
> Thank you for taking the time to create the issue, I fixed it ✨
> 
> I also think you are the first Unraid user since my application was added recently by a certain Ethan to the Unraid store, so welcome aboard. If you find any issue with running it together with Unraid feel free to let me know and I can look into it. Cheers!

I'll be sure to report any issues I run into, but I find Unraid's container creation process too cumbersome compared to docker-compose. So any issues I discover are probably not going to be related to Unraid. 😆

**Comment by qdm12** [comment]
Ah great! Yes docker-compose fanboy as well here. Sorry for assuming that was coming the Unraid template 😅
