### ISSUE TITLE
Bug: Unraid missing entries in drop down for vpn provider

### ISSUE THREAD

**Issue by adwilk13** [qdm12/gluetun#549]
**Is this urgent?**: Yes

**Host OS** (approximate answer is fine too): unraid

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: VPNunlimited

**What are you using to run your container?**: Docker Compose

**What is the version of the program** latest 

```
Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)
```

**What's the problem** 🤔

Drop down for VPN providers ends at torguard when installing via community applications

** No logs as software cannot start installation

**Comment by qdm12** [comment]
Please [email Ethan Jessee](mailto:ethan.jessee@jesseefamily.org) who is responsible for the Gluetun Unraid template, I have no control over it. Thanks!

For any other issue, this repository is the place though!
