### ISSUE TITLE
Bug: unversioned API: requested URI not found

### ISSUE THREAD

**Issue by Zazou89** [qdm12/gluetun#567]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): unRAID 6.9.2

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: Windscribe

**What are you using to run your container?**: Docker template

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-08-17T19:39:36Z (commit 384a4ba)
```

**What's the problem** 🤔

Error message on WebUI : 
`unversioned API: requested URI not found`

**Share your logs... (careful to remove in example tokens)**

Logs tells me creditentials may wrong but I triple checked, creditentials are good.

```log

2021/08/18 10:44:15 INFO openvpn: SIGUSR1[soft,auth-failure] received, process restarting
2021/08/18 10:44:25 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]38.101.74.19:443
2021/08/18 10:44:25 INFO openvpn: UDP link local: (not bound)
2021/08/18 10:44:25 INFO openvpn: UDP link remote: [AF_INET]38.101.74.19:443
2021/08/18 10:44:26 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1601', remote='link-mtu 1550'
2021/08/18 10:44:26 WARN openvpn: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
2021/08/18 10:44:26 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2021/08/18 10:44:26 INFO openvpn: [cle-146.windscribe.com] Peer Connection Initiated with [AF_INET]38.101.74.19:443
2021/08/18 10:44:26 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1601', remote='link-mtu 1550'
2021/08/18 10:44:26 WARN openvpn: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
2021/08/18 10:44:26 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2021/08/18 10:44:26 INFO openvpn: [cle-146.windscribe.com] Peer Connection Initiated with [AF_INET]38.101.74.19:443
2021/08/18 10:44:27 ERROR openvpn: AUTH: Received control message: AUTH_FAILED

```

**Comment by qdm12** [comment]
> Error message on WebUI :

Hey there, there is no Web UI, only an HTTP API, see https://github.com/qdm12/gluetun/wiki/HTTP-Control-server

> Logs tells me creditentials may wrong but I triple checked, creditentials are good.

1. If it's your first time using gluetun: Try surrounding your username and passwords with double quotes `"` since some symbol characters can sometimes be ignored
2. If it was working before: try using the image `qmcgaw/gluetun:v3.21.1` see if it works?

**Comment by Zazou89** [comment]
Oh okay ! Thank for you answer. 

It's my first time with Gluetun, I have special characters in my password **[ -**, unfortunatly as with double quote, I have the same error in logs : 

`2021/08/18 14:27:46 ERROR openvpn: AUTH: Received control message: AUTH_FAILED`

This is my configuration : 
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='GluetunVPN' --net='bridge' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e 'TZ'='europe/paris' -e 'VPNSP'='windscribe' -e 'OPENVPN_USER'='ForSylvanas' -e 'OPENVPN_PASSWORD'='"censured"' -e 'REGION'='' -e 'SERVER_HOSTNAME'='' -e 'SERVER_NAME'='' -e 'OPENVPN_VERSION'='2.5' -e 'PROTOCOL'='udp' -e 'OPENVPN_FLAGS'='' -e 'DOT'='on' -e 'DOT_PROVIDERS'='cloudflare' -e 'SHADOWSOCKS'='off' -e 'SHADOWSOCKS_PASSWORD'='' -e 'SHADOWSOCKS_METHOD'='chacha20-ietf-poly1305' -e 'HTTPPROXY'='off' -e 'HTTPPROXY_USER'='' -e 'HTTPPROXY_PASSWORD'='' -e 'FIREWALL_INPUT_PORTS'='' -e 'FIREWALL_OUTBOUND_SUBNETS'='' -e 'PUBLICIP_FILE'='/gluetun/ip' -e 'SHADOWSOCKS_ADDRESS'='8388' -e 'HTTPPROXY_STEALTH'='off' -e 'SHADOWSOCKS_LOG'='off' -e 'HTTPPROXY_PORT'='8888' -e 'HTTPPROXY_LOG'='off' -e 'FIREWALL_DEBUG'='off' -e 'HTTP_CONTROL_SERVER_PORT'='8000' -e 'HTTP_CONTROL_SERVER_LOG'='on' -e 'PUID'='1000' -e 'PGID'='1000' -p '8888:8888/tcp' -p '8388:8388/tcp' -p '8388:8388/udp' -p '8000:8000/tcp' -v '/mnt/user/appdata/gluetun':'/gluetun':'rw' --cap-add=NET_ADMIN --restart always 'qmcgaw/gluetun' `

**Comment by qdm12** [comment]
Try with `-e OPENVPN_PASSWORD="censured"` without the single quotes.

If it still doesn't work, try with the image `qmcgaw/gluetun:v3.21.1` as it may be a bug I introduced recently 🤔

**Comment by Zazou89** [comment]
Same error with `qmcgaw/gluetun:v3.21.1`
I'll try with a secret file. I created variables, seems ok. But I think I'm not using this method correctly : 

`2021/08/18 18:47:16 ERROR cannot read Openvpn settings: environment variable OPENVPN_USER: cannot read secret file: read /run/secrets/openvpn_user: is a directory`

![image](https://user-images.githubusercontent.com/206181/129955063-8bef5b3f-586e-4b4d-9bc4-f450c825697b.png)

In each folder I created a file without extension ("user", "pass") with credentials inside.

**Comment by qdm12** [comment]
`is a directory` would point that there is no such file on your host machine, make sure `/mnt/user/appdata/gluetun/user` is there. For example: `cat /mnt/user/appdata/gluetun/user` should not give an error. This is because by default Docker creates directories for bind mounts if there is no file existing on the host.

Now, I still don't really see why the environment variables don't work, they should be working fine. I built an image `qmcgaw/gluetun:567`, please try it with the environment variables (without secret files). It should log out your username and password so you can check if it's right / empty etc.

```
+============= DEBUG: USERNAME IS (without double quotes): "yourusername"
+============= DEBUG: PASSWORD IS (without double quotes): "yourpassword"
```

**Comment by Zazou89** [comment]
Yes `cat /mnt/user/appdata/gluetun/user` returns `is a category`, I have to put file (for example` user` inside `/mnt/user/appdata/gluetun/user`, right ? 

I tried with your last build, user and password are correct.

**Comment by Zazou89** [comment]
Okay, I found why.

With windscribe you can't just use you login / password provided to connect to your account management / browser extension / desktop software .

You have to generate an openvpn with predetermined user / password :  https://fra.windscribe.com/getconfig/openvpn

![image](https://user-images.githubusercontent.com/206181/129978816-570b66fd-6689-455a-ae11-fcfa65f486bf.png)

**Comment by qdm12** [comment]
1. For the files: no you should bind mount the files directly. So `/mnt/user/appdata/gluetun/user` is a file, not a directory (or category) and you should get your username by `cat`ing it. Note this file bind mount only works on Linux, on Windows and OSX you can only bind mount directories.
2. Good to know! Let's keep this issue opened so I can add it to the Wiki documentation, and will close it soon.

**Comment by qdm12** [comment]
Documentation added to https://github.com/qdm12/gluetun/wiki/Environment-variables for `OPENVPN_USER` and `OPENVPN_PASSWORD` for Windscribe
