### ISSUE TITLE
Http proxy local traffic?

### ISSUE THREAD

**Issue by Chris230291** [qdm12/gluetun#572]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Ubuntu 18

**CPU arch** or **device name**: amd64

**What VPN provider are you using**:Proton

**What is the version of the program**:Running version latest built on 2021-08-16T19:24:38Z (commit 836412b)

**What's the problem** 🤔
First of all thanks for putting this together. It has been working very well for me.

I have a small fastapi python app that takes some parameters in a http request and returns a redirect url 307
I am trying to use this proxy with my python app and with ffmpeg eg `ffmpeg -http_proxy http://10.0.1.200:8086 -i http://10.0.1.200:8084/channel/119313 -c copy -f mpegts pipe:`

Because of the proxy my app never gets the request. I was wondering if this is normal behaviour or not and if I can "fix" it? I would have thought local traffic would not be sent through the proxy? What I expected was only the redirect (which is external) to go through the proxy. This is all above my head though so any help is appreciated.

Cheers,
Chris

**Comment by qdm12** [comment]
A few questions to clarify this:

1. Is `http://10.0.1.200:8086` the HTTP proxy built-in gluetun or another proxy?
2. Are you running this Python app in a container or not?
3. `Because of the proxy my app never gets the request`: which request are you expecting?
4. `local traffic would not be sent through the proxy` it depends on your configuration, you might want to share it

**Comment by Chris230291** [comment]
Thanks for the reply.
- Yes 8086 is the http proxy that is built into gluetun
- My python app is in another container
- If I make a http request like the one above `http://10.0.1.200:8084/channel/119313` my app does stuff, then returns a stream url from the internet in the form of a redirect. I should see the initial request in my apps debug logs but the request never gets through the proxy. If I disable the proxy it works as normal.
- I'm not sure what configuration info is needed. here is how I created the gluetun container...

```
docker create \
--name=ProtonVPN-US \
--restart=always \
--cap-add=NET_ADMIN \
-p 8085:8888 \
-e VPNSP="ProtonVPN" \
-e COUNTRY="United States" \
-e OPENVPN_USER=**** \
-e OPENVPN_PASSWORD=****\
-e HTTPPROXY="on" \
-e HTTPPROXY_STEALTH="on" \
-e TZ=Europe/London \
qmcgaw/gluetun:latest
```

Thank,
Chris

**Comment by qdm12** [comment]
It's likely a bug on my end (also related to #564), I'll investigate in the coming days. In the mean time, you could run another HTTP proxy container connected to gluetun and that might solve it. I'll let you know when I have something you can test out.

**Comment by qdm12** [comment]
You can configure outbound subnets in the firewall environment variables (see the wiki) so gluetun would be aware of your LAN network, and that should do.

But if there is no need to tunnel through the vpn why use it 😄

**Comment by Chris230291** [comment]
Thanks!
