### ISSUE TITLE
Bug: VPN environment variable MULTIHOP_ONLY

### ISSUE THREAD

**Issue by frepke** [qdm12/gluetun#589]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Debian Buster

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: Surfshark

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-08-23T21:24:48Z (commit 0d6800a)
```

**What's the problem** environment variable MULTIHOP_ONLY has no default value 🤔

That feature doesn't work

**Share your logs... (careful to remove in example tokens)**

```log

ERROR cannot read VPN settings: cannot read provider settings: environment variable MULTIHOP_ONLY: value can only be 'yes' or 'no':

```

**Comment by qdm12** [comment]
Oops thanks for letting me know!

Fixed in 9f12ffc069ed4d95f2b4f19adad359155c59b8ed
