### ISSUE TITLE
Gluetun does not create service or network 

### ISSUE THREAD

**Issue by Rakth** [qdm12/gluetun#595]
Hi

I not sure what this is related to but when I use your guide to create a docker container it doesn't create a service or network for Gluetun so I can't route traffic through Gluetun at all. I am using OMV5 and latest portainer.
I have done it 10 times so I knwo for a fact that NET_ADMIN is there.
Have you heard of this problem before?

Thanks for a GREAT solution! (I just need to get it working )

**Comment by qdm12** [comment]
Please share the logs and config in a discussion instead:  https://github.com/qdm12/gluetun/discussions/new
