### ISSUE TITLE
Feature request: Allow WIREGUARD_PRIVATE_KEY to be specified via a secret file

### ISSUE THREAD

**Issue by Sn0wCrack** [qdm12/gluetun#614]
**What's the feature?** 🧐

Allow `WIREGUARD_PRIVATE_KEY` to be specified via a Docker Compose secret file.

**Optional extra information** 🚀

I usually like to do this so I can have any sensitive data I'd normally put in my docker-compose file in a permission controlled directory.

**Comment by nearcatch** [comment]
Also WIREGUARD_PRESHARED_KEY and WIREGUARD_ADDRESS, I would think.

**Comment by qdm12** [comment]
- `WIREGUARD_PRIVATE_KEY` yes
- `WIREGUARD_PRESHARED_KEY` I guess so 
- `WIREGUARD_ADDRESS` meh not really, an attacker can't do much with it anyway right?

Also why do you guys see an interest in using files instead of env variables? Sensitive variables are unset at start once read in memory, so the only place they are vulnerable is in your e.g. docker-compose.yml... which is also a file 🤔 Just being curious! Thanks!

**Comment by Sn0wCrack** [comment]
> 
> 
>     * `WIREGUARD_PRIVATE_KEY` yes
> 
>     * `WIREGUARD_PRESHARED_KEY` I guess so
> 
>     * `WIREGUARD_ADDRESS` meh not really, an attacker can't do much with it anyway right?
> 
> 
> Also why do you guys see an interest in using files instead of env variables? Sensitive variables are unset at start once read in memory, so the only place they are vulnerable is in your e.g. docker-compose.yml... which is also a file. And for more advanced systems like K8s, I think you can specific a secret file to be plugged in as env variable 🤔 Just being curious! Thanks!

Honestly you're right, I could just separate out all of my variables into a separate environment file the same way the secrets files work on my system.

**Comment by nearcatch** [comment]
> 
> 
>     * `WIREGUARD_PRIVATE_KEY` yes
> 
>     * `WIREGUARD_PRESHARED_KEY` I guess so
> 
>     * `WIREGUARD_ADDRESS` meh not really, an attacker can't do much with it anyway right?
> 
> 
> Also why do you guys see an interest in using files instead of env variables? Sensitive variables are unset at start once read in memory, so the only place they are vulnerable is in your e.g. docker-compose.yml... which is also a file. And for more advanced systems like K8s, I think you can specific a secret file to be plugged in as env variable 🤔 Just being curious! Thanks!

Removing sensitive items from my default .env means other containers won't see the variables. I could use an .env specifically for gluetun, but having separate files also lets me write to a file from command-line easily and change the value without messing around with nano.

**Comment by qdm12** [comment]
See https://github.com/qdm12/gluetun/pull/1348#issuecomment-1646538214 I'll get to it soon.

**Comment by qdm12** [comment]
This is possible with `WIREGUARD_PRIVATE_KEY_SECRETFILE` now, thanks for your patience!

**Comment by Moohan** [comment]
> This is possible with `WIREGUARD_PRIVATE_KEY_SECRETFILE` now, thanks for your patience!

@qdm12 I was just searching for exactly this. I couldn't find documentation on how to use it though?

https://github.com/search?q=repo%3Aqdm12%2Fgluetun-wiki%20WIREGUARD_PRIVATE_KEY_SECRETFILE%20&type=code

**Comment by filcuk** [comment]
@Moohan this is more of a docker compose question.  

You can find all the available vars here: https://github.com/qdm12/gluetun/blob/master/Dockerfile
And how to use compose secrets here: https://docs.docker.com/compose/how-tos/use-secrets/

Your compose should look something like this:
```yaml
secrets:
  wireguard_private_key:
    file: ${DOCKER}/secrets/wireguard_private_key

services:
  gluetun:
    image: qmcgaw/gluetun:${GLUETUN_TAG-latest}
...
    secrets:
      - wireguard_private_key
...
    environment:
      - WIREGUARD_PRIVATE_KEY_SECRETFILE=/run/secrets/wireguard_private_key
...
```
