### ISSUE TITLE
Help: Windscribe and Wireguard

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#617]
From comment posted on #134 by @TheNexter

Log:

```
<log removed for brevity>
2021/09/12 21:04:55 ERROR vpn: cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": dial tcp: lookup api.github.com on 1.1.1.1:53: read udp 100.96.45.0:35235->1.1.1.1:53: i/o timeout,
2021/09/12 21:05:01 INFO healthcheck: program has been unhealthy for 6s: restarting VPN,
2021/09/12 21:05:01 INFO vpn: stopping,
2021/09/12 21:05:01 INFO vpn: starting,
2021/09/12 21:05:01 INFO firewall: setting VPN connection through firewall...,
2021/09/12 21:05:01 INFO wireguard: Wireguard is up
```

Config:

```
docker run -d \
 --name gluetun \
 --cap-add=NET_ADMIN \
 -e VPNSP="windscribe" \
 -e VPN_TYPE="wireguard" \
 -e WIREGUARD_PRIVATE_KEY="mypersonalkeyisputhere" \
 -e WIREGUARD_ADDRESS="100.96.45.0/32" \
 -e WIREGUARD_PORT="1194" \
 -v /home/ubuntu/Documents/gluetunconfig:/gluetun \
 qmcgaw/gluetun
```

**Comment by qdm12** [comment]
@TheNexter Can you try running it with `-e HEALTH_VPN_DURATION_INITIAL=100s -e LOG_LEVEL=debug` and report back what errors you get in the logs?

**Comment by TheNexter** [comment]
|--Server address: 127.0.0.1:9999,
   |--Address to ping: github.com,
   |--VPN:,
      |--Initial duration: 1m40s,
      |--Addition duration: 5s,
|--HTTP control server:,
   |--Listening port: 8000,
   |--Logging: enabled,
|--Public IP getter:,
   |--Fetch period: 12h0m0s,
   |--IP file: /tmp/gluetun/ip,
|--Github version information: enabled,
2021/09/12 21:51:23 INFO routing: default route found: interface eth0, gateway 172.17.0.1,
2021/09/12 21:51:23 INFO routing: local ethernet link found: eth0,
2021/09/12 21:51:23 INFO routing: local ipnet found: 172.17.0.0/16,
2021/09/12 21:51:23 INFO routing: default route found: interface eth0, gateway 172.17.0.1,
2021/09/12 21:51:23 DEBUG routing: ip rule add from 172.17.0.3/32 lookup 200 pref 100,
2021/09/12 21:51:23 INFO routing: adding route for 0.0.0.0/0,
2021/09/12 21:51:23 DEBUG routing: ip route replace 0.0.0.0/0 via 172.17.0.1 dev eth0 table 200,
2021/09/12 21:51:23 INFO firewall: firewall disabled, only updating allowed subnets internal list,
2021/09/12 21:51:23 INFO routing: default route found: interface eth0, gateway 172.17.0.1,
2021/09/12 21:51:23 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...,
2021/09/12 21:51:23 INFO firewall: enabling...,
2021/09/12 21:51:23 DEBUG firewall: iptables --policy INPUT DROP,
2021/09/12 21:51:23 DEBUG firewall: iptables --policy OUTPUT DROP,
2021/09/12 21:51:23 DEBUG firewall: iptables --policy FORWARD DROP,
2021/09/12 21:51:23 DEBUG firewall: iptables --append INPUT -i lo -j ACCEPT,
2021/09/12 21:51:23 DEBUG firewall: iptables --append OUTPUT -o lo -j ACCEPT,
2021/09/12 21:51:23 DEBUG firewall: iptables --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT,
2021/09/12 21:51:23 DEBUG firewall: iptables --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT,
2021/09/12 21:51:23 DEBUG firewall: iptables --append OUTPUT -o eth0 -s 172.17.0.3 -d 172.17.0.0/16 -j ACCEPT,
2021/09/12 21:51:23 DEBUG firewall: iptables --append INPUT -i eth0 -d 172.17.0.0/16 -j ACCEPT,
2021/09/12 21:51:23 INFO firewall: enabled successfully,
2021/09/12 21:51:23 INFO healthcheck: listening on 127.0.0.1:9999,
2021/09/12 21:51:23 INFO http server: listening on :8000,
2021/09/12 21:51:23 INFO firewall: setting VPN connection through firewall...,
2021/09/12 21:51:23 DEBUG firewall: iptables --append OUTPUT -d 31.7.57.243 -o eth0 -p udp -m udp --dport 1194 -j ACCEPT,
2021/09/12 21:51:23 INFO dns over tls: using plaintext DNS at address 1.1.1.1,
2021/09/12 21:51:23 DEBUG firewall: iptables --append OUTPUT -o wg0 -j ACCEPT,
2021/09/12 21:51:23 DEBUG wireguard: Routine: decryption worker 1 - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: handshake worker 1 - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: encryption worker 2 - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: decryption worker 2 - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: handshake worker 2 - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: TUN reader - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: event worker - started,
2021/09/12 21:51:23 DEBUG wireguard: Interface up requested,
2021/09/12 21:51:23 DEBUG wireguard: UDP bind has been updated,
2021/09/12 21:51:23 DEBUG wireguard: Interface state was Down, requested Up, now Up,
2021/09/12 21:51:23 DEBUG wireguard: Routine: receive incoming v6 - started,
2021/09/12 21:51:23 DEBUG wireguard: UAPI: Updating private key,
2021/09/12 21:51:23 DEBUG wireguard: Routine: receive incoming v4 - started,
2021/09/12 21:51:23 DEBUG wireguard: UAPI: Updating fwmark,
2021/09/12 21:51:23 DEBUG wireguard: UAPI: Removing all peers,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - Starting,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - UAPI: Created,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - UAPI: Updating endpoint,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - UAPI: Removing all allowedips,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - UAPI: Adding allowedip,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - UAPI: Adding allowedip,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - Routine: sequential receiver - started,
2021/09/12 21:51:23 DEBUG wireguard: Routine: encryption worker 1 - started,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - Routine: sequential sender - started,
2021/09/12 21:51:23 DEBUG wireguard: Interface up requested,
2021/09/12 21:51:23 INFO wireguard: Wireguard is up,
2021/09/12 21:51:23 INFO dns over tls: downloading DNS over TLS cryptographic files,
2021/09/12 21:51:23 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:23 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:28 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:28 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:33 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:33 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:38 WARN dns over tls: cannot update files,
2021/09/12 21:51:38 INFO dns over tls: attempting restart in 10s,
2021/09/12 21:51:38 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:38 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:43 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:43 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:48 INFO dns over tls: downloading DNS over TLS cryptographic files,
2021/09/12 21:51:48 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:48 ERROR vpn: cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": dial tcp: lookup api.github.com on 1.1.1.1:53: read udp 100.96.45.0:59590->1.1.1.1:53: i/o timeout,
2021/09/12 21:51:48 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:53 ERROR ip getter: Get "https://api.ipify.org": context deadline exceeded (Client.Timeout exceeded while awaiting headers),
2021/09/12 21:51:53 INFO ip getter: retrying in 5s,
2021/09/12 21:51:53 DEBUG wireguard: peer(3+eh…SkxQ) - Handshake did not complete after 5 seconds, retrying (try 2),
2021/09/12 21:51:53 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:53 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:51:58 WARN dns over tls: cannot update files,
2021/09/12 21:51:58 INFO dns over tls: attempting restart in 20s,
2021/09/12 21:51:58 DEBUG wireguard: peer(3+eh…SkxQ) - Handshake did not complete after 5 seconds, retrying (try 2),
2021/09/12 21:51:58 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:51:58 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:52:03 DEBUG wireguard: peer(3+eh…SkxQ) - Handshake did not complete after 5 seconds, retrying (try 2),
2021/09/12 21:52:03 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:52:03 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194,
2021/09/12 21:52:08 ERROR ip getter: Get "https://ifconfig.me/ip": dial tcp: lookup ifconfig.me on 1.1.1.1:53: read udp 100.96.45.0:48732->1.1.1.1:53: i/o timeout,
2021/09/12 21:52:08 INFO ip getter: retrying in 5s,
2021/09/12 21:52:09 DEBUG wireguard: peer(3+eh…SkxQ) - Handshake did not complete after 5 seconds, retrying (try 2),
2021/09/12 21:52:09 DEBUG wireguard: peer(3+eh…SkxQ) - Sending handshake initiation,
2021/09/12 21:52:09 DEBUG wireguard: Received invalid response message from 31.7.57.243:1194

**Comment by qdm12** [comment]
I see some `Received invalid response message from 31.7.57.243:1194` which is odd. I tried your command with some garbage private key and I only get `Sending handshake initiation` messages without the `invalid response` messages. As far as I know, you manage to authenticate and there is a Wireguard server responding.

What do you get with `uname -a`, and also what's your OS?

**Comment by TheNexter** [comment]
> I see some `Received invalid response message from 31.7.57.243:1194` which is odd. I tried your command with some garbage private key and I only get `Sending handshake initiation` messages without the `invalid response` messages. As far as I know, you manage to authenticate and there is a Wireguard server responding.
> 
> What do you get with `uname -a`, and also what's your OS?

Raspberry pi os 64bit
![image](https://user-images.githubusercontent.com/17613028/133129479-d86275b8-d240-4e9a-82b5-39dfa30a577d.png)

**Comment by qdm12** [comment]
Looks like I broke Wireguard in a recent update, I'm investigating. Try with `:v3.24.0` for now?

**Comment by TheNexter** [comment]
> Looks like I broke Wireguard in a recent update, I'm investigating. Try with `:v3.24.0` for now?
> 
> EDIT: never mind my subscription expired LOL! Renewing-it!

Don't troll me 😂

Same error :)
![image](https://user-images.githubusercontent.com/17613028/133143457-06c31716-4b5a-41c7-8408-14d93f550767.png)

**Comment by qdm12** [comment]
Try with `:latest`:

```sh
docker pull qmcgaw/gluetun
```

I tried running gluetun with emulation on `arm64` and `arm/v7` (like your rpi), but it doesn't like the emulation and gluetun fiddling with IP routes so it fails `no such process` & `operation not supported` 😢. I was wondering if the Wireguard implementation wouldn't work on arm architectures, but I guess I need to dig out my old raspberry pi from my drawer.

If it still doesn't work with the latest image, try with:

```sh
docker run -it --rm --cap-add=NET_ADMIN -e VPNSP=custom -e VPN_TYPE=wireguard \
-e WIREGUARD_ENDPOINT_IP=86.106.143.67 -e WIREGUARD_PORT=1194 \
-e WIREGUARD_PUBLIC_KEY="5FXy0/tMXj/TYKVj9PHJ42lCpbWP4qLAOpLZa6FnsRw="  \
-e WIREGUARD_ADDRESS="11.48.216.37/32" \
-e WIREGUARD_PRIVATE_KEY="OFf8G73HKurisHXAUmrXxU5C0VD50EMn3N9KAbut/1k=" \
qmcgaw/gluetun
```

Replacing your values in there. If this still does not work, and you can change/revoke your Wireguard keys, feel free to shoot a Wireguard configuration file at [quentin.mcgaw@gmail.com](mailto:quentin.mcgaw@gmail.com) so I can find the problem faster. No obligation of course though.

**Comment by TheNexter** [comment]
> Try with `:latest`:
> 
> ```shell
> docker pull qmcgaw/gluetun
> ```
> 
> I tried running gluetun with emulation on `arm64` and `arm/v7` (like your rpi), but it doesn't like the emulation and gluetun fiddling with IP routes so it fails `no such process` & `operation not supported` 😢. I was wondering if the Wireguard implementation wouldn't work on arm architectures, but I guess I need to dig out my old raspberry pi from my drawer.
> 
> If it still doesn't work with the latest image, try with:
> 
> ```shell
> docker run -it --rm --cap-add=NET_ADMIN -e VPNSP=custom -e VPN_TYPE=wireguard \
> -e WIREGUARD_ENDPOINT_IP=86.106.143.67 -e WIREGUARD_PORT=1194 \
> -e WIREGUARD_PUBLIC_KEY="5FXy0/tMXj/TYKVj9PHJ42lCpbWP4qLAOpLZa6FnsRw="  \
> -e WIREGUARD_ADDRESS="11.48.216.37/32" \
> -e WIREGUARD_PRIVATE_KEY="OFf8G73HKurisHXAUmrXxU5C0VD50EMn3N9KAbut/1k=" \
> qmcgaw/gluetun
> ```
> 
> Replacing your values in there. If this still does not work, and you can change/revoke your Wireguard keys, feel free to shoot a Wireguard configuration file at [quentin.mcgaw@gmail.com](mailto:quentin.mcgaw@gmail.com) so I can find the problem faster. No obligation of course though.

Still dont work :(
When i use my file in linuxserver/wireguard it's work amazing :(

**Comment by qdm12** [comment]
> Still dont work :(

You need to pull the latest image as I mentioned, your image is outdated.

Also the `WIREGUARD_ENDPOINT_IP` must be an IP address, not a hostname. You can set it to `37.120.213.164` or `185.156.175.180` which I got from resolving `zrh-112-wg.whiskergalaxy.com`.

**Comment by TheNexter** [comment]
Same with latest :(

**Comment by qdm12** [comment]
One last tiny suggestion, maybe it does a difference, try **without** double quotes around the private and public keys?

I also asked Windscribe users on #134 if it still works for them with the latest image so we can nail down if it's a program bug or a configuration issue.

**Comment by TheNexter** [comment]
Same :(

**Comment by qdm12** [comment]
> Same with latest :(

1. Please share your run command you use now (remove private key)
2. Please share your logs with the latest image

@blckwhtx confirmed it's still working for Windscribe with the latest image, so this is likely a configuration error. See https://github.com/qdm12/gluetun/issues/134#issuecomment-919194565
