### ISSUE TITLE
Bug: OpenSSL error while connecting to OpenVPN server with latest update

### ISSUE THREAD

**Issue by Raptor039** [qdm12/gluetun#622]
**Is this urgent?**: Yes

**Host OS** (approximate answer is fine too): Debian 11

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: custom OpenVPN Server

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built (commit cc18b15)
```

**What's the problem** 🤔

OpenSSL error while connecting to server (worked fine with previous build)

**Share your logs... (careful to remove in example tokens)**

```log

2021/09/13 19:46:51 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/09/13 19:46:51 INFO openvpn: OpenSSL: error:0909006C:PEM routines:get_name:no start line

2021/09/13 19:46:51 INFO openvpn: OpenSSL: error:140AD009:SSL routines:SSL_CTX_use_certificate_file:PEM lib

2021/09/13 19:46:51 INFO openvpn: Cannot load inline certificate file

2021/09/13 19:46:51 INFO openvpn: Exiting due to fatal error

2021/09/13 19:46:51 ERROR vpn: exit status 1

2021/09/13 19:46:51 INFO vpn: retrying in 15s

2021/09/13 19:46:57 INFO healthcheck: program has been unhealthy for 6s: restarting VPN

```
Many thanks for your help to fix that. Waiting for more information to give if needed.

**Comment by qdm12** [comment]
Try with `docker run -it --rm -e OPENVPN_CUSTOM_CONFIG=/yourfile.conf -v /yourfile.conf:/gluetun/yourfile.conf qmcgaw/gluetun openvpnconfig`; there should be maybe some line missing that you can spot?

I just reworked the custom config system this morning, so that's why. If it's urgent, use release image tag `:v3.24.0`. But I appreciate the help debugging if you can afford it thanks!

**Comment by Raptor039** [comment]
Hi,

just tried to debug with the command posted above. Unfortunately, I didn't find any line wich could be missing from my conf file.
Maybe a problem with the wrapper who browse inline certificates or key to be linked to the openvpn client?

Luckily, the v3.24.0 works like a charm however :)

**Comment by qdm12** [comment]
Actually just spot the difference between:

```sh
docker run -it --rm -e OPENVPN_CUSTOM_CONFIG=/yourfile.conf -v /yourfile.conf:/gluetun/yourfile.conf qmcgaw/gluetun openvpnconfig
```

and

```sh
docker run -it --rm -e OPENVPN_CUSTOM_CONFIG=/yourfile.conf -v /yourfile.conf:/gluetun/yourfile.conf qmcgaw/gluetun:v3.24.0 openvpnconfig
```

That should be obvious what changed and why it fails now 😉 

Apart from that, gluetun should not modify anything it doesn't know how to handle ([relevant code](https://github.com/qdm12/gluetun/blob/master/internal/provider/custom/openvpnconf.go#L32-L82)).

Things I can think of that changed which might be a cause:

- Lines are de-duplicated at the end, maybe you have duplicate lines in your certificate values etc.?
- Empty lines are removed

Thanks!

**Comment by Raptor039** [comment]
Here what's happen after launched `docker run -it --rm -e OPENVPN_CUSTOM_CONFIG=/gluetun/bt.ovpn \
-v /srv/docker_data/gluetun/bt.ovpn:/gluetun/bt.ovpn \
qmcgaw/gluetun:v3.24.0 openvpnconfig`


`2021/09/13 21:13:35 INFO creating /gluetun/servers.json with 11860 hardcoded servers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7bb3d7]

goroutine 9 [running]:
github.com/qdm12/gluetun/internal/cli.(*CLI).OpenvpnConfig(0x0, {0x7fb3f9f1a118, 0xc00006c3c0}, {0xc1c158, 0xc00001e3c0})
        github.com/qdm12/gluetun/internal/cli/openvpnconfig.go:33 +0x217
main._main({0xc0ff18, 0xc000086400}, {{0xbfed58, 0x7}, {0xbfed50, 0x7}, {0xc00660, 0x14}}, {0xc00001e040, 0x2, ...}, ...)
        ./main.go:130 +0x37a
main.main.func1()
        ./main.go:80 +0x150
created by main.main
        ./main.go:79 +0x5a6`

**Comment by Raptor039** [comment]
> Actually just spot the difference between:
> 
> ```shell
> docker run -it --rm -e OPENVPN_CUSTOM_CONFIG=/yourfile.conf -v /yourfile.conf:/gluetun/yourfile.conf qmcgaw/gluetun openvpnconfig
> ```
> 
> and using 3.24.0...
> 
> ```shell
> docker run -it --rm -e OPENVPN_CUSTOM_CONFIG=/yourfile.conf -v /yourfile.conf:/gluetun/yourfile.conf qmcgaw/gluetun:v3.24.0 openvpnconfig
> ```
> 
> That should be obvious what changed and why it fails now 😉
> 
> Apart from that, gluetun should not modify anything it doesn't know how to handle ([relevant code](https://github.com/qdm12/gluetun/blob/master/internal/provider/custom/openvpnconf.go#L32-L82)).
> 
> Things I can think of that changed which might be a cause:
> 
> * Lines are de-duplicated at the end, maybe you have duplicate lines in your certificate values etc.?
> * Empty lines are removed
> 
> Thanks!

**Comment by qdm12** [comment]
Ah yeah bummer it wasn't a supported operation back then 😢 

I pushed an image (amd64 only) `qmcgaw/gluetun:622`, please try with it and see if it works? It's basically `latest` with the deduplication removed, the empty line removal removed, and the trailing line removed. If it works, I'll proceed re-adding those 3 one by one to see which one is faulty. Thanks for your help!

**Comment by Raptor039** [comment]
Hello!

I tried your image (622) and it works fine, no error at all and connection OK.

Waiting for the follow.

_PS (not technical) : J'ai vu que tu avais bossé à Nice et que tu parlais français ; j'en profite donc pour te remercier en français pour ton aide et pour le travail fourni à la réalisation de gluetun, c'est vraiment un beau projet très utiles pour pleins de situations diverses. A très vite._  😉

**Comment by Raptor039** [comment]
Ok so... I belive the problem is coming from the dedup... Just pass a grep of `QTETMBEGA1UEBxMKTGVzUm91c3NlczENMAsGA1UEChMESG9tZTESMBAGA1UEAxMJ` and here the result : 

```shell
grep -r QTETMBEGA1UEBxMKTGVzUm91c3NlczENMAsGA1UEChMESG9tZTESMBAGA1UEAxMJ glutun*.txt
glutun-latest.txt:QTETMBEGA1UEBxMKTGVzUm91c3NlczENMAsGA1UEChMESG9tZTESMBAGA1UEAxMJ
glutun622.txt:QTETMBEGA1UEBxMKTGVzUm91c3NlczENMAsGA1UEChMESG9tZTESMBAGA1UEAxMJ
glutun622.txt:QTETMBEGA1UEBxMKTGVzUm91c3NlczENMAsGA1UEChMESG9tZTESMBAGA1UEAxMJ
```

**Comment by qdm12** [comment]
Hey @Raptor039!

Wonderful, thanks for taking the time to diff this. The 'dumb deduplication' step was definitely, well, dumb. I changed it in 91ce790b6b7412b7c83d14133617c613d6d07d51 (on the latest image) to use a 'smarter' deduplication, where it's removing lines case by case to avoid duplicates from the runtime modifications. The certificate values etc. won't be affected anymore 👍

> J'ai vu que tu avais bossé à Nice et que tu parlais français ; j'en profite donc pour te remercier en français pour ton aide et pour le travail fourni à la réalisation de gluetun, c'est vraiment un beau projet très utiles pour pleins de situations diverses. A très vite.

Ah un message de remerciement avec plein d'accents, ça fait plaisir 😄 Merci à toi aussi pour ton aide et d'avoir pris le temps de reporter le problème!
