### ISSUE TITLE
Bug: REGION variable ignored when using NordVPN

### ISSUE THREAD

**Issue by louis-ad** [qdm12/gluetun#640]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Arch Linux

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: NordVPN

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-05-23T21:55:31Z (commit 0c4f01a)
```

**What's the problem** 🤔

Similar to issue #593, the variable REGION is ignored when using NordVPN.
e.g. In compose-file
REGION=Sweden
but gluetun connects to random countries like Japan, India, UK and USA

**Share your logs... (careful to remove in example tokens)**

```log

2021/09/24 19:52:06 INFO openvpn configurator: starting openvpn
2021/09/24 19:52:06 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/09/24 19:52:06 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/09/24 19:52:06 WARN openvpn: --ping should normally be used with --ping-restart or --ping-exit
2021/09/24 19:52:06 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]185.240.244.91:1194
2021/09/24 19:52:06 INFO openvpn: UDP link local: (not bound)
2021/09/24 19:52:06 INFO openvpn: UDP link remote: [AF_INET]185.240.244.91:1194
2021/09/24 19:52:07 INFO openvpn: [us8434.nordvpn.com] Peer Connection Initiated with [AF_INET]185.240.244.91:1194

```

**Comment by qdm12** [comment]
Use `COUNTRY` for now. It's a bug, it should be retro compatible, I'll check!

**Comment by qdm12** [comment]
Never mind, it's still `REGION` nothing changed. Not a bug. It was probably a bug back in May, just pull the latest release or the latest image and it will fix it. Cheers.

**Comment by louis-ad** [comment]
Thanks, sorry about that, I thought I understood docker compose, but it turns out I was still using an image from May and not "latest".
