### ISSUE TITLE
Custom provider option seems non-functional now

### ISSUE THREAD

**Issue by steamyRayV** [qdm12/gluetun#651]
### Is this urgent?

Yes

### Host OS

Ubuntu 20.04

### CPU arch

x86_64

### VPN service provider

IVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

v3.25.0

### What's the problem 🤔

No matter what permissions I set, custom.conf can't be read inside the container. I used Glutun a few months back and setup was easy, now it's broken.

"2021/09/29 16:03:11 ERROR cannot read VPN settings: cannot read provider settings: cannot extract configuration from file: cannot read file: open /gluetun/custom.conf:ro: no such file or directory"

The instructions also seem different than I remember and there appears to be a typo in the example run command from the wiki:
# OpenVPN
docker run -it --rm --cap-add=NET_ADMIN \
-e VPNSP=custom -e VPN_TYPE=openvpn \
-v /yourpath/yourconfig.conf:/gluetun/config.conf \ #here it's "config.conf"
-e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf:ro \ #but here it is "custom.conf"
-e OPENVPN_USER=abc -e OPENVPN_PASSWORD=abc qmcgaw/gluetun

custom.conf and config.conf are two files, or is this a typo?

Anyway I think I cleaned that up (unless I'm misunderstanding something) and used this: 

docker run -it --rm --cap-add=NET_ADMIN \
-e VPNSP=custom -e VPN_TYPE=openvpn \
-v /home/user/gluetun/custom.conf:/gluetun/custom.conf \
-e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf:ro \
qmcgaw/gluetun

My OVPN file is saved at '/home/user/gluetun/custom.conf' And I've tried every permission I can think of. This worked for me before but not now. I also tried leaving in the typo from the example in the wiki. This container was really easy to use a few months ago so I can't imagine what I've got wrong.

Thanks.

### Share your logs

```log
"2021/09/29 16:03:11 ERROR cannot read VPN settings: cannot read provider settings: cannot extract configuration from file: cannot read file: open /gluetun/custom.conf:ro: no such file or directory"
```

### Share your configuration

```yml
docker run -it --rm --cap-add=NET_ADMIN \
-e VPNSP=custom -e VPN_TYPE=openvpn \
-v /home/user/gluetun/custom.conf:/gluetun/custom.conf \
-e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf:ro \
qmcgaw/gluetun
```

**Comment by steamyRayV** [comment]
There's no option for "custom" and it wouldn't let me submit the report otherwise. I picked IVPN to get through. Ignore that.

**Comment by steamyRayV** [comment]
So after correcting the custom/config typo, I found the second issue in the Wiki. 
-e OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf:ro

Remove the ':ro' and it works. Maybe this should be mounted in the Docker run command as read only, but when it's attached to the environmental variable, it doesn't work currently.
Maybe just the Wiki should be corrected.

**Comment by qdm12** [comment]
I'm twice ashamed 😅

- The wiki is fixed (you can bind mount the config file as read only instead, although it's optional)
- I added custom to the list of provider options in the bug issue template. Thanks for pointing it out as well!

Anyway, thanks again for taking the time to report all this. I'm thinking having the wiki bundled inside gluetun with each github release would be nice 😉  Maybe one day, to avoid silly me breaking wiki instructions!

**Comment by qdm12** [comment]
Also note gluetun should be retro-compatible, so you don't need to update your config. The wiki changed since I'm migrating things (with retrocompatibility), such as the new `custom` provider for both Openvpn and wireguard.

I will do a v4.0.0 release in the coming months, and that will however remove retrocompatibility aspects. Hopefully the transition will be smoother with those retro compatible migration steps I'm taking.
