### ISSUE TITLE
Feature request: add ghcr.io registry as part of release build workflow

### ISSUE THREAD

**Issue by ksurl** [qdm12/gluetun#688]
### What's the feature 🧐

See [here](https://github.com/ksurl/docker-buildtest/blob/main/.github/workflows/build.yml) for an example on pushing to Docker hub and Github. you will need to create a personal access token for it and add it as a repo secret.  The package will be set to private by default as well, so it needs to be set to public manually

This could be an additional option for pulling the image since docker hub has rate limiting if you're using something like watchtower to do updates.

**Comment by ksurl** [comment]
Any update on this?

**Comment by qdm12** [comment]
@ksurl Your PR worked flawlessly without any extra setup on my side :100: 
Image now available at `ghcr.io/qdm12/gluetun` :tada:
