### ISSUE TITLE
Wiki issue: 

### ISSUE THREAD

**Issue by VictorDrijkoningen** [qdm12/gluetun#694]
all links inside the wiki redirect to the homepage because they have a double _github_/wiki/wiki/_pagename__

**Comment by AyyKamp** [comment]
had this too yesterday, very likely a github issue

**Comment by qdm12** [comment]
Uh strange. Let me know if you find out how to reproduce it.

**Comment by qdm12** [comment]
Will close for now, feel free to let me know if it happens again
