### ISSUE TITLE
Feature request: port forwarding support for custom providers

### ISSUE THREAD

**Issue by calebsw83** [qdm12/gluetun#716]
### What's the feature 🧐

I'm trying to enable port forward settings with OVPN.com as my provider, using custom provider settings. I am able to connect just fine, but I'm not sure how I'd enable port forwarding. I looked around and couldn't find anything related to this specific issue, but I did see that there was an open item about adding [official support to OVPN.com](https://github.com/qdm12/gluetun/issues/495).

Assuming port forwarding with a custom provider is not possible currently, is it something that could be added? Further, when OVPN is officially supported, will port forwarding be available to use at that time? Thanks.

**Comment by steamyRayV** [comment]
Weird that you just posted this less than a day ago. I'm trying to switch to this container from another OpenVPN container (https://github.com/dperson/openvpn-client). The dperson OpenVPN container is allowing the port to be opened with the environmental variable: -e "VPNPORT=1234"
With this container I've tried "FIREWALL_VPN_INPUT_PORTS" and "FIREWALL_INPUT_PORTS" to no avail. I'm not sure which we should be using, but neither are working.

**Comment by steamyRayV** [comment]
Actually disregard what I said. I had this container working a couple months ago and planned to switch over. Between then and now the custom provider setup got broken entirely. I may try older versions to see where it happened but for now I'm just going back to the dperson container as it just takes an ovpn file. This project is huge and has so many moving parts compared to the dperson container.
Try the environmental variables I posted for this container if this is working at all for you.

**Comment by qdm12** [comment]
Yeah custom port forwarding is only for PIA for now since it needs to do some http exchange with their API to get a port. If you just need to open a port in your firewall, use `FIREWALL_VPN_INPUT_PORTS` as @steamyRayV suggested.
