### ISSUE TITLE
Wiki issue: A few wiki issues i noticed

### ISSUE THREAD

**Issue by arpitgupta** [qdm12/gluetun#747]
1. https://github.com/qdm12/gluetun/wiki/Mullvad: WIREGUARD_ADDRESS - I see this specific to the key. If i generate a new key they i get a new address.
2. iptable errors and openvpn errors links in FAQ lead back to the home page.

**Comment by qdm12** [comment]
Fixed and fixed, thanks for taking the time to report it! Also my apologies for 1 month delay 😄
