### ISSUE TITLE
Wiki issue: ProtonVPN FREE_ONLY environment variable

### ISSUE THREAD

**Issue by ftruzzi** [qdm12/gluetun#759]
Hi, and thank you for your work!

Looks like the `FREE_ONLY` env var for ProtonVPN should be `yes`/`no` rather than `on`/`off` as reported in the Wiki.

I'm running version `latest built on 2021-12-14T18:21:24.225Z (commit ca82fcb)` from `qmcgaw/gluetun` on Docker Hub.

**Comment by qdm12** [comment]
Since 7d824a51798f3e635e116dfece6056fd2ad4a2c6 the following should work for any 'boolean' environment variables:

- enabled: "enabled", "yes", "on",
- disabled: "disabled", "no", "off"

So issue solved, although a bit by accident :smile: 

Anyway thanks so much for reporting the issue!
