### ISSUE TITLE
Feature request: Ability to disable updater

### ISSUE THREAD

**Issue by matt-laird** [qdm12/gluetun#766]
### What's the feature 🧐

Currently, the Updater that handles pulling the latest VPN information for each VPN provider runs at the start of a container. It would be nice to be able to disable this request for those users that update the `servers.json` themselves. Like the wiki states - [update-mechanism](https://github.com/qdm12/gluetun/wiki/Updating-servers#update-mechanism)

A suggestion would be to make the `UPDATE_PERIOD` variable allow for a `-1` which means it will only pull the data once if there is no `servers.json` present, this allows users to update the file in place via other means, and it will not be constantly regenerated. This option also allows users to only update the file via [`gluetun`'s internal CLI](https://github.com/qdm12/gluetun/wiki/Updating-servers#cli-operation) only when needed.

**Comment by qdm12** [comment]
It's actually not run when the container starts. Setting `UPDATE_PERIOD=0` (default) also disables periodic updates. Now if you want to manually update it you need to update the timestamp for the servers in servers.json or the built-in data will override it.
