### ISSUE TITLE
Bug: HTTPPROXY_PORT is not longer respected in the latest release

### ISSUE THREAD

**Issue by LeoRX** [qdm12/gluetun#778]
### Host OS

Unraid

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

HTTPPROXY_PORT environment variable is not longer respected.  I noticed when my proxied application stopped working and found the log stating http proxy port is set to the default 8888.
I'm currently using working around by redirecting my custom port to 8888 through docker.  not big issue on my part, but I thought its worth pointing out. 

Cheers.

### Share your logs

```log
2022/01/08 00:03:57 INFO http proxy: listening on :8888
```

**Comment by qdm12** [comment]
Fixed in 05f42f0cb866b0aaa7dea0e5d623bc0b6ae20259 it was a typo (`HTTTPPROXY_PORT` previously)

Thanks for pointing it out :+1: You can also use `HTTPPROXY_LISTENING_ADDRESS=":8888"` alternatively (the newer variable).

**Comment by toniopelo** [comment]
FYI @qdm12, the newer variable is not present [on the wiki here](https://github.com/qdm12/gluetun/wiki/HTTP-proxy-options) :)

**Comment by qdm12** [comment]
Thanks @toniopelo I updated the wiki to reference `HTTPPROXY_LISTENING_ADDRESS` instead :wink:
