### ISSUE TITLE
Bug: Unraid docker fails to install "Invalid IP address too many colons in address"

### ISSUE THREAD

**Issue by Seltonu** [qdm12/gluetun#793]
### Is this urgent?

Yes

### Host OS

Unraid 6.9.2

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker run

### What is the version of Gluetun

Latest from Unraid community applications, 3.26.0

### What's the problem 🤔

GluetunVPN was working until an update this morning and I have not been able to get it installed on my server anymore. The docker just completely fails to install due to an invalid IP with too many colons in the default template. I have not modified the ports/IP. I have **cleared out the previous install's appdata** and this did not fix it.

![image](https://user-images.githubusercontent.com/10287568/149653184-4ae2f76b-db81-4456-9f36-8dcbac2bab58.png)

Note: manually removing the extra colon from the 8388 port in the template gives a **similar error**, "Invalid IP address: 8388" without mentioning the extra colon.

Marked as **urgent** because it's a critical bug and many of my other dockers are shut down until GluetunVPN is back up.

### Share your logs

```log
Failure to install:

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='GluetunVPN' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'TZ'='America/Los_Angeles' -e 'VPNSP'='private internet access' -e 'VPN_TYPE'='openvpn' -e 'OPENVPN_PROTOCOL'='udp' -e 'OPENVPN_USER'='[REDACTED]' -e 'OPENVPN_PASSWORD'='[REDACTED]' -e 'OPENVPN_VERSION'='2.5' -e 'OPENVPN_VERBOSITY'='1' -e 'OPENVPN_FLAGS'='' -e 'OPENVPN_CIPHER'='' -e 'OPENVPN_AUTH'='' -e 'OPENVPN_ROOT'='no' -e 'OPENVPN_TARGET_IP'='' -e 'OPENVPN_IPV6'='off' -e 'OPENVPN_CUSTOM_CONFIG'='' -e 'OPENVPN_INTERFACE'='tun0' -e 'OPENVPN_PORT'='' -e 'WIREGUARD_PRIVATE_KEY'='' -e 'WIREGUARD_PRESHARED_KEY'='' -e 'WIREGUARD_PUBLIC_KEY'='' -e 'WIREGUARD_ADDRESS'='' -e 'WIREGUARD_ENDPOINT_IP'='' -e 'WIREGUARD_ENDPOINT_PORT'='51820' -e 'WIREGUARD_INTERFACE'='wg0' -e 'REGION'='' -e 'COUNTRY'='' -e 'CITY'='' -e 'SERVER_HOSTNAME'='' -e 'FIREWALL'='on' -e 'FIREWALL_VPN_INPUT_PORTS'='' -e 'FIREWALL_INPUT_PORTS'='' -e 'FIREWALL_OUTBOUND_SUBNETS'='' -e 'FIREWALL_DEBUG'='off' -e 'LOG_LEVEL'='info' -e 'DOT'='on' -e 'DOT_PROVIDERS'='cloudflare' -e 'DOT_PRIVATE_ADDRESS'='127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff:7f00:1/104,::ffff:a00:0/104,::ffff:a9fe:0/112,::ffff:ac10:0/108,::ffff:c0a8:0/112' -e 'DOT_VERBOSITY'='1' -e 'DOT_VERBOSITY_DETAILS'='0' -e 'DOT_VALIDATION_LOGLEVEL'='0' -e 'DOT_CACHING'='on' -e 'DOT_IPV6'='off' -e 'BLOCK_MALICIOUS'='on' -e 'BLOCK_SURVEILLANCE'='off' -e 'BLOCK_ADS'='off' -e 'UNBLOCK'='' -e 'DNS_UPDATE_PERIOD'='24h' -e 'DNS_PLAINTEXT_ADDRESS'='' -e 'DNS_KEEP_NAMESERVER'='on' -e 'HTTPPROXY'='off' -e 'HTTPPROXY_LOG'='off' -e 'HTTPPROXY_USER'='' -e 'HTTPPROXY_PASSWORD'='' -e 'HTTPPROXY_STEALTH'='off' -e 'SHADOWSOCKS'='off' -e 'SHADOWSOCKS_LOG'='off' -e 'SHADOWSOCKS_PASSWORD'='' -e 'SHADOWSOCKS_CIPHER'='chacha20-ietf-poly1305' -e 'HEALTH_SERVER_ADDRESS'='127.0.0.1:9999' -e 'HEALTH_ADDRESS_TO_PING'='github.com' -e 'HEALTH_VPN_DURATION_INITIAL'='6s' -e 'HEALTH_VPN_DURATION_ADDITION'='5s' -e 'UPDATER_PERIOD'='0' -e 'PUBLICIP_FILE'='/gluetun/ip' -e 'PUBLICIP_PERIOD'='12h' -e 'VERSION_INFORMATION'='on' -e 'HTTP_CONTROL_SERVER_LOG'='on' -e 'PUID'='1000' -e 'PGID'='1000' -p '8888:8888/tcp' -p ':8388::8388/tcp' -p '8000:8000/tcp' -v '/mnt/user/appdata/gluetun':'/gluetun':'rw' --cap-add=NET_ADMIN --restart always 'qmcgaw/gluetun'

docker: Invalid ip address :8388: address :8388:: too many colons in address.
See 'docker run --help'.

The command failed.
```

**Comment by Seltonu** [comment]
Bug in template was fixed as mentioned on the unraid forums [here](https://forums.unraid.net/topic/111725-support-diamondprecisioncomputing-all-images-and-files/page/5/?tab=comments#comment-1085624)

Closing this issue, apologies for cluttering the github.

**Comment by qdm12** [comment]
Hey @Seltonu I can fix it with a PR. See https://github.com/qdm12/gluetun/discussions/550

Can you use an older release then perhaps? For example image `qmcgaw/gluetun:v3.26.0` should work fine.

**Comment by qdm12** [comment]
That seems fixed in https://github.com/DiamondPrecisionComputing/unraid-templates/commit/cda62dc4e528eb6083d687812d5165e110ff3276

Yes it was a bad variable configuration trying to force `SHADOWSOCKS_LISTENING_ADDRESS` to be a port, although it was never a port. Not a problem from this repo, so re-closing 😉 

In the future feel free to read / comment on #550 if you have any Unraid issue 👍
