### ISSUE TITLE
Feature request: Mobile Application: Ongoing notification to disconnect all tunnels

### ISSUE THREAD

**Issue by TomCos** [qdm12/gluetun#799]
Similarly to Google Chrome's incognito mode, the **option** for an ongoing notification to disconnect all tunnels would be a nice feature to have, as opposed to having to open the app and disconnect manually.  My current usage is on Android.  I am not sure if something like this would be possible on iOS.

**Comment by qdm12** [comment]
Can't delete, but no problem 😄
