### ISSUE TITLE
Bug: DNS_UPDATE_PERIOD=0 no longer works (gluetun exits on start)

### ISSUE THREAD

**Issue by julianlore** [qdm12/gluetun#810]
### Is this urgent?

No

### Host OS

Ubuntu 20.04.3 LTS

### CPU arch

x86_64

### VPN service provider

Surfshark

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-01-19T00:42:09.225Z (commit a1a1128)

### What's the problem 🤔

Specifying `DNS_UPDATE_PERIOD=0` as an environment variable as indicated in the [DNS options page on the wiki](https://github.com/qdm12/gluetun/wiki/DNS-options) to disable block lists updates causes gluetun to error and quit on start.

Not urgent as it works fine with the default option for `DNS_UPDATE_PERIOD`, even though `DOT` is off and all blocking is off.

Probably due to #756, where [`gluetun/internal/configuration/sources/env/dot.go`](https://github.com/qdm12/gluetun/blob/master/internal/configuration/sources/env/dot.go) uses `envToDurationPtr` to parse the duration but does not account for 0 (or maybe the validation should account for it).

### Share your logs

```log
Running version latest built on 2022-01-19T00:42:09.225Z (commit a1a1128)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022/01/23 00:18:08 WARN DNS_PLAINTEXT_ADDRESS is set to 10.2.0.3 so the DNS over TLS (DoT) server will not be used. The default value changed to 127.0.0.1 so it uses the internal DoT server. If the DoT server fails to start, the IPv4 address of the first plaintext DNS server corresponding to the first DoT provider chosen is used.
2022/01/23 00:18:09 INFO storage: merging by most recent 11100 hardcoded servers and 11100 servers read from /gluetun/servers.json
2022/01/23 00:18:09 ERROR failed validating dns settings: failed validating DoT settings: update period is too short: 0s must be bigger than 30s
2022/01/23 00:18:09 INFO Shutdown successful
```

### Share your configuration

```yml
docker-compose.yml:

 gluetun:
   image: qmcgaw/gluetun
     container_name: gluetun
     cap_add:
       - NET_ADMIN
     env_file: private/gluetun.env

gluetun.env:

  OPENVPN_USER=******
  OPENVPN_PASSWORD=*****
  VPNSP=surfshark
  REGION=*****
  DOT=off
  DOT_CACHING=off
  DNS_UPDATE_PERIOD=0
  BLOCK_MALICIOUS=off
  DNS_KEEP_NAMESERVER=off
  DNS_PLAINTEXT_ADDRESS=10.2.0.3
```

**Comment by qdm12** [comment]
Hey @julianlore thanks so much for digging it out even in the source code 😉 

Fixed in 2cff64fd80949e3bbe9c595f4324157b0888bca4 !
