### ISSUE TITLE
Wiki issue: 

### ISSUE THREAD

**Issue by gazsy** [qdm12/gluetun#847]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/VPN-Unlimited

### What's the issue?

Hello,

I have an issue with RPI4/Docker
I used the VPN unlimeted, but I do not understand what I did wrongly. :(

[_gluetun_gluetun_1_logs (1).txt](https://github.com/qdm12/gluetun/files/8056053/_gluetun_gluetun_1_logs.1.txt)

**Comment by gazsy** [comment]
Regenerate the VPN key. now it seems to be right :)

**Comment by qdm12** [comment]
Good to know, thanks for closing the issue :wink:
