### ISSUE TITLE
Wiki issue: Dupe Name in Env Variable for PIA Port Forward File

### ISSUE THREAD

**Issue by mattyams** [qdm12/gluetun#871]
https://github.com/qdm12/gluetun/wiki/Private-internet-access#optional-environment-variables

Shouldn't `PRIVATE_INTERNET_ACCESS_VPN_PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE` just be `PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE`

**Comment by qdm12** [comment]
Yes totally! Fixed!
Thanks for reporting the issue.
