### ISSUE TITLE
Feature request: Add support for VyprVPN in a GIGANEWS Account

### ISSUE THREAD

**Issue by Draxter** [qdm12/gluetun#872]
### What's the feature 🧐

The company that owns VyprVPN also sells it via their [GIGANEWS](https://giganews.com) website bundled together with a Usenet service.

Currently Gluetun supports using VyprVPN only if it was purchased on vyprvpn.com. It would be useful to also enable its use for users who purchased it on giganews.com.

### Extra information and references

Region names appear to be the same, but the hostnames have `eu1.vpn.giganews.com` format instead of `eu1.vyprvpn.com`

**Comment by qdm12** [comment]
Hey there, thanks for proposing this.

1. Did you try with the current VyprVPN gluetun setup (see the wiki), what error do you get?
2. Try adding `-e VPN_ENDPOINT_IP=128.90.96.17` to see if it works? (IP found with `nslookup eu1.vpn.giganews.com`)
3. Is it the only difference? Did you compare both OpenVPN configuration files from vyprvpn.com and giganews.com? If you don't have a vyprvpn openvpn config, please share a giganews config file (and remove your username+password)

**Comment by Draxter** [comment]
Hi. Here is the info you requested:

1. Yes, I ran the following command: `docker run --cap-add NET_ADMIN -e VPN_SERVICE_PROVIDER=vyprvpn -e OPENVPN_USER=someusername -e OPENVPN_PASSWORD=somepassword qmcgaw/gluetun:latest`

Part of the log output:
```
2022/03/07 10:49:03 INFO openvpn: UDP link remote: [AF_INET]209.99.93.18:443
2022/03/07 10:49:06 INFO openvpn: [us6.vyprvpn.com] Peer Connection Initiated with [AF_INET]209.99.93.18:443
2022/03/07 10:49:07 ERROR openvpn: AUTH: Received control message: AUTH_FAILED

Your credentials might be wrong 🤨
```

2. I added the environment viable as follows: `docker run --cap-add NET_ADMIN -e VPN_SERVICE_PROVIDER=vyprvpn -e OPENVPN_USER=someusername -e OPENVPN_PASSWORD=somepassword -e VPN_ENDPOINT_IP=128.90.96.17 qmcgaw/gluetun:latest`

Part of the log output:
```
2022/03/07 10:42:59 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]128.90.96.17:443
2022/03/07 10:42:59 INFO openvpn: UDP link local: (not bound)
2022/03/07 10:42:59 INFO openvpn: UDP link remote: [AF_INET]128.90.96.17:443
2022/03/07 10:43:00 INFO openvpn: [eu1.vpn.giganews.com] Peer Connection Initiated with [AF_INET]128.90.96.17:443
2022/03/07 10:43:01 INFO openvpn: TUN/TAP device tun0 opened
2022/03/07 10:43:01 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
2022/03/07 10:43:01 INFO openvpn: /sbin/ip link set dev tun0 up
2022/03/07 10:43:01 INFO openvpn: /sbin/ip addr add dev tun0 10.2.0.21/24
2022/03/07 10:43:01 INFO openvpn: UID set to nonrootuser
2022/03/07 10:43:01 INFO openvpn: Initialization Sequence Completed
2022/03/07 10:43:01 INFO dns over tls: downloading DNS over TLS cryptographic files
2022/03/07 10:43:10 INFO dns over tls: downloading hostnames and IP block lists
2022/03/07 10:43:15 INFO dns over tls: init module 0: validator
2022/03/07 10:43:15 INFO dns over tls: init module 1: iterator
2022/03/07 10:43:15 INFO dns over tls: start of service (unbound 1.13.2).
2022/03/07 10:43:15 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/07 10:43:15 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/07 10:43:16 INFO dns over tls: ready
2022/03/07 10:43:16 INFO vpn: You are running on the bleeding edge of latest!
2022/03/07 10:43:16 INFO ip getter: Public IP address is 128.90.138.60 (Netherlands, North Holland, Amsterdam)
```

So, it works nicely.

3. Unfortunately, I only have the giganews subscription that gives me vyprvpn, instead of the direct vyprvpn one, so i can't compare the two. However, I found their .ovpn config files, which can be downloaded [here](https://www.giganews.com/downloads/openvpn/VyprVPN%20OpenVPN%20Conf.zip)

**Comment by mossyblog** [comment]
> 2. Try adding `-e VPN_ENDPOINT_IP=128.90.96.17` to see if it works? (IP found with `nslookup eu1.vpn.giganews.com`)

I had the same issue, once i put in this endpoint it fixed the issue and now works. Legend.

**Comment by qdm12** [comment]
Hi there, trying to revive this. Basically, since for the same "region" the giganews and vyprvpn server IP addresses differ, would it be safe to say these are like 2 different providers? Does giganews only sell vyprvpn as a vpn provider? If so I can pretty much copy pasta vyprvpn's code in gluetun and rename it to either giganews or giganews-vyprvpn

**Comment by bakedgoodz** [comment]
Yes I think it is safe to say they are separate providers. Near as I can tell Giganews is reselling vyprvpn. However when going through Giganews you are required to use the Giganews branded servers. 
Yes vyprvpn appears to be the only VPN that Giganews is reselling

**Comment by qdm12** [comment]
Where do you get their Openvpn configuration files from? Is there a public link? Similarly to Vyprvpn's https://support.vyprvpn.com/hc/article_attachments/360052617332/Vypr_OpenVPN_20200320.zip

**Comment by qdm12** [comment]
Can you please try `qmcgaw/gluetun:pr-2479` following documentation of https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/vyprvpn.md and just change `VPN_SERVICE_PROVIDER=vyprvpn` to `VPN_SERVICE_PROVIDER=giganews`. Let me know if it works fine or not, thanks!

**Comment by bakedgoodz** [comment]
Thank you so much!! 

Seems to be working just fine. IP getter says I'm pulling a Netherlands IP. Have yet to spin up qBittorrent and see if traffic actually works..but so far it looks like a win.

**Comment by qdm12** [comment]
Done in #2479
