### ISSUE TITLE
ipv6 route to container gateway is not working 

### ISSUE THREAD

**Issue by dsm1212** [qdm12/gluetun#880]
8### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

Portainer

### What is the version of Gluetun

da2bddaf7c3b

### What's the problem 🤔

The gluetun container seems to have had a serious regression. It's missing support for ipv6. I think this must have broken in the last month or so. I have other services on the same docker network and they can no longer connect using ipv6 with services that are sharing "service:gluetun". It's sort of benign because web traffic falls back to ipv4 but it adds delay and all the web services are slower. You have to have ipv6 enabled in docker and what not, but then connect to the gluetun container and issue the command ip6tables --list-rules. You get:

```
# ip6tables --list-rules
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.7 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
```

Also, if you have another interface on the same network you can try ping or traceroute. Here I ping the gateway:

```
# ping -6 fd00::3:0:0:1
PING fd00::3:0:0:1 (fd00::3:0:0:1): 56 data bytes
ping: sendto: Operation not permitted
```

This is the error you get when the ipv6 routing tables are misconfigured.

### Share your logs

I omitted the certificate which was printed out since that seemed sensitive to me. Header gets truncated, maybe by portainer?

```log
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Address to ping: github.com
|   └── VPN wait durations:
|       ├── Initial duration: 5s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: America/New_York
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2022/03/04 10:11:11 INFO routing: default route found: interface eth0, gateway 172.31.0.1
2022/03/04 10:11:11 INFO routing: adding route for 0.0.0.0/0
2022/03/04 10:11:11 INFO firewall: setting allowed subnets...
2022/03/04 10:11:11 INFO routing: default route found: interface eth0, gateway 172.31.0.1
2022/03/04 10:11:11 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022/03/04 10:11:11 INFO pprof http server listening on [::]:6060
2022/03/04 10:11:11 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2022/03/04 10:11:11 INFO http server: listening on :8000
2022/03/04 10:11:11 INFO healthcheck: listening on 127.0.0.1:9999
2022/03/04 10:11:11 INFO firewall: allowing VPN connection...
2022/03/04 10:11:11 INFO openvpn: OpenVPN 2.5.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] 
[LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 15 2021
2022/03/04 10:11:11 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10
2022/03/04 10:11:11 INFO openvpn: CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
2022/03/04 10:11:11 INFO openvpn: 
<OMITTTED>
2022/03/04 10:11:11 INFO openvpn: -----END X509 CRL-----
2022/03/04 10:11:11 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]199.36.223.224:1197
2022/03/04 10:11:11 INFO openvpn: UDP link local: (not bound)
2022/03/04 10:11:11 INFO openvpn: UDP link remote: [AF_INET]199.36.223.224:1197
2022/03/04 10:11:11 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1554'
2022/03/04 10:11:11 WARN openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
2022/03/04 10:11:11 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2022/03/04 10:11:11 INFO openvpn: [montreal410] Peer Connection Initiated with [AF_INET]199.36.223.224:1197
2022/03/04 10:11:11 INFO openvpn: TUN/TAP device tun0 opened
2022/03/04 10:11:11 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
2022/03/04 10:11:11 INFO openvpn: /sbin/ip link set dev tun0 up
2022/03/04 10:11:11 INFO openvpn: /sbin/ip addr add dev tun0 10.30.110.23/24
2022/03/04 10:11:11 INFO openvpn: UID set to nonrootuser
2022/03/04 10:11:11 INFO openvpn: Initialization Sequence Completed
2022/03/04 10:11:11 INFO dns over tls: downloading DNS over TLS cryptographic files
2022/03/04 10:11:11 INFO dns over tls: downloading hostnames and IP block lists
2022/03/04 10:11:12 INFO healthcheck: healthy!
2022/03/04 10:11:17 INFO dns over tls: init module 0: validator
2022/03/04 10:11:17 INFO dns over tls: init module 1: iterator
2022/03/04 10:11:17 INFO dns over tls: start of service (unbound 1.13.2).
2022/03/04 10:11:17 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/04 10:11:17 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/04 10:11:20 INFO dns over tls: ready
2022/03/04 10:11:21 INFO vpn: You are running on the bleeding edge of latest!
2022/03/04 10:11:21 INFO vpn: VPN gateway IP address: 10.30.110.1
2022/03/04 10:11:21 INFO port forwarding: Found saved forwarded port data for port 28887
2022/03/04 10:11:21 INFO port forwarding: Forwarded port data expires in 36 days
2022/03/04 10:11:21 INFO port forwarding: Port forwarded data expires in 36 days
2022/03/04 10:11:21 INFO port forwarding: port forwarded is 28887
2022/03/04 10:11:21 INFO firewall: setting allowed input port 28887 through interface tun0...
2022/03/04 10:11:21 INFO port forwarding: writing port file /gluetun/forwarded_port
2022/03/04 10:11:21 INFO ip getter: Public IP address is 199.36.223.224 (Canada, Quebec, Montréal)
2022/03/04 13:02:58 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/04 15:34:13 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/04 18:07:51 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/03/04 20:46:59 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: lsio
    cap_add:
      - NET_ADMIN
    ports:
      - 8191:8191 # flaresolvrr
      - 9092:8080 # calibre
      - 9093:8086 # calibre api
    volumes:
      - /apps/gluetun:/gluetun
    environment:
      - DOT_IPV6=on
      - VPNSP=private internet access
      - OPENVPN_USER=xxx
      - OPENVPN_PASSWORD=yyy
      - OPENVPN_FLAGS=--fast-io --sndbuf 512000 --rcvbuf 512000 --txqueuelen 2000 --tun-mtu 1498
      - REGION=CA Montreal
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - TZ=America/New_York
    restart: unless-stopped
```

**Comment by dsm1212** [comment]
Ah, the ip6tables command I guess is missing on purpose so use the ping or traceroute to test this. I fell back to v3.27.0 and it works fine so this just happened recently.

**Comment by qdm12** [comment]
Are you sure? The error you get is related to a missing kernel module. Maybe you forgot to enable ipv6 in your container configuration?

Have you also tried v3.28.0?

**Comment by dsm1212** [comment]
Ah, I thought latest was the same as v3.28.0. I just tried v3.28.0 and it is fine. Only latest is broken. 

Just changing the tag makes pinging the gateway work so I think I've got ipv6 setup correctly. System has been working with ipv6 for quite a while. All the containers and networks have ipv6 addresses. I'll take a look at the diffs on latest to see if there is anything obvious that might affect my config.

**Comment by dsm1212** [comment]
Seems likely it was this commit which changed some iptables: 006b218ade0b4c6a75349ea91f4f66ffb795b966

**Comment by qdm12** [comment]
That's strange, let's see how I can fix this commit then.

What do you get with

```sh
docker run -it --rm --cap-add=NET_ADMIN  --entrypoint=/bin/sh gluetun:v3.28.0
ip6tables -L
echo $?
ip6tables-nft -L
echo $?
exit
```

**Comment by dsm1212** [comment]
Here you go... The nft output is why it looked to me like no ipv6 firewall.

# docker run -it --rm --cap-add=NET_ADMIN  --entrypoint=/bin/sh qmcgaw/gluetun:v3.28.0
/ # ip6tables -L
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.7 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
/ # echo $?
3
/ # ip6tables-nft -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
/ # echo $?
0
/ # exit

**Comment by dsm1212** [comment]
I found the post-rules.txt option. Am I required to set the ipv6 rules mysef or should there be default ones?

**Comment by dsm1212** [comment]
Looking at this some more, the PIA tunnel doesn't have an IPV6 address and my container is bridged so really I don't need an ipv6 firewall. I think my only issue is the bad image. thx

**Comment by qdm12** [comment]
Hey again!

> Am I required to set the ipv6 rules mysef or should there be default ones?

There are default ones set up.

> the PIA tunnel doesn't have an IPV6 address and my container is bridged so really I don't need an ipv6 firewall

I think you do; if you have ipv6 enabled on the container, it means something can use ipv6 and not go through the ipv4-only vpn.

> I think my only issue is the bad image.

The image isn't bad, it falls back on ip6tables-nft if ip6tables fails. Somehow the nft variant works I have no idea why.

How do you have ipv6 configured in your containers? How do you have it in gluetun? Usually you need to add a line in your docker-compose.yml to enable it. That would explain why ip6tables fails.

**Comment by dsm1212** [comment]
Ok, I'll elaborate :-). I have enabled ipv6 in the docker json file and I'm using a network which has ipv6 enabled, that's the line you are referring to, but I precreated the network, it's not in my docker compose. So gluetun is using this network "network_mode: lsio" which is ipv6 enabled. Then I have 6 or 7 other contiainers tied to gluetun using "network_mode: service:gluetun". Those things all have the same IP as gluetun, 172.31.0.3 and fd00::3:0:0:3. There is another service using network lsio and it gets address 172.31.0.4 and fd00::3:0:0:4. The service at fd00::3:0:0:4 (swag which contains nginx) tries an http request to one of the services at fd00::3:0:0:3 and with 3.28.0 it succeeds, but with latest it fails and then falls back to 172.31.0.3 and succeeds. So I have a timeout happening all time on latest and it's very noticable. That led me to noticing that on latest from within the gluetun container pinging fd00::3:0:0:1 fails. In 3.28.0 it works. So something changed that broke the ipv6 traffic in the gluetun container. Another way to describe this is that on 3.28.0 I can connect to the fd00::3:0:0:4 container and do a wget to fd00::3:0:03 and it will work but with latest it fails. is that consistent with this image issue?

**Comment by dsm1212** [comment]
Oh, my comment about not needing a firewall is because pia does not have ipv6 enabled on the tun device, nothing v6 will come in or go out over that interface. And the traffic that goes through the bridge to the host, when it's working, is not encrypted so it gets firewalled with host v6 rules and later on the router port I have v6 rules set up.

**Comment by qdm12** [comment]
Ok makes sense.

Although what I think is happening is that:

- v3.28.0 and below, there is no ip6tables firewall since it doesn't work (`ip6tables -L` fails)
- latest there is an ipv6 firewall, since ip6tables-nft works. You can probably check it with `docker exec gluetun ip6tables-nft -L`. Maybe that would bring some unsight why it works over the ipv4 firewall but not the ipv6? You can compare with `docker exec gluetun iptables -L`. 

I'm still curious since I guess most people don't have a host firewall configured.

**Comment by qdm12** [comment]
I figured it out I think, your traceroute failed on latest because:

- v3.28.0 sees ip6tables fails so assumes ipv6 isn't available and stops there
- latest sees ip6tables fails but ip6tables-nft works, so it uses this once. Tables policy are all set to `DROP` which hence blocks the traceroute. You can check with `docker exec gluetun ip6tables-nft -L` while it's running.
So I think this is the desired expected behavior. If you want to run your traceroute command, you can always use the custom rules text file as you mentioned above to relax the ip6tables-nft firewall setup.

> Is it possible something is confused because PIA forces the tun device to ipv4

No firewalling is independent, it even gets set at container start before any vpn gets modified. Although it will allow the vpn connection through dynamically.

> I noticed that I never had any kind of host ipv6 rule violated so for the moment I disabled them. They really only protect from things on my lan since the router protects from outside. Disabling them made no difference with this issue.

Yeah the ipv6 firewall is really to drop by default:

- ipv6 inbound traffic from the vpn server coming through the tunnel
- ipv6 outbound traffic from gluetun and especially from container-connected containers using gluetun as their network. 

And maybe with pia tunneling ipv4 only, ipv6 gets lost.

**Comment by dsm1212** [comment]
Yes, I think you are correct. When I actually start the container and connect to it I see the ip6 rules are default DROP. I added the post-rules.txt file to adjust things the way I want and things seem to be working again using latest. Thanks!
