### ISSUE TITLE
Wiki issue: Surfshark SERVER_REGION

### ISSUE THREAD

**Issue by Crazycurly** [qdm12/gluetun#881]
it should be "REGION",  "SERVER_REGION" is not working on https://github.com/qdm12/gluetun/wiki/Surfshark

**Comment by qdm12** [comment]
Which version are you running? It should on v3.28.0 and latest, but older images do use REGION indeed.

**Comment by Crazycurly** [comment]
I use rpi4 64bit os pull the latest version of arm64
VERSION=latest CREATED=2022-02-26T23:00:01.006Z COMMIT=006b218 TARGETPLATFORM=linux/arm64

**Comment by barkap** [comment]
Same problem with Private Internet Access (latest as well as v3.28)

**Comment by qdm12** [comment]
It's `SERVER_REGIONS`, I fixed the Wiki thanks for reporting it!
