### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by fgurdradee** [qdm12/gluetun#932]
### Host OS

Windows 10

### CPU arch

x86_64

### VPN service provider

Privado

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

the default BLOCK MALICIOUS=ON blocks Usenetserver servers:
news.usenetserver.com and news-eu.usenetserver.com

if I use - BLOCK_MALICIOUS=OFF in my compose file I am then able to connect to the servers. 

requesting to whitelist the above two servers.

### Share your logs

```log
n/a
```

**Comment by qdm12** [comment]
Use `UNBLOCK=usenetserver.com` and that should do it :wink:

**Comment by fgurdradee** [comment]
thanks @qdm12
