### ISSUE TITLE
Wiki issue: Synology prerequisites page: DSM 7.0 uses systemd

### ISSUE THREAD

**Issue by martinbjeldbak** [qdm12/gluetun#940]
I've been working on getting `gluetun` set up on my Snology NAS (thanks for this awesome project by the way!) and noticed that the "Synology prerequisites" page at https://github.com/qdm12/gluetun/wiki/Synology-prerequisites could use a small update since DSM 7.0 released recently and has changed startup systems.

As per https://gist.github.com/SanCoder-Q/f3755435e6e8bd46ba95bf0ec54ae1a4?permalink_comment_id=3844174#gistcomment-3844174, `systemd` is the new way to run scripts on startup.

On my NAS, I have created the following systemd service to run `tun` on system startup, which seems to be working nicely. I've placed it in `/etc/systemd/system/tun.service`:

```
[Unit]
Description=Run tun at startup
After=network.target

[Service]
Type=simple
User=root
ExecStart=/sbin/insmod /lib/modules/tun.ko
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Then enabling it to run it on every startup with

```sh
$ cd /etc/systemd/system
$ sudo systemctl enable tun.service
```

Hopefully this can be added to the wiki so others like me can get up and running quickly

**Comment by cchhat01** [comment]
This is amazing, I learned something new today. 
I'm going to set this up shortly, I always hated that bloody startup script that I had to run to install the tun device.
Much appreciated.
Thanks.

**Comment by qdm12** [comment]
Thanks for sharing :+1: 
I updated the [Wiki page](https://github.com/qdm12/gluetun/wiki/Synology-prerequisites) for DSM >= 7.0
