### ISSUE TITLE
phpmyadmin & mysql

### ISSUE THREAD

**Issue by shayfer** [qdm12/gluetun#967]
I cannot connect to mysql from phpmyadmin when using the gluetun container. On gluetun I have port 3306 tcp opened for mysql and the container logs say it's listening. phpmysql I have ports 8080 bind to 80 and can get to the admin login no problem. The logs also do not report any errors. When I try to login I receive this message:

mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known

If I take this out of the gluetun container and just stack them it works just fine. 

Does anyone know what I need to open up on gluetun to allow phpmyadmin to communicate with mysql?

Thanks and fantastic project otherwise! Really love it!

**Comment by shayfer** [comment]
Closing this issue as I finally figured it out. In phpmyadmin instead of using the named service of mysql, (I had it as mysl_db), or using the host IP address, like I do for Radarr for example host:port you have to use the ip address of the gluetun container. So in the environment of phpmyadmin set the PMA_HOST to 172.17.0.X or whatever private addresses you are using.

**Comment by qdm12** [comment]
Sorry I wasn't able to reply earlier.

Is your mysql using the gluetun as its network? Why?

Also you can probably use gluetun:3306 from phpmyadmin to reach the mysql database through gluetun, as long as gluetun and phpmyadmin are in the same docker network.

**Comment by shayfer** [comment]
Good morning and thanks for the reply. I was setting Ombi and when you login it suggests migrating your DB over to mysql which has phpmyadmin in the stack. I thought I'd keep it all together but I guess the mysql can sit in a bridge or host network. Working great in gluetun though!
