### ISSUE TITLE
Add API function

### ISSUE THREAD

**Issue by orgserj** [qdm12/gluetun#970]
### What's the feature 🧐

pls add API function reconnect disconnect connect

example:

/v1/vpn/reconnect 
/v1/vpn/connect
/v1/vpn/disconnect 

if you send a command
(HTTP PUT to /v1/openvpn/status with a body {"status":"stopped"} to stop Openvpn)
the server will automatically  up

may be change region
/v1/vpn/region/netherlands

thank

**Comment by qdm12** [comment]
> /v1/vpn/reconnect
> /v1/vpn/connect
> /v1/vpn/disconnect

These calls can be achieved with `/v1/openvpn/status`.

> if you send a command
(HTTP PUT to /v1/openvpn/status with a body {"status":"stopped"} to stop Openvpn)
the server will automatically up

Yes this is the healthcheck that runs independently from the VPN. I don't really see a reason to keep it stopped actually, why would gluetun have its VPN disabled :thinking: ?

For the region change, subscribe to #91

There is a lot more work to do in this server, such as turning off the healthcheck or patch the VPN settings. I'll get to it, but don't expect it to be ready in the coming few days...
