### ISSUE TITLE
Bug: servers.json file manual change is not working

### ISSUE THREAD

**Issue by ACNiC03** [qdm12/gluetun#991]
### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest (3.29.0) built on 2022-05-6 (commit e32d251)

### What's the problem 🤔

I started the container as default with my credentials, the logs said "Host Unreachable". So I checked the servers.json file and the ip addresses of the servers were not right (PIA Netherlands), so i changed it to the current ip addresses; 
"191.96.168.188",
"181.214.206.88",
"212.102.35.152" 
I have putted them in just like the original format but now the container wont even start (read logs)
NOTE: I have changed nothing else but this part below...
![image](https://user-images.githubusercontent.com/64742934/169152206-21b39a9f-e871-4030-b299-4944c48361b3.png)

### Share your logs

```log
Running version latest built on 2022-05-07T07:18:37.602Z (commit e32d251),
...
2022-05-18T22:30:04+02:00 INFO [routing] default route found: interface eth0, gateway 172.23.0.1 and assigned IP 172.23.0.2,
2022-05-18T22:30:04+02:00 INFO [routing] local ethernet link found: eth0,
2022-05-18T22:30:04+02:00 INFO [routing] local ipnet found: 172.23.0.0/16,
2022-05-18T22:30:04+02:00 INFO [firewall] enabling...,
2022-05-18T22:30:04+02:00 INFO [firewall] enabled successfully,
2022-05-18T22:30:04+02:00 ERROR cannot read servers from file: cannot decode versions: invalid character ']' looking for beginning of value,
2022-05-18T22:30:04+02:00 INFO Shutdown successful
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/<user>/Gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=***
      - OPENVPN_PASSWORD=***
      - SERVER_REGIONS=Netherlands
      - TZ=Europe/Amsterdam
```

**Comment by qdm12** [comment]
There was an extra `,` at the end of the array elements of the ips field 😉
I'll eventually change it to support decoding a more flexible json format, so these don't bother again.

Thanks for the well formed issue as well, it's rare these days! 👍
