### ISSUE TITLE
Bug: Question, if we can reconnect IP from another container

### ISSUE THREAD

**Issue by marrakechi** [qdm12/gluetun#995]
### Is this urgent?

No

### Host OS

Windows

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Hello, 

I want to know if we can reconnect Nordvpn from another machine, using the webservices, 
I have seen that we have an endpoint updater, but I didn't understand it well. 

My case, I'm using gluetun, and another ubuntu container, using the HTTP proxy I could connect to NordVPN server, I want to change the NordVPN server from the ubuntu machine from Netherlands to France for example. 

I want to know if it's possible to do that? 

Thank you, 

### Share your logs

```log
gluetun_1  | 2022-05-20T10:35:16Z INFO [dns over tls] ready
gluetun_1  | 2022-05-20T10:35:16Z INFO [healthcheck] healthy!
gluetun_1  | 2022-05-20T10:35:16Z INFO [vpn] You are running on the bleeding edge of latest!
gluetun_1  | 2022-05-20T10:35:17Z INFO [ip getter] Public IP address is 185.222.240.50 (France, Provence-Alpes-Côte d'Azur, Marseille)
gluetun_1  | 2022-05-20T10:35:19Z INFO [http server] 200 GET /ip wrote 205B to 172.19.0.1:48956 in 181.8µs
gluetun_1  | 2022-05-20T10:35:24Z INFO [http server] 200 PUT /status wrote 22B to 172.19.0.1:48966 in 1.4951ms
gluetun_1  | 2022-05-20T10:35:24Z INFO [updater] updating Nordvpn servers...
gluetun_1  | 2022-05-20T10:35:29Z INFO [updater] Updated servers information
gluetun_1  | 2022-05-20T10:35:38Z INFO [http server] 200 GET /ip wrote 205B to 172.19.0.1:48984 in 369.7µs
gluetun_1  | 2022-05-20T10:35:45Z INFO [updater] starting
gluetun_1  | 2022-05-20T10:35:45Z INFO [http server] 200 PUT /status wrote 22B to 172.19.0.1:48994 in 319.8µs
gluetun_1  | 2022-05-20T10:35:45Z INFO [updater] updating Nordvpn servers...
gluetun_1  | 2022-05-20T10:35:50Z INFO [updater] Updated servers information
gluetun_1  | 2022-05-20T10:35:53Z INFO [http server] 200 GET /ip wrote 205B to 172.19.0.1:49004 in 80.9µs
```

**Comment by qdm12** [comment]
Right now it's not really possible although it is definitely my goal to have an HTTP endpoint to do all this. Subscribe to issue #91 (old but still relevant). Closing this to avoid duplicate issues, thanks!
